### ISSUE TITLE
Server level hint feature

### ISSUE THREAD

**Issue by Choupom** [teeworlds/teeworlds#1000]
"The idea is to put an indicative icon of the server's recommanded level: newbie, middle and pro. Many games already include this option, and the aim isn't to forbid the access to some severs, it's only to prevent players that a server fit or not their playing level."

Old post and mockup by LordSkelethom: http://lordskelethom.posterous.com/server-level

Would be pretty nice if it was added to the new server browser!

**Comment by Dune-jr** [comment]
@oy close? :)
