### ISSUE TITLE
Fix graphics asynchronous rendering

### ISSUE THREAD

**Issue by Choupom** [teeworlds/teeworlds#1001]
On my laptop (win64, 1core, 1thread), gfx_asyncrender decreases the game performance by a lot.
With V-Sync: from 30fps to ~15fps
Without V-Sync: from ~230fps to ~10fps
This should be either fixed or disabled by default.

**Comment by oy** [comment]
Does this problem persists in 0.7?

**Comment by Choupom** [comment]
Can't reproduce on 0.7.
