### ISSUE TITLE
fix pistol offset

### ISSUE THREAD

**Issue by SushiTee** [teeworlds/teeworlds#1013]
the offset to make the pistol match the projectiles let the pistol look weird... if u aim down the pistol is very long while its beeing very short when aiming up due to the rotation.

**Comment by Fisico** [comment]
I am not sure if this can be fixed in the bitmap.

![pistol](https://user-images.githubusercontent.com/329471/47951816-67724380-df66-11e8-9af2-e0efeea51062.png)

**Comment by Zatline** [comment]
intresting @Fisico yes I feel like this actually is code based and perhaps intentional. To me it looks like the gun is locked on the hand and the hand just doesn't have the rotation radius aligned with the body which doesn't seem actually that wrong since hands are naturaly in the lower half body area. Someone should investigate the code @Oy! I feel like this is more of a feature than an issue.

**Comment by Dune-jr** [comment]
@Fisico @Zatline: this is just about center of the gun being low. It can be adjusted, but how should it be?
The code is about there:
https://github.com/teeworlds/teeworlds/blob/0b25463b750f2732f52c574681688decfcc919f4/src/game/client/components/players.cpp#L411-L413
and it should be the same problem with the shotgun, just less noticeable.

**Comment by oy** [comment]
The idea was to revert this in the code 0b0f8e2f1ce5dbdc8fb0e79eeada21fec1f05c02
And instead move the pistol in the game png a bit down and shorten its grip. So it looks like it does now when you aim to the right and the left. The top/bottom thing gets corrected by the revert in the code.

**Comment by Zatline** [comment]
@oy alright I see what I can do 👍

**Comment by oy** [comment]
@Zatline 
Could you check how it looks when you move the pistol a bit down in the game.png? So it matches more the start of the bullet ingame.

**Comment by Zatline** [comment]
I tried already when doing that some pixels were leaking into the shotgun area ingame while on the svg grid they didn't wierd thing not sure why but couln't move it more down :/

**Comment by oy** [comment]
@Zatline 
Ok, then I have to figure sth out.

**Comment by Dune-jr** [comment]
@oy wasn't this already fixed?

**Comment by oy** [comment]
@Dune-jr no it's back to the old state where the bullet doesn't match the pistol and it looks like the weapon is on the tees shoulder.
![screenshot_2018-12-12_20-34-03](https://user-images.githubusercontent.com/293850/49894161-8ad5bb80-fe4d-11e8-8852-020c1949d6a5.png)

**Comment by fokkonaut** [comment]
Right now:
![image](https://user-images.githubusercontent.com/35420825/97241810-72c57600-17f2-11eb-84b5-d77e39f76297.png)
![image](https://user-images.githubusercontent.com/35420825/97241817-79ec8400-17f2-11eb-9480-62b1451e6b30.png)

The version where the gun is lower, which I prefer:
![image](https://user-images.githubusercontent.com/35420825/97241838-8c66bd80-17f2-11eb-9940-33ed9a55f197.png)
![image](https://user-images.githubusercontent.com/35420825/97241849-94bef880-17f2-11eb-928b-37a098415c62.png)

As you can see, its never the same length up and down, so I would just go with the one where the position actually matches the projectiles and the hook.
