### ISSUE TITLE
Mouse pointer constantly moves upwards in windowed mode

### ISSUE THREAD

**Issue by T-X** [teeworlds/teeworlds#1023]
I just started teeworlds and changed the resolution to 1280x800, windowed. After restarting teeworlds the mouse cursor now constantly, slowly moves upwards all the time (needs about 8 seconds for those 800 pixels). Enabling fullscreen again and the issue is gone. Also enabling 'inp_grab' works.

I'm on a recent Debian Sid, 64bit (kernel+userspace). My window manager is xmonad. Teeworlds 0.6.1+dfsg-1.

settings.cfg: http://pastebin.com/TGfKGseU

**Comment by oy** [comment]
Should be fixed.

**Comment by SirKalrin** [comment]
Its not fixed
