### ISSUE TITLE
Clearly separate vanilla Teeworlds from custom gametypes

### ISSUE THREAD

**Issue by Dunedune** [teeworlds/teeworlds#1035]
It's been a long time I should have posted this suggestion. It's a decision to be taken or not, give your opinions on that, but there needs to be a discussion on the topic imo.

To me, Teeworlds should have two tabs, one as "Teeworlds", another one as "Custom gametypes"/"Custom servers"/"Modifications"/whatever.

This would help greatly to mark the difference of what is Teeworlds and what is fan-made stuff. At the moment, the only thing doing this is the little exclamation point sign on the server list, and noone ever notice it - or know what it means.

Original post: https://www.teeworlds.com/forum/viewtopic.php?pid=102288#p102288

Example of how it has been done in another game: http://puu.sh/1s2oi

Waiting your opinion on the topic!
Dune.

**Comment by oy** [comment]
Fixed.
