### ISSUE TITLE
Add Palestinian flag

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1042]
Add Palestinian flag.

**Comment by minus7** [comment]
A job for @Landil maybe? The ISO 3166-1 alpha-2 code is "PS".

**Comment by MegaManSec** [comment]
(we wait for OMG PL isn't a country)

**Comment by Soreu** [comment]
Except if Landil have original source file, there you go:

![PS](https://cloud.githubusercontent.com/assets/14035306/9830883/3c2a7d3c-5940-11e5-80d4-705b6ac7e437.png)
