### ISSUE TITLE
defined color values for teams

### ISSUE THREAD

**Issue by Zatline** [teeworlds/teeworlds#1059]
Replace randomized team color values with defined team color values for all skins.

Blue: http://imageshack.us/a/img843/8776/blueval.png

body.hue := 154
body.sat := 240
body.lgt := 111

hands.hue := 154
hands.sat := 240
hands.lgt := 151

feet.hue := 154
feet.sat := 240
feet.lgt := 151

Red: http://imageshack.us/a/img812/8567/redval.png

body.hue := 252
body.sat := 240
body.lgt := 111

hands.hue := 255
hands.sat := 240
hands.lgt := 151

feet.hue := 254
feet.sat := 240
feet.lgt := 151

**Comment by KingteEGER** [comment]
**fyi:** 404 not found.
The images are not online anymore.

**Comment by Dune-jr** [comment]
I'm not sure what this is about? 

> Replace randomized team color values with defined team color values for all skins.

Team color values are not randomized atm?

**Comment by oy** [comment]
No idea, can probably be closed?
Actual team colors seem alright.

**Comment by Dune-jr** [comment]
Yeah
