### ISSUE TITLE
Convert automap rules

### ISSUE THREAD

**Issue by cinaera** [teeworlds/teeworlds#1066]
The automap rules need to be converted to be compatible with the new json-parser

**Comment by Dune-jr** [comment]
@android272

Might be interested to do that and suggest improvements for the automapper along the lines of https://www.teeworlds.com/forum/viewtopic.php?id=11496 ? :)
Still need some doc on how they work?

**Comment by oy** [comment]
Maybe we should specify what we need and then improve/change them.

**Comment by Dune-jr** [comment]
I believe this is fixed by #814
