### ISSUE TITLE
Gameplay: Balance LMS

### ISSUE THREAD

**Issue by cinaera** [teeworlds/teeworlds#1069]
Current situation:
You start with some weapons, there are no pickups and the round ends, when only 1 tee is alive

Atm it's not really useful to kill a tee because you waste ammo and life. So if you kill much tees you run out of ammo but you will probably be killed in the end by ppl who prefer to hide and run away than seek other players.

Imho there should be some kind of reward ( ammo, shields,.. ?) if you kill a tee or sth else.

**Comment by Fisico** [comment]
Team LMS/Survival plays out a bit boring cause there is no way to regenerate or pickup more Ammo.

My Idea for a mod with pickups:
player should start with 10 Hearts, 0 Armour, 10 Pistol shots and Hammer

Place some Weapons and Hearts/Armour on the Maps(Symetrical on Sur1) so the rounds are a bit longer and the Players are able to regenerate. So there is way more tension.

Kind of a round based TDM

**Comment by oy** [comment]
Don't think that there should be pickups in survival gametypes, matches are supposed to be quick - prefer some kind of reward for killing/hurting others so you're able to keep the pressure on.

**Comment by Zatline** [comment]
@oy like this perhaps
- dead player drops amunition of the weapon he had last, how much?
- dead player drops some armor / health also how much?
- item spawn on dead player? make them pickable for everyone?

**Comment by oy** [comment]
Probably best to just refresh ammo. But kinda hard to find the right balance. Do a pickup? Or automatically give it to the killer? But what if he just finished him off and someone else did f.e. 9 damage before...

**Comment by Dune-jr** [comment]
Probably best to ignore killsteal issues imo, not much to do about that.
Automatically give something like +2/+2/+1 shotgun/grenade/laser, mayyybe?

**Comment by oy** [comment]
Well, we could reward ammo for the damage you did instead of kills. F.e. for doing 10 damage you get x ammo. Might be more fair?

**Comment by LordSk** [comment]
How about exploding drops on death? The weapon could be random, as well as the amount of health/armor. It will create a pressure point on the map and it's also way more fun/intuitive than give some health back based on damage done. Survival is not about being fair after all, it's about surviving.
This also has the added bonus of strategic planning, who do you give the drops to, in a team scenario?

![survival_mockup_death](https://user-images.githubusercontent.com/294603/48555920-c8910400-e8e2-11e8-98ba-6f2f404d5f3f.png)

**Comment by Zatline** [comment]
> How about exploding drops on death? The weapon could be random, as well as the amount of health/armor. It will create a pressure point on the map and it's also way more fun/intuitive than give some health back based on damage done. Survival is not about being fair after all, it's about surviving.
> This also has the added bonus of strategic planning, who do you give the drops to, in a team scenario?

spawning a weapon seems a bit meh too much perhaps, 
I'd suggest spawn ammo instead max 1-2 of the weapon the dead player had last in their hands 
btw I kinda like the gradient visuals there 👍

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
