### ISSUE TITLE
Random crashes in windows 8 with ssd

### ISSUE THREAD

**Issue by janot** [teeworlds/teeworlds#1079]
Random crashes when playing teeworlds (game freezes and then Windows shows crash dialog).  I've encountered with this crash after installing Windows 8 and ssd (everything was ok on Win7 and hard drive). I've noticed, that before I installed Intel Rapid Storage driver (needed for my laptop), this crash froze whole system (probably it froze ssd and then ssd froze the system) and then I had BSOD. After installing this driver this crash just freezes teeworlds. Crashes happen once per 2-3 days.  

Here is crash dialog text translated to english:
"Description:
   Error led to a halt cooperation program with Windows.

Problem signature:
   Problem Event Name: AppHangB1
   Application Name: teeworlds.exe
   Application Version: 0.0.0.0
   Application Timestamp: 4e35c7a9
   Signature hangs: c14b
   Type hang 0
   OS Version: 6.2.9200.2.0.0.256.4
   Language code: 1049
   Extras. hang signature 1: c14bdf9a9fdf4a2942b0602d00a24a38
   Extras. hang signature 2: 82f4
   Extras. hang signature 3: 82f4476eff79b9e98576d66dcfff48d6
   Extras. hang signature 4: c14b
   Extras. hang signature 5: c14bdf9a9fdf4a2942b0602d00a24a38
   Extras. hang signature 6: 82f4
   Extras. signature hangs 7: 82f4476eff79b9e98576d66dcfff48d6"

Here is original crash dialog text (I have russian Windows):
"Описание:
  Ошибка привела к остановке взаимодействия программы с Windows.

Сигнатура проблемы:
  Имя события проблемы:	AppHangB1
  Имя приложения:	teeworlds.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	4e35c7a9
  Сигнатура зависания:	c14b
  Тип зависания:	0
  Версия ОС:	6.2.9200.2.0.0.256.4
  Код языка:	1049
  Доп. сигнатура зависания 1:	c14bdf9a9fdf4a2942b0602d00a24a38
  Доп. сигнатура зависания 2:	82f4
  Доп. сигнатура зависания 3:	82f4476eff79b9e98576d66dcfff48d6
  Доп. сигнатура зависания 4:	c14b
  Доп. сигнатура зависания 5:	c14bdf9a9fdf4a2942b0602d00a24a38
  Доп. сигнатура зависания 6:	82f4
  Доп. сигнатура зависания 7:	82f4476eff79b9e98576d66dcfff48d6"

**Comment by oy** [comment]
Outdated and probably not teeworlds related.
