### ISSUE TITLE
Mouse input issue with threaded rendering on mac

### ISSUE THREAD

**Issue by cinaera** [teeworlds/teeworlds#1114]
I've seen several reports on the forum so far.
Seems like the mouse input wont be recognized by mac with threaded rendering

**Comment by heinrich5991** [comment]
Some forum thread about possibly the same problem: https://www.teeworlds.com/forum/viewtopic.php?id=11602. If someone wants to debug the problem, they could probably get help from the person in the forum.

**Comment by oy** [comment]
It works fine with SDL2.

**Comment by oy** [comment]
Fixed.
