### ISSUE TITLE
Maybe whitelist some UTF-8 for names

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1129]
We could whitelist chinese and russian, etc. characters, so those people can actually write in their language in their names.

**Comment by PathosEthosLogos** [comment]
Hello,

Chinese? Teeworlds doesn't support any East Asian languages.

Please enable äöü at least. Perhaps just take a look at Danish and see how weird of a language it is! :D  I joke, but lack of unicode and non-English alphabets make friends list useless.

**Comment by MegaManSec** [comment]
for reference: https://en.wikipedia.org/wiki/IDN_homograph_attack

**Comment by heinrich5991** [comment]
This can be defeated by e.g. enumerating similarly-looking names just as we enumerate same names today.

**Comment by oy** [comment]
Fixed by 85b4cfd2455983ae62fe88e838882af0c2f6c3d7.
