### ISSUE TITLE
[map editor] texture aspect ratio

### ISSUE THREAD

**Issue by Landil** [teeworlds/teeworlds#1132]
If you use the seamless pattern functionality of a quad (shift+click on the nodes and mouse drag) you can create seamless patterns. But it is nearly impossible to keep the original aspect ratio. A click on the aspect ratio button currently uses the graphic's aspect ratio instead of the shifted and looped pattern. Thus we have a lot of blur effects in official maps.

It's hard to explain. If you did not understand and wanna help, ask me.

**Comment by oy** [comment]
Guess this should be fine now (de82ad7a26d6ebb6029a6e60c619f8a310ea2ee6) as you can adjust the texture offsets directly via buttons. If this still needs improvements, leave a reply. @Landil
