### ISSUE TITLE
Remove weapons with no ammo

### ISSUE THREAD

**Issue by Landil** [teeworlds/teeworlds#1133]
It does not make sense to let it show up in the mouse wheel selection cycle, just because you had it once. It is really annoying. Not only for beginners, even for intermediate players as I am. Removing out of ammo weapons from the cycle would follow the keep it simple strategy. It fastens game play for people who use the mouse wheel.

The very tiny advantage at survival pretending to have a full loaded weapon without having it can be kept by allowing to select the weapon with corresponding weapon key.

**Comment by oy** [comment]
Won't fix - discussed before, it's part of the game.
