### ISSUE TITLE
[game graphics] Weapon spawn place graphics

### ISSUE THREAD

**Issue by Landil** [teeworlds/teeworlds#1134]
![image1](https://f.cloud.github.com/assets/333183/1007701/a0a4f828-0b0e-11e3-887d-c68aea8bc480.png)

This has been on the to-do list since 0.3 and now I've just made a gfx-concept.
Two tile wide spawn places look best (I suggest using quads instead). A solution for in-air spawn places needs to be found.

Another idea which can be realized with this is to let the spawn point blink a couple of seconds before the weapons respawn.

Please give feedback if you want to implement it. 

edit:
:-1: The weapon colors need be more present

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
