### ISSUE TITLE
update_localization.py infinite loop

### ISSUE THREAD

**Issue by MegaManSec** [teeworlds/teeworlds#1185]
Running update_localization.py multiple times, makes it change every time.
For example;

I run it the first time, and git commit .. https://github.com/MegaManSec/teeworlds-translation/commit/569314620a80989044fdb2125e8070fbbfa3dbca

Run it a second time, git commit.. https://github.com/MegaManSec/teeworlds-translation/commit/ede8fc206a27304a0b9332dd09ccf6cf99c59fec

 And a third tie.. https://github.com/MegaManSec/teeworlds-translation/commit/48cbd0a5fd12d7d163a5434d74f2418be73f300b , And you can see it's now the same as the original commit.

All I did was re-run update_localization.py

(Could I get confirmation that the correct person has read this, so I can delete my reeworlds-translation repo?)

**Comment by minus7** [comment]
Would be obsolete with #1239
