### ISSUE TITLE
Add shortcuts to the menu navigation

### ISSUE THREAD

**Issue by Sepulzera** [teeworlds/teeworlds#1200]
I want to propose to add shortcuts to the menu, e.g. F5 - refresh
Or in the main menu: p - Play, e - Editor, s - settings, q - quit

**Comment by CytraL** [comment]
Now you can:
LCTRL+LSHIFT+Q = EXIT
LCTRL+LSHIFT+D = TOGGLE DEBUG
LCTRL+LSHIFT+G = TOGGLE DEBUG GRAPHICS
LCTRL+LSHIFT+E = TOGGLE EDITOR

**Comment by Henningstone** [comment]
I also want 'enter' to open the serverlist if in the main menu, but 'F5' for refresh won't be done due to possible binding conflicts. This idea had been there yet.

**Comment by oy** [comment]
Fixed.
