### ISSUE TITLE
Add AppData

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1228]
As per request via email, we should consider adding an appdata file.

>Subject:     Please create an AppData file for Teeworlds
>Date:     Tue, 27 May 2014 12:12:01 +0100
>From:     Richard Hughes <<hugh...@gmail.com>>
>To:     contact@teeworlds.com
>
>Please consider writing and installing an AppData file with the
>application description and some screenshots, else Teeworlds looks
>really bad in the GNOME and KDE Software Centers. We'd love to
>showcase more applications, but without the extra data file we can't.
>See http://people.freedesktop.org/~hughsient/appdata/ for details;
>thanks!
>
>Richard

**Comment by minus7** [comment]
Depends on #1238

**Comment by oy** [comment]
Fixed by d1a09b7764012d633ef7db00154f0251f98654e9.
