### ISSUE TITLE
Uppercase 'i' looks like lowercase 'L'

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1241]
This can be used to spoof nicknames.

Previous issue #1106 was closed on grounds that the fonts won't be changed, however there should be other ways of fixing this issue.

I'm sorry for reopening so many issues, but they're simply closed without much of an explanation (like this one, where just a proposal for a fix was dismissed, not the issue itself), I can't reopen them and discussing them in the closed state just buries them somewhere where nobody reads it. This issue tracking is via github issues so asynchronous, maybe using a chat would be preferable instead of closing many issues as 'wontfix' and giving no opportunity to discuss the issues.

**Comment by oy** [comment]
Fixed by 85b4cfd2455983ae62fe88e838882af0c2f6c3d7.
