### ISSUE TITLE
RFC: Move to OpenGL 3+

### ISSUE THREAD

**Issue by cinaera** [teeworlds/teeworlds#1247]
The current graphics backend uses (mainly) OpenGL 1.1 functions.
There are several reasons to move towards a more modern approach:
* Greyscale shader for skins and menuimages (currently used a 2nd texture)
* Static vertexbuffer for a map (at least the tilelayers) instead of recreating all the tiles again each frame
* Correctly blend transparent text
* (General performance improvement)
* (Get rid of fixed pipeline)

**Comment by oy** [comment]
Won't fix. There's no real gain from that.
