### ISSUE TITLE
Make seek bar in demo player togglable

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1267]
> ![Picture of the seek bar in the demo player](http://i.solidfiles.net/adfe812963.png)
>Make this demo player [seek bar] be toggleable or automatically hide it after a few seconds. Makes it easier for video editors.
[wappsify – Teeworlds forums](https://www.teeworlds.com/forum/viewtopic.php?pid=111598#p111598).

**Comment by oy** [comment]
Fixed by 7e180dfdb9e4aaa24f2b7fb2032565e9763b2530 and following.
