### ISSUE TITLE
[RFC] Hide player votes until the local player voted

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1270]
> ![Picture of the voting interface with the current vote section grayed out](http://i.solidfiles.net/5f31e1a4f3.png)
> Because hivemind is strong. Maybe make it configurable by server admins so it can be disabled if not desired.
> [wappsify – Teeworlds forums](https://www.teeworlds.com/forum/viewtopic.php?pid=111598#p111598).

**Comment by Robyt3** [comment]
> Won't add, the actual vote behaviour is the better approach. - @oy #1280 #1345

That probably closes this issue or is there something left to discuss?
