### ISSUE TITLE
Compilation of 0.7 under Windows could be more convenient

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1275]
There should at least be a little python script which automatically downloads freetype and SDL.

**Comment by Learath2** [comment]
I use `git checkout 0.6 -- /other`. Which just replaces the other directory with the one from 0.6 which obv gets rid of library updates but does get you compiling code.

**Comment by Henningstone** [comment]
Just one question, if you checkout the thing from 0.6, how do you get SDL2 then?

**Comment by Learath2** [comment]
You don't that comment was before sdl2 stuff was merged in.

**Comment by Henningstone** [comment]
Oh sure. I didn't look at the date :O

**Comment by oy** [comment]
Fixed.
