### ISSUE TITLE
Flashing window on chat highlighting

### ISSUE THREAD

**Issue by cinaera** [teeworlds/teeworlds#1278]
Would be nice as notification when getting highlighted

**Comment by minus7** [comment]
Assuming you mean when Teeworlds is minimized the window should set a window hint so it blinks in the task bar?

**Comment by heinrich5991** [comment]
It's not too bad to call a platform-dependent function for this.

**Comment by oy** [comment]
Won't fix - sdl doesn't pvovide that feature. And doing it platform-dependent would be too much of a hassle regarding linux and OS X.

**Comment by heinrich5991** [comment]
Seriously? Why not Windows-only then?

**Comment by minus7** [comment]
Also, there's no need to remove labels, rather add a new one "wontfix"
