### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1287]
In `src/game/client/render_map.cpp`, there's dead code in `CRenderTools::RenderQuads`, line 249, there's a variable that's always `false`, later a condition is based on that variable.

Introduced in this commit: [3effd735](https://github.com/teeworlds/teeworlds/commit/3effd73596fb8c804d0e5dafbd95d1d1b62e5cf4).

@cinaera Do you still know why you changed this?

**Comment by jordy-ruiz** [comment]
@heinrich5991 I don't think the problem exists anymore, does it?

**Comment by heinrich5991** [comment]
It seems more code was commented out in https://github.com/teeworlds/teeworlds/commit/99f26dc020a8aa9d84207fdd3f1e9b889a3c8be0. That fixes the "dead code" part I guess, but we still have the code in comments.
