### ISSUE TITLE
You can pick up the flag after the game ended

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1291]
![You can pick up the flag after the game ended.](http://s14.directupload.net/images/140126/usvkxwme.png)

[Forum thread](https://www.teeworlds.com/forum/viewtopic.php?pid=109924#p109924)

Probably only needs a check in the flag code that it cannot be picked up while the game is over (paused?).

**Comment by Sonix-** [comment]
I doesn't make any issue anyway, imo

**Comment by cinaera** [comment]
Wasn't this fixed some time/years ago?

**Comment by tbu-** [comment]
I don't know, the forum post said it's `0.6.1` where this happened. @cinaera Can you point me to a fix?

**Comment by oy** [comment]
Invalid - fixed years ago.
