### ISSUE TITLE
Links to GitHub should be on the front page/downloads page

### ISSUE THREAD

**Issue by minus7** [teeworlds/teeworlds#1293]
The link is somewhere in the docs right now, probably not the best place.

**Comment by cinaera** [comment]
Maybe sth like this?
https://github.com/blog/273-github-ribbons

**Comment by minus7** [comment]
Isn't that more meant for the websites themselves? Not sure if that is the right thing

**Comment by minus7** [comment]
Added a link in the download box on the front page, will add one to the downloads page somewhere. The big space where the donation button used to be can probably be used somehow.
![screenshot - 2015-01-05 - 20 18 59](https://cloud.githubusercontent.com/assets/419104/5618335/3ea3c6aa-9518-11e4-97bd-f8fc68136606.png)
