### ISSUE TITLE
Master server list

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1296]
The master server list should probably return IPv4 addresses as `::/96` instead of `::ffff:0:0/96`, the current one is for actual routing, and the other one for storing IPv4 addresses in IPv6 addresses[[1]].

[1]: http://en.wikipedia.org/wiki/IPv6_address#Default_address_selection

**Comment by minus7** [comment]
The linked wikipedia article shows ::/96 as deprecated though. Also, we just use it as an indicator and parse to IPv4 addresses from it anyway (currently at least).

**Comment by oy** [comment]
Invalid.
