### ISSUE TITLE
Compiling Error with Fresh Source

### ISSUE THREAD

**Issue by TedRoastBeef** [teeworlds/teeworlds#1298]
My Bam Thros me a bunch of Errors if i try to Compile the Server.

im using vs 10 and i think anything is right.

Does anyone need mor Information Please write themto me

**Comment by MegaManSec** [comment]
Perhaps include the error messsage.

**Comment by TedRoastBeef** [comment]
[16/16] #1 link teeworlds_srv.exe
character.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1600
" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
flag.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1600" sti
mmt nicht mit dem Wert "1800" in console.obj ³berein.
laser.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1600" st
immt nicht mit dem Wert "1800" in console.obj ³berein.
pickup.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1600" s
timmt nicht mit dem Wert "1800" in console.obj ³berein.
projectile.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "160
0" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
entity.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1600" s
timmt nicht mit dem Wert "1800" in console.obj ³berein.
eventhandler.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1
600" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
gamecontext.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "16
00" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
gamecontroller.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert
"1600" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
ctf.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1600" stim
mt nicht mit dem Wert "1800" in console.obj ³berein.
tdm.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1600" stim
mt nicht mit dem Wert "1800" in console.obj ³berein.
gameworld.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1600
" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
player.obj : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1600" s
timmt nicht mit dem Wert "1800" in console.obj ³berein.
LIBCMT.lib(new.obj) : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert
 "1600" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
LIBCMT.lib(typinfo.obj) : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der
Wert "1600" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
LIBCMT.lib(stdexcpt.obj) : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der
 Wert "1600" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
LIBCMT.lib(typname.obj) : error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der
Wert "1600" stimmt nicht mit dem Wert "1800" in console.obj ³berein.
LINK : fatal error LNK1123: Fehler bei der Konvertierung in COFF: Datei ist ung³
ltig oder beschõdigt.
bam: 'teeworlds_srv.exe' error 1123
bam: error: a build step failed

its in Germany :/

**Comment by cinaera** [comment]
Remove all the *.obj files in your build directory and try to re-build everything

**Comment by TedRoastBeef** [comment]
did work :)

bam config
bam -c all

dont know why but now is all fine :)
