### ISSUE TITLE
Using gettext

### ISSUE THREAD

**Issue by SafaAlfulaij** [teeworlds/teeworlds#1300]
Current localization process uses a json file. It doesn't support plural strings or changing placeholder places (I think).
Using gettext will make things easier.

**Comment by heinrich5991** [comment]
Gettext doesn't support reordering, does it?

**Comment by SafaAlfulaij** [comment]
http://www.hep.by/gnu/gettext/c_002dformat.html#c_002dformat

**Comment by oy** [comment]
There are no plans to expand the localisation system in the near future.
Maybe that will be an idea some years in the future, maybe it gets removed completely. Will see some day. Closing it for now.
