### ISSUE TITLE
Sanitize path names

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1302]
Sanitize path names by removing ".." and "." from it.

**Comment by heinrich5991** [comment]
Sanitizing pathnames is hard, it would probably be best to just refuse to use pathnames including `/` or `\` – and if that's too much, disallow pathnames using `..`.

Some file systems might perform path normalizations, but I'm not sure how that affects `..` (think unicode zero-width space or so).

**Comment by oy** [comment]
Fixed by 6506cf4ddf5ede653eccfa6ceb59d737d466a66f and previous.

**Comment by heinrich5991** [comment]
From what I can see this still allows pathnames like `/etc/passwd`.

Have you researched in how OS X does path normalization? Or Windows? Might things like `.<zero-width-space>.` behave the same way as `..`.

**Comment by oy** [comment]
Subdirectories should be accessible.

**Comment by heinrich5991** [comment]
`/etc/passwd` is a global path specification and not necessarily a subdirectory though.

As said above, I don't know how this interacts with path normalization. The above is a definite vulnerability of the current function, the latter is a possible weakness that should be researched.

**Comment by oy** [comment]
Just paths+subdirectories specified in storage.cfg are accessible.
