### ISSUE TITLE
CRC calculation is wrong

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1307]
It starts with an initial value of 0, whereas another value should be used (can't remember which one). Could be fixed for 0.7, **should not** be fixed for 0.6.

**Comment by cinaera** [comment]
Do you mean like this(https://github.com/cinaera/teeworlds/commit/ed6df2df32368f550042a29b170995bcc54fac13)?
Following the usage example from zlib documentation
``` 
uLong crc = crc32(0L, Z_NULL, 0);

while (read_buffer(buffer, length) != EOF) {
	crc = crc32(crc, buffer, length);
}
```

**Comment by heinrich5991** [comment]
Yes.
