### ISSUE TITLE
Change Z-order of quads in a layer

### ISSUE THREAD

**Issue by cinaera** [teeworlds/teeworlds#1314]
On adding a new quad to a layer it will be placed in front of the other ones, but you can't change the Z-order per hand (reordering the array of quads)
Either adding an option in the context menu and/or using keybinds (pageup, pagedown, home, end) would be helpful

edit: fix typo

**Comment by heinrich5991** [comment]
Is there a default Z-order right now? Is it the order in which the quads are added to a group?

**Comment by heinrich5991** [comment]
I did not understand what this issue before @cinaera explained it to me on IRC: This issue is about changing the order in which quads from a *single* layer are rendered to the screen.
