### ISSUE TITLE
Add exit button to menu again

### ISSUE THREAD

**Issue by Henningstone** [teeworlds/teeworlds#1316]
IMO we should add an exit button to the menu or at least to the ingame overlay, like it used to be, because when I am on a server and then want to exit the game, it is really annoying if I have to go through three different menus, all the time clicking 'back' to finally reach the startscreen, from where I can exit (on prompt; another click). Of cause it is possible to bind `exit`, but this isn't what it's meant to be is it? And to be honest, how many people would waste a key for _exiting_ ;)
Or is there something else already in planning which will take the nice space near 'Disconnect' while on a server?

**Comment by ARomberg** [comment]
You don't have to "waste" a key to exit the game: Simply press Strg + Shift + Q

**Comment by Henningstone** [comment]
I'm not sure, but isn't this similar to an "dirty" exit? In previous versions I had the feeling that some settings or binding I made in the session weren't there anymore after doing this. Correct me if I'm talking rubbish :)

**Comment by ARomberg** [comment]
As far as I know, pressing Ctrl + Shift + Q is just like hitting "Exit" and then confirming with "Yes".

**Comment by oy** [comment]
Yeah using Ctrl+ Shift + Q closes the game correctly.
When you're not ingame you can use the escape button to get back to the main menu and open the quit dialog.

**Comment by Henningstone** [comment]
Ok thank you, I really was convinced that it used to be a dirty shutdown.
Anyway, I'm not sure how many usual players know this keycombo, though.
Closed.
