### ISSUE TITLE
Fix premultiplied alpha

### ISSUE THREAD

**Issue by cinaera** [teeworlds/teeworlds#1317]
Using PMA  (https://github.com/teeworlds/teeworlds/commit/c3bce451200c9a6a38a99dbe486e9102b3153213) seems to break blending.
Can be seen on ctf2: Animation of stars is wrong, they should fade in and out

**Comment by cinaera** [comment]
Not fixed, it's a general incompatibility with vertex colors.
Premultiplying the color doesn't solve the problem imho as the color attribute won't be interpolated correctly over the triangle/quad then.
Another example: 
![screenshot_2015-02-24_17-35-46](https://cloud.githubusercontent.com/assets/755260/6353903/4bac15d6-bc4c-11e4-86d1-f439d81bb02a.png)

**Comment by oy** [comment]
Could you upload that map file?

**Comment by cinaera** [comment]
https://github.com/cinaera/teeworlds-maps/raw/pma/pma.map
(unfortunatly github doesn't allow attaching it directly)

**Comment by cinaera** [comment]
I don't really see a way to achieve the same output compared with straight alpha by using the fixed-function pipeline only.
The vertex colors need to be non-premultiplied before the interpolation of the vertex attributes to prevent data loss of the rgb values (e.g (1.0, 1.0, 1.0, 0.0) and (1.0, 0.3, 0.7, 0.0) would create the same values).
The multiplication needs to happen in the pixel shader stage, which seems to be not possible.

**Comment by cinaera** [comment]
New test map concerning color interpolation
Expected output:
![screenshot_2015-02-27_11-18-50](https://cloud.githubusercontent.com/assets/755260/6410844/e3682e32-be72-11e4-90aa-03a2a1461c42.png)
https://github.com/cinaera/teeworlds-maps/blob/pma/pma2.map?raw=true

**Comment by oy** [comment]
That's a one example of how non-multiplied alphas mess up the colours when using transparencies. An alpha of zero means full transparency and should have no effect on the colours.
And it's correct that both (1.0, 1.0, 1.0, 0.0) and (1.0, 0.3, 0.7, 0.0) become (0, 0, 0, 0).

**Comment by oy** [comment]
Fixed.
