### ISSUE TITLE
[RFC yet] Custom texture support (texturepacks?)

### ISSUE THREAD

**Issue by Henningstone** [teeworlds/teeworlds#1321]
It would be interesting to have the possibility of having custom texture support, meaning you don't have to edit/replace the original files, but we'll have a folder to put them all into (the textures) and this folder will be placed into an texture collections folder, from which we can select a 'texture collection' in the options (like we are doing it for skins already, making it easy for the average-user to change the look of the game). I'll give an example (meaning the directory structure) to get you understand my weird explanation.
> ./teeworlds/data
> ../audio
> ../countryflags
> ../..........
> ../skins
>
> ../textures (or whatever to call it)  [--> the main directory for texture collections]
> .././default_textures :package:
> ../././game.png (the default one)
> ../././particles.png
> ../././some icons.png
> ../././every thing else go here.png
>
> .././custom_textures_1 :package:
> ../././game.png (now the edited one)
> ../././particles.png (edited too)

The packs may change things like e.g. weapons, particles or some icons, and everything which is _not_ in the custom pack will be loaded from the default one. That way, all the textures will finally get their own directory too :P

Might seem like a silly idea, but I think the community would make excessive use of it by creating tons of texturepacks (or how to call them?).

I really would like to have your opinion on this.

**Comment by oy** [comment]
You're supposed to use the "storage.cfg" for that. Put your custom content in a folder(layout similar to the data dir) and then put the path in the mentioned file(above "add_path $DATADIR" if you use the default one).

**Comment by heinrich5991** [comment]
That's not a convenient solution, "just edit that non-documented configuration file" is harder than "put it into the folder and select in Teeworlds".

**Comment by Henningstone** [comment]
That was my reason for opening this. Sure, you can search for tutorials online and many texture modders put their own tutorials within their forum threads, but it would be much more convenient to simply select one in the menu.
Anyway, you declined it so I won't hang up on this topic :)

**Comment by oy** [comment]
Well we ship teeworlds just with the(one) standard texture set and there're no plans to expand that. So there is no need to add that kinda ingame feature.

**Comment by Henningstone** [comment]
Yeah of cause, but, just to understand, my intention was that the community should make custom textures. We just would simplify everything a bit. But ok, might be too much to stick to the kiss principle :)
