### ISSUE TITLE
Rcon/Econ possible commands

### ISSUE THREAD

**Issue by Schwertspize** [teeworlds/teeworlds#1322]
Hi, is it possible to integrate a possiblecommands command in each server which displays all commands in rcon (and Econ!) and a feature in the client to render these commands (and only these commands) because the autocorrection and explaining mode is not good working in most of the mods. 
Also nice would be a graphical Econ like in f3
Thanks

**Comment by oy** [comment]
Invalid. There already is for the rcon - won't add sth for econ.
