### ISSUE TITLE
Fail2ban

### ISSUE THREAD

**Issue by Schwertspize** [teeworlds/teeworlds#1323]
Can someone change the time format for logging to yyyy and not only yy

**Comment by MegaManSec** [comment]
Why?
What does this have to do with fail2ban?

**Comment by Schwertspize** [comment]
Sorry, but I found some article where this problem is explained. Fail2ban can't work with logs in that format, but I think many people want to use that tool
https://gist.github.com/floreo/3f0612641c104d38fc23 he uses gawk to change the output, a very bad solution...

**Comment by Schwertspize** [comment]
I tried that way and normal starting, the only thing that is not good for fail2ban is the yy

**Comment by oy** [comment]
Invalid. That is a timer - "The value returned generally represents number of seconds since 00:00 hours, Jan 1, 1970 UTC".
