### ISSUE TITLE
Console history not working

### ISSUE THREAD

**Issue by cinaera** [teeworlds/teeworlds#1331]
It's not possible to walk through the console history (least recent submitted commands) via `Up/Down`-Keys.

**Comment by pielover88888** [comment]
Walking through the console history is done with pageup/pagedown if I am not mistaken.

**Comment by Henningstone** [comment]
You are right, and I even have to add that no more keys are working in console anymore! Neither Up/Down to recall the typed commands, nor PageUp/PageDown to scroll through the history.

**Comment by Henningstone** [comment]
Just messed around a bit with the console code to determine the problem.
If you change that `else if (Event.m_Key == KEY_UP)` in Line 117 to for example `else if (Event.m_Key == KEY_W)` everything will work well: Pressing W in console will recall the command you executed before!

**Comment by Pierre-Sassoulas** [comment]
Probably related with the SDL update (#1246)
