### ISSUE TITLE
Button fading not working correctly

### ISSUE THREAD

**Issue by Zwelf** [teeworlds/teeworlds#1337]
When you reenter a menu, the button you previously pressed, is still fading out, no matter how long you have been elsewhere.

**Comment by Henningstone** [comment]
I think I may know now what causes this. (Unfortunately not how to fix it, yet)

The fadevalue is being calculated and then stored in the variable which's address serves as the button's id (```pID```). This variable is a static one, so the value in it (= the fadevalue) is being kept throughout calls. This means, when re-entering the menu, the value is exactly the same like when you left it.


Look at the function which calculates the fadevalue:
https://github.com/teeworlds/teeworlds/blob/master/src/game/client/components/menus.cpp#L78-L90
It gets the pID and then returns it again? Makes no sense to me, never mind.

Therefore, it could return nothing instead, and this
https://github.com/teeworlds/teeworlds/blob/master/src/game/client/components/menus.cpp#L128-L128
could have been written like that:
```c++
ButtonFade(pID, Seconds, Checked);
float *pFade = (float*)pID;
```
just to tell you what I mean.
Sure is, that it causes the fading error.
