### ISSUE TITLE
Nickname tab completion using shift-tab is broken.

### ISSUE THREAD

**Issue by tbu-** [teeworlds/teeworlds#1340]
To reproduce this, press the chat key, then tab, and then shift-tab. The expected result is that you get one name in the chat name, but the actual result is that you get two, like this: "First Player: First Player|" (`|` indicates the cursor).

Could be a candidate for inclusion in the 0.6 series.

**Comment by Henningstone** [comment]
It isn't broken, it actually doesn't exist. Pressing any key than `tab` will cause the automatic completion to reset, and a 'backjump' is not intended.
So typing something is in this case the same as clicking your mouse or pressing shift. Just try any key you can imagine; as long as you don't press tab, it will show exactly the same behaviour.

**Comment by Zwelf** [comment]
If it isn't a bug, it should be a new feature. It would be nice to go back in the name list by pressing shift-tab.

**Comment by oy** [comment]
Fixed.
