### ISSUE TITLE
Add favourites to serverlist

### ISSUE THREAD

**Issue by Henningstone** [teeworlds/teeworlds#1343]
There is no more thing like the old "Favorites" button in 0.6 to only see the favorite servers. In my opinion, therefore the "favorites" tab in the serverlist should be at least right at the top, because this are my favorite servers and of cause I don't want to scroll down all the way to see them, do I? Or is there any deeper intention behind having them at the bottom?

**Comment by pielover88888** [comment]
I agree, they should be at the top. Perhaps at the top of the serverlist inside a collapsible box/accordion-like thing?

**Comment by oy** [comment]
There will be favourite list box within the server list - not done yet.

**Comment by Dune-jr** [comment]
@oy This should probably be closed.
