### ISSUE TITLE
RFC: Maybe a new Gamemode?

### ISSUE THREAD

**Issue by Henningstone** [teeworlds/teeworlds#1349]
Teeworlds 0.7 is indeed a very big update. Might it worth to think of a new vanilla gamemode to make the whole thing even more exciting? Because this topic is very hot in the community and so many people would like to see something completely new after all these years, I thought of poking this topic over to the development, since it hasn't really been discussed yet here. I don't say "we need a new gamemode, or otherwise it would be boring", and it doesn't (and shouldn't) has to be something totally overestimated or even a clone of a mod! Just a new vanilla gamemode, and I think the community would be exited about discovering something new. Another big pro argument is that users doesn't have to look for and set up a modserver if they want something different from the classic stuff, but they only have to do `sv_gamemode gamemode` and there you go.

If you may have ideas for new gamemodes to get a actual imagination, you are most requested to post them.
I would be grateful about hearing some statements and other opinions, to get discussion running :)
I'm personally in favour of the idea of playing (and making :P) a new official gamemode. There are so many possibilities...

**Comment by MegaManSec** [comment]
race

**Comment by Henningstone** [comment]
I knew that this will come :D

**Comment by MegaManSec** [comment]
A very simple zombie gamemode would be good. It's probably the most common mod for games.

**Comment by Henningstone** [comment]
Yeah, zomies are everywere and are watching you! :mag: No, just joking :)

I thought of something which is a bit tactically, for example to destroy the enemy base or something.

**Comment by KillaBilla** [comment]
* Writing a *good* zombie AI is most likely too much work for anyone and playing against a bad AI seems boring too me
* Race gametype is already approved (#33)
* Some gametypes that most other games have (i.e. Domination, Defusion) would be interesting

**Comment by heinrich5991** [comment]
@Henningstone As it happens, Teeworlds 0.7 already has a new gametype, LMS – Last man standing and SUR – Survival. For each of them death is permanent until the end of the round, no pickups spawn besides the initial ones and the last tee or the last team that survives wins.

**Comment by Henningstone** [comment]
Oh ok, that is interesting. I have to admit that I didn't know that :). Something like these gametypes came actually to my mind too. But I can totally agree with point 3 of KillaBilla aswell; some kind of teamplay-enforcing gameplay would be very nice. To get an example: now, only the score connects the team. For the classic gametypes and for these new ones either, you don't really have to play together with your team mates (maybe a bit at CTF since you could defend the flag carrier, but well, who does?...).
On the other hand, it would need a testing if something like this will work for the actually very fast teeworlds gameplay.

**Comment by Zwelf** [comment]
In my opinion it woud be great if Double Domination would be added.
> Double Domination — Your team scores by capturing and holding both Control Points for ten seconds. Control Points are captured by touching them. After scoring, the Control Points are reset to neutral.

**Comment by Henningstone** [comment]
Yeah, also thought of such.

**Comment by oy** [comment]
0.7 will provide 2 new gametypes last man standing(lms) and survival(sur).
Some domination gametype might be added as well - not sure yet.

**Comment by Henningstone** [comment]
Yeah I was told yet, sorry for my misknowledge :)

**Comment by TheRealOrangus** [comment]
GTF/HTF - Grab/Hold The Flag, a non-team gamemode with 1 flag for all players, they would fight for it, the player which holds the flag is getting points over time.

**Comment by Henningstone** [comment]
Good idea! It may be a very funny and fast gamemode. I think I gonna write it :)

**Comment by android272** [comment]
Halo had a game type called odd ball where you try to hold the skull for
the longest time.  In odd ball you could only use the skull as a melee
weapon to kill people or drop the skull to use your weapons. But if you
doped the skull you are not gaining points for holding the skull. In most
games the first player to hold the skull for two minutes won.

--
Jesus is my Lord and Savior. Praise be unto God for giving us a way to live
with him.

<https://www.facebook.com/android272>
<https://plus.google.com/u/0/113439282950133616549/posts>
<http://www.linkedin.com/pub/andrew-pullins/6a/2b3/366>
<https://twitter.com/android272>  <http://android272.deviantart.com/>

**Comment by android272** [comment]
Halo had a game type called odd ball where you try to hold the skull for the longest time.  In odd ball you could only use the skull as a melee weapon to kill people or drop the skull to use your weapons. But if you doped the skull you are not gaining points for holding the skull. In most games the first player to hold the skull for two minutes won.

**Comment by android272** [comment]
Zombie/Survival game mode:
The object of the game is for the "living" players to stay "uninfected" as long as possible while the zombies try to kill every living player.
 
A player is selected at random to become the Zombie at the start of the game, but this can be changed in the options. The goal of a zombie is to infect as many living players as possible. When a Zombie kills a living player, they are infected and they become a zombie.  Zombies drops their guns and then can only use a hammer.  The more living players a Zombie kills the more points they gain.
Living players keep their keep their Tee color while Zombies turn dark green.
When there is just one living player left, they are declared "Last Man Standing".


Juggernaut: At the start of the game a player is randomly selected to be the juggernaut. The juggernaut is a ninja with infinite time/slashes (what ever makes the ninja power go away.) Killing the ninja will make you the ninja. The player who has been the ninja the longest after 2 minutes wins the round.


King of the Hill: Team/single player that has control of the hill for (2 minutes) wins.

Territories: Like King of the hill but there are multiple hills(six or so) to take control of.  Take a territory by standing near it for a certain amount of time. The enemy team can take territories back by killing those who have captured that territory and standing near it to capture. 

There are two bases on the ends of the map with three territory on each half of the map. each territories that is captured moves your teams spawn point closer to the enemy base.

**Comment by Henningstone** [comment]
1. You just told us how the mod "Zombie" works, fine :)
2. The same as in the post above mentioned "Hold the Flag" but with ninja instead of flag
3. Would not fit into the fast gameplay of teeworlds I think since you have to stand on the Hill to win
4. This exists as a mod too, it's called "Battle" (also know as "Battlefield")

**Comment by android272** [comment]
3.  you have not played in the king of the hill matches that I have then. King of the hill can be extremely fast pace and cathodic.  In a small map, with one static hill you are lucky if you serve 3 seconds on the hill.

1. / 2.  would it be too hard to take these mods and add them to the game? if the work is already done why not integrate them into Teeworlds?

**Comment by ObaniGemini** [comment]
I agree with Domination game mode. It's a very famous mode and has not been implemented even has a custom mod yet (Excepted in Battlefield mode, but it has so much elements that it cannot be compared to a simple Domination)

**Comment by cinaera** [comment]
Concerning domination: I've some basic implementation floating around on my repository, would need a proper concept as it's currently rather a prototype (no sound samples, lacking visual support, gameplay..)
https://github.com/cinaera/teeworlds/commits/domination

**Comment by ObaniGemini** [comment]
@cinaera : this looks really interesting !
Maybe shall we start a new issue for this domination mod and list everything to do for it, and what has already been done.

**Comment by Slinack** [comment]
Also we'd need perfectly balanced maps for each new gametype suggested (which may be the hardest part).
I think we could do that for domination, if we really wanted to add it.

**Comment by ObaniGemini** [comment]
Perfectly balanced maps are not so hard to make. For survival, just do not put a too cheated spawn, for team-play, make the map look symetric.
So it would be hard to make balanced maps if they're not symetric, than if they are

**Comment by Slinack** [comment]
Are you kidding? Look at how many successful ctf maps were ever made...

**Comment by TheRealOrangus** [comment]
> Perfectly balanced maps are not so hard to make. For survival, just do not put a too cheated spawn, for team-play, make the map look symetric.
So it would be hard to make balanced maps if they're not symetric, than if they are

What?

> Are you kidding? Look at how many successful ctf maps were ever made...

Agree.

**Comment by heinrich5991** [comment]
@TheRealOrangus Please don't make a post to just disrespectfully disagree. Thanks.

**Comment by DekuScrub** [comment]
I've mentioned this on the main TW forums, but I think that the names "LMS" and "SUR" aren't very elegant, especially if the only difference is whether there are teams. I think a more concise and more self-explanatory naming scheme would be EL - Elimination; and TEL - Team Elimination. Keeps it simple.
If I'm not mistaken, "Elimination" is the common name used by other games to refer to this type of mode, and for basic modes it's best to stick with the common names so as to avoid confusion...

**Comment by Irradius** [comment]
mine tee, in a more simple way

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
