### ISSUE TITLE
The server should try to open a port of the router

### ISSUE THREAD

**Issue by Zwelf** [teeworlds/teeworlds#1353]
It would be easier for players, if the server automatially open the port at the router. This should happen, if the config var sv_register is 1.

**Comment by pielover88888** [comment]
Seeing as routers require you to log in to do things such as port forward, and seemingly every router handles port forwarding differently, I doubt this is achievable.

**Comment by BotoX** [comment]
https://github.com/BotoX/teeworlds/tree/upnp-portmap

**Comment by oy** [comment]
Won't fix. That's up to the server hosters and people who don't know how to host a server shouldn't host one.
