### ISSUE TITLE
Remove fork status of this repo

### ISSUE THREAD

**Issue by Croydon** [teeworlds/teeworlds#1355]
Since it's a permanent "fork" remove the status from this repo. You can do this by simple contact the GitHub support here: https://github.com/contact

For the next time: You can also transfer repos from one account to another one or an organisation. So forking wasn't really necessary at this point.

**Comment by Henningstone** [comment]
Good idea, since this is the main repo of teewords now.

**Comment by Schwertspize** [comment]
please, oy. just do it :D 5 minutes

**Comment by ObaniGemini** [comment]
I totally agree with this

**Comment by Croydon** [comment]
Why did this never happen? It is -really- easy.

**Comment by ObaniGemini** [comment]
I think there's no teeworlds devel anymore, and if there's one, it has not any goal. Follow [ninslash](ninslash.com) or some modes if you want to see some activity :)

**Comment by oy** [comment]
Done.
