### ISSUE TITLE
Tournament chat mode

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1368]
Add a feature to automatically limit the chat-mode for spectators to team when a game is running(not paused/warmup/ended/authed).

**Comment by Meskalin** [comment]
How exactly should this work? Just don't send the message/display an error when the spectator trys to send a message in the normal chat or automatically redirect any message to the team chat?

**Comment by heinrich5991** [comment]
I'd say automatically redirect it to team chat.

**Comment by Henningstone** [comment]
Would be the easiest and most efficient way to implement it, IMO.

**Comment by oy** [comment]
"automatically redirect any message to the team chat" yeah.

**Comment by savander** [comment]
https://github.com/savander/VanillaMod/blob/0.6/src/engine/shared/config_variables.h#L114
https://github.com/savander/VanillaMod/blob/0.6/src/game/server/gamecontext.cpp#L655-L669

Like this?

**Comment by Henningstone** [comment]
Disabling the chat completely is not the intention behind this. Rather forcing spectators' chat into team, so that players cannot read it. This restriction should leave out admins (authed).

**Comment by savander** [comment]
it works like that, you have 3 configurations. Spectators can't talk, only admin can talk and nobody can't talk(exclude authed). ( admin can talk in every configuration)

**Comment by oy** [comment]
Fixed.
