### ISSUE TITLE
Reopen "Changing skin only take effect when you change the server"

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1369]
There are many solutions to "abuse" of this function, but crippling the UX for anybody is not a good one. I don't know why you closed this and I find the current behavior very user-unfriendly and definitely not the way to go for a casual game.

I would like to discuss these issues with you directly, but this always has high-latency and as such the only resort I see is to reopen each of the issues where I strongly disagree with the closing.

See also #1350.

**Comment by oy** [comment]
Duplicate #1350.
