### ISSUE TITLE
Reopen "The server should try to open a port of the router"

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1370]
Casual players might want to open a server and this should not be made harder than usual, and this seems to be by far the most common issue with server creation. We shouldn't hinder people from exploring new things, and this includes hosting their own server with their own map that they just created in the editor.

See also #1353.

**Comment by oy** [comment]
@1370, 1369
Teeworlds isn't heading for casual players/mainstream. It's a niche game and it'll stay that way. Furthermore i'm keeping it minimalistic and not bloat it with features. It already got a few steps in the wrong direction and I'll cut down some things here and there.

Next time continue in the original topic and don't spam new ones.

Dupicate #1353.
