### ISSUE TITLE
vector2_base<T> constructor wrong type

### ISSUE THREAD

**Issue by kichris** [teeworlds/teeworlds#1371]
https://github.com/teeworlds/teeworlds/blob/master/src/base/vmath.h#L20
	vector2_base(float nx, float ny)
	{
		x = nx;
		y = ny;
	}
the class' constructor only accepts floats, despite the fact that the type of x and y are T, which could be anything else
same for vector3_base and vector4_base

**Comment by heinrich5991** [comment]
Good find!
