### ISSUE TITLE
Add serversided localization

### ISSUE THREAD

**Issue by Henningstone** [teeworlds/teeworlds#1374]
Just a idea I've had: Serversided stuff could be localized by the server instead of the client (e.g. serverchat etc.).
The server would just needs the language setting of each client, and so can localize the strings before sending it to them. Mainly, this would give modders a lot more possibilities about custom localizations, but imo it makes much more sense, too.

**Comment by Meskalin** [comment]
I think some messages (join/leave) are client-side in 0.7 already... Not sure if they are localized, Ill take a look at it later.

**Comment by Henningstone** [comment]
Oh that is actually what I was thinking of :)
But not quite, because I thought of moving this client-sided localizations of server-sided string to the server. The implementation of this can be used by modders then, to localize any of their string. (Just for understanding, _not_ the server sets the language in this scenario, but the client tells the server which language it wants and the strings will be localized individually)

**Comment by Meskalin** [comment]
Ah right, now I got it! I agree, that would be nice.

**Comment by oy** [comment]
Won't fix. Mods are irrelevant for the development process. The actual system is sufficient and the servers shouldn't play a role in the localisation.
