### ISSUE TITLE
Welcome Page and Settings

### ISSUE THREAD

**Issue by K1773R** [teeworlds/teeworlds#1376]
v0.6.3 built from source
armv7l @ odroid X2 with glshim

- dosnt create settings.cfg
- settings arent saved
- always shows welcome page

when exiting the game, i get this
[55aa6513][client]: disconnecting. reason='unknown'
*** Error in `git/teeworlds/teeworlds': free(): invalid pointer: 0x0021420c ***
Aborted

**Comment by heinrich5991** [comment]
Whic OS are you on? odroid -> Android?

**Comment by K1773R** [comment]
linux

**Comment by heinrich5991** [comment]
Could you try to run `teeworlds` in a debugger? Like, execute
```gdb ./teeworlds```
and when it crashes, type `bt` into the debugger console and paste the output here.

**Comment by K1773R** [comment]
already did in the meantime ;)
i get different error each time i do a bt.

i think this is because of glshim/glues...

Program received signal SIGABRT, Aborted.
__libc_do_syscall ()
    at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
44	../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb) bt
#0  __libc_do_syscall ()
    at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
#1  0xb6c1af0e in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xb6c1d766 in __GI_abort () at abort.c:89
#3  0xb6c16150 in __assert_fail_base (
    fmt=0x1 <error: Cannot access memory at address 0x1>, 
    assertion=0xb6fab010 "((mutex)->__data.__kind & 127) == PTHREAD_MUTEX_ERRORCHECK_NP", assertion@entry=0x0, file=0xb6fab36c "pthread_mutex_lock.c", 
    file@entry=0xb6486220 "\001", line=151, line@entry=3066925228, 
    function=function@entry=0xb6fab06c <__PRETTY_FUNCTION__.10293> "__pthread_mutex_lock") at assert.c:92
#4  0xb6c161e6 in __GI___assert_fail (assertion=0x0, file=0xb6486220 "\001", 
    line=3066925228, line@entry=151, 
    function=0xb6fab06c <__PRETTY_FUNCTION__.10293> "__pthread_mutex_lock")
    at assert.c:101
#5  0xb6fa4a1e in __GI___pthread_mutex_lock (mutex=0xb6cd90ac <lock>)
    at pthread_mutex_lock.c:151
#6  0xb6b3b43c in XrmDestroyDatabase ()
   from /usr/lib/arm-linux-gnueabihf/libX11.so.6
#7  0xb6b2bfe4 in _XFreeDisplayStructure ()
   from /usr/lib/arm-linux-gnueabihf/libX11.so.6
#8  0xb6b212bc in XCloseDisplay ()
   from /usr/lib/arm-linux-gnueabihf/libX11.so.6
#9  0xb6e3d60e in ?? () from /usr/lib/arm-linux-gnueabihf/libSDL-1.2.so.0

**Comment by heinrich5991** [comment]
Mh. I don't really know what this backtrace means. It seems the process is handling some kind of signal (?).

**Comment by K1773R** [comment]
happens with nexuiz via glshim too. once GL is destroyed it crashes. so its not a teeworld issue.
