### ISSUE TITLE
Don't open the console while starting Teeworlds 

### ISSUE THREAD

**Issue by Zwelf** [teeworlds/teeworlds#1378]
Write the log into a file instead.

**Comment by KillaBilla** [comment]
You can add -s as an argument when running teeworlds to hide the console. See #48

**Comment by Zwelf** [comment]
Normal users don't require this console. Hiding the console should be enabled by default.

**Comment by heinrich5991** [comment]
@KillaBilla The console still opens for a brief time if you pass that parameter.

**Comment by oy** [comment]
Won't fix. Use the -s start param to hide the console as suggested.
