### ISSUE TITLE
Extra projectile messages should not be vital, but rather flush

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1381]
The vital flag means that it gets a sequence number, but extra projectiles should be handled the same way as snapshots, i.e. no problem if they get lost. They should also get the flush flag so they get sent out immediately.

**Comment by heinrich5991** [comment]
And apparently the client won't accept extra projectiles from old servers.

**Comment by east** [comment]
I agree, extra projectile shouldn't be vital and there has to be an exception since the client drops non-vital game messages.

**Comment by oy** [comment]
Pretty useless feature that should have stayed buried. Should remove that.

**Comment by heinrich5991** [comment]
It allows the server to send the projectile if it's not in the tick that gets snapshotted.
