### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Neox76** [teeworlds/teeworlds#1382]
The client can be crashed if the server sends something wrong about snapshots.
As I don't know many things about snapshots and that I have the fix for the client, I'll tell you all I know about the bug ;
Go to src\engine\shared\snapshot.cpp
Then here :
```
 // unpack updated stuff
 for(int i = 0; i < pDelta->m_NumUpdateItems; i++)
 {
  if(pData+2 > pEnd)
   return -1;

  Type = *pData++;
  ID = *pData++;
  if(m_aItemSizes[Type])
   ItemSize = m_aItemSizes[Type];
```
The problem is that pData can get a negative value, and of course no negative values for arrays... (pData has a negative value, which is attributed to Type and ID)
The fix I've written is this :
```
  Type = *pData++;
  ID = *pData++;
  if(Type < 0)
   return 0;//change the return value, idk what to return
  if(m_aItemSizes[Type])
   ItemSize = m_aItemSizes[Type];
```

**Comment by KillaBilla** [comment]
To whoever fixed this: some parameter names are not conform to the naming convention / misspelled:
- snapshot.h:110 `int Get(int Tick, int64 *Tagtime, CSnapshot **pData, CSnapshot **ppAltData);`<br>Arguments should be `int64 *pTagtime` and `CSnapshot **ppData`
- snapshot.h:135 `int Finish(void *Snapdata);`<br>Argument should be `void *pSnapdata`
- snapshot.cpp:530 `int CSnapshotBuilder::Finish(void *SpnapData)`<br>Argument should be `void *pSnapdata`
