### ISSUE TITLE
(0.6) Map download doesn't start

### ISSUE THREAD

**Issue by Henningstone** [teeworlds/teeworlds#1385]
Fresh compiled 0.6 branch, the map download doesn't start when joining a server.
Or is that a incompatibilitiy between 0.6.3 and 0.6.4?

**Comment by east** [comment]
See here:
https://github.com/teeworlds/teeworlds/commit/f457b58d68e72df83128a7bc779d71a5208dfe47#commitcomment-12771442
Many modifications do not use VITAL flag for MAP_DATA messages.

**Comment by oy** [comment]
Invalid. Works fine - don't care about mods.
