### ISSUE TITLE
Mistake in your code in src/base/vmath.h

### ISSUE THREAD

**Issue by TheRealOrangus** [teeworlds/teeworlds#1387]
In 0.6 branch, in src/base/vmath.h, at line 29(I think), there is:
`vector2_base operator /(const T v) const { return vector3_base(x/v, y/v); }`
It tries to return vector3 in vector2 overloaded operator, which makes compilation errors.
Replace it with 
`vector2_base operator /(const T v) const { return vector2_base(x/v, y/v); }`
please.

**Comment by oy** [comment]
Fixed.
