### ISSUE TITLE
Some sequence bits unused

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1396]
Currently there's some unused bits in the `ack` field in packet headers, namely the upper two bits. This is because `NET_MAX_SEQUENCE` is defined as `1<<10`.

Cannot be changed in a backward-compatible fashion, thus it's 0.7 only.

**Comment by oy** [comment]
I know - wil be fixed with the token stuff.

**Comment by oy** [comment]
Invalid.
