### ISSUE TITLE
Flip Tee's feet when looking left

### ISSUE THREAD

**Issue by android272** [teeworlds/teeworlds#1399]
The next thing that would make Tees look better would be to turn their feet around and flip their skin when they look left.  Currently when a Tee is looking left it looks as though their feet are pointing right and when they walk left and it looks odd. 

I purpose that the Tee's feet be flipped when they look left or 91° to 270° and then flipped again when they look right or 90° to 271°.

![trun body](https://cloud.githubusercontent.com/assets/5912527/9835003/1d5a17ac-59a2-11e5-825f-3fea9eb9b133.png)

**Comment by android272** [comment]
This is how the tees would look if this issue were to be put in place. On the left you see what I think looks like a better tee, of the right you see a tee that looks odd.  The eyes are looking left but the body looks as though it is still looking right.
![tees eyes move](https://cloud.githubusercontent.com/assets/5912527/10561439/eab87fb2-74f6-11e5-811c-ef571ccd5452.gif)

some people have brought up how this will not look good with high-sens players. And my responce to that is that high-sens players do not look good today, so you would rather every player look bad instead?  why no make most players look better?
![tee eyes move fast](https://cloud.githubusercontent.com/assets/5912527/10561440/ee14442a-74f6-11e5-8d4c-3a994514760d.gif)

**Comment by oy** [comment]
Won't fix - this would be just annoying with mouse movements.
