### ISSUE TITLE
Flip Tee's body when looking left

### ISSUE THREAD

**Issue by android272** [teeworlds/teeworlds#1400]
There are many skins out there that do not look good when the Tee is looking left as they do when they are looking right.  I purpose that the skin be flipped when the Tee looks left or 91° to 270° and then fliped again when they look right or 90° to 271°.

![flip skin](https://cloud.githubusercontent.com/assets/5912527/9834998/fadf9364-59a1-11e5-901b-f4be96d194ae.png)

**Comment by xushTW** [comment]
Not sure, but i think there are no really non-symmetric standard skins.

Plus this would disturbing for high-sens players.

**Comment by android272** [comment]
Yes this is not a problem for symmetric skins.  They are symmetric because asymmetric skins looks strange when you look left or right and the skin does not change with the direction the player is looking.  

The problem with symmetric skins is that it looks very weird as the body looks as though it is looking striate at the the audience but there feet and eyes look as though they are looking right(not left as the feet are wrong as well see https://github.com/teeworlds/teeworlds/issues/1398).

how would this be distutbing for high-sens players? what does that even mean?

**Comment by TsFreddie** [comment]
high-sens players.
![spinning](https://cloud.githubusercontent.com/assets/3797859/9839612/7e8bd712-5a34-11e5-9e02-b2b08a90dbf0.gif)
![spinning2](https://cloud.githubusercontent.com/assets/3797859/9839628/d0deae0e-5a34-11e5-947c-c7884a0498ab.gif)

**Comment by TsFreddie** [comment]
if we do flip the tee, we might need a separate shadow layer or design both sides of tee individually.

**Comment by android272** [comment]
I think it would look a lot better. Exempt for the hign-sens players, they already annoy me. Looks too twitchy or like bots to me.  But I don't see too many of them.

**Comment by TsFreddie** [comment]
I just want to make a GIF xD. I already made flipping skin into my own client, it just looks weird on 0.6 skin system. We NEED a separate shadow layer to achieve the natural feeling.

**Comment by android272** [comment]
High-sens players in my opinion look like crap today.  I don't think that a feature that will make Tees look better overall should be shot down because there are some high-sens players that will make it look like crap when they already do.

**Comment by TsFreddie** [comment]
Stop using the word "crap" then everybody wins. Don't let the post start to being offensive. Nobody have definitely disagreed with you so far, just chill and wait code implementation first.

**Comment by android272** [comment]
I was posting this because someone posted on this https://github.com/teeworlds/teeworlds/issues/1401 that what you pointed out would make them look like "crap".  I just wanted to let it be known on this issue that I don't think high-sens players look as well as they could either way. Whether or not this issue gets implemented high-sens players Tees don't look good.

**Comment by android272** [comment]
This is how the tees would look if this issue were to be put in place. On the left you see what I think looks like a better tee, of the right you see a tee that looks odd.  The eyes are looking left but the body looks as though it is still looking right.
![tees eyes move](https://cloud.githubusercontent.com/assets/5912527/10561480/17b61438-74f8-11e5-9c5e-308aea1454ed.gif)
some people have brought up how this will not look good with high-sens players. And my responce to that is that high-sens players do not look good today, so you would rather every player look bad instead?  why no make most players look better?
![tee eyes move fast](https://cloud.githubusercontent.com/assets/5912527/10561481/19c6b91c-74f8-11e5-8d6d-261791b7c551.gif)

**Comment by Henningstone** [comment]
A possibility to get it all together would be to make an option to disable the flipping, so that high-sens players or players who just don't like the feature can disable it, according to their needs.

**Comment by TheRealOrangus** [comment]
Flipping same image would look ugly because shadow is also flipped, so 2 images per skin have to be drawn.

> A possibility to get it all together would be to make an option to disable the flipping, so that high-sens players or players who just don't like the feature can disable it, according to their needs.

Which one would be used then?

**Comment by android272** [comment]
>Flipping same image would look ugly because shadow is also flipped, so 2 images per skin have to be drawn.

I think that having two bodies one for each side with different shadows would look much better as well.  This post is mostly about pointing out the fact that tees look really strange when their bodies do not change direction with their eyes.  They look fine if the user is playing with the default skin or a symmetric skin, but in the case of a asymmetric skin like above they look rather odd.

**Comment by ObaniGemini** [comment]
@android272 : it's not really about high sens but personally I can't play without turning my crosshair everywhere so this feature would be really bad to me :x

**Comment by oy** [comment]
Won't fix - this would be just annoying with mouse movements.

**Comment by Soreu** [comment]
What about making it dependent on last tee movement direction - either player own movement or someone hooking him (I'd rather keep weapons not affecting facing direction) - instead of on mouse movements?
Then it shouldn't be annoying at all (well, maybe except for guys who love to do moonwalk), and still would look much better than currently

**Comment by android272** [comment]
> What about making it dependent on last tee movement direction - either player own movement or someone hooking him (I'd rather keep weapons not affecting facing direction) - instead of on mouse movements?
Then it shouldn't be annoying at all (well, maybe except for guys who love to do moonwalk), and still would look much better than currently

I feel as though this would make more since if this game was like mario and did not have you aiming your gun with the mouse.  If Teeworlds was more like shoot what ever is straight in front of you that would work.  But since you can aim it would only make since to flip the body depending on which direction you are aiming.

**Comment by android272** [comment]
It would work something like this http://www.kongregate.com/games/JuiceTin/strike-force-heroes-2
