### ISSUE TITLE
Binds trigger on media buttons

### ISSUE THREAD

**Issue by dimidrolqq** [teeworlds/teeworlds#1403]
I often use media buttons for pause/unpause and next song. While in tw, those buttons trigger some actions, which are bound to other buttons. Next song button for example triggers binds for "p".

**Comment by dimidrolqq** [comment]
Not sure how to add labels. Or is it limited by user restrictions?

**Comment by heinrich5991** [comment]
It's restricted.

**Comment by dimidrolqq** [comment]
I had a look into it and it looks like an SDL problem. I guess not much can be done then

**Comment by oy** [comment]
You could check if the problem still exist in 0.7 as it uses sdl2.

**Comment by dimidrolqq** [comment]
I wasn't able to build 0.7 yet. (Or rather i built it, but what i built was unusable)
However looking at the code it looks SDL 1 doesn't have key codes for the media buttons, while SDL 2 does. So i guess it will be fixed with an SDL upgrade.

SDL 1 keycodes https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlkey.html
SDL 2 keycodes https://wiki.libsdl.org/SDL_Keycode?highlight=%28%5CbCategoryEnum%5Cb%29%7C%28CategoryKeyboard%29

**Comment by oy** [comment]
Fixed.
