### ISSUE TITLE
Feet animation bug when a tee's X is less than 0

### ISSUE THREAD

**Issue by TheRealOrangus** [teeworlds/teeworlds#1404]
So, on 0.6 when X of a tee is less than 0(I mean lefter than the left edge of the map), the feet movement direction is reversed, and it's going, like, backwards.

**Comment by msiglreith** [comment]
This has been fixed for 0.7 (https://github.com/teeworlds/teeworlds/pull/1206), but not merged into 0.6 so far.

**Comment by TheRealOrangus** [comment]
Would be nice if it would be fixed or merged, like you say, until 0.6.4 get released public.

**Comment by oy** [comment]
Fixed.
