### ISSUE TITLE
Game apparantly adds an English keyboard layout to the system on Windows 10

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1406]
[Li on Steam](http://steamcommunity.com/app/380840/discussions/0/517142253869825750/):
>I do not use an english keyboard on Windows 10. When I launch the game, it adds an english keyboard to my computer until I restart my computer. I won't play the game until this is fixed. I do not want to restart my computer every time I play the game.

**Comment by oy** [comment]
Should be fixed.
