### ISSUE TITLE
minimizing teeworlds through bind does not work fine

### ISSUE THREAD

**Issue by tyurderi** [teeworlds/teeworlds#1408]
When playing Teeworlds 0.6.3, downloaded & compiled myself I have a little problem minimizing the game. Actually I have to open the console (F1), type minimize and press enter. That works fine but when I want to do that over a bind it doesn't works well.

So, I made a bind "bind kp8 minimize". Now when I press kp8 Teeworlds get minimized but my mouse stucks in the middle of my screen.

Actually I'm using Ubuntu Mate (https://ubuntu-mate.org/) if that's necessary.

PS: It also appears when I use a non-keypad key.

**Comment by oy** [comment]
Additional note:
- not restricted to kp8 or numpad keys
- happens in windowed mode

**Comment by oy** [comment]
Could you check if it works for you when you remove this line https://github.com/teeworlds/teeworlds/blob/0.6/src/engine/client/input.cpp#L114 and the following one?

**Comment by tyurderi** [comment]
Yup. Almost the same issue without these two lines. Also doesn't matter if KP8 or K key.

**Comment by tyurderi** [comment]
@oy: Got an idea. It works when the console is open and I enter minimize or using a computed shortcut to minimize teeworlds. When the console is open the mouse is in another mode as it normally do. So to solve the problem we could change the mode of the mouse (like when the console is opened) and then minimize the game. What do you think? I'll try to test it for sure on my own and tell you then.

**Comment by oy** [comment]
When the mouse is stuck and you open the console after that can you move the mouse then?

**Comment by tyurderi** [comment]
Yup.

**Comment by oy** [comment]
Could you check if the problems persists in 0.7?

**Comment by tyurderi** [comment]
Nope, I can't compile it. But I would.

**Comment by CytraL** [comment]
No problems here... im using Linux Mint with MATE and 0.6.x,0.7 works fine....

**Comment by tyurderi** [comment]
Still doesn't works for me. But I am using a workaround, which works pretty well. But I made a new console command for that.
bind <key> "open_local_console; minimize"
