### ISSUE TITLE
Multiple username choices

### ISSUE THREAD

**Issue by IBPX** [teeworlds/teeworlds#1410]
It would be cool to have the username field be a comma-seperated list, so if the first one isn't available when you join a server, it would try the next, then the next.

Many IRC clients do this.

**Comment by Henningstone** [comment]
But than you won't be able to have commas in your name, though :D
(Despite from who ever wants commas in his name, but well...)

Nice idea, anyways :)

**Comment by xushTW** [comment]
You could use quotes aswell. (/escaped quotes)

**Comment by pielover88888** [comment]
or not separated by commas, but separate text fields, like Hexchat and Xchat IRC clients.



From: xushTW
Sent: ‎Wednesday‎, ‎September‎ ‎30‎, ‎2015 ‎1‎:‎32‎ ‎AM
To: teeworlds/teeworlds





You could use quotes aswell. (/escaped quotes)

**Comment by Schwertspize** [comment]
I think you can use a list. maybe I will do it. /maybe assign

I'm just making a feature that the server calculates the chat (player names,...)  and the client just displays it. big advantage: server mods. and you can make a list (at the client) of words where the chat is highlighted (example '***' at beginning is yellow standard.)

**Comment by oy** [comment]
Invalid due 85b4cfd2455983ae62fe88e838882af0c2f6c3d7.
