### ISSUE TITLE
Advanced map features.

### ISSUE THREAD

**Issue by TheRealOrangus** [teeworlds/teeworlds#1417]
There are poor mapping features, and I'd like to see some, more "interesting" maps, in _vanilla_ teeworlds, without requirement to download custom client(to play without glitches).

##### Platform tile
This tile is needed for some cases of _"a background hill that you can jump on & off"_. The gametile would work like some platforms in some old platformers: you can jump on, and go through. It would work differently dependently to is the tee that colliding it, crouching(?) or not. If it's not, then the tee may jump up through the platform, but land on it when fall, and may hook down through it. But if the tee **is** crouching, then it would fall through, and couldn't jump up through, but will collide instead, and could hook up through, but not down.

There might be cases, that the tee may just fastly crouch, then uncrouch, and then it may stay inside platform, and not falling, but still, it could jump up though, it should be that way.

There have to be 2 kinds of platforms, horisontal, and vertical.

##### Door tile
This gametile is some kind of dynamic map style, where the server can enable and disable these tiles, during the game. When they are enabled, they are like, well, whatever they'd do, but when they're disabled, they're like air and tees can go through.

These tiles can be combined into something like these:
Air, Solid, Unhookable, Platform, Unhookable Platform, Door, Unhookable Door, Platform Door, Unhookable Platform Door.

### Dynamic envelopes

Some way so the server would control envelopes of the map on the clients, which has some optional flag enabled "dynamic", such envelopes may have more than 1 graph, the server can select which one is used, during the game, as well as pausing, resuming and scrolling them.

So then, some interesting maps can be created in teeworlds without requirement to modify the client, 'cause it woud be vanilla already.

**Comment by android272** [comment]
I was just about to post an idea for platforms in vanilla.  I really like it. 

I don't quite understand the door tile though.  Server can enable and disable these tiles? what do you mean? how does the server enable and disable these tiles? "When they are enabled, they are like, well, whatever they'd do"... What? what do they do? not let you pass?

When I started reading this I thought you meant that these doors would be enabled and disabled by a button or something.  But then I got confused.

**Comment by TheRealOrangus** [comment]
> What? what do they do? not let you pass?

Well, door wouldn't be itself as a kind, it would be rather, _a co-kind_, like um, unhookable door, when it is enabled - it acts like unhookable tile, when disabled - like air.

> When I started reading this I thought you meant that these doors would be enabled and disabled by a button or something. But then I got confused.

This could be implemented on server-side, without requirement to mod the client.
For example: by some chat commands; by some kind of button tile(server-side only), which will affect the door state, after a tee touched it;

**Comment by android272** [comment]
So the player can not hook doors(posibly even shoot through it).  When they touch the door tile then it disapears and turns to air.  How does this tile turn back into a unhookable door? would it then turn back into a door once the player moves more than a tile away from it?

**Comment by Henningstone** [comment]
That sounds like a walk-through-only tile, does it?
Would be pretty much easier than making a solid tile disappear when a player get near. :)

**Comment by android272** [comment]
yah but if it is supposed to be a door it might look weird to just walk through it.

**Comment by TheRealOrangus** [comment]
> That sounds like a walk-through-only tile, does it?

I don't remember that I have described it as you have found..
Walk-through-only? No, doors are like other tiles, that can be disabled and enabled any time and any amount of times during the gameplay, and when it is disabled, it behaves like air, **ONLY** when disabled.

**Comment by android272** [comment]
> It's state is dynamic, and may be changed any amount of times during the game, the state is changed when the server sends "door-state-change" packet which contains X, Y and new State(enabled/disabled) to a client.

Yes this makes since that the server would have to do something like this. But my question is how do I a player in the game activate and deactivate a door in game?  So you have a tile that you have designated as a door block.  Is it proximity based?  So when the player gets within one/two/three blocks away from the door it would disappear and turn into an air block?  When you leave the one/two/three block radius would the door reappear and act as a normal unhookable wall?

I am just wondering how this would work in game.  The actual mechanics of how it would work in code can be figured out by someone else.

**Comment by TheRealOrangus** [comment]
> So when the player gets within one/two/three blocks away from the door it would disappear and turn into an air block? When you leave the one/two/three block radius would the door reappear and act as a normal unhookable wall?

Eeh... No. Control of the doors should be implemented on the server side, by the coder, and may be different on different servers. Or you suggest put control scripts(?) into map files themselfs?

**Comment by android272** [comment]
Your not understanding me. Yes all the code that actually controls the state of the door would be on the server it self.  My question is this.  You are playing on a map that has a door.  Right now the door is a solid unhookable tile that may or may not be able to be shot through.  Now does the player do something to make the door turn to air or is it all just random? When the player gets to the door is there nothing they can do to open the door?  Yes the server would control which state the door is in, either a solid block or an air block, but does the player do anything to activate some server side code that switches the state of the door.

**Comment by TheRealOrangus** [comment]
> Your not understanding me.

I think that _You_ are not understanding _Me_:
I meant that the _coder_ would implement how would players controll doors. I don't define any exact way to do this, the _coder_ can make so doors can be controlled by buttons, or by distance to the door as you said. On a not modyfied server, doors would be uncontrollable.

**Comment by heinrich5991** [comment]
>> Your not understanding me.
> 
> I think that You are not understanding Me:

Both of you, please keep the discussion civilised. There's no need to point your finger at someone and tell them "you're wrong, I'm right". Try to understand what the other person does or does not understand and try to help them.

**Comment by TheRealOrangus** [comment]
>>> Your not understanding me.

>> I think that You are not understanding Me:

> Both of you, please keep the discussion civilised. There's no need to point your finger at someone and tell them "you're wrong, I'm right". Try to understand what the other person does or does not understand and try to help them.

He did pointed his finger at me first(kid-like excuse).

But then I explained him.

Also, it would be nice to add some simple scripting to maps, to make maps interactive, as he was asking, there would be no way to interact with maps on a not-modified server, but with simple built-in maps scripts, there would.

**Comment by android272** [comment]
> Both of you, please keep the discussion civilised. There's no need to point your finger at someone and tell them "you're wrong, I'm right". Try to understand what the other person does or does not understand and try to help them.

I am trying to understand how his idea would work in game.  I understand now that it would be up to who ever was making the map. I was thinking he was suggesting of some sort of entity that would be the same on each map.  If that was the case then I wanted some clarification on how the door worked.  I guess this is not the case.  I was not saying that he was wrong and I was right but trying to clarify what he was saying.

**Comment by oy** [comment]
This doesn't fit teeworlds.
