### ISSUE TITLE
Demo tuning param size is still wrong

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1420]
See #1286.

`sizeof(CTuning) < sizeof(CNetObj_De_TuneParams)`, yet they're `mem_copy`ed into each other (no memory unsafety, but still an unnecessary member of `CNetObj_De_TuneParams`).

**Comment by heinrich5991** [comment]
Actually it kind of is, because as said in #1286, an unrelated member is copied into the demo.

**Comment by oy** [comment]
Ah you mean that CTuningParams has a different size than m_aTuneParams within CNetObj_De_TuneParams.

**Comment by heinrich5991** [comment]
Sorry, could've been clearer.
