### ISSUE TITLE
Simple problem with ninja texture

### ISSUE THREAD

**Issue by ObaniGemini** [teeworlds/teeworlds#1422]
![ninjaprob1](https://lut.im/FpKzGHKiEU/sIzBdwghp5EQMyJX.png)
![ninjaprob2](https://lut.im/FIA5W0wR6H/EAk1QR0TyFV5e4In.png)

##### There are maybe two things to do to fix that :

- [ ] Make those textures a little bit darker ![donny](https://raw.githubusercontent.com/teeworlds/teeworlds/master/datasrc/skins/marking/donny.png) ![duodonny](https://raw.githubusercontent.com/teeworlds/teeworlds/master/datasrc/skins/marking/duodonny.png) I propose that configuration 0 0 150 100 (taint, saturation, color, alpha)

- [ ] Load eyes at last, for it overrides every other textures

P.S : if you can't see the textures here, that's because they're 255 255 255

**Comment by TheRealOrangus** [comment]
Maybe just add outline to eyes colored same as cloth(dark gray)?

**Comment by ObaniGemini** [comment]
Don't know. Do as you wish, that's just an idea about a very low priority feature :)

**Comment by oy** [comment]
What's the problem?

**Comment by Postremus** [comment]
the sword is over the eyes

2015-10-29 18:47 GMT+01:00 oy <notifications@github.com>:

**Comment by oy** [comment]
It's not - at least not on the pictures i see.

**Comment by heinrich5991** [comment]
I believe what you're seeing (the white arc) is part of the ninja skin, so it's probably intentional.

**Comment by ObaniGemini** [comment]
I think you should read the post :/
If there is a big blank in my explanation it's because I showed those two blanks textures : https://raw.githubusercontent.com/teeworlds/teeworlds/master/datasrc/skins/marking/donny.png https://raw.githubusercontent.com/teeworlds/teeworlds/master/datasrc/skins/marking/duodonny.png .

In singleplayer, those textures have the same color as the eyes, so it looks like the eyes are hidden by those.

**Comment by TheRealOrangus** [comment]
Hidden by? Well not for all, for me they are just _"blending"_ into a _"white hole"_.

**Comment by ObaniGemini** [comment]
![ninjabug](https://lut.im/gmIzxkGHjI/gihHSCamQ166Mit3.png)

**Comment by TheRealOrangus** [comment]
> ![image](https://camo.githubusercontent.com/8407604ca9c44364a0bc304f99cfe362a8fe2fa4/68747470733a2f2f6c75742e696d2f676d497a786b47486a492f676968485343616d513136364d6974332e706e67)

On pictures with red and blues ninjas, that thing behind eyes are lighter than them.
So I guess light gray(or just gray) eyes would be **Ok**.

**Comment by ObaniGemini** [comment]
Just not the same color, that's all :)

**Comment by TheRealOrangus** [comment]
I thought, and I guess changing ninja would affect not just teamless, but also red and blue versions.
So making it **Ok**, may make red and blue **Unok**.

**Comment by ObaniGemini** [comment]
NO
It's just about the color code used, not about the texture. Blue-team ninja uses a color-code, while red uses another and the simple tee uses another.
The goal is just to change the color-code used to colorize eye/donny of the simple tee, but I don't where it is supposed to be in code :)

**Comment by Sonix-** [comment]
I can live with it

**Comment by TheRealOrangus** [comment]
> NO
It's just about the color-code used, not about the texture. Blue-team ninja uses a color-code, while red uses another and the simple tee uses another.
The goal is just to change the color-code used to colorize eye/donny of the simple tee, but I don't where it is supposed to be in code :)

The code where ninja color is picked is [here](https://github.com/teeworlds/teeworlds/blob/master/src/game/client/components/players.cpp#L555).

**Comment by oy** [comment]
Seems the marking used to be grey.
