### ISSUE TITLE
Add a music API to the game

### ISSUE THREAD

**Issue by ObaniGemini** [teeworlds/teeworlds#1424]
I think it would be a good thing to add a .cfg file or a place in source code to simply add music.
I think the function should permit to do something like that :

blank_lenght = X seconds : *defines the blank time between two unlooping tracks*

register music *music.wv* :

        *type* = menu / game / editing : *defines if the music is played while in main menu, in game or in map editor*

        *loop* = true / false : *defines if the music loops or not. Menu musics shall loop and game not IMO. Also, music is randomly chosen and don't stop looping until the game closes / another type is charged.*

        *name* = name of the music : *defines name, to use in a graphical showing in_game*

        *artist* = artist of the music : *defines artist, to use in a graphical showing in_game (showed in italic)*

What do you think of this idea ?

**Comment by MegaManSec** [comment]
Please, no.. If people want to listen to music, they can listen to music themselves.

**Comment by oy** [comment]
Won't fix - use an external app to play music.
