### ISSUE TITLE
Don't clear server list when realoding

### ISSUE THREAD

**Issue by TheRealOrangus** [teeworlds/teeworlds#1426]
I suggest to add features so instead of clearing and refilling server list when reloading, wait until it gets reloaded, and then delete only the servers that are not appearing anymore.

Because this is really annoying...

**Comment by ObaniGemini** [comment]
As the reloading time isn't really long, I don't think that would be a really important feature to add. But still a good idea :)

**Comment by TheRealOrangus** [comment]
> As the reloading time isn't really long

Well maybe you have high speed internet, and it reloads in a second, or 12 seconds(as it is for me) is not long, but for me, this is enough long to be annoying.

> I don't think that would be a really important feature to add

Some people have really slow internet connection, so it's not 12 or 20 seconds for them, but a few minutes!

> But still a good idea :)

Exactly, I would really like to see that servers wouldn't disappear at reloading.

**Comment by oy** [comment]
Won't fix - just nonsense.

**Comment by ObaniGemini** [comment]
Also, people who have a really slow internet connection would not be abled to play a multiplayer game with no lags

**Comment by TheRealOrangus** [comment]
> just nonsense.
I don't understand what you don't understand, maybe you describe this so I can explain, if you don't understand something.

**Comment by tyurderi** [comment]
@TheRealOrangus Do a mergerequest and be lucky if Oy accepts it. I think its a nice idea, too.
