### ISSUE TITLE
[BUG] HUGE sounds problems

### ISSUE THREAD

**Issue by ObaniGemini** [teeworlds/teeworlds#1427]
Those sounds seems to be due to recent commits (I just compiled this morning, last time was about 3 days ago)

#### VIDEO :

https://up1.ca/#kJ9_zA5JWFG4khapHdQTLg

Segmentation error is the error I get when crashing the game. I also get this 
*[5637a8af][]: pFont memory usage: 3014656
[5637a8af][]: pFont memory usage: 4063232*
and then Segmentation Error

I always make it crash spam-clicking the hammer and then switching to pistol

Thanks for reading and seeing this

- [ ] Fix crash
- [ ] Fix problem with sounds

P.S : there is no ninja on the map

**Comment by heinrich5991** [comment]
Can you git-bisect it?

**Comment by saibotu** [comment]
Caused by [`random_int()`](https://github.com/teeworlds/teeworlds/commit/b84b8ddfdabba3d2b77d62bdab7d7548e739380f#diff-93e1753e794875315e000ac3e3c030d2R50) returning negative values.

**Comment by TheRealOrangus** [comment]
> Caused by random_int() returning negative values.

```c++
(unsigned)random_int()
```
