### ISSUE TITLE
Add prompt to econ

### ISSUE THREAD

**Issue by CytraL** [teeworlds/teeworlds#1428]
Now it's impossible known when a 'task' are finished in external console... you need play with timeouts and this make all slowly when works with scripts....

Or exists some method for detect this? :\

**Comment by heinrich5991** [comment]
The right way to do this would probably be to make an econ client.

**Comment by CytraL** [comment]
In python with "telnetlib":
```python
def send_econ_command(port, password, commands):
    conn = telnetlib.Telnet('localhost', port, 1)
    conn.read_until(b'Enter password:',1)
    conn.write("{0}\n".format(password))
    for cmd in commands:
        conn.write("{0}\n".format(cmd))
    netrcv = conn.read_until(b"\n\n", 1) #-> Can't wait for nothing... really, here stop by timeout.
    conn.close()
    return netrcv
```

**Comment by heinrich5991** [comment]
Oh, I misunderstood you.

You could send `echo <random_string>` and wait for the server to output that before closing the connection.

**Comment by CytraL** [comment]
Oh! nice... thx heinrich5991!
