### ISSUE TITLE
sort by ping first

### ISSUE THREAD

**Issue by android272** [teeworlds/teeworlds#1433]
Would it be possible to sort the server browser by ping first then what ever the user picks?  No body wants to play a game with high ping and people don't want to play with people with low ping.  I personally like to sort by how many people are in the room but recently I have been sorting by ping to get the best experience.

**Comment by oy** [comment]
Won't fix, it should sort by what the player chooses - default is player count. Besides that the ping is coloured now so players have a good indication.
