### ISSUE TITLE
The audio device couldn't be initialised.

### ISSUE THREAD

**Issue by erayerdin** [teeworlds/teeworlds#1435]
I have tried to open Teeworlds and I've been playing it for a long time. However, it throwed an error this morning, saying: "The audio device couldn't be initialised.". I still can play the game, but there's no sound. I run it on terminal and this was the output:

    ...
    [5659e2e9][client]: starting...
    [5659e2e9][client/sound]: unable to open audio: No available audio device
    [5659e2e9][engine/mastersrv]: refreshing master server addresses
    [5659e2e9][textrender]: loaded pFont from '/usr/share/games/teeworlds/data/fonts/DejaVuSans.ttf'
    ...

I recently installed Kivy of Python, and to install that, I installed pygame and a dependency called SDL.

However, there was a bug in the package, so I had to patch it manually as [instructed in here](https://www.linuxquestions.org/questions/linux-from-scratch-13/blfs-sdl-4175466360/).

I succesfully compiled and installed the dependency. However, Teeworlds now throws error above.

The same issue has [a question on Askubuntu](http://askubuntu.com/questions/703609/the-audio-device-couldnt-be-initialised-on-teeworlds).

**Comment by oy** [comment]
Teeworlds uses SDL for the audio, so there's probably a problem with your SDL lib.

**Comment by Ryan8781** [comment]
I am having the same issue. I have these packages already installed:

- `libsdl2-2.0-0` (version `2.0.4+dfsg1-2ubuntu2`)
- `libsdl2-mixer-2.0-0` (version `2.0.1+dfsg1-1`)

OS: Linux Mint 18.1 Xfce 64-bit

What am I missing? I can't find a way to fix this problem. Please reopen the issue.

**Comment by heinrich5991** [comment]
Can you hear sound from other applications?

**Comment by Ryan8781** [comment]
>Can you hear sound from other applications?

Yes.

I actually just solved the problem. The problem was that I had previously compiled SDL myself on my system, and the game used the lib from `/usr/local/lib/` instead of `/usr/lib/`. Uninstalling my compiled version fixed the problem.
