### ISSUE TITLE
SDL2 Tab out of the game

### ISSUE THREAD

**Issue by nifker** [teeworlds/teeworlds#1439]
When will it support SDL2?

**Comment by heinrich5991** [comment]
Teeworlds on the master branch (for the upcoming 0.7) already uses SDL2.

**Comment by nifker** [comment]
So why hasnt been the possibility been added to tab out of the game?

**Comment by oy** [comment]
It's already there - SDL provides it.

**Comment by nifker** [comment]
Guess what? I wouldnt ask if I would be able to tab out.

**Comment by nifker** [comment]
@oy nice support anyway
