### ISSUE TITLE
Map details menu is ignored by most mappers

### ISSUE THREAD

**Issue by H-M-H** [teeworlds/teeworlds#1443]
This feature is widely ignored as there is only a tiny button which leads you to the map details menu: https://github.com/teeworlds/teeworlds/blob/ceadee1d756cda68bd49e0bd9e741c4b800a113e/src/game/editor/editor.cpp#L3298-L3307. For some discussion on this see https://github.com/ddnet/ddnet/pull/391 .

Some stats: out of 2106 maps only 128 make use of this feature.

**Comment by Deku-mintpi** [comment]
I utilize this feature, but then again I don't think I've released any yet... I agree though that it's not very obvious at all.

**Comment by oy** [comment]
It's good that it isn't used and not gonna put more attention to it.

**Comment by H-M-H** [comment]
Why is it good that it is not used ? And even if so, why does it still exist then ?

**Comment by oy** [comment]
Dunno why it exists, but that just leads to lots of crying and such. It's better to have people using/sharing it like before.
