### ISSUE TITLE
DejavuSans font is not enough for CJK languages

### ISSUE THREAD

**Issue by marguerite** [teeworlds/teeworlds#1449]
Hi,

We have simplified_chinese.json translation in 0.7 trunk now.

Thanks for the work!

But unfortunately the DejavuSans can't cover all the characters. You can set language to Simplified Chinese and see those "unknown  blocks".

DroidSansFallbackFull.ttf or NotoSansCJKsc-Regular.otf will be good.

But they're huge in size for us to bundle.

So I propose a feature to use system fonts in stead of the hardcoded one....

Marguerite

**Comment by marguerite** [comment]
btw, in commit [401697b](https://github.com/teeworlds/teeworlds/commit/401697b35d0ee8f333371b4ab7c4295be3d0a53d), fonts is stored in an `char aBuf[256]`, which is certainly not enough for Chinese characters. it needs at least 30000.

**Comment by marguerite** [comment]
and even after I patched the variable `MACRO_CONFIG_STR(ClFontfile, cl_fontfile, 255, "DejaVuSans.ttf", CFGFLAG_CLIENT|CFGFLAG_SAVE, "What font file to use")` to use DroidSansFallFull.ttf, it still prompts errors about `[gameclient]: failed to load font. filename='fonts/DejaVuSans.ttf'`. seems the previous didn't give the possibility to use other fonts when compiling.

**Comment by MegaManSec** [comment]
That aBuf[256] is purely for the filename of the font.

**Comment by marguerite** [comment]
@MegaManSec thanks! 

Is there other places hardcoding DejavuSans.ttf besides src/game/variables.h? I change the fontname in variables.h, place the font in datasrc/fonts. it can be installed, but can't be loaded.

**Comment by xushTW** [comment]
Try setting it in the config file as well and also do a [code]bam content[/code] because afaik the font won't be loaded from datasrc

**Comment by marguerite** [comment]
@xushTW As I see from log, the font is copyed to data from datasrc. so where's the config file and how to set the font then?

**Comment by msiglreith** [comment]
You should be able to set the font via the console (`F1`) and type `cl_fontfile DroidSansFallbackFull.ttf` (the corresponing file should be located at `data/fonts/`).
The new font will loaded at restart. You can also directly edit the `settings.cfg` (https://www.teeworlds.com/?page=docs&wiki=client_config) and modify the `cl_fontfile` setting directly.

**Comment by marguerite** [comment]
but I have replaced "DejaVuSans.ttf" string everywhere in the source code. why does it still give me a configuration with DejaVu set as default font?

**Comment by Dune-jr** [comment]
@marguerite quite late but that's probably because you still have the `settings.cfg` with the old default font value.

---

I don't think there is anything to do in this issue? It sucks that DejaVuSans does not cover all characters but the other fonts would be huge to bundle, and they can just be set with `cl_fontfile`.
