### ISSUE TITLE
vote between rounds not disappearing

### ISSUE THREAD

**Issue by dingens** [teeworlds/teeworlds#1455]
I've seen the following happen twice within the last days: Someone called a vote to kick somebody just before the end of the round. After the reconnect (the automatic one, I didn't disconnect explicitly) the vote display did not disappear, it stayed there until I closed teeworlds, displaying "-123 seconds left"

I reproduced it using an empty server, see screenshot:

![screenshot_2016-02-17_00-04-11](https://cloud.githubusercontent.com/assets/147521/13094308/173fd044-d50a-11e5-8b79-56a7187dfcbd.png)

**Comment by marcoms** [comment]
I also experienced this a while ago, though I'm not sure of the details
