### ISSUE TITLE
Wrong CalcPos for Projectiles

### ISSUE THREAD

**Issue by SNSnoop** [teeworlds/teeworlds#1458]
![screenshot_2016-04-03_12-32-11](https://cloud.githubusercontent.com/assets/6138073/14231772/270e8594-f998-11e5-8797-9d5765c96452.png)
White line: real projectile direction;
Black line: client projectile direction;
Problem caused by this:
Server: https://github.com/teeworlds/teeworlds/blob/master/src/game/server/entities/projectile.cpp#L94
Client: https://github.com/teeworlds/teeworlds/blob/master/src/game/client/components/items.cpp#L47

**Comment by Irradius** [comment]
is just a mathematic decimal approssimation error?

**Comment by heinrich5991** [comment]
The problem is that the server doesn't send all the information the client needs. Either the server needs to forget that information, or it has to send it.

**Comment by Indie-Mods** [comment]
so, it need to cut the Direction value after 2 decimal numbers also for the server calculation

**Comment by Dune-jr** [comment]
@heinrich5991 Every time a packet is sent? Wouldn't that make the server forget about <0.01f information a bit too often?

**Comment by trml** [comment]
Only the the initial position/velocity and the start tick of projectiles is used (both in physics calculations and for rendering by the client), so it would be sufficient to forget the information at the time projectiles are created.
