### ISSUE TITLE
git: zero-padded file modes

### ISSUE THREAD

**Issue by H-M-H** [teeworlds/teeworlds#1459]
```
> git fsck --full
(...)
warning in tree 411ebc45beade8a2fe55914e7667b795f5e29bf2: zeroPaddedFilemode: contains zero-padded file modes
warning in tree ef726cdbc13e62798213b118a7be991b99fec355: zeroPaddedFilemode: contains zero-padded file modes
warning in tree 842a9b81fa1120e6c874d8d4cda8925ed2551a3e: zeroPaddedFilemode: contains zero-padded file modes
warning in tree 8c3b580e9c94e88af71a0741005fa37b5e560e51: zeroPaddedFilemode: contains zero-padded file modes
warning in tree b9afd1807f0256a6c34cf1e0a87ca72026fdd74e: zeroPaddedFilemode: contains zero-padded file modes
warning in tree b23abaab47a81ca8a22441d66c4e5d24d9d29866: zeroPaddedFilemode: contains zero-padded file modes
(...)
```

Problem:
This can make git think two tree-objects differ even though they actually are the same, which can bloat the repository. Additionally some hosts for git-projects (gitlab, not sure if there are more) refuse creating new repositories with this issue.
It is possible to fix this (see first link down there), however, this will change all SHA values, which is obviously not the very best thing to happen. The DDrace and DDNet repository also give this warnings, which probably means that the cause of this is rather old.

further info:
http://stackoverflow.com/a/14839059
http://stackoverflow.com/a/15605031
https://www.perforce.com/blog/150109/git-out-vulnerability-out-fire

**Comment by oy** [comment]
Yeah known, was created by a bug within the github editor some years back I think. Not gonna do something about it.
