### ISSUE TITLE
Missing braces causing gfx_screen_width and gfx_screen_height to be overridden on OS X

### ISSUE THREAD

**Issue by H-M-H** [teeworlds/teeworlds#1460]
https://github.com/teeworlds/teeworlds/blob/master/src/engine/client/backend_sdl.cpp#L683-L688

See https://github.com/ddnet/ddnet/issues/445#event-646622935 .

**Comment by oy** [comment]
This is done on pupose.

**Comment by H-M-H** [comment]
> This is done on pupose.

Are you sure ? Like this it is impossible on Mac to start the game in windowed mode with proper resolution. This works just fine for fullscreen but in windowed mode there is a little less space (height) for the window and thus the bottom is cut off.

**Comment by oy** [comment]
Well when I did this 2.03 was the latest SDL release and this was the only non-fubar option. Have to do some tests with the new SDL version.
