### ISSUE TITLE
[0.6] antique logic mistake (listbox bug)

### ISSUE THREAD

**Issue by Henningstone** [teeworlds/teeworlds#1463]
https://github.com/teeworlds/teeworlds/blob/0.6/src/game/client/components/menus_demo.cpp#L352
this doesn't make any sense, does it? 

Was introduced here: (topmost commit) 
https://github.com/teeworlds/teeworlds/commits/72c06a258940696093f255fb1061beb58e1cdd0b
Maybe it goes even further back, but this is the last commit to where I could trace it down.
A quite antique thing, hm? ;)

As far as I can see, this was supposed to be rather 

``` c++
if(Item.m_HitRect.y < gs_ListBoxOriginalView.y)
```

Apparently it seems that this bug only causes problems for listboxes with a huge row height value.

**Comment by oy** [comment]
Fixed.
