### ISSUE TITLE
Add ctrl + left/right/backspace commands for chat

### ISSUE THREAD

**Issue by Zwelf** [teeworlds/teeworlds#1467]
ctrl + left/right for skipping words and ctrl + backspace for removing words.

**Comment by Henningstone** [comment]
Maybe not only for chat, but also for textboxes and the consoles.

**Comment by H-M-H** [comment]
I would like to point out that ctrl + left/right is already reserved for switching workspaces on MacOS.

https://support.apple.com/kb/PH18757

**Comment by heinrich5991** [comment]
What do you use for moving between words on OS X?

**Comment by jxsl13** [comment]
Alt + arrow keys if I'm not mistaken

**Comment by H-M-H** [comment]
Yes, alt + arrow keys is used on macOS normally.
