### ISSUE TITLE
Teeworlds Server opens pointless 'open file' dialog box before starting on Mac OS X

### ISSUE THREAD

**Issue by daviewales** [teeworlds/teeworlds#1472]
The following screenshots show the process required to launch Teeworlds Server on Mac OS X:

1. Double click Teeworlds Server.  
A dialog box appears, which requires you to select a file (it doesn't matter which file you select.)  
![screen shot 2016-09-02 at 11 31 05 am](https://cloud.githubusercontent.com/assets/2499066/18189752/eb72cd16-7100-11e6-94df-a6360772ef6d.png)  
2. After selecting the file, and clicking 'Open', the server launches normally, as you would expect.  
![screen shot 2016-09-02 at 11 31 16 am](https://cloud.githubusercontent.com/assets/2499066/18189753/eb75bad0-7100-11e6-81b4-3dc9be70e93d.png)

I would have expected the server to jump straight to step 2.
Or am I not understanding the purpose of the 'select file' dialog?

**Comment by H-M-H** [comment]
> Or am I not understanding the purpose of the 'select file' dialog?

The purpose of this dialog is to select an additional config-file.

**Comment by daviewales** [comment]
OK. Perhaps a title explaining that would be good.

**Comment by oy** [comment]
Not part of teeworlds and can't reproduce. Probably linked to the stuff your running.

**Comment by H-M-H** [comment]
Huh, what do you mean by this @oy ? There is the serverlaunch program: https://github.com/teeworlds/teeworlds/blob/master/bam.lua#L136 / https://github.com/teeworlds/teeworlds/blob/master/src/osxlaunch/server.m which is used to start a teeworlds-server on macOS if you doubleclick the .app folder. It will invoke a dialog as described above to select a configfile and start the server with it. Of course you can circumvent it and directly start the teeworlds-server but this is not done if you doubleclick the program(-folder).
