### ISSUE TITLE
Specialcharacterselection while playing on macOS

### ISSUE THREAD

**Issue by H-M-H** [teeworlds/teeworlds#1475]
Holding down a key while playing can lead to a popup menu for selecting a special character as described here: https://support.apple.com/HT201586

However, I do not think this is intended. This behaviour is new and does happen with neither 0.6 nor DDNet.

This is how it looks like:

![tw](https://cloud.githubusercontent.com/assets/7461564/18258267/bb57c1fc-73d2-11e6-82a4-72ee58c063fc.png)

**Comment by oy** [comment]
Can't reproduce with latest source.

**Comment by H-M-H** [comment]
Just tested with 170b487430b93ea8ec3f46725d5955bddb0746dc (as of now the latest version) and this still happens.

**Comment by oy** [comment]
After using the latest SDL version it's there for me as well.
