### ISSUE TITLE
Better Internationalization

### ISSUE THREAD

**Issue by necropotame** [teeworlds/teeworlds#1477]
TeeWorlds need a better internationalization system. There is several problems in the actual system that make life hard for asian and african players.
 * Missing glyph: some languages are not supported because the DejaVuSans font is not complete (appears for Korean, Japanese and Chinese)
 * Right to left (RTL) writing system not supported: Arabic, Hebrew and other RTL writing system are ont displayed in the corrected direction. In addition, menus are not adapted to these languages because they are hardcoded to be LTR (side menu in the editor, order of tabs and buttons, alignment, ...)
 * No ligatures for complex writing system: in arabic and tamil, letters MUST be attached to be readable. Actually, each letter is separated.
 * No way to input complex letters with a regular input system: It's impossible to write chinese ideogram with a classical keyboard an Koreans, Japaneses and Chineses use a completion system for that. And it's not possible to use a system-wide solution because the completion window may not appear in a SDL window. But it's really a hard problem to solve because a solution must be done language per language with dictionaries.

I'm working on a fork of TeeWorlds (Teeuniverse) in which I want to fix all of these problems (it's half done in the current state). I think it could be great if TeeWorlds could benefit of it. However, my code is not compatible with TeeWorlds. [You can take a look here](https://github.com/teeuniverses/teeuniverses/blob/master/src/tu/client/textrenderer.cpp). So the first question is: did you want to solve these problems ? The second question is how do you want to fix it ?
Here is the solution that I've found and partially implemented:

### Better cache for glyph
The problem:
 * Support more non latin character can lead some times to a too big glyph cache. The size of the largest glyph is used to create a grid of glyph. It's very inefficient in term of memory cost. [Here is the state of the cache after displaying the server list](http://s11.postimg.org/8mt601u0j/teeworlds_glyphcache.png)
 * The algorithm to find a glyph is linear, which impact the speed in practice.
 * The last problem concern the way glyph are updated: it's based on timeget() instead of a tick based on the frame. This mean that some glyph can be replaced during the rendering of the same frame. (Maybe I'm wrong about this one)

The solution:
 * I've implemented a way to pack glyph in the cache in a more compact way. [Here is the state of my cache after displaying a lot of text in a lot of sizes](http://s18.postimg.org/9u87hhgpl/teeworlds_text_tu_cache.png). The equivalent with vanilla code is bigger than my screen. However it's slower than with the vanilla system
 * I've replaced the linear search by a better search algorithm using a sorted_array. With that, my cache system is now 4x faster than the vanilla one.

### Alternative Fonts
 * Multiple fonts must be loaded. If a glyph is not present in the first one, it must be searched in the other ones. The part is easy to backport to vanilla. A free CJK Font like Noto is around 16Mb, but It could be an option.

### Ligatures
Ligatures of text can be done using a text shaper like HarfBuzz (used in firefox, chromium, ...). HarfBuzz takes a string and generate the list of glyph (this part is implemented and arabic is displayed correctly). However, the language must be detected first (I've not implemented that part, but I think ICU can fix it, see next section). To be efficient, I've implemented a TextCache, a class that store the list of quads that must be renderer for a given text. Each time the text change, the list of quads is updated using HarfBuzz. This is faster, but each time you want to draw a text, you must store the result somewhere. So it needs a lot of work to be implemented in TeeWorlds. An alternative way to do it is to store all renderer text some where in a hash table, and remove old entries. But I've not found a good solution to decide which text is old or not.

### Bidirectional text
If you write in arabic but you mention a player with an Latin name, then your text must be separated in multiple parts depending of the writing direction before be shaped by HarfBuzz. It's a hard problem, but solved by at least two libraries: ICU and FriBiDi. The first one seems easier to use and contains useful functions to display numbers in local format (Hindi-Arabic for example). So it can be used for other purpose. I've implemented this part.

### RTL GUI
I've implemented a GUI system with a lot of virtual call and inheritence, so you will probably don't like it that much :P. But I think it is easier to maintain because there is no more hard coded things. The good point with it is that GUI element are placed using layout that can be switched to LTR or RTL easly.

**Comment by oy** [comment]
Duplicate. There're already issues for that.
