### ISSUE TITLE
In need of new admins to approve pull requests!

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#1489]
As discussed [here](https://www.teeworlds.com/forum/viewtopic.php?pid=119720), [mentioned here](https://www.teeworlds.com/forum/viewtopic.php?id=7335) and [here](https://www.teeworlds.com/forum/viewtopic.php?id=7311), 
it is time for the old generation, which does not seem to have the time nor the will to participate in this development, to step down.
I think it is heavily wanted by the whole developer community and the players, that this game is being developed and continues to be improved, not necessarily the gameplay, but the whole code base, e.g. in order to have an easier modding base and at least a better map editor. 
The developers with time and the will are doing what they can and a lot of ideas seem promising, the problem is **you**, the admins of this repository. You hinder this game from improving, because nobody reviews the pull requests.
That's why I opened this issue, in order to get some new people into the position of admin to approve pull requests and to review them.
It's time to change, what's been wrong for too man years now.
I recommend [heinrich5991](https://github.com/heinrich5991), [unsigned char*](https://github.com/CytraL), [Dune](https://github.com/Dunedune) as possible people capable of being admins in this repository.
If this will not change, I, and hopefully the whole community will stress this repo to be abandoned and reopen a new one with capable people to maintain the code base, who also have the time to do so.

**Comment by xushWT** [comment]
DUNE xD

gets me everytime.
