### ISSUE TITLE
Server info is not being updated after map reload

### ISSUE THREAD

**Issue by Speedy-Consoles** [teeworlds/teeworlds#1490]
[Commit 7c43b767](https://github.com/teeworlds/teeworlds/commit/7c43b76758d44ab0edeeea2de177f3b08af8a008) separates the connection less packets from regular packets. However the server info packets from the server one is currently connected to are also connection less, but they are received by the regular network client, which drops them due to `if(Packet.m_ClientID != -1)` in `src/engine/client/client.cpp:1445`. With this, the client only receives the server info at the beginning of a connection. If the server info (e.g. game type or map name) changes during the connection, the client does not show the new info in the server info tab.

**Comment by oy** [comment]
Yeah known - not gonna do something about it.
