### ISSUE TITLE
0.6.4 branch mapchecker buggy

### ISSUE THREAD

**Issue by VOID001** [teeworlds/teeworlds#1494]
master fix the mapchecker bug, but 0.6.4 still buggy
It cause teeworlds server cannot load map like dm2 dm1, etc
Below is the 0.6.4 branch related code
https://github.com/teeworlds/teeworlds/blob/0.6.4-release/src/engine/shared/mapchecker.cpp
Below is the commit to fix the bug
https://github.com/teeworlds/teeworlds/commit/453f7202124261c7a6bf545a1a39d409da6a53b4

Hope to see 0.6.5 fix the bug :)

**Comment by oy** [comment]
There's nothing wrong with the mapchecker in the 0.6.4 branch. It prohibits you from loading modified standard maps. And iIt's disabled in the master branch cause 0.7 is in development and the maps are worked on.
