### ISSUE TITLE
Add more information in the output console/log of server to provide even more game stats

### ISSUE THREAD

**Issue by allan-simon** [teeworlds/teeworlds#1496]
First thanks for this awesome game.
Currently at my company we play this game a lot and we've started  a  "teeworlds to elastic search" script that basically take the server output on STDOUT,  format them as json and then send it to elasticsearch for indexing, so that we latter use Kibana for displaying stats about number of kill, top killer etc.

i.e  we transform

`[5971f26d][game]: kill killer='2:Directee' victim='1:Alex' weapon=4 special=0` 

into 

```json
{
   "event":  "kill",
   "killer": "Directee",
   "killer_id": 2,
   "victim":  "Alex",
   "victim_id": 1,
   "weapon":  4,
   "special": 0
}
```
Of course being geeks we love numbers and the information we would like to see:

 * when somebody takes a damage have a log
 * for the kill log message, to have the team id of the victim and killer
 * for the `flag_grap` event to have the team id of the player who grab the flag
 * [optional] when a fire is shot to have a log (so that we can calculate hit ratio, prefered weapon etc.)

For these ones I see where to add these information in the code, would a PR going in that way would be welcome ?

**Comment by allan-simon** [comment]
just to clarify a bit:

1.  I'm not asking to json-ify the log output, I'm happy to parse the log as they are currently done and to do the json-ification on my side.
2. for this kind of game, people are addicted to all kind of stats you can output (most used weapons, maximun velocity reached etc. ) and I'm only asking about the "easy to get" ones
3. I don't think it will affect in any way the performance (but I'm willing to hear somebody who knows the code telling me my understanding is wrong)
4. It will make the server log output more verbose but is it a problem ? (if yes please tell me why, so that we can discuss)

**Comment by allan-simon** [comment]
Thanks for the output, I was wondering about the `console_output_level` option 

As it's mostly for us at the company, I will then certainly submit a PR and compile a patched version of the 0.6 for our local needs :)

**Comment by allan-simon** [comment]
Hello back, it's 2019, and I'm starting once again to play teeworlds, and I'm very happy to see that 0.7.x is now officially released, I still have my patch somewhere, and i'm re-asking if making a PR would make sense ?

**Comment by allan-simon** [comment]
@oy  @Dune-jr  ?

**Comment by Dune-jr** [comment]
It would be interesting to have those stats accessible from the console. Having an output per default for every damage or bullet sounds too spammy, but like @H-M-H pointed out, you can put that in a verbose level.
I think this would make sense and I'd gladly welcome a PR. That is conditional to @oy's avail though

**Comment by oy** [comment]
Yeah, would be fine if it's kept as additional output.

**Comment by allan-simon** [comment]
ok thanks I will try to propose you a PR soon then

**Comment by allan-simon** [comment]
I've made a first PR,  for the kill event, I'm having issue to get the killer's team, as we only have the client id of the killer, and the team is in the Player class, and I haven't found a way to go from client id -> player (the other way around seems easy as Player as a GetCID method)

**Comment by oy** [comment]
@allan-simon `m_apPlayers[ClientID]`

**Comment by allan-simon** [comment]
thanks for the merge and for the tips, new PR incoming soon ^^'

**Comment by oy** [comment]
Seems fixed now.

**Comment by allan-simon** [comment]
yes we're good, thanks a lot :)

**Comment by ChillerDragon** [comment]
https://github.com/chillavanilla/TeeworldsEconMod

Was able to detect teams on flag grabs and kills with 0.6 logs already. You can just track the ids on team change. The only limitation was ``shuffle_teams`` since that didn't show the new teams in the log. Id rather print more information during shuffle than spawn the logs with redundant information.

**Comment by allan-simon** [comment]
it obliges your  intermediate script to be stateful, in our case where we parse in real time the log as they go, it means that you can't  stop the stream and take it back, because you've lost the state. In a more general way it's the recipe for bug to have two systems keeping track of the same state

moreover we're talking about 10 characters, not dozen of lines :)

**Comment by ChillerDragon** [comment]
@allan-simon I don't see how our scripts are different? We both parse the logs line by line. And you have to track state anyways to associate ids with playernames.

And 10 characters can cause a line break and thus worse readability for sure.

**Comment by allan-simon** [comment]
the playername was already in the log line , so no https://github.com/allan-simon/teeworlds-logs-to-elastic-search/blob/master/log_to_es.py no state here
also you could have a logrotate that kicks in the middle etc.

> And 10 characters can cause a line break and thus worse readability for sure.

emphasis on "can" 

 * "flag_grab player='%d:%s' team=%d"  
 * "shot player='%d:%s' team=%d weapon=%d"
* "flag_capture player='%d:%s' team=%d"
* "flag_return player='%d:%s' team=%d"

all of these are ~40 characters and will not break in any case before/after (most unix tools assume your terminal is at least 80 characters for displaying)

the only case where you can got over 80 characters might be

* "kill killer='%d:%s' victim='%d:%s' weapon=%d special=%d killer_team:%d victim_team:%d"

that would break if you have 80 characters width terminal, but `less`  (or `most` if you're fancy) can hide the end of the line instead of doing a break of line

**Comment by ChillerDragon** [comment]
Ok weird somehow I thought there were no names only ids. Also the 80 char limit sounds fine.
