### ISSUE TITLE
TeeWorlds 0.6.4 is not working on macOS Sierra 10.12.5

### ISSUE THREAD

**Issue by johanlunds** [teeworlds/teeworlds#1498]
Is this a known issue?

<img width="1000" alt="problem_report_for_teeworlds" src="https://user-images.githubusercontent.com/22144/28720469-8fec56dc-73ad-11e7-9e92-3c547d3b5390.png">

Gist with full crash log:

https://gist.github.com/johanlunds/638bb6d4fad4205db2ae6306865d6842

**Comment by H-M-H** [comment]
Yes, but nobody fixed it yet :/, see https://www.teeworlds.com/forum/viewtopic.php?id=12105 for more info and a working build.

**Comment by heinrich5991** [comment]
The Steam version is ok. :/

**Comment by johanlunds** [comment]
Thank you for the response!

**Comment by blucell** [comment]
Will this be fixed any time soon upstream? Does not work in High Sierra, either.

**Comment by H-M-H** [comment]
One might find this script I created for bundling libraries on macOS useful: https://github.com/H-M-H/bundle_libs

**Comment by oy** [comment]
Fixed the mac version in the release section.

**Comment by blucell** [comment]
https://downloads.teeworlds.com/teeworlds-0.6.4-osx.dmg still downloads the old version

**Comment by minus7** [comment]
@blucell Fixed. Should be the same file as in the release section now.
