### ISSUE TITLE
Why is the game not updated?

### ISSUE THREAD

**Issue by loskiq** [teeworlds/teeworlds#1499]
Why is the game not updated?

**Comment by xushWT** [comment]
Because there is currently no need to do so.

**Comment by Henningstone** [comment]
There is a variety of forum threads on this topic:

https://www.teeworlds.com/forum/viewtopic.php?id=12210

https://www.teeworlds.com/forum/viewtopic.php?id=12196

https://www.teeworlds.com/forum/viewtopic.php?pid=119733#p119733
