### ISSUE TITLE
Add pause command

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#15]
For clan wars could be cool to be able to freeze the game if a member disconnect of whatever.

**Comment by ixPost** [comment]
> The problem with this feature is how to implement it. One possibilty would be to create a new server command for it. Then admins could use it viw rcon and and it would be possible to vote on it. However, as said before, voting on it is kind of sensless, because it needs to be applied instantly. So what to do if an admin is not available? The other possibility would be to implement a system similar to how it is done on some server modifiactions. There the playing people can simply write "stop" in the usual chat, and the game will pause until they write "go". However, this method is also not sufficient, because it would break with the way teeworlds handles the way servers are commanded. We implemented the vote functionality to give the players a possibility to change server options etc, but also to give the admin the possibilities to decide on what the players can decide. Also this method could be abused quite easy, as it was said before.
> I am not really sure what would be a good way to implement this feature...

Just have a key(on the keyboard not in the game) for it.
