### ISSUE TITLE
errors building client release on windows (no sdl.h & ft2build.h files)

### ISSUE THREAD

**Issue by Irradius** [teeworlds/teeworlds#1500]
CLIENT ERRORS
> D:\Programmi\diffutils-2.8.7\bin\teeworlds-master>..\b5\bam conf=release client
> [1/6] [1] c++ src/engine/client/sound.cpp
> [2/6] [2] c++ src/engine/client/input.cpp
> [3/6] [3] c++ src/engine/client/client.cpp
> [4/6] [4] c++ src/engine/client/backend_sdl.cpp
> [5/6] [5] c++ src/engine/client/text.cpp
> src/engine/client/input.cpp(3) : fatal error C1083: Impossible open the file including 'SDL.h': No such file or directory
> bam: 'c++ src/engine/client/input.cpp' error 2
> src/engine/client/sound.cpp(11) : fatal error C1083: Impossibile aprire il file inclusione 'SDL.h': No such file or directory
> bam: 'c++ src/engine/client/sound.cpp' error 2
> src/engine/client/backend_sdl.cpp(2) : fatal error C1083: Impossibile aprire il file inclusione 'SDL.h': No such file or directory
> bam: 'c++ src/engine/client/backend_sdl.cpp' error 2
> src/engine/client/client.cpp(52) : fatal error C1083: Impossibile aprire il file inclusione 'SDL.h': No such file or directory
> bam: 'c++ src/engine/client/client.cpp' error 2
> src/engine/client/text.cpp(13) : fatal error C1083: Impossibile aprire il file inclusione 'ft2build.h': No such file or directory
> bam: 'c++ src/engine/client/text.cpp' error 2
> bam: error: a build step failed

other things (server, masterserver, tools) working well

**Comment by Irradius** [comment]
by navigate in the old issue I find a topic about sdl library
and the 2.0 version work fine! [http://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip](url)

but remain the second file to find where?

> [1/2] [1] c++ src/engine/client/text.cpp
src/engine/client/text.cpp(13) : fatal error C1083: Impossibile aprire il file inclusione 'ft2build.h': No such file or directory
bam: 'c++ src/engine/client/text.cpp' error 2
bam: error: a build step failed

**Comment by Irradius** [comment]
i try with this freetype library but nothing changes
[http://download.savannah.gnu.org/releases/freetype/freetype-2.6.tar.gz](url)

**Comment by Irradius** [comment]
I think isn't a good way to try to put missed files!

**Comment by oy** [comment]
You have to install freetype/sdl on your own [now](https://github.com/teeworlds/teeworlds/pull/1072#issuecomment-20754614).
