### ISSUE TITLE
cliquer's cl is wrongly identified as Windows compiler

### ISSUE THREAD

**Issue by rffontenelle** [teeworlds/teeworlds#1503]
[cliquer](https://www.archlinux.org/packages/community/x86_64/cliquer/) has a binary named `cl`, which has the same name of the Windows compiler. Because of that, when cliquer is installed in a Linux system, Teeworlds wrongly identifies the system as a Windows and the build fails.

**Environment:**
Distro: Arch Linux 64bit
Packages:  gcc 7.2.0, teeworlds git master, bam 0.5.0, cliquer 1.21

**Files:**
[build-output.txt](https://github.com/teeworlds/teeworlds/files/1346269/build-output.txt)

**Comment by heinrich5991** [comment]
This workaround might work: Open the generated `config.lua` and change the relevant line to `compiler.driver = 'gcc'`.

**Comment by rffontenelle** [comment]
This would be hard in a packaging system, as it fails before I'm able to make this change.

But I just learned that a fix in bam solves it. See above backlink reference.

**Comment by oy** [comment]
Switched gcc and cl detection - should prevent that for teeworlds.

Odd that the binary is calles cl in arch - in debian it's cliquer.
