### ISSUE TITLE
Follow XDG basedir specification

### ISSUE THREAD

**Issue by Lucki** [teeworlds/teeworlds#1504]
Right now a new folder for configurations and userdata is created in `$HOME/.teeworlds`.
To be more flexible it would be nice to implement the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

> `$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used.
> `$XDG_CONFIG_HOME` defines the base directory relative to which user specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.
> `$XDG_CACHE_HOME` defines the base directory relative to which user specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache` should be used.

This would result in the following folders:

- `$XDG_CONFIG_HOME/teeworlds/<MASTERS.CFG|SETTINGS.CFG>` defaulting to `$HOME/.config/teeworlds/<MASTERS.CFG|SETTINGS.CFG>` when `$XDG_CONFIG_HOME` is not set or empty.
- `$XDG_DATA_HOME/teeworlds/<DEMOS|DOWNLOADED MAPS|MAPS|SCREENSHOTS>` defaulting to `$HOME/.local/share/teeworlds/<DEMOS|DOWNLOADED MAPS|MAPS|SCREENSHOTS>` when `$XDG_DATA_HOME` is not set or empty.
- `$XDG_CACHE_HOME/teeworlds/<DUMPS>` defaulting to `$HOME/.cache/teeworlds/<DUMPS>` when `$XDG_CACHE_HOME` is not set or empty. - _I'm not sure about this one, the folder is empty here._

**Comment by Lucki** [comment]
This dumps all into `XDG_DATA_HOME`. I haven't tested this a lot.
There's still no distinction between data, cache and config files.
~~~ patch
diff --git a/src/base/system.c b/src/base/system.c
index 860ffe24..0e1a7e81 100644
--- a/src/base/system.c
+++ b/src/base/system.c
@@ -1375,8 +1375,16 @@ int fs_storage_path(const char *appname, char *path, int max)
                return -1;
        _snprintf(path, max, "%s/%s", home, appname);
        return 0;
-#else
+#elif defined(CONF_PLATFORM_MACOSX)
        char *home = getenv("HOME");
+#else
+       char *home = getenv("XDG_DATA_HOME");
+       if(!home)
+       {
+               home = getenv("HOME");
+               if(home)
+                       home = strcat(home, "/.local/share");
+       }
 #if !defined(CONF_PLATFORM_MACOSX)
        int i;
 #endif
@@ -1386,8 +1394,8 @@ int fs_storage_path(const char *appname, char *path, int max)
 #if defined(CONF_PLATFORM_MACOSX)
        snprintf(path, max, "%s/Library/Application Support/%s", home, appname);
 #else
-       snprintf(path, max, "%s/.%s", home, appname);
-       for(i = strlen(home)+2; path[i]; i++)
+       snprintf(path, max, "%s/%s", home, appname);
+       for(i = strlen(home)+1; path[i]; i++)
                path[i] = tolower(path[i]);
 #endif
~~~

**Comment by heinrich5991** [comment]
Would need some backward-compatibility. Also, you must not write to a `char *` returned by `getenv`, but you do so in the `strcat` line.

**Comment by Lucki** [comment]
Yes, you're right. I'm not a developer, I hope this helps someone with more experience.

**Comment by Lucki** [comment]
I've experimented a bit around and come up with this. It includes the enhancements @heinrich5991 mentioned before.
There's still no distinction between config, cache and user data but it moves the folder for backward compatibility to the new location if it's found at the old location.

~~~ patch
diff --git a/src/base/system.c b/src/base/system.c
index 860ffe24..7eef4f97 100644
--- a/src/base/system.c
+++ b/src/base/system.c
@@ -1377,19 +1377,47 @@ int fs_storage_path(const char *appname, char *path, int max)
 	return 0;
 #else
 	char *home = getenv("HOME");
-#if !defined(CONF_PLATFORM_MACOSX)
-	int i;
-#endif
+	
 	if(!home)
 		return -1;
-
+	
 #if defined(CONF_PLATFORM_MACOSX)
 	snprintf(path, max, "%s/Library/Application Support/%s", home, appname);
-#else
+	return 0;
+#endif
+
+	int i;
+	char *xdgdatahome = getenv("XDG_DATA_HOME");
+	char xdgpath[max];
+	
+	/* old folder location */
 	snprintf(path, max, "%s/.%s", home, appname);
 	for(i = strlen(home)+2; path[i]; i++)
 		path[i] = tolower(path[i]);
-#endif
+
+	if(!xdgdatahome)
+	{
+		/* use default location */
+		snprintf(xdgpath, max, "%s/.local/share/%s", home, appname);
+		for(i = strlen(home)+14; xdgpath[i]; i++)
+			xdgpath[i] = tolower(xdgpath[i]);
+	}
+	else
+	{
+		snprintf(xdgpath, max, "%s/%s", xdgdatahome, appname);
+		for(i = strlen(xdgdatahome)+1; xdgpath[i]; i++)
+			xdgpath[i] = tolower(xdgpath[i]);
+	}
+	
+	/* check for old location / backward compatibility */
+	if(fs_is_dir(path))
+	{
+		/* move folder to XDG path */
+		if(fs_rename(path, xdgpath) != 0)
+			return 0; /* renaming failed but old folder exists, we use it */
+	}
+	
+	snprintf(path, max, "%s", xdgpath);
 
 	return 0;
 #endif
~~~
