### ISSUE TITLE
score system.

### ISSUE THREAD

**Issue by m4rc0khan** [teeworlds/teeworlds#1512]
HI I'M user playing teeworlds

I find some problem score system

if player die a fall score -1 but. because of that score show - score(-10. -110. etc)
i think -socre have some problem

and if die for other user score decrease 1 but it is to 0. don't down minus

and some time it doesn't work well

i want modify that?

How can i do that?

## If I understand you correctly, you want to decrease a player's score when they die, but not to a negative number?

i think that not negative number is better

**Comment by Dune-jr** [comment]
Should be closed.

**Comment by oy** [comment]
The score system is fine, not gonna change that. If you want to change it in your mod - fokkonaut gave you a hint.
