### ISSUE TITLE
How to Contribute

### ISSUE THREAD

**Issue by dantehemerson** [teeworlds/teeworlds#1516]
[LINUX] How to install the programs to modify this game. Thank you.

**Comment by Stitch626** [comment]
Depends on your system (and distribution in this case). There is a little help page about it: https://www.teeworlds.com/?page=docs&wiki=compiling_everything

**Comment by jxsl13** [comment]
First of all you would need to install (if your system is based on Debian, like Ubuntu, XYZ-buntu, ...):
`sudo apt install build-essential` using a terminal.

Then you will need to use bam to compile the game:
Some bash scripts that you can put in your teeworlds base folder, where the whole bam.lua etc. stuff lies, to easily build the game are these:

Builds server from source after downloading and compiling bam(needs git to be installed):
Put into a file like `build.sh`
`cd /path/to/the/teeworldsSource/`
and give that file execution permissions with
`chmod +x build.sh`
afterwards execute with:
`./build.sh`

Depending on what kind of build you want, you could change stuff in the `build_server ()` function of that script.
Like if you want to build a server executable with debugging stuff to attach a debugger like `gdb`, you could change `server_release` to `server_debug`, `client_release` to `client_debug` and `release` to `debug`
```bash
#!/bin/bash

# downloads bam if necessary, and builds server from source
BASE_DIR=$(pwd)

back_to_base_directory (){
	cd $BASE_DIR
}

build_server (){
	back_to_base_directory
	# release -> build both
	# release_client -> build client
	../bam/bam -a server_release
}

clean_previous_build (){
	back_to_base_directory
	../bam/bam -c all
}

check_build_bam (){
	if [ ! -f ../bam/bam ]; then
    # Download and compile bam:
    cd ..
    git clone https://github.com/matricks/bam.git bam
    cd bam

    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        # ...
        chmod +x make_unix.sh
        ./make_unix.sh
        chmod +x bam

	elif [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX
        chmod +x make_unix.sh
        ./make_unix.sh
        chmod +x bam

	#elif [[ "$OSTYPE" == "cygwin" ]]; then
        # POSIX compatibility layer and Linux environment emulation for Windows
	#elif [[ "$OSTYPE" == "msys" ]]; then
        # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
	#elif [[ "$OSTYPE" == "win32" ]]; then
        # I'm not sure this can happen.
	#elif [[ "$OSTYPE" == "freebsd"* ]]; then
        # ...
	else
        echo "Not supported operating system."
	fi

	back_to_base_directory

fi
}

check_build_bam
clean_previous_build
build_server
```

**Comment by Dune-jr** [comment]
Close? @oy

#1541 too probably
