### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by r00ster91** [teeworlds/teeworlds#1517]
I think after 810 commits it could be time to release version 0.7.0. It's been 19 months since the last release. I would really like to play this game again after 810 commits!

**Comment by stavrossk** [comment]
Yes, that would be great!

**Comment by android272** [comment]
Is there really anything crucial that needs to be done? Just release
already.

**Comment by itsrachelfish** [comment]
Does this release fix the issue where anybody can flood servers with connections? Currently nobody can even play teeworlds on the public servers. It doesn't matter if your server has a password, the botnet still floods it with connections.

![screenshot from 2018-08-15 15-44-30](https://user-images.githubusercontent.com/1670549/46647573-f0f04a80-cb4d-11e8-827d-a84366f48763.png)

This started happening in August and continued for weeks. Now the botnet is back and nobody can play Teeworlds except on DDNet servers. None of these "users" even establish a connection to the server. They just send the packet that they are connecting and time out.

![teeworlds-ddos-user-spam](https://user-images.githubusercontent.com/1670549/46647581-0d8c8280-cb4e-11e8-9487-d082782cdf6a.png)

Teeworlds should not report a player as being "connected" until they are actually in game.

**Comment by heinrich5991** [comment]
Yes, it does. The problem is not as simple as "not counting players until they're in game", because then attacker would just send the "enter game" message as well.

**Comment by lilydjwg** [comment]
> because then attacker would just send the "enter game" message as well.

If they were replying to a server packet to do this, then I could just ban their IPs as the IPs would be real.

**Comment by heinrich5991** [comment]
> If they were replying to a server packet to do this, then I could just ban their IPs as the IPs would be real.

No, unfortunately that is not the case if the handshake is entirely predictable.

The fake client can just send the CONNECT packet and then the rest of the predictable handshake, without waiting for answers from the server.

**Comment by itsrachelfish** [comment]
@heinrich5991 But you said this new release fixes this issue? Does that mean version 0.7.0 implements a randomized connection handshake?

**Comment by heinrich5991** [comment]
Yes, it does.

**Comment by Kriss7475** [comment]
Teeworlds 0.7.0 has different hook gameplay (See issue #1488). Was it intended?

**Comment by ChillerDragon** [comment]
The lack of broadcast is an crucial issue ._.

**Comment by oy** [comment]
@Kriss7475 
Kind of, but will revert it for now.
