### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1529]
what are the reasons for removing broadcast? Can we have it back in a 0.7.1 patch please?

**Comment by fokkonaut** [comment]
can we re-implement Broadcast?

**Comment by oy** [comment]
What do you need it for?

**Comment by fokkonaut** [comment]
its just cool to have and funny if youre on a server with many people and use it. its centered on the screen, some people might not have a look at the chat and you can simply easy moderate a server using it.

**Comment by MrCosmoX** [comment]
It is simply a simpler method to send information to players without spamming the chat. And I know you don't want to hear this oy but it's also a great feature for mods. We accept that you don't want great mod support but a feature to display messages that have been around since the beginning of Teeworlds, really now?

**Comment by ChillerDragon** [comment]
I am playing teeworlds for a while now and broadcast has always been around. The chat makes annoying sounds and scrolls. The broadcast is easy to read and replaces the last one silently. That makes it perfect to display some live stats of something. The broadcast is nice for admins and mods. And the broadcast has simply a different value than normal chat messages.

I see a lot of positive aspects and don't understand why it got removed.

**Comment by Zatline** [comment]
If the majority of the community wants it back just add it back! This could still made optional to turn off in the settings menu if you as a player don't like it in case server admin is spaming the shit out of it! 
Broadcast messages will then be visable in chat as "Brodcast:" or be turned off entirely.

**Comment by themisak** [comment]
Please bring Boradcast Back! It is especially usefull for tournaments and Teeworlds was an ESL game dont forget that. Broadcast was a very usefull feature and should be added back thanks for your great work so far guys !

**Comment by fokkonaut** [comment]
lol accidently clicked on close

**Comment by oy** [comment]
@LordSk is working on it.
@Stitch626 yeah should be possible to disable them.
