### ISSUE TITLE
Tiles with alpha

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1530]
tiles with alpha (transparency) arent shown right ingame.

**Comment by oy** [comment]
Could you provide an example map?

**Comment by fokkonaut** [comment]
just create a map, make some tiles and change the alpha to < 255

**Comment by fokkonaut** [comment]
![base profile screenshot 2018 10 20 - 22 28 42 47](https://user-images.githubusercontent.com/35420825/47260236-b1175480-d4b7-11e8-82dd-620a28e2640d.png)
0.7 transparent tiles
![ddnet exe screenshot 2018 10 20 - 22 30 30 63](https://user-images.githubusercontent.com/35420825/47260241-c8564200-d4b7-11e8-8d41-548234e80f44.png)
how it looks like in 0.6

**Comment by fokkonaut** [comment]
[ChillBlock5.zip](https://github.com/teeworlds/teeworlds/files/2498516/ChillBlock5.zip)

example map, because github does now allow .map files its in .zip

**Comment by fokkonaut** [comment]
oh, this bug with the transparency does not seem to be a bug with the tiles only. if you make an emote and you see it disappear it also doesnt get more transparency, instead its getting more and more white till it disappears.

**Comment by nheir** [comment]
Related to c3bce451200c9a6a38a99dbe486e9102b3153213
