### ISSUE TITLE
Server browser

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1538]
Improve the server browser.
Suggestions?

**Comment by Wuerstchen** [comment]
Make all input boxes (also both F1+F2 consoles) selectable with mouse and keyboard shortcuts. Also allow cut/copy/paste with keyboard shortcuts.

**Comment by fokkonaut** [comment]
make the browser more like 0.6, generally make menus more like 0.6 xd

**Comment by ZombieToad** [comment]
fix favourites not showing if they arent in the masters list

**Comment by jordy-ruiz** [comment]
This is related to the open pull request #1171 

> * New scoreboard
> * some changes on the server browser
> * Background map animation

**Comment by jordy-ruiz** [comment]
The open pull request #1171 is relevant to this and should be looked into.

> * New scoreboard
> * some changes on the server browser
> * Background map animation

It's a fairly large commit though, we might need anyone's (ideally @SushiTee's) help to test out things and ease up the work pressure on @oy

**Comment by Sonix-** [comment]
- We should be able to move Favorites tab above "All" tab.
- Tab positions should be remembered and not reseted everytime we start the game
- It shouldn't be able to deactivate 'Standard gametype' in the 'Standard gametype'-tab (from #988)
- Add a settings button next to the quit button. A simple "⚙️" would be enough.
- Add back a sidebar that displays the server info and the players list of the selected server (the sidebar could be collapsable if possible; when the sidebar is collapsed popup infos should be activated automatically)
- Use only one column for favorites (the stars), currently 2 are used. Suggestion: use only the left column.
- Make the text/type boxes in the server filter more visible and also reduce/properly align the flag (doesn't look that good to me)
![filter](https://user-images.githubusercontent.com/2030615/47305977-6cacc580-d62b-11e8-8ac7-49a71aefb333.png)

- Actually display [Server Skill Level](https://github.com/teeworlds/teeworlds/commit/e2973652f790b72079e5f5c379d285748ef67fd6) in Server info, use stars as rating:
"Skill level: :star::star:"

I would suggest to make it look like this (note: its a quick sketch):
![serverbrowser_ui](https://user-images.githubusercontent.com/2030615/47305459-cc09d600-d629-11e8-9f4c-67568d79b051.png)

**Comment by jordy-ruiz** [comment]
@Sonix- 
Oh, right, that skill level feature! I remember it was proposed by @LordSk back in the days (2011).
I remember implementing his mockup in a 0.5 (!) client mod:

![image](https://user-images.githubusercontent.com/355114/47367447-f6b66600-d6df-11e8-84fd-dc59df10bfb8.png)

Does that look good to you?

**Comment by oy** [comment]
@jordy-ruiz 
Grabbed everything but the scoreboard from that pull request I think.
These icons are more compact than the stars which is probably good, though I'm not sure about the colours. Red usually indicates sth bad.

@Sonix- 
That's good.
What do you mean by "We should be able to move Favorites tab above "All" tab"? Isn't it already above the "All"-tab?

**Comment by jordy-ruiz** [comment]
> These icons are more compact than the stars which is probably good, though I'm not sure about the colours. Red usually indicates sth bad.

Yeah, I tend to like colourful stuff but since the Teeworlds menus are completely black&white, should we drop the colors altogether and just have those icons in white?

> @jordy-ruiz
> Grabbed everything but the scoreboard from that pull request I think.

Oh, cool. So what's left to do with the scoreboard in PR #1171 then? Reviewing, merging? Could a reviewer be assigned, maybe?

**Comment by oy** [comment]
The ping already got coloured (green=good, red=bad). So we just have to be carefull :)

I'm not sure if the scoreboard is finished in there. But if someone wants to work on/add it, that would be fine with me.

**Comment by ZombieToad** [comment]
it would be nice if server browser favourites could show hostnames instead of ips and also show hostnames that it didnt manage to get an ip for

**Comment by oy** [comment]
We should probably move the scorebaord discussion to a seperate issue.

**Comment by LordSk** [comment]
![server_broswer_mockup_lines](https://user-images.githubusercontent.com/294603/47577257-b6a4ec80-d946-11e8-9bf8-49f062f9e355.png)

Scaling/aligning properly is hard, so please consider the general idea of the mockup.
When you click on a server, it expands downward showing details and player list.

[Here](https://github.com/LordSk/teeworlds/blob/develop/server_browser_mockup/server_broswer_mockup_lines.svg) is the file, if you want to tinker with it.

**Comment by Zatline** [comment]
(https://lh3.googleusercontent.com/eKKlz3T9MBJ7RApIbnkraapKkQbJT-RNf509MixpRR8gbo4NJDugmDgFcGudo66_CTT-d86haCPCug=w3840-h1782-rw)

will make some concepts soon once I get Inkscape back running, here a lil draft of what needs to be fixed

**Comment by JamesTrj** [comment]
What do you think? Do you have any idea to improve it? (the "information" tab isn't complete, yet)
![screenshot_1](https://user-images.githubusercontent.com/44511917/47601314-c692ef80-d98b-11e8-99b8-2b16a221d1fe.jpg)
![screenshot_2](https://user-images.githubusercontent.com/44511917/47601315-c692ef80-d98b-11e8-9a05-08ce463143f0.jpg)
![screenshot_3](https://user-images.githubusercontent.com/44511917/47601317-c692ef80-d98b-11e8-994e-d8ba1edba3ba.jpg)
![screenshot_4](https://user-images.githubusercontent.com/44511917/47601318-c692ef80-d98b-11e8-8ec8-f7ced1ed344a.jpg)

**Comment by oy** [comment]
@LordSk 
That's too cluttered with details for my taste, prefer it simpler. It's hard to get the information you're looking for at first sight.
And in general I prefer the favourite servers in the internet tab. There were supposed to be custom filters as well. So if you like to play some setting you make a custom filter for it. Then you see the available servers/players right away  and don't need to change the search criterion each time.

**Comment by Dune-jr** [comment]
I believe the custom filters appear as a drop-down on the right on the said mockup (it says "Default").

**Comment by oy** [comment]
![untitled](https://user-images.githubusercontent.com/293850/47602569-0df79b00-d9e1-11e8-8464-e32ececbe3a3.jpg)
With the custom filters you don't need the server filter menu showing all the time.

**Comment by Dune-jr** [comment]
Those are quite well hidden in their current state, I couldn't figure how to filter.

**Comment by Sonix-** [comment]
Gonna post an update of my mockup, I've added @LordSk server filter in the sidebar and I also like hid idea of displaying skill levels (tee eyes). I've made 2 versions regarding skill level icons:
![mockup_browser_ui_skill1](https://user-images.githubusercontent.com/2030615/47603194-e86e8f80-d9e8-11e8-93e9-65c59d5818e8.png)

![mockup_browser_ui_skill2](https://user-images.githubusercontent.com/2030615/47603196-ec021680-d9e8-11e8-8ff5-d0a97f3f99c2.png)

There still should be a tooltip once you hover the icons with the cursor saying: Competitive/Hard, Medium/Normal, Easy

**Comment by Dune-jr** [comment]
I like the tee expressions much more: I think something that says "Casual/Competitive" would be closer to the reality of what those are likely to be used for than proper skill ranks.

I really like the settings button on the top right, I feel like it was missing. If possible, also improve the close button that just looks like an `X` for now.

Another suggestion: some sort of easier-to-spot visual indicator for empty/full servers would be cool (darker background maybe?).

**Comment by Dune-jr** [comment]
It was brought to attention that the UI is also missing a button to save filter settings other than using JSON files like:
 ```
   {"custom": {
        "type": 0,
        "extended": 1,
        "settings": {
            "filter_hash": 65537,
            "filter_gametype": "",
            "filter_ping": 999,
            "filter_address": "",
            "filter_country": -1,
            }
        }
    },
```

**Comment by Zatline** [comment]
> do we keep the 0.6 filter bar on the right?

the thing is it still has to work on a 4:3 aspect ratio, having it on the right would't be a problem for widescreen ratios but what when the game is played on 4:3 it would clip beyond the visable so an exception has to be hard-coded in case of clipping.

**Comment by oy** [comment]
LordSk's server rank icons with tooltip would be my choice.
Also like the gametypes selecting from LordSk's mockup.
Expanding it like LordSk did would be better for 4:3 ratio like Zatline mentioned.
We could check how the filter bar on the right looks like. If it isn't too squeezed then go for it.

**Comment by Zatline** [comment]
@Oy been working on some fresh concepts last night addressing all open issues gotta clean it up and refine it some more so it can be used as 1:1 template and guid for u guys to code.

**Comment by android272** [comment]
@LordSk's mockup looks the best to me. I was working on something like this like two years ago but stopped for some reason.  I feel as though it shows everything you need to know about that server clearly right there. You don't need to know the column names as you do now. Currently, unless you have been playing Teeworlds for a bit you may not know the difference between the game type column and the map column as most maps are named after what you play on them. But as his mockup shows you can play LMS on a dm7. The icons clearly show you what each of these letters actually means. You can just infer that the icon that looks like a Mario map is probably the map and the icon with a tee standing on bones is the game type. especially with the icon above that in the previous server shows two flags indicating that the server is playing CTF. This is very simple and in my opinion, the way we should go with this.

I am kinda mixed on whether to go with the meddles or the tee eyes for the difficulty level.

**Comment by JamesTrj** [comment]
![steam_server_browser](https://user-images.githubusercontent.com/44511917/47766447-4d014700-dc94-11e8-91f7-24c437f7474a.png)

**Comment by JamesTrj** [comment]
![700px-02-03_02_1_serverbrowser_newlook5](https://user-images.githubusercontent.com/44511917/47767386-04985800-dc99-11e8-80d3-819e9e27bbbe.jpg)

**Comment by 1stDecadeTW** [comment]
Teeworlds deserves this server browser, it's simple, useful and neat. From beginners and old players is easy to use, and find things.

This is the dark version, I will later upload the lighter version (both are supposed to be eligible in advance configs).
![11](https://user-images.githubusercontent.com/44511917/47894516-fbd68c00-de28-11e8-8747-9bc1335d9aa7.jpg)
![12](https://user-images.githubusercontent.com/44511917/47894517-fc6f2280-de28-11e8-8be5-9636a5aea9d8.jpg)
![13](https://user-images.githubusercontent.com/44511917/47894518-fc6f2280-de28-11e8-91e6-811e01819d90.jpg)
![14](https://user-images.githubusercontent.com/44511917/47894519-fc6f2280-de28-11e8-96c0-27c4f88e3349.jpg)
![15](https://user-images.githubusercontent.com/44511917/47894520-fc6f2280-de28-11e8-9af6-c22e511132f5.jpg)
![16](https://user-images.githubusercontent.com/44511917/47894521-fc6f2280-de28-11e8-8203-6a25f49d49c4.jpg)

**Comment by Dune-jr** [comment]
Maybe late, I like the tabs design for the right panel though. It is very apparent that you can switch :)
Not everything looks feasible, like the checklist of gametypes or the size of maps (that the client doesn't know).

But overall lots of things are good-looking. Things I personally like:
- the reset friends button
- the difficulty choosing panel
- the country flag that isn't a scrolling list
- the overall floating panels and their color/transparency levels

Too bad it's a bit late. We shouldn't have split the issues with #1588 :/

**Comment by Sonix-** [comment]
Why is it late? To me looks like Zatline didn’t even consider the ones we suggested, and made one on his own

**Comment by Dune-jr** [comment]
@Sonix- yeah, I'm a bit upset about that too :/

**Comment by Dune-jr** [comment]
From my understanding, @oy said he would like to code a prototype this weekend though, so there needs to be a consensus on what it should look like.

**Comment by LordSk** [comment]
@oy Sounds great to me.

**Comment by Dune-jr** [comment]
@oy I second this, it sounds very good.

**Comment by Zatline** [comment]
@oy sounds very good indeed

**Comment by oy** [comment]
Ok. then we'll try it that way.
We gonna need gametype icons, an icon for the header of the server level column and the icons for the 3 tabs of the sidebar.

**Comment by Zatline** [comment]
![browse_main](https://user-images.githubusercontent.com/344608/47957585-032c9f80-dfb9-11e8-832b-3bc2e6fc6265.png)

**Comment by 1stDecadeTW** [comment]
Maybe upload the UI advance of the current server browser to see how we can continue improving it, and see how it looks like?

**Comment by 1stDecadeTW** [comment]
> Not everything looks feasible, like the checklist of gametypes or the size of maps (that the client doesn't know).

@Dune-jr 
I will be really helpfull that the client could display this kind of Quick filters, specially when you have the collapsable side panel hided.

Adicional function: new players could discover all kind of game types in teeworlds.

![screenshot_2](https://user-images.githubusercontent.com/44511917/47960229-50ab0b80-dfbd-11e8-92e6-d7d398d952b4.jpg)
![screenshot_3](https://user-images.githubusercontent.com/44511917/47960230-5143a200-dfbd-11e8-884c-6ee186eece14.jpg)
![screenshot_4](https://user-images.githubusercontent.com/44511917/47960231-5143a200-dfbd-11e8-8ae2-3bab85eb02c1.jpg)
![screenshot_5](https://user-images.githubusercontent.com/44511917/47960232-5143a200-dfbd-11e8-87ac-72cf83f2e14e.jpg)

**Comment by 1stDecadeTW** [comment]
![gametypes icons](https://user-images.githubusercontent.com/44511917/47969513-66ace080-e03e-11e8-8e21-266838d37053.png)
![screenshot_1](https://user-images.githubusercontent.com/44511917/47969514-66ace080-e03e-11e8-8086-242846bb724d.jpg)

**Comment by Zatline** [comment]
@1stDecadeTW I think it's a nice and honorable thing to provide an icons for the very most iconic and popular community mods like Race and Instagib and perhaps DDrace but besides that there should just be a universal icon for mods / non-offical gametypes.

**Comment by 1stDecadeTW** [comment]
![imagen1](https://user-images.githubusercontent.com/44511917/48102912-cc41ce00-e1f2-11e8-9714-213e094e2e3a.png)
![screenshot_1](https://user-images.githubusercontent.com/44511917/48102913-cc41ce00-e1f2-11e8-9f12-0b77f978e61c.jpg)
