### ISSUE TITLE
Before releasing 0.7.1

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1541]
please fix all the bugs, dont release unfinished project like 0.7.0 please!

AND please, dear Oy, please listen to the community and dont make changes the community doesnt like. its an open source game and we, the playing community, want to influence the project. stuff like removing broadcast is just not neccessary, what was wrong with it?

There are many things that the community doesnt like about 0.7 at all, so fixing those in 0.7.1 would be great.

**Comment by jordy-ruiz** [comment]
I believe the plans for 0.7.1 are precisely to fix all the issues 0.7.0 opened, so this should go well.
As for design choices like removing broadcast, I believe that was done years ago :/

**Comment by ChillerDragon** [comment]
@jordy-ruiz yes removing broadcast was years ago but the community feels the effect right now.
Imo we should do a vote or something on broadcast.

**Comment by jordy-ruiz** [comment]
@ChilleDragon A vote doesn't really seem like the way to go, to me, but if you have arguments in favor of restoring the broadcast feature you should probably write them at #1529. I too, would like to keep this feature.

**Comment by jordy-ruiz** [comment]
@ChillerDragon A vote doesn't seem like the way to go to me but if you have arguments in favor of restoring that feature it's probably best to post them on #1529
