### ISSUE TITLE
Favourite Servers

### ISSUE THREAD

**Issue by ZombieToad** [teeworlds/teeworlds#1542]
Favourite servers only show if they are in the master server list

**Comment by nheir** [comment]
Where favorites have to be in server browser ? Only favorites ? Teeworlds ? All ?
I think they should be in every filter they match but do @oy @Dune-jr and you have another idea ?

**Comment by Dune-jr** [comment]
I second this, I think the favorites list should be like an additional local masterserver list.
@oy may have a different opinion on that.

**Comment by oy** [comment]
If you see it as an additional masterserver then it should be in all. I would be fine with either way.
