### ISSUE TITLE
`Show social` and `id: name` seems wrong

### ISSUE THREAD

**Issue by nheir** [teeworlds/teeworlds#1544]
_Using 0.7 version_

I don't know if this is intended but when disabling `Showsocial` the scoreboard show client numbers `0: ` `1: ` etc.
That is also the case for nameplates and score in the HUD.

It might be coherent to also remove the number (and/or the `:`)
I don't understand well the purpose of this option though.

**Comment by oy** [comment]
That feature disables all social stuff like names, chats etc. But I think it's ok to just show the id's then, so you're able to react if someone is f.e. blocking the game.
