### ISSUE TITLE
Update license.txt

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1548]
Copyright is still 2007-2016

**Comment by oy** [comment]
We also need a list of authors for all the content - probably a tricky one.

**Comment by Dune-jr** [comment]
All we need is a list of artists who did not contribute directly through git, right?

**Comment by oy** [comment]
Yeah. We should probably list all artists who worked on the content all together, instead of listing all content items and showing each authors respectively.

**Comment by Dune-jr** [comment]
@Fisico nicely proposed to help try to document some list of artists, as hard as it may be. 

But, huh, do we need to list them all since Teewars inception? That sounds impossible.

**Comment by Fisico** [comment]
my progress so far.
![image](https://user-images.githubusercontent.com/329471/48793685-0b464800-ecf8-11e8-9a44-a8aa9342ed5f.png)

**Comment by oy** [comment]
matricks did maps yeah.
Dunno if we need to list all the contributors per category or just list them completely.

**Comment by Fisico** [comment]
update
![image](https://user-images.githubusercontent.com/329471/48798190-5c5c3900-ed04-11e8-888a-4460b362c4dd.png)

**Comment by Fisico** [comment]
Here is my List sorted by category and alphabet

Graphics:
android272
Crises
Echchouik
Fisico
Landil
Lappi
maikka
red_com
serpis
SkizZ
Sonix
teetow
Zatline


Maps:
Chi11y (chi1)
Daniel
ghost
Landil
LordSk
Matricks
Pocram
serpis
somerunce
Sonix
Stephanator
teetow
Zatline


Documentation:
cinaera
Fisico
KillaBilla
Landil
Matricks
Minus
oy
Sonix
Tardo
teetow


Music/Sounds:
serpis
teetow

**Comment by oy** [comment]
What's documentation?
Hm, probably should do sth for the translations as well? Authors within the language files? Or in the license.txt?

**Comment by Dune-jr** [comment]
Yeah gotta add Ubu.

Documentation is relative to the Teeworlds/documentation git, it shouldn't be included imo.

Credits for languages should be in the language files probably. It's an issue over there.

A link towards the compilation docs in the readme would be nice.

**Comment by Fisico** [comment]
added Ubu

translation list is easy to get over the repo

**Comment by oy** [comment]
> Documentation is relative to the Teeworlds/documentation git, it shouldn't be included imo.

Yeah not part of the release.

> Credits for languages should be in the language files probably. It's an issue over there.

Should probably update the script. Or add by hand - probably have to do it anyway for the transifex contributors.

>A link towards the compilation docs in the readme would be nice.

Yeah.

**Comment by Dune-jr** [comment]
If we don't do categories, this is the list of content contributors:

android272, Chi11y (chi1), cinaera, Crises, Daniel, Echchouik, Fisico, KillaBilla, Landil, Lappi, LordSk, maikka, matricks, Minus, oy, Pocram, red_com, serpis, SkizZ, somerunce, Sonix, Stephanator, Tardo, teetow, Ubu, Zatline
