### ISSUE TITLE
Redesign menus

### ISSUE THREAD

**Issue by chachad** [teeworlds/teeworlds#1551]
- Make in-game pause screen background more dark, as it was on previous versions.
- Make option to disable background animation in main menu.

**Comment by chachad** [comment]
> > Make in-game pause screen background more dark, as it was on previous versions.
> 
> Do you have an example/screenshot?
> 
Sorry, I was wrong. I was mean what the background color at 0.7 too light, and if a map uses bright, light tiles, the white letters at the pause menu doesn't looks good in my opinion. I think it is will be more better, if ingame pause menu will has more darker background for every submenu(like Game, Players, Call vote, Settings and also for settings too).

**Comment by oy** [comment]
Should probably add a setting option for this.

**Comment by Dune-jr** [comment]
@oy could it be cleared up what remains to be done for this?

**Comment by oy** [comment]
Just higher alphas for ingame menu i guess.
