### ISSUE TITLE
Improve the scoreboard

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1556]
Split from issue #1538 
-------
About the scoreboard, this is what I've found in Zatline's original project:
![fireshot capture 16 - teeworlds 0 7 x - user inte_ - https___zatline carbonmade com_projects_5691196](https://user-images.githubusercontent.com/2030615/47385403-2f6b3500-d70a-11e8-88c5-12015f685ec0.png)

_Originally posted by @Sonix- in https://github.com/teeworlds/teeworlds/issues/1538#issuecomment-432384931_

----------
With respect to the scoreboard, I've been looking for screenshots of the old spl0nk's [Teecomp](https://www.teeworlds.com/forum/viewtopic.php?id=3913) modification

It looked like this; (0.5)

![image](https://user-images.githubusercontent.com/355114/47387912-0f8b3f80-d711-11e8-9f06-8c7e2668292f.png)

A simpler version: (0.6)

![screenshot_2018-10-23_22-18-29](https://user-images.githubusercontent.com/355114/47388110-a22bde80-d711-11e8-9df5-fd8a596acc1c.png)

This more detailed scoreboard was built on a different command/hotkey, as additional statistics, and displayed at the end of the match. This isn't the kind of stuff that I would say belong on a 0.7.1 roadmap, but it's cool nonetheless. It may deserve a separate discussion.

_Originally posted by @jordy-ruiz in https://github.com/teeworlds/teeworlds/issues/1538#issuecomment-432404830_

-------
We should probably move the scorebaord discussion to a seperate issue.

_Originally posted by @oy in https://github.com/teeworlds/teeworlds/issues/1538#issuecomment-432765385_

**Comment by oy** [comment]
There're 2 similar issues #158 and #354.
I think the extended version should be just shown at the end of a game like Ubu- proposed.

**Comment by Sonix-** [comment]
@Dune-jr Is talking about a secondary scoreboard that kinda has nothing to do with the main scoreboard, the so called "statsboard". The statsboard was used by many high level players, it's an useful feature for players to exchange and compare stats with other players or even to use as info on how to improve on certain aspects.

It should be bindable like the scoreboard or shown just at the end of a round. Maybe we could discuss on how it should look or enhance the look of the ones @Dune-jr has shown.

**Comment by Zatline** [comment]
@Dune-jr  think there is a client somewhere were Sushi started coding the scoreboard it was the very last thing I remember that we did before the project then died got to check.

**Comment by oy** [comment]
![untitled](https://user-images.githubusercontent.com/293850/47608017-0c04fa80-da28-11e8-8ebf-b544c8ae529a.jpg)
That's the one from here #1171

**Comment by Zatline** [comment]
@Oy precisely what I was looking for

**Comment by Dune-jr** [comment]
If I'm not mistaken, that's the Teecomp scoreboard that was already mentioned in the first post.

**Comment by Fisico** [comment]
> ![untitled](https://user-images.githubusercontent.com/293850/47608017-0c04fa80-da28-11e8-8ebf-b544c8ae529a.jpg)
> That's the one from here #1171

why not add the Scoreboard from the pull request. Yea it has to be merged manually but I really like it and its way better than the actual one.

**Comment by Zatline** [comment]
@Fisico it's also quite close to what the original concept shows what I had in mind for it. Some minor astethic things perhaps left to refine like fit aspect and other marginals but nothing of big deal. I'd love see it merge  :)

**Comment by Dune-jr** [comment]
I merged the scoreboard from @SushiTee's #1171 here: https://github.com/Dune-jr/teeworlds/tree/feature-scoreboard2

This is what it looks like, right now:
![screenshot_2018-11-08_16-31-21](https://user-images.githubusercontent.com/355114/48208925-346bed80-e374-11e8-9990-f93a716f8a41.png)

Some adjustments are probably needed.

**Comment by oy** [comment]
Looks a bit sqeezed.

**Comment by Fisico** [comment]
> I merged the scoreboard from @SushiTee's #1171 here: https://github.com/Dune-jr/teeworlds/tree/feature-scoreboard2
> 
> This is what it looks like, right now:
> ![screenshot_2018-11-08_16-31-21](https://user-images.githubusercontent.com/355114/48208925-346bed80-e374-11e8-9990-f93a716f8a41.png)
> 
> Some adjustments are probably needed.
> Maybe it should be repositioned; also, flags need to be added.

its a dynamic scoreboard... less players = small scoreboard in height.
It should always be in the middle of the screen(Top-Bottom and Left-Right) and it needs some spacing to the spectator section.
I really like it.

**Comment by quadCoreZ** [comment]
there is also a little bug. the kills/deaths reset doesn‘t work properly. every time the game is paused & will be unpaused, the stats reset again. i think it only needs a reset after gameover or roundover

**Comment by TsFreddie** [comment]
![screenshot_2018-11-24_11-36-58](https://user-images.githubusercontent.com/3797859/48964254-412c4a80-efde-11e8-8126-3249c444a225.png)
I made this scoreboard a long time ago, too bad I lost the code for it.

**Comment by oy** [comment]
Fixed.
