### ISSUE TITLE
Improve client-side whisper UX

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1557]
Right now I can't tell the difference between a whisper and a ping. It should have a different color or something.
![image](https://user-images.githubusercontent.com/355114/47527512-f9ad8400-d8a2-11e8-80f7-de27d1d55d97.png)

Show the name of the receiving player, at least for outgoing PMs?

Other suggestions:
- implement shift+tab
- start with the last whispered player so we don't have to cycle through all of them again
- some sort of "/r"-style fast reply?
- etc.

If anyone has design suggestions... :)

Edit: Okay, it's even hard-coded to be displayed the exact same as a highlight:
https://github.com/teeworlds/teeworlds/blob/fa83830e48716f6fb6ed0ec6f9a263274f219239/src/game/client/components/chat.cpp#L435
@cinaera

**Comment by oy** [comment]
Dunno about another colour, nobody might get what's what anymore. But some indicator for PMs would be good.
Starting with the last whispered player would be good too.

**Comment by Sonix-** [comment]
Perhaps using an icon or some unicode symbol before the nicknames?
Some examples:
**nameless tee:** hello
**💬 nameless pink:** Hi
**⤷ nameless red:** Good morning
**⭢ nameless blue:** Hello
**⯈ nameless green:** What's up?
**⮞ nameless orange:** Sup

**Comment by Dune-jr** [comment]
That sounds good to me. Would you introduce those icons for all chats, or only PMs?

**Comment by Sonix-** [comment]
Only whispers, in order to differentiate them from regular chat messages

**Comment by oy** [comment]
Yeah, a symbol just for whispers would be good.
An icon might be best. The unicode character someone could fake in his name. There is the id in front of every name, but still.
