### ISSUE TITLE
Survival gametypes wait time before rounds is too long

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1558]
Even with some 5-6 players, between the scoreboard and the warmup, there is a lot of waiting time and I feel like it could be sped up a bit. Could something be done about that?

**Comment by oy** [comment]
You mean the round over scoreboard is shown too long? Reduce it by half?

**Comment by Dune-jr** [comment]
> You mean the round over scoreboard is shown too long? Reduce it by half?

Yeah, exactly.
