### ISSUE TITLE
Client command 'team' was removed in 0.7

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1561]
This `team` client command:
https://github.com/teeworlds/teeworlds/blob/344a58cd858669f2b742827024dff7fd25fccccf/src/game/client/gameclient.cpp#L177-L180

was removed in 0.7:
https://github.com/teeworlds/teeworlds/blob/fa83830e48716f6fb6ed0ec6f9a263274f219239/src/game/client/gameclient.cpp#L225-L228

breaking all binds to switch to red team, blue team, or spectators :disappointed: 

Is there a reason for this or should it be restored?

**Comment by oy** [comment]
Could be added again. But needs some check/response message in the client. Server drops not allowed ones silently (that should stay that way).

**Comment by Dune-jr** [comment]
> Server drops not allowed ones silently

That is?

I'm a bit confused, the join button is just client-side sugar-coating, right?

**Comment by oy** [comment]
The client knows now, when you can join/change a team and makes the buttons just available when you can.

**Comment by Dune-jr** [comment]
@oy then making the command ineffective when we can't join/change team should do it?
Just like the buttons.

**Comment by oy** [comment]
Yeah, maybe drop a message in the client console?

**Comment by Dune-jr** [comment]
Sounds good, yeah.

**Comment by Dune-jr** [comment]
Awesome, thanks!
