### ISSUE TITLE
SUR/LMS gametypes have confusing names

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1562]
> I still personally consider the naming scheme of the elimination modes to be a mistake - just call it "elimination" or EL. Then team elimination is TEL. It's a lot more consistent than the current lms/sur naming scheme - I for one have no recollection of which one of those is a team mode and which one isn't. I would really like to see this changed.

[_Deku on the forums_](https://www.teeworlds.com/forum/viewtopic.php?pid=121817#p121817)

----

It might be a bit late but I believe being consistent with the DM/TDM naming scheme would yield something much more intuitive. Could this be looked into?

**Comment by LordSk** [comment]
EL and TEL are much better names I agree.

**Comment by ZombieToad** [comment]
Last Man Standing (LMS) or Last Team Standing (LTS)

**Comment by oy** [comment]
I'd prefer what @ZombieToad proposed over EL/TEL.

**Comment by Dune-jr** [comment]
Wikipedia supports @ZombieToad's proposal:

> **Last Man Standing (LMS)** or **Last Team Standing (LTS)** is a multiplayer deathmatch gameplay mode featured in some first-person shooter computer and video games, and is also the essence of battle royale games.

https://en.wikipedia.org/wiki/Last_man_standing_(gaming)

**Comment by Sonix-** [comment]
I second the LMS / LTS names.

**Comment by Sonix-** [comment]
@oy Do we have to? I mean, LMS can be played pretty much on any map, while LTS on specific maps.
Calling them sur / survival maps is ok imo, "lts1" sounds odd to me but maybe more efficient for people to link them with the gametype. I'm okay either way.

**Comment by oy** [comment]
Linking them to the gametype might be better, not sure. True, lts1 is kinda odd.

**Comment by Dune-jr** [comment]
I think either way is fine.

**Comment by nheir** [comment]
Following `dm[1-9]`, it should be `lms1` that is a bit better.

**Comment by Dune-jr** [comment]
@oy This doesn't seem completely fixed to me. The client needs to recongize lms1 as a pure map, right? Also, maps need to be renamed, this should be an issue in teeworlds-maps

**Comment by oy** [comment]
Hm, dunno if the map needs to be renamed to lms. It's about survival (that's the keyword here), the internal gameflag is survival, would be ok to keep it sur1.

**Comment by Dune-jr** [comment]
Good point. Might still be a bit confusing? What do you think, @Sonix- ?

**Comment by Sonix-** [comment]
I’m okay either way. Logically should be linked to its gametype to avoid confusion

**Comment by oy** [comment]
But we don't have tdm maps either and play it on dm and ctf maps. But I'm okay either way too :)
