### ISSUE TITLE
4k scaling wrong fullscreen like borderless window 

### ISSUE THREAD

**Issue by Zatline** [teeworlds/teeworlds#1563]
gave 0.7  a shot and run into some scaling issues first launch, tried to change resulution didn't seem to work whatever I picked it always reselected the lowest available resulution even when I edited the settings.cfg file by hand. My monitor's native resolution is 3840x2160. 

Thing is I guess I found a temporary workaround by selecting borderless window instead of fullscreen. 
That at least didn't reset the resulution to the lowest available value and gave me a much clearer image.

But weird non the less because this way 1080p actually appears perfectly fullscreen.
Which in theory is wrong for a 2160p display, also any resolution greater than 1080p actually goes beyond my display. Things really get messy then, interference with Windows 10 built-in scaling perhaps?

**Comment by Dune-jr** [comment]
See #1505 too

**Comment by LordSk** [comment]
https://wiki.libsdl.org/SDL_CreateWindow
**SDL_WINDOW_ALLOW_HIGHDPI**
We should take a look at this window creation flag.

**Comment by oy** [comment]
Fixed by 9b22b2426daf71bac6078a2376544a96cd7f06b4
