### ISSUE TITLE
Dyncam as a default setting

### ISSUE THREAD

**Issue by AlphaSwag** [teeworlds/teeworlds#1565]
I'm reposing this from Tw forum:

Take off dynamic camera as a default setting! How is that good? It's a nice feature but it's completely un-intuitive compared to a fixed camera and it must not help those new players getting smashed as mentionned earlier!

Especially on vanilla mods where almost everyone starts, not only does it have little use for newbies but it just makes your fighting not flow right.

How many times do you see obvious first-time players with decent gaming sense but awful movement just wandering around and likely quitting and never playing again?

If someone plays more they can experiment with dynamic camera and choose onwards, but naturally it shoud be a fixed camera.

Although this is a trivial change, If the default gameplay was more intuitive, it would make a certainly noticable difference for new players which is something everyone would like to see in TW.

I've been playing tw since 2008 and have always tried to get new players into the game teach them basics etc and many, many new players struggle with movement, and this is due to stock dyncam. 

You see them walking on the ground slowly, trying to shoot people (with decent aim!) but their static movement just makes them extremely easy to kill for even lower skill players who don't have this, and also develop better aim due to better natural reflexes possible with no dyncam. They see others ``flying`` around and think they're hacking or just gods in another league.

 I really think it would make a big difference for the many new players who come and quit rapidly, I've spoken with many tees about this as well and they all seemed to agree. So yeah just submitting this small but important factor imo.

**Comment by oy** [comment]
Well, when you play the game for the first time you just run/jump around cause moving with the hook is hard and needs time to get used to it. A wider range of sight maybe more usefull in this situation.
But maybe we can have a vote about it?

**Comment by Dune-jr** [comment]
Referenced on the teeworlds.com forums: https://www.teeworlds.com/forum/viewtopic.php?pid=121830

**Comment by Sonix-** [comment]
I'm ok for disabling it by default. But the player should be able to choose which one to use on first start in the future (Tutorial or User configuration on first start).

**Comment by Zatline** [comment]
agree with Sonix and perhaps have a hotkey that enables dynamic camera when hold in case dynamic camera is disabled, maybe set shift or strg as default bind if those ain't binded yet.

**Comment by Dune-jr** [comment]
> I'm ok for disabling it by default. But the player should be able to choose which one to use on first start in the future (Tutorial or User configuration on first start).

Makes me think, we still have that welcome screen where you choose your name, right? Sounds like a good place to at least make the player aware of the choice.

**Comment by oy** [comment]
It's hard to decide on something you didn't test so far. So not sure about putting it on welcome screen.

**Comment by Dune-jr** [comment]
Yeah, you're right.

**Comment by Dune-jr** [comment]
A lot of people have asked for a way to set a dynamic camera toggle. But actually, #888 already introduced the console commands `toggle` and `+toggle`.

So all that needs to be done is to add a `ClDynamicCamera` setting. It would also greatly improve stuff like
https://github.com/teeworlds/teeworlds/blob/9eeb7dffa5826c38c7b5ef70cb787a3dd65bc3e1/src/game/client/components/menus_settings.cpp#L709-L723
and not go back to defaults everytime it is enabled/disabled

**Comment by oy** [comment]
@Dune-jr 
Sounds good. But there should still be an option to reset to default values in case you took a wrong turn.

**Comment by oy** [comment]
Then you reset everything. 
Probably better to be able to just reset the dynamic camera, when you can't do it with the enable/disable button anymore.

**Comment by Dune-jr** [comment]
@oy The thing is, a Camera Reset button would be weird when there are zero settings anywhere on the menus to change how the camera behaves.

I wouldn't be against adding sliders for the mouse/camera in the Controls settings though. But right now the Dynamic Camera checkbox is in general. So, ugh.

- What behavior do we want the "Dynamic Camera" checkbox to have? Keep camera settings or reset them to default everytime?
- Do we want the camera to be customisable + resettable in the menus?

I see several options:

1. Keep the same UI behavior. Checking/unchecking from the menus resets camera settings. This does not break `+toggle cl_dynamic_camera 0 1` if the user doesn't touch the menus.
1. Change the UI behavior to not reset camera options. Do not add any additional settings or reset button. This means that, if the user changes the camera using the console, the only way to reset is to use the big "Reset" button
1. Change the UI behavior to not reset camera options, add camera settings to tune it in the Controls menus, and a specialized reset button. This means Dynamic Camera would probably have to quit the General menus, making it less visible.

I believe 1. is the best from the user experience. What do you think?

**Comment by oy** [comment]
@Dune-jr 
Yeah option 1 is the best.
