### ISSUE TITLE
Checkered bg (cl_menu_map none) should be made default again

### ISSUE THREAD

**Issue by Zatline** [teeworlds/teeworlds#1566]
menu map thing is a cool option sure but more distructiv to the user experience than perhaps intended, the day jungle map is very bright and gets anoying after some time while the night jungle map is calm but leads to UI details getting lost in the dark.

the thing that I originaly intend to fit the UI was a simple blue sky with some clouds moving along similar to this image https://i.gyazo.com/b9561d035aa8347b32dafc819ec419c4.png 
had that on my list for the menu at some point down the line

othetwise the classic checkered bg (cl_menu_map none) should be made default again, it suits the UI best.

**Comment by Dune-jr** [comment]
I think it's quite cool at first. Wouldn't an option to disable it in the General tab do it, for the regular players?

**Comment by Sonix-** [comment]
I have no problems with the new background maps. Perhaps an option to disable them and use the default bg would be ok or for those who find them too bright/dark a brightness slider?

**Comment by LordSk** [comment]
Can we get a very slow moving (not zapping around like now), which does not in any way react with UI events, plain and calm looking background map? A map that feels like a background. Perhaps some mountains in the distance, to create a feeling of depth?

**Comment by Dune-jr** [comment]
Wholeheartedly agree, @LordSk .
I would hope that #1668 would address this - I left a comment in this direction - and maybe some other map theme like you are suggesting :)

**Comment by oy** [comment]
The camera movements within the menu aren't linked to the background map. You can adjust the speed it moves to a different position and the camera movement when in postion.

**Comment by LordSk** [comment]
@oy Yeah I meant remove UI triggered movements altogether. A moving background at that speed takes focus **away** from the actual menus.

**Comment by Dune-jr** [comment]
The heavens themes was meant to address this point of the issue:

> the thing that I originaly intend to fit the UI was a simple blue sky with some clouds moving along similar to this image https://i.gyazo.com/b9561d035aa8347b32dafc819ec419c4.png
> had that on my list for the menu at some point down the line

as an alternative to:

> othetwise the classic checkered bg (cl_menu_map none) should be made default again, it suits the UI best.

Setting heavens to default: 

https://github.com/teeworlds/teeworlds/blob/6b5f2d8a31ade430f04f3ba77cc98dc255e473b1/src/game/variables.h#L89

should fix the issue then (right, @Zatline ?)

**Comment by Zatline** [comment]
yep, themes turned out awesome! good job @ dune-jr @sonix-
