### ISSUE TITLE
highlight chat sound

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1568]
now that the normal chat also uses the highlighting sound, ive replaced the normal chat sound with the old one. but now also the highlight chat and whispers uses the normal chat sound. why?

**Comment by Dune-jr** [comment]
> now that the normal chat also uses the highlighting sound

No, it doesn't? The normal chat sound and the highlight sound are different.

When it comes to questions about modding your Teeworlds install, it's probably best to use the forums: https://www.teeworlds.com/forum/

**Comment by fokkonaut** [comment]
it does use the same, lol

**Comment by fokkonaut** [comment]
just redownloaded, for me the chat always uses highlight sound. if i replace the normal chat sound with the real normaol chat sound file from other client (ddnet) also highlight message are in that sound. help :c

**Comment by Dune-jr** [comment]
That's strange, I don't have the issue. Do sfx_msg-client.wv and sfx_msg-highlight.wv make the proper sounds, in data/audio ? Which version are you using, the 0.7.0 release?

**Comment by oy** [comment]
Normal and highlight chat sound have been switched in 0.6.2 (#630). It works how it should be - dunno what's up in the modded client that you use(d).

**Comment by fokkonaut** [comment]
stupid
