### ISSUE TITLE
Players max limit could be raised, to allow 48 spectators

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1574]
Following @oy's suggestion. Originally, player limit was raised from 12 to 16 to allow more spectators.

This is related and may be dependent on #1201

**Comment by nheir** [comment]
Ok, the first proposal is simply to increase the number of clients the server AND the client can handle.
This has the advantage to have a small footprint on the actual code and can make modded server not too hacky when handling more than 16 players. (i have no idea how a scoreboard with 64 players should look though).

A second proposal can be closer to the idea of separation of spectators and players.
I'm leaving some thought on implementation details.

Originally, there is a parallel between ClientID in engine/network_server and ClientID in game/server. Separating players and spectators can be done by some kind of translation table with ClientID (engine) to "PlayerID" or "SpectatorID".
The spectators team and CPlayer class will be incompatible, moving to spectator meaning destroying the instance and creating a CSpectator class for instance.
Each game event that need playerID uses it (without caring for clientid) but chat messages have to be aware of spec/player and clientID.
The translation table should be use also on client.

**Comment by prathje** [comment]
In my opinion splitting spectators from the actual players requires much effort (like nheir stated).
If I think about some sort of streaming, just allowing more spectators will also result in other problems. 

Keeping the current max of 16 players in config and just increase the overall MAX_CLIENTS would allow more spectators to the default gametypes and also better support for mods supporting like 48 or 64 players.

**Comment by Dune-jr** [comment]
> What about adding 64 actual slots but setting the config max in game players to 16.
> So spectators are not separated at all and modding is just changing a max value in the code.

That's already what is being proposed. See #1580

**Comment by oy** [comment]
fixed.
