### ISSUE TITLE
Transparency slider for UI 

### ISSUE THREAD

**Issue by Zatline** [teeworlds/teeworlds#1576]
Went through old to-do-list that I found inside the UI project files and there was this noted, still relevant!

**Comment by Dune-jr** [comment]
UI in general needs to be darker.
When the game ends and the scoreboard is shown, menus are sometimes barely unseable because of how transparent they are

**Comment by oy** [comment]
I think Sushi removed that on purpose.
If it would be added again the ui should be visible very good on default value.

**Comment by Dune-jr** [comment]
To illustrate my point:
![screenshot_2018-10-28_15-55-37](https://user-images.githubusercontent.com/355114/47617712-43c47e80-daca-11e8-9e4c-7f0085a4cac4.png)

**Comment by Zatline** [comment]
that's a bug scorebord should never be mixed with any other menu .. when hitting tab while being in the settings menu there either shoould nothing happen or settings menu gets hidden while tabing the moment tab gets released setting appears again, but both? seems wrong.

**Comment by oy** [comment]
The scoreboard at the end of the game comes automatically.
But it's not just the scoreboard - depending on the background it gets harder to read.
![screenshot_2018-10-29_17-55-10](https://user-images.githubusercontent.com/293850/47666538-0fbd8c00-dba4-11e8-9242-d255f403ec26.png)

**Comment by Zatline** [comment]
@Oy okay let's say we get the trancparancy slider and the current transparency value as seen in this screenshot is the very lowest available value, I find that pretty okay the thing that actually makes things confusing imo are the small stripe inbetween 🤕

**Comment by Dune-jr** [comment]
This is what 0.25 -> 0.50 alpha does:
![webp net-gifmaker](https://user-images.githubusercontent.com/355114/47852472-2a7a4580-dddc-11e8-8cfb-28c6ffa2ea78.gif)

**Comment by oy** [comment]
Much better readability with higher alpha.

**Comment by Dune-jr** [comment]
Teeworlds should look good out-of-the-box. I think we should enforce a higher alpha in the menus instead of a transparency slider, @Zatline @oy

**Comment by oy** [comment]
Yeah, that slider would be a lot of work to make it work pretty good.

**Comment by Zatline** [comment]
@Oy maybe toggle options instead of a slider? 0.25 low , 0.5 mid (set as default), 0.75 high

**Comment by Dune-jr** [comment]
If, as you propose, the 0.25 is still given an option, we ought to find another way to fix some situations like menus+scoreboard.
Options should be to alternate between different tastes of well-working menus. It feels like adding an option like this would make it up to the user to find which states give a functional Teeworlds.

**Comment by oy** [comment]
Adding a slider for the background is probably easier than doing it for the whole menu.

**Comment by oy** [comment]
I'm open for improvements ;)
