### ISSUE TITLE
Teeworlds Client - Windows - Hide Console Window

### ISSUE THREAD

**Issue by Fisico** [teeworlds/teeworlds#1583]
I think there should be a setting in the config file to hide the console that starts with the game on Windows and/or hide it by default.

It is not important for players to have it and I think it is kind of annoying to have a second window in the taskbar.

![image](https://user-images.githubusercontent.com/329471/47620213-f0f9bf80-dae7-11e8-9736-b3ef0cff9141.png)

**Comment by Dune-jr** [comment]
Yeah, it always felt really weird and unnecessary to me.

**Comment by Dune-jr** [comment]
@Stitch626 send us your patches then :)

**Comment by ChillerDragon** [comment]
@Dune-jr ddnet client has the option as well.

**Comment by Stitch626** [comment]
But is it really a good idea to copy code out of ddnet? I mean, that edit is like ten lines? (if I remember allright)

**Comment by Dune-jr** [comment]
I personally see no reason why a clean patch that does what we want wouldn't be applied, regardless of the source, as long as the license allows it.

**Comment by ChillerDragon** [comment]
@oy if it is deactivated by default it should be easy to activate it again. And not only by a console parameter. Something simple like ticking and option or executing an command in the in game console would be good.

It is super for reading chat while being on desktop ( if teeworlds is launched in fullscreen ).
And i am sure i am not the only one that uses that console a lot ( including many non tech people ).

**Comment by nheir** [comment]
Is F1 not what you want ? teeworlds is not a chat system, but if you want to see the chat while not playing, you can launch in windows mode. By the way, what you want is not this console but an external chat, no need for every game event. This is different from the actual log.

Anyway, is it possible to open a pre-filled console window on demand ?

**Comment by ChillerDragon** [comment]
@nheir what? Please simply don't remove the console feature. Teeworlds makes a lot of sense in fullscreen. And sometimes you have to tab out and you are not able to close the client ( in mods where you can loose progress like ddrace ).

**Comment by nheir** [comment]
you misunderstand, i'm not talking about removing console, only about the revelance of having a switch on/off on runtime. An option should be enough, like fullscreen/resolution/others graphics options that need a restart.

**Comment by Dune-jr** [comment]
The console feature should never be a default. It should be a console option for debugging or, at best, a menu setting.
Do you know of any other game with a console like that?

**Comment by ChillerDragon** [comment]
Oh yes @nheir i misunderstood that.
We don't need a feature to toggle the console without restarting the client. But i just wanted to go sure that nobody decides to make the console default deactivated and only invokable with an commandline parameter.

It should be as easy as an ingame console command or even an settings option to activate the console (client restart is totally okay after toggling console).

**Comment by Dune-jr** [comment]
> But i just wanted to go sure that nobody decides to make the console default deactivated and only invokable with an commandline parameter.

Well, that would be by far the easier solution. You see, the console must be initialized before loading the settings. Debug releases should probably have the console by default.

**Comment by ChillerDragon** [comment]
Exactly that is what i was trying to avoid...
Just implement it the way ddnet did it. You have a option in settings and as console command to deactivate or activate console. And then after restart of client the change takes effect.

There are people out there that play teeworlds in fullscreen and need the console to read chat on desktop while doing other things. You can't force all these people (including non techs) to compile their own debug build.

**Comment by Dune-jr** [comment]
@ChillerDragon That is because the console must be initialized before the settings.cfg is read. See:

> Well, that would be by far the easier solution. You see, the console must be initialized before loading the settings. 

> There are people out there that play teeworlds in fullscreen and need the console to read chat on desktop while doing other things. You can't force all these people (including non techs) to compile their own debug build.

They can use the -c option or windowed mode.

> Just implement it the way ddnet did it. You have a option in settings and as console command to deactivate or activate console. And then after restart of client the change takes effect.

If you know of a way to implement that as a console command, you can submit the patch to add that option (later, even).

**Comment by ChillerDragon** [comment]
> If you know of a way to implement that as a console command, you can submit the patch to add that option (later, even).

https://github.com/ddnet/ddnet/commit/fe22edadaacfe2abd0b3a5fbbfcb2067ca26c0a7

**Comment by oy** [comment]
@Fisico 
Yeah, that works.

**Comment by ChillerDragon** [comment]
@Fisico oh nice thanks

**Comment by Fisico** [comment]
maybe we should set up a better documentation for this.
