### ISSUE TITLE
Higher resolution for sun, moon and stars

### ISSUE THREAD

**Issue by Fisico** [teeworlds/teeworlds#1584]
The sun, moon and stars are very pixilated. Will higher resolution images break every map?

![image](https://user-images.githubusercontent.com/329471/47620539-674bf100-daeb-11e8-8316-0ee441297db9.png)

**Comment by Dune-jr** [comment]
What resolution is this?

**Comment by Fisico** [comment]
My game resolution is 1920x1080

the image resolution is 256x256

**Comment by oy** [comment]
Should work flawlessly.
Though we should test it with non-dilated images.

**Comment by Dune-jr** [comment]
From the discord:

> what do you think.. is 700kb for desert_sun to much?
> teeworlds can't handle pngs with modern compression.. i dont know why so i can only use one tool and this is not compressing much

**Comment by oy** [comment]
@Dune-jr 
No compression thing. Teeworlds can't handle png's with an indexed palette.

**Comment by Fisico** [comment]
@oy 
What do you think, is it a problem to update the graphics to 4k?
The whole graphics folder will grow fast in size. I don’t know if this is a deal breaker.

We have think about adding support for 4k tilesets and doodads or not. 4K resolutions are a big thing now and i think it would be sad, to see teeworlds get stuck in the 1080p days.

I also have to admit I don’t really know how much work it is to make teeworlds ready for 4k bitmaps.
Zatline told me that the graphics team already vectorised many tilesets and doodads. So from this side, it does not look like a big problem.

I think this should be discussed.

#1564

**Comment by Fisico** [comment]
I redid the sun, moon, desert_sun and stars. 
The Problem: in combination they are 1,18MB that’s half the size than all other graphics in the mapress folder combined.
If that is ok i will send a pull request.

Stars: 1024x512 (66,9KB)
Sun: 2048x2048 (66KB)
Moon: 2048x2048 (330KB)
Desert_sun: 2048x2048 (755KB)

**Comment by oy** [comment]
Well, that seems pretty big.

**Comment by Dune-jr** [comment]
So apparently, this pixellisation only really happens with the Texture Compression option enabled. That's why we couldn't reproduce it @oy

**Comment by Fisico** [comment]
its still a bit pixelated without compression.

Made a Pullrequest. Doubled the resolution.
