### ISSUE TITLE
Incorrect ping in the serverbrowser

### ISSUE THREAD

**Issue by axblk** [teeworlds/teeworlds#1585]
Because the client has to request a token from the server before it can request the server info, the ping value in the server browser is incorrect (about twice the correct value).

If the token for the corresponding server is still in the cache, the value is correct, but since the cache is quite small and tokens expire after 5 seconds, this rarely happens.

**Comment by Stitch626** [comment]
Or just check how long it takes to response with a token? So measure the time between client requests token -> and server send an answer?
