### ISSUE TITLE
Conceptuals addressing the Server Browser

### ISSUE THREAD

**Issue by Zatline** [teeworlds/teeworlds#1588]
addressing #1538 

- **Side Panel**, for widescreen displays

what has been added/ fixed/ changed marked in red!
![srv-browser_sidepan-exp](https://user-images.githubusercontent.com/344608/47692240-42dc3b80-dbf5-11e8-94bc-4eb487ed7539.png)

Friends:
![srv-browser_sidepan-01friends](https://user-images.githubusercontent.com/344608/47692138-09a3cb80-dbf5-11e8-9a0a-c4f5010758a6.png)

Set Filter:
![srv-browser_sidepan-02-01filter](https://user-images.githubusercontent.com/344608/47692182-1b856e80-dbf5-11e8-93e2-87a2ff882bdb.png)
![srv-browser_sidepan-02-02filter](https://user-images.githubusercontent.com/344608/47692190-1e805f00-dbf5-11e8-95c3-a03d9f839156.png)

Server Information:
![srv-browser_sidepan-03srvinfo](https://user-images.githubusercontent.com/344608/47692216-2dffa800-dbf5-11e8-94f5-fbf79e4c823f.png)

- **Overlay Panel**, for non-widescreen displays like 4:3 and 5:4 

**(bad solution, out of debate)** [Friends](https://user-images.githubusercontent.com/344608/47692617-aadf5180-dbf6-11e8-84f5-6324d6d2990c.pngl), [Set Filter](https://user-images.githubusercontent.com/344608/47692618-aadf5180-dbf6-11e8-9b57-e934c4d41dc7.png), [Server Information](https://user-images.githubusercontent.com/344608/47692619-aadf5180-dbf6-11e8-8fc1-9df3061220bd.png) 

map preview test image: #1578 
![rect3840](https://user-images.githubusercontent.com/344608/47694085-90a87200-dbfc-11e8-9ca9-fb7d866aa290.png)

@LordSk this is for you: difficulty.png
<img width="77" alt="difficulty" src="https://user-images.githubusercontent.com/344608/47693067-694fa600-dbf8-11e8-9dfc-8c941541fa2e.png">

Feedback like additional suggestions welcome, have fun coding! 🎃

**Comment by ChillerDragon** [comment]
i like the difficulty.png c:

**Comment by Dune-jr** [comment]
I quite like the difficulty.png too :)

Lots of good things. I am glad to have the Settings and Quit buttons back. The manager button isn't implemented, so it shouldn't be there.

Doing different things for non-widescreen resolutions sounds kinda bad. Also, the sidebar seems... awful in terms of usability.  To quote Oy:

>Expanding it like LordSk did would be better for 4:3 ratio like Zatline mentioned.
>We could check how the filter bar on the right looks like. If it isn't too squeezed then go for it.

**Comment by Zatline** [comment]
k thanks for the feedback got the point, guess I gonna give it another shot then.

**Comment by android272** [comment]
I really like showing the map preview. There is another place I would like to use that. Also, I really like your difficulty icons.

**Comment by Zatline** [comment]
> We could check how the filter bar on the right looks like. If it isn't too squeezed then go for it.

worked out new concept @Oy I'm a bit surprised how well squeezing it turned out!! 
it fits perfecrly well, I squezed by the size of removing one main menu botten @Dune-jr @LordSk 
We could definitely go for it as default as aspect ratio wouldn't matter anymore.

![srv-browser_squezed](https://user-images.githubusercontent.com/344608/47866043-04659d00-ddfe-11e8-8f8a-3d8ed604742c.png)

compare with old here [unsquezed](https://i.imgur.com/uRCLkPQ.png) !

**Comment by Sonix-** [comment]
Not bad, Cant wait to see how will server info proposed by @LordSk fit there.

**Comment by oy** [comment]
Looks good. Someone want's to work on it, leave a reply here. Otherwise I give it a try on the weekend.

**Comment by Dune-jr** [comment]
I think it's a bit of a pity how little ideas from @LordSk's mockup would be implemented:

![image](https://user-images.githubusercontent.com/355114/47874085-27e71280-de13-11e8-8757-db90776da914.png)

 The expand-to-view-details, the gametype filter, and static filters on the right were better usability imo.

Remove all the icon cluttering, implement @Zatline's friends tab, difficulty icons and you get something pretty good.

**Comment by oy** [comment]
> the gametype filter, and static filters on the right were better usability imo.
Looks to me like they're there. On top the tee for the friends filter, three boxes the filter settings and the i for the server info.
I'd go for a prototype and the go for improvements from there.

**Comment by Fisico** [comment]
an idea for zatlines server info sidebar.
The server info sidebar should be highlighted so it is instant visible that the sidebar corresponds to the selected server.


![image](https://user-images.githubusercontent.com/329471/47921316-94661e00-deb4-11e8-8ab3-10d5620fe92e.png)
