### ISSUE TITLE
Chat readability got bad with IDs

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1591]
>Why do we even have the IDs in front of the name? Sorry wasn't really able to test 0.7 yet, but is it an default? Imo the ID in front of names should be an debug/admin option and not default (if it isnt already).

>Sorry for the offtopic.

_Originally posted by @ChillerDragon in https://github.com/teeworlds/teeworlds/pull/1590#issuecomment-434726906_

---

I strongly agree with @ChillerDragon. I think it is absolutely insane that IDs are displayed next to players everywhere by default.
This is a technical thing, that should be enabled at best when someone is logged as admin.
It even adds a space before the name, breaking alignments and all sort of things.

I have seen several people talk ingame asking wtf that feature is, like if it means the order in which players joined the server, etc. People don't even _know_ what an ID is.

**Comment by Dune-jr** [comment]
> in 0.7 multiple people can have the same name and how would you know who was talking without the ids

There's got to be a better solution, like a `(1)` and `(2)` if two players have the same name, done client-side.

**Comment by oy** [comment]
It's just a coincidence, that these are the ids. These numbers are there to easily and properly identify a player. It's not about same names but similar ones.

**Comment by ChillerDragon** [comment]
Maybe just show them if the names collide?
Inside a () As we all know it already.
Just instead start counting from (1) place the id in there.

**Comment by Dune-jr** [comment]
@ChillerDragon 

> It's not about same names but similar ones.

It seems like the concern is there because the names aren't sanitized/look similar and I guess some players want to identify them quickly ingame.
I still think the current solution brings more downsides than upsides, though.

**Comment by ChillerDragon** [comment]
Oh the the big i ``I`` and small L ``l`` thing for example?
I never experienced this as a problem in vanilla. And if this is the case just turn on the ID mode.

**Comment by Fisico** [comment]
yea in the old days it was common some name "fakers" messed with people. I also think the ID system is not a good way to get rid of this problem.

**Comment by oy** [comment]
@LordSk had an idea to improve it.

@ChillerDragon it's not just small L and big i. There're as well all the utf8 characters and other simillarities like tttttttttttttttttttttt and tttttttttttttttttttt, that you can't spot right away.

**Comment by ChillerDragon** [comment]
Ye i get it. But who cares about people called tttttttt xd. And i am playing teeworlds for some years now i never had a problem with it in vanilla. I can imagine it could cause some. But trading chat readability is not the best approach imo. What do you think about an option @oy? Maybe not even as too hidden developer/debug option but easy visible for average users.

**Comment by oy** [comment]
Saw it a lot. People faking others and tried to get them kick voted. That's why the names in 0.6 got restricted to printable ascii chars.

**Comment by ChillerDragon** [comment]
@oy when did you saw it? Oh and i didn't know 0.7 allows more characters. Ye i guess it is like in the 0.6 mods.

**Comment by nheir** [comment]
I saw this kind of behaviour multiple times on vanilla servers too. In the last year. It doesn't happen too often but it's a pain not to know which fake to kick when it does.

**Comment by LordSk** [comment]
![id_mockup](https://user-images.githubusercontent.com/294603/47876314-4819d000-de19-11e8-9e9b-868c21c406b8.png)

**Comment by Dune-jr** [comment]
Awesome :+1: 
I think the second one is the best. Discreet yet readable.

**Comment by ChillerDragon** [comment]
@LordSk chat looks good to me. The shadow thing is a real improvement. But the ID part looks totally distracting. I am totally agianst showing ids in chat in general but i think it could still look better even with id. Maybe a different design for the id part. This filled box seems very distracting to me. Maybe try giving the ID just a border.

**Comment by Dune-jr** [comment]
@ChillerDragon I agree, but like Lord said

> this probably shouldn't be enabled by default.

so I think it's fine if the player wants to have something to spot others, other than their names.

**Comment by Fisico** [comment]
maybe make it smaller?

**Comment by LordSk** [comment]
It is small enough believe me, you have to be able to read it. Here is a full screenshot.

![image](https://user-images.githubusercontent.com/294603/47932676-8e7f3580-ded2-11e8-8dd2-d422c4997fba.png)

**Comment by oy** [comment]
Hm, the numbers don't look that catchy anymore, probably because the colour takes the focus.
Maybe the first 2 examples you provided with white background might be better?
How would it look if the indicator would be displayedat the right side of the name?

**Comment by heinrich5991** [comment]
DDNet solves the problem of confusable names by using the Unicode specification for confusables checking. :) I think the problems of people with close names has basically gone away since then.

E.g. capital i and small L compare equal according to that method.

[Unicode Technical Standard #39: Mixed-Script Confusables](https://www.unicode.org/reports/tr39/#Mixed_Script_Confusables)

Another option for Teeworlds would probably to only allow characters from one script for each name (only Cyrillic, or only Latin, or only Chinese letters) — then one would only have to detect single-script confusables.

**Comment by oy** [comment]
@heinrich5991 
That just checks for similar characters but not for similar names right?
