### ISSUE TITLE
Screen size Options

### ISSUE THREAD

**Issue by SHADOWELITE7** [teeworlds/teeworlds#1595]
I used to play teeworlds a lot when I was on an older pc. I got a new one. the game runs well but I can only see this when the game pops up.
![image](https://user-images.githubusercontent.com/33847580/47812515-fc82fb80-dd1e-11e8-9971-1958eb6d546c.png)

**Comment by Dune-jr** [comment]
What is your monitor resolution?

**Comment by Dune-jr** [comment]
@SHADOWELITE7 have you tried deleting settings.cfg in your C:\<user>\AppData\Roaming folder?

**Comment by SHADOWELITE7** [comment]
@Dune-jr my Resolution size is ``1920 x 1080``. I will also try out ``settings.cfg`` to see if that works.

**Comment by SHADOWELITE7** [comment]
I looked for ``settings.cfg`` but I am not sure why its saying its part of the game Project Hedra
![image](https://user-images.githubusercontent.com/33847580/47943706-ba4bec80-decd-11e8-9fa5-2b1239f32a4a.png)

**Comment by Dune-jr** [comment]
That's your editor. Please delete settings.cfg as I suggested @SHADOWELITE7

**Comment by nheir** [comment]
I got a similar issue when using fullscreen and a lower resolution than my screen.
I only have the bottom right corner.
```
gfx_screen_width 640
gfx_screen_height 360
gfx_fullscreen 1
``` 
Right before the game screen, I see a part of my desktop zoom in (top left corner)

**Comment by oy** [comment]
@nheir 
When using 0.7? First post shows 0.6 which doesn't use SDL2.

**Comment by nheir** [comment]
0.7, almost upstream.

Le 3 novembre 2018 10:45:54 GMT+01:00, oy <notifications@github.com> a écrit :
>@nheir 
>When using 0.7? First post shows 0.6 which doesn't use SDL2.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/teeworlds/teeworlds/issues/1595#issuecomment-435574682

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by SHADOWELITE7** [comment]
@Dune-jr it could be that I use the steam version. I can't seem to find that file in the teeworlds folder

**Comment by Dune-jr** [comment]
@SHADOWELITE7 Steam version should not matter.

> I can't seem to find that file in the teeworlds folder

In the `AppData\Roaming\Teeworlds` folder? Hm, I guess that would make sense if you never had a normal Teeworlds quit. Can you at least locate this folder?

A hotfix would be for you to locate (or create) this folder and add a `settings.cfg` file containing:
`gfx_screen_width 1920
gfx_screen_height 1080`

It seems like a bug, given that @nheir has the same issue.

**Comment by SHADOWELITE7** [comment]
ok I will see if this will work

**Comment by SHADOWELITE7** [comment]
I have been very busy over the past months. The current update now works on my resolution size. I think I will close this issue for now.
