### ISSUE TITLE
Improving the controls menus: small proposal

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1597]
After changing a bit of code:

![screenshot_2018-11-01_13-15-09](https://user-images.githubusercontent.com/355114/47851234-4bd93280-ddd8-11e8-95ff-0fa4c8b09c23.png)

Before:
![screenshot_2018-11-01_13-17-33](https://user-images.githubusercontent.com/355114/47851304-86db6600-ddd8-11e8-9731-c6a147691a4f.png)

What do you think? :)

**Comment by Fisico** [comment]
love it... the close button looks a bit strange... not square at all and the X is to big

**Comment by LordSk** [comment]
Everything should be open and not closable. I'd rather scroll a bit than have to switch between each expand thing.

**Comment by Dune-jr** [comment]
> love it... the close button looks a bit strange... not square at all and the X is to big

I didn't change it, I think I took those screenshots on different resolutions. And yeah the X looks awful.

**Comment by Zatline** [comment]
much better yep

**Comment by Dune-jr** [comment]
I would say two-columns + sections + scrollbar would be the best for usability.

**Comment by oy** [comment]
Looks good.
But wouldn't use columns, some translation are really long ;)
