### ISSUE TITLE
Teeworlds Client - Hide Console Window

### ISSUE THREAD

**Issue by Fisico** [teeworlds/teeworlds#1599]
#1583 is not fixed. 

The console is still there.

I built the latest github version with "bam conf=release -f"

**Comment by Dune-jr** [comment]
Argh. God dammit.

https://github.com/teeworlds/teeworlds/blob/8221dac5de6bb2c848bd0f13683eb75cd1807f7e/src/engine/client/client.cpp#L2453-L2455

`if(!UseDefaultConsoleSettings)` and `if(UseDefaultConsoleSettings)` were swapped by mistake. Just need to swap them again.
