### ISSUE TITLE
RFC: Flash window when being highlighted in the chat (Windows)

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1600]
Since the removal of the Windows console triggered some complaints about people wanting to monitor the chat from the desktop, I was thinking we could implement the taskbar icon flashing when some specific events happen, for example being highlighted in the chat.

Unfortunately, this isn't an SDL2 feature, so if done, it would have to be platform dependent code. I don't know if there is an easy way to do that on Linux, too. That kinda sucks.
What do you think?

**Comment by Fisico** [comment]
i dont think it is necessary and when it is not even a SDL feature i don't think its worth the effort.
People who would like to read the chat in the console should start TW over a shortcut with --console.

**Comment by oy** [comment]
Agree with @Fisico that it's not really necessary and you need platform dependent code for all 3 platforms.

**Comment by Dune-jr** [comment]
@Fisico @oy makes sense. It was just a suggestion, it can be closed.

**Comment by fokkonaut** [comment]
ddnet client has that

**Comment by ChillerDragon** [comment]
And it is very annoying if you are trying to be productive on desktop while being afk in teeworlds.
