### ISSUE TITLE
Graying out servers

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1605]
The AEON server in the following picture is grayed out:
![image](https://user-images.githubusercontent.com/355114/47923313-633c1c80-deb9-11e8-9bf6-12b729c57104.png)

I asked some other people why they think that would be, but no one gave the right answer. I thought it could be a bug. Eventually, I looked in the code and found that it is a feature, triggered when all player slots are occupied:

https://github.com/teeworlds/teeworlds/blob/8221dac5de6bb2c848bd0f13683eb75cd1807f7e/src/game/client/components/menus_browser.cpp#L372

My point is that this doesn't feel too intuitive, it feels like I *can't join* the server.
Thoughts?

**Comment by oy** [comment]
Yeah, agree. Should just gray out servers that you can't join.
