### ISSUE TITLE
[macOS] teeworlds uses the bundle identifier 'org.DDNetClient.app'

### ISSUE THREAD

**Issue by core-code** [teeworlds/teeworlds#1608]
your CFBundleIdentifier entry in your Info.plist file is 'org.DDNetClient.app'
this is wrong, as thats the bundleIdentifier of another app (DDNet) and you can't just use theirs. 
as Apple's developer documentation explains, distinct apps need to have distinct bundle identifiers.

**Comment by Dune-jr** [comment]
@core-code I don't know too much about macOS-specific stuff, but given that DDNet is a Teeworlds fork, it's probably the other way around.

**Comment by core-code** [comment]
there is some documentation here: 
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105

hm, if DDNet is a fork, how did they manage to change your bundle identifier to their name?

**Comment by Dune-jr** [comment]
I extracted the 0.6.5 release and indeed it contains that erroneous string.

The trunk code however doesn't: 
https://github.com/teeworlds/teeworlds/blob/0b25463b750f2732f52c574681688decfcc919f4/scripts/make_release.py#L171-L190

So it sounds like a mistake that happened during the packaging. Thanks for the report, @core-code

**Comment by core-code** [comment]
thank you.
if this is fixed in trunk then lets close this.

**Comment by Dune-jr** [comment]
@heinrich5991 Do you know who handled the MacOS 0.6.5 release? It ought to be fixed.

**Comment by heinrich5991** [comment]
I did…

**Comment by Dune-jr** [comment]
Alright, makes sense.

**Comment by core-code** [comment]
the mac binary for 0.7.0 is missing anyway ... ;)
