### ISSUE TITLE
Mouse cursor is offset compared to actual position

### ISSUE THREAD

**Issue by LordSk** [teeworlds/teeworlds#1609]
This comes from the cursor image, illustrated here:

![image](https://user-images.githubusercontent.com/294603/48011995-47d34a80-e121-11e8-87a5-7d960b0dd1fc.png)

Now we could change the code everywhere the cursor is displayed to account for the offset, but an easier solution would be to move/rework the image.

**Comment by Sonix-** [comment]
I believe @Zatline already made/planned one for 0.7

**Comment by Sonix-** [comment]
![inkedcursor_bug_li](https://user-images.githubusercontent.com/2030615/48286141-0adebf00-e465-11e8-8597-0f80b5de5ac7.jpg)
