### ISSUE TITLE
Reports that motd can get stuck in the server list

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1610]
Apparently, if you join a server and leave quickly, the MOTD gets printed in the background of the server list. Can anyone reproduce that, or did anyone experience it?

Edit: I managed to. Somehow the screenshot bugs to this:

![screenshot_2018-11-05_19-20-40](https://user-images.githubusercontent.com/355114/48018237-a48a3180-e130-11e8-8c00-fe9a033151d8.png)

This happens because the MOTD is shown before the loading finishes, so if you abort before, you don't clear up the MOTD.

By the way, testing this bug was pretty hard because rejoining some two times is already enough to warrant a ban on 0.7 servers it seems...

**Comment by fokkonaut** [comment]
i reported it on discord.

**Comment by Dune-jr** [comment]
This is the only place where to report bugs, @fokkonaut. Saying it on a discord will do nothing.
