### ISSUE TITLE
Ingame menus look weird (#1534 split 3/4)

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1611]
>  esc menu looks weird

I agree that the ingame menus look particularly strange/clunky. I personally can't get used to them.
Mouse has to travel a lot from the top to the bottom of the screen, and going back is not very intuitive as some buttons get replaced by the Back button.

Often I will find myself going to the ingame menus to change team, only to realize I'm still in settings menus, and struggling to go back to the ingame menus. I kinda miss having the join team/spectate buttons on the top.

As a personal opinion, I enjoyed being able to use `Esc` to go back in the settings menu, instead of being forced to click the "Back" button on the bottom.

Maybe there could be some discussion around this.

**Comment by LordSk** [comment]
Quick mockup:

![ig_menu_mockup1](https://user-images.githubusercontent.com/294603/48727139-a7594c00-ec31-11e8-8c2b-f509a7db862d.png)

**Comment by Dune-jr** [comment]
Another (simple) approach:

![screenshot_2018-11-20_17-36-36](https://user-images.githubusercontent.com/355114/48788383-029b4500-eceb-11e8-8d4f-f19bdbf07ead.png)

I feel like it is already more intuitive than the current menus with that simple change. Here is also a version without the black background:

![screenshot_2018-11-20_17-30-15](https://user-images.githubusercontent.com/355114/48788371-fadba080-ecea-11e8-9c33-20fa8c19081d.png)

**Comment by Fisico** [comment]
like that idea with the second buttom row.
but maybe remove the gradient from the second button menu.

**Comment by Fisico** [comment]
with.. not to dark

**Comment by Zatline** [comment]
hmm kinda like this as well @Dune-jr but I would actually keep the gradient for consistancy reasons

**Comment by oy** [comment]
@Zatline but there isn't a gradient on the top button line between the buttons (call vote and settings) either.
But some kinda indicator would be nice, so you see to which button on top the sub menu is linked.

**Comment by Zatline** [comment]
@oy yeah true forgot about the removal of Skin and Player options, this looks weird indeed maybe close the gap by moving General to the left? 
other solution would be add back Skin and and Player but highlight them visualy as not interactable something like 25% transparent  font and when mouse hovers over these bottons don't visualy change.

**Comment by Sonix-** [comment]
Make them actually look like tabs? And connect the tabs to the content with a container. It’s just messy that way

**Comment by Dune-jr** [comment]
Not sure if I have the time to make it fancy. If someone wants to do it, sure.

**Comment by oy** [comment]
I can give it a try.

**Comment by oy** [comment]
How about this (blend out the not linked tabs)?
![screenshot_2018-11-22_11-59-31](https://user-images.githubusercontent.com/293850/48898849-288d2a80-ee4e-11e8-9bed-f6aa56805589.png)

**Comment by Dune-jr** [comment]
@oy I would have done this for the Player/Tee tab, because it feels a bit like you can't click on it? Not sure.

**Comment by oy** [comment]
@Dune-jr 
When you hover over the blended out buttons they get totally white and behave like normal ones.

**Comment by Dune-jr** [comment]
@oy I see. How are you going to deal with the Player/Tee tabs? The gradient looks weird right now

> other solution would be add back Skin and Player but highlight them visualy as not interactable something like 25% transparent font and when mouse hovers over these bottons don't visualy change.

**Comment by oy** [comment]
Hm, blending them out like the ones on top doesn't feel consistent - when you can use some and others not.
Maybe use a grey text colour for player/tee as well? So their is a visual difference.

**Comment by oy** [comment]
Anything else?

**Comment by Zatline** [comment]
Looks good to me, not beraking any desing rules either as far as I can tell it's doing it's job 👍 
I think improvments could eventually be made but not sure in what degree and how ..

**Comment by Fisico** [comment]
the gradient from the second button menu bar looks horrible...

**Comment by Dune-jr** [comment]
Hm, I agree it's overdone.

**Comment by oy** [comment]
Could try some less alpha for the disabled buttons.
The gradient walks across the whole line.

**Comment by Fisico** [comment]
the gradient does not make any sense... the top line ok.. there it fades in from the top of the screen. 
just remove the gradient and make it solid.

**Comment by Dune-jr** [comment]
We still have to think about where to put this Reset button if we make the "Game" buttons permanent.

**Comment by 1stDecadeTW** [comment]
Second choice looks really nice.
