### ISSUE TITLE
Chat and HUD aren't displayed when menus are opened (#1534 split 2/4)

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1613]

**Comment by oy** [comment]
I think that was done on purpose. Do they need to be displayed?

**Comment by Dune-jr** [comment]
Good question, I don't know. What do others think?

**Comment by Zatline** [comment]
it's intentional like Oy suspects. HUD elemetns are naturaly hidden in quite every polished game out there to well avoid a mess of intersecting layers but also to put focus purly on the menus that just opened.
There is nothing wrong here, in fact quite the opposite.

**Comment by fokkonaut** [comment]
open again! its useful, sometimes youre in the menu for changing settings and someone writes you a msg you cant read it anymore

**Comment by oy** [comment]
Use the console to read it. Chat would be barely readable when the menus are displayed.
