### ISSUE TITLE
In ingame menus, sometimes, all buttons are highlighted as if they were all hovered (#1534 split 4/4)

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1614]
I've experienced this bug a lot but was not able to reproduce it recently, might have been fixed?

**Comment by Zatline** [comment]
Hovering over whatever button once is trigering it, disconnect then reconnect,
all not hoverd buttons remain normal those that got hoverd are now bugged until game restart.

<a href="http://www.youtube.com/watch?feature=player_embedded&v=xv4hGb1MdmY
" target="_blank"><img src="http://img.youtube.com/vi/xv4hGb1MdmY/0.jpg" 
alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

**Comment by fokkonaut** [comment]
happens for me when alt+tabbing around
