### ISSUE TITLE
SMART CAMERA: introduce a "smart camera" option to the game.

### ISSUE THREAD

**Issue by 1stDecadeTW** [teeworlds/teeworlds#1615]
I think that dynamic camera is not as "dynamic" as its name suggest.

Why don't you implement a camera that zooms out a bit when the tee gets higher in the sky or go faster?

Here is an example of how it should work in game:
https://youtu.be/PH6PvdtyVdk?t=36

This is how it will work using the hook or interacting with movable objects:
https://youtu.be/oKCsmWN9nwk?t=8

And this is a camera logic review: https://youtu.be/TCIMPYM0AQg

**Comment by Zatline** [comment]
This guy's game looks very familiar to teeworlds, race in particular lol but these physics are glorious.

**Comment by 1stDecadeTW** [comment]
Hey guys, this feature has been add to another client! 

AllTheHaxx (ATH) teeworlds client has introduced this useful and awesome feature ingame, you can test it by downloading the client, turning on the smart zoom in configs and give it a try on a race map :d (it needs to be smoother, just as the example videos).

![screenshot_1](https://user-images.githubusercontent.com/44511917/48298265-3fac3f80-e480-11e8-8a60-6da17a4b6227.png)

**Comment by Dune-jr** [comment]
@1stDecadeTW I'm still confusing what this is supposed to be like. Could you link to a capture/video of this camera?

**Comment by oy** [comment]
It should zoom out a bit when you get faster(pretty fast)?

**Comment by Sonix-** [comment]
All the examples shown are featured in a race gametype, why would we need it in deatmatch games (f.e)?

**Comment by oy** [comment]
Don't you get pretty fast in ctf as well?

**Comment by Dune-jr** [comment]
> It should zoom out a bit when you get faster(pretty fast)?

> Don't you get pretty fast in ctf as well?

Yeah, agree. Having a camera that zooms out when going very fast in ctf doesn't sound bad to me.

**Comment by oy** [comment]
We talked about that feature and decided not to add it.
