### ISSUE TITLE
script tw_api.py is not working with 0.7.0

### ISSUE THREAD

**Issue by titilambert** [teeworlds/teeworlds#1617]
Hello,

I'm trying to run the  tw_api.py to my own server.
The variable `PACKET_GETINFO3 = "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xffgie3" + "\x00"` seems not working anymore with the version 0.7.0 (And it's still working with 0.6.5)
Does this package changed ?

Thanks for your answer !

**Comment by oy** [comment]
Yeah, doesn't work anymore. The script has do be updated like the other ones in the script folder ;)

**Comment by titilambert** [comment]
@oy Thanks for your answer. I'm wondering what is the right packet content to send to the server 0.7.x to get the same data as we got with `PACKET_GETINFO3` and server version 0.6.5 ?

**Comment by oy** [comment]
It's not that simple anymore. You first have to acquire the actual token from the server and then you are able to retrieve the server info.

**Comment by titilambert** [comment]
@oy oh !! oki, do you have an example ? I could try to translate it in python

**Comment by oy** [comment]
https://github.com/teeworlds/teeworlds/blob/master/src/engine/shared/network_token.cpp#L251 this grabs the token from the server

https://github.com/teeworlds/teeworlds/blob/master/src/engine/shared/network_client.cpp#L100 this where the client gets the token

https://github.com/teeworlds/teeworlds/blob/master/src/engine/client/serverbrowser.cpp#L483 that's how the client asks for the server info

**Comment by titilambert** [comment]
@oy Thanks !

**Comment by titilambert** [comment]
@nheir @oy Thanks for this commit/update !
