### ISSUE TITLE
Add faster background map animation

### ISSUE THREAD

**Issue by Fisico** [teeworlds/teeworlds#1618]
The faster map animation from Sushi's PR(#1171) looks and feels so much better than the current very slow animation.

https://streamable.com/mciai

**Comment by Fisico** [comment]
fixed typos

**Comment by Dune-jr** [comment]
If I may add, I find the "heavens" background quite nice too, even though it's simple:

![image](https://user-images.githubusercontent.com/355114/48227794-9ee85200-e3a3-11e8-89b6-6c9d84e3ec94.png)

**Comment by Zatline** [comment]
@Dune-jr clouds need to be animated if not already and there should be more passing over the screen

**Comment by oy** [comment]
@Sonix- 
Could be pimped up a bit - more clouds, sun?, butterflies? :)
And/Or include the old 0.2 background :)
![menu_background](https://user-images.githubusercontent.com/293850/48282017-cb11da80-e458-11e8-96d2-f31a19ddf5f5.png)

**Comment by Fisico** [comment]
@oy 
the speed is good now.. but something still feels wrong... Is another typ of movement possible? maybe try a exponential speed movment?

**Comment by Dune-jr** [comment]
Personal opinion: I think it's too fast and sudden, now.

**Comment by Fisico** [comment]
i can't help, for me sushi's version is simply good :)

**Comment by oy** [comment]
Could try to slow the movement a bit down before reaching the destination.

**Comment by Dune-jr** [comment]
Thanks, didn't know @Sonix-

@oy sounds good, gotta try!
