### ISSUE TITLE
Ninja progress bar

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1622]
Update the ninja progress bar to use the new game.png.

**Comment by Dune-jr** [comment]
According to @Zatline in #1620, the ninja progress bar is supposed to look like:
![image](https://user-images.githubusercontent.com/355114/48282124-0dd3b280-e459-11e8-9170-fe0f77bd0b57.png)

**Comment by oy** [comment]
That's how it looks currently
![screenshot_2018-11-09_20-10-14](https://user-images.githubusercontent.com/293850/48283036-9b180680-e45b-11e8-9baa-de88ad972990.png)

**Comment by Zatline** [comment]
do we need the gradient? didn't know if I should include it thought it would make things more complicated to code I mean it should look good even without gradient, otherwise I'd add a gradient graphic to game.png if whoever codes this is up to the challange.

**Comment by Dune-jr** [comment]
Don't worry, @LordSk is on it

**Comment by Zatline** [comment]
@Dune-jr gradient by pure code then? sounds good :)
