### ISSUE TITLE
Pickup option for Team LMS

### ISSUE THREAD

**Issue by Fisico** [teeworlds/teeworlds#1623]
Team LMS/Survival plays out a bit boring cause there is no way to regenerate or pickup more Ammo.

My Idea for a mod with pickups:
player should start with 10 Hearts, 0 Armour, 10 Pistol shots and Hammer

Place some Weapons and Hearts/Armour on the Maps(Symetrical on Sur1) so the rounds are a bit longer and the Players are able to regenerate. So there is way more tension.
 
Kind of a round based TDM

**Comment by oy** [comment]
There's already a topic to improve the survival gametypes #1069 . I think this discussion should be continued there ;)
