### ISSUE TITLE
Health and armor looks a bit darker and its difficult to see it ingame.

### ISSUE THREAD

**Issue by 1stDecadeTW** [teeworlds/teeworlds#1625]
Current health and armor in game.png looks too darker and its difficult a bit to see it in game, maybe use a lighter and teeish game.png instead?

![deepinscrot-2536](https://user-images.githubusercontent.com/44511917/48289262-70668780-e434-11e8-9dca-290d6802272b.png)
![game](https://user-images.githubusercontent.com/44511917/48289263-70ff1e00-e434-11e8-81ab-34b1cbab3e72.png)

**Comment by 1stDecadeTW** [comment]
@Zatline could you please share me your "SVG" of game.png, I'd like to experiment with those shapes and colors D:

**Comment by Fisico** [comment]
it seems the hearts and armour get skaled down... i think they are a bit to small. Color is very good i think

**Comment by Fisico** [comment]
i think the issue should be closed.
For me I don't see a reason why the colors should be changed and the scaling issues are already fixed.

**Comment by oy** [comment]
Looks fine to me.
