### ISSUE TITLE
Votes are glitched, sometimes underestimate the count of eligible voters

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1627]
This server had 3 people: 
![screenshot_2018-11-09_20-19-41](https://user-images.githubusercontent.com/355114/48292008-e7257400-e478-11e8-9e7b-e1fab7ece95c.png)

I was able to make a vote fail by f4-ing, even though they wanted to send me to spectators.
There were no spectators. I am not sure what caused this, but all votes estimated the max count of votes to 2.

**Comment by oy** [comment]
Maybe the other 2 had the same IP, then they only count as 1 individual vote.

**Comment by Dune-jr** [comment]
@oy Aaah, didn't think of that. That's most likely.
