### ISSUE TITLE
Ease up toggling audio on and off

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1630]
Right now, if `cl_snd_enable` is not set to 1 at startup, sounds are not initialized and thus cannot be turned off:

https://github.com/teeworlds/teeworlds/blob/693c409b963227b3783fc285c745f9d52bd78e97/src/engine/client/sound.cpp#L209-L210

 This is quite inconvenient if you're someone like me who finds yourself regularly turning it on and off. Is there a good reason for not initializing audio?

I'm also thinking we could have some sort of UI notification when the sound is being turned on & off, e.g. a small 🔊 / 🔇 somewhere. Toggling audio could then become a command of its own, bound by default. What do you think?

**Comment by oy** [comment]
If you keep the sound disabled the client doesn't need to load all the ressources.

**Comment by Dune-jr** [comment]
Are those resources that heavy, though? It seems to me like the ability to turn on the sound if it was left turned off is a bigger deal than optimizing the loading phase.

**Comment by oy** [comment]
It's not just the better loading phase. It doesn't need the audio part of sdl and the program needs less ressources in general.
Should still be possible to turn that off. I had it always turned off.

**Comment by heinrich5991** [comment]
Yeah, maybe one could make a separate switch "turn audio off"/"don't initialize audio systems".

**Comment by Dune-jr** [comment]
🔊 / 🔇 is not part of DejaVuSans so we'll need some icons there

**Comment by Dune-jr** [comment]
Thanks to @Zatline for providing icons.

I'm thinking about creating a new components file, as I don't see where such notifications would belong in the current components list. HUD is not displayed when in menus.

**Comment by oy** [comment]
Where/how do you want to display the icon?

**Comment by Dune-jr** [comment]
I don't know, on the left or right side?

**Comment by oy** [comment]
Ingame too? just for a few seconds after activating/deactivating it? Same when you're not ingame?

**Comment by Dune-jr** [comment]
> Ingame too? just for a few seconds after activating/deactivating it? Same when you're not ingame?
> Should probably have the same place then.

Yes to all

**Comment by Dune-jr** [comment]
So we create a new file for that, @oy?

**Comment by Dune-jr** [comment]
So it seems like we're going to need a notification component, working similarly to debughud.

Here are Zatline's icons:
![image](https://user-images.githubusercontent.com/355114/50736334-af0e8900-11bc-11e9-9590-9c9bef7d390e.png)
