### ISSUE TITLE
Option to switch Warm Up and Game start cool down off/on

### ISSUE THREAD

**Issue by themisak** [teeworlds/teeworlds#1635]
I think we should get the option to switch off this warumup at the start. Some sort of a server command. Sometimes it can be anoying when your playing and moving on a map and then someone joins and everything restarts. 

Also the 3 seconds countdown after a game has finished feels partly unsmooth and there should be an option to disable this cooldown and warumup.

Please bring a server command so people can decide.

What do you think? Thanks Guys !

**Comment by oy** [comment]
Set sv_warmup to -1.

**Comment by themisak** [comment]
But there its still 3 seconds warmup after a game has finished, like if the scorelimit is set to 10 in dm and someone has 10 score the game is finished and then the new game still starts with 3 seconds warumup even tough I have now set sv_warmup to -1. 

Also when I type in f2 restart ist doesent restart instandly. It takes also 3 seconds. I have no chance to get the game to restart instandly I always have to w8 the 3 seconds. 

But if I want to w8 3 seconds then I could also just type restart 3 wich would be the same there.

**Comment by Sonix-** [comment]
This is probably due to the "ready" not even working but included? Game shouldn't start until everyone is ready right?

**Comment by themisak** [comment]
So it will get fixed ?

**Comment by themisak** [comment]
Hey today I tested the the sv_warumup -1 command with Dune and somehow my servers always have warmup time no matter what I do. I used the latest Master from Github. Something seems bugged please have a look at it Guys!

Many Thanks!

**Comment by oy** [comment]
That's the current behaviour - no bug. Nothing changed yet in that regard.

**Comment by Dune-jr** [comment]
So there is no way to disable the 3 seconds warmup, @oy ?

**Comment by oy** [comment]
@Dune-jr no there's no option to turn it off.

**Comment by themisak** [comment]
Could you Guys make it possible to disable this 3 seconds timer? Would be Great cause it can get very anoying.

**Comment by Sonix-** [comment]
Yeah that's what i've reported on discord a week ago or so.
