### ISSUE TITLE
Gametype icons

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1637]
How should the gametype icons that will be displayed in the server info tab look like?

**Comment by oy** [comment]
LMS - a tee standing on a field of corpses
SUR - 2 tees (team color?) standing on a field of corpses

**Comment by Sonix-** [comment]
There should be icons only for vanilla gametypes

**Comment by Sonix-** [comment]
A quick sketch regarding CTF and Survival icons:
![gametype_icons_test2](https://user-images.githubusercontent.com/2030615/48304953-0bd62600-e523-11e8-84cb-0efa200ced2f.png)

**Comment by Zatline** [comment]
@Oy for dm and tdm those are placeholders! 
I'm going to make a skull with two crossing bones I think, need a little break now ^^

![rect7787](https://user-images.githubusercontent.com/344608/48307914-8325ad00-e557-11e8-9236-e74f06457c6c.png)

**Comment by oy** [comment]
Yeah @Sonix- is right there should just be icons for official gametypes.

**Comment by Zatline** [comment]
I would suggest to have a directory where every icon is saved in name of the type it represents so if there is a non-official mod and the mod is called let's say CQ, saving a 64x64 sized image with name CQ.png in that directory would enable that image to all server that run this mod. There should at least be an ability to extend beyond official gametypes imo, I personally would want that.
If there is no image of the modifications name in the gametype directory then the wrench image is used, Teeworlds by default will only come with the images of the standard mods.

**Comment by Zatline** [comment]
@oy dm, tdm, lms, tlms, ctf
![gametypes](https://user-images.githubusercontent.com/344608/48315015-59a96780-e5d1-11e8-9ee9-845897d3574d.png)

**Comment by oy** [comment]
@Zatline 
the dm/tdm icons look like survival ones, cause we have the dead tee there in the scoreboard

**Comment by oy** [comment]
Maybe like 2 tee's with weapons getting ready to fight another for dm (team colours in tdm)?
f.e.
![untitled](https://user-images.githubusercontent.com/293850/48436623-6cfa3580-e77f-11e8-9ef7-54c313625a6f.png)

**Comment by Zatline** [comment]
I'm worried that things get too detailed, icons should be minimalistic and 1:1 aspect ratio.

**Comment by Landil** [comment]
Keep in mind: form follows function!

The icon should scream out for what it stands for. Meaning, if we deal with "capture the FLAG" there is supposed to be a tee which "captures a flag". etc. 

My experience shows that superior results will be achieved if people work together. Thus I suggest to use Sonix's icons as a start and Zatline might update them, add some different and then it's again Sonix turn and so on. Use as much standard and known graphics as possible. Then after some drawing rounds we will have cool icons to choose the best from.

**Comment by Zatline** [comment]
I partly agree icons should indeed be representetiv of the gametype yes but I don't think the example ctf as you said would necessarily need to show a tee capturing that flag it makes sense tho and I do see the point there but it adds bias when having color involved since you only can rly make it one way or another either show red tee capturing blue flag or blue tee capturing red flag in my opinion the icon should neither be bias to a side nor misrepresenting the mode which is why I just chose a red and a blue flag in those colored examples above as that made the most sense and it looks quite clean.

Having said that, having no color involved would be a different story at least to me for ctf you could easely show a tee with a flag sure no color no bias no problem. That however on the flipside would add difficulty getting those other gametype nailed colorless.

**Comment by Sonix-** [comment]
If its a blue team coloured tee anyone can relate it to team gametype... its either teamcoloured or default. Its hard to misunderstand

**Comment by Dune-jr** [comment]
I think @1stDecadeTW's suggestion for CTF (crossed flags) was simple and nice.
A tee capturing a flag sounds pretty nice too but it could be a bit hard to execute, like @Zatline said.

**Comment by Zatline** [comment]
Tried crossing the flags, had to scale the flags down so I can rotate them to fit the 1:1 aspect ratio that means same amount of detail is now in a smaller frame of pixel not so idealistic for icons. Forground flag is also kinda blocking out the backround flag as I really can only cross at the pole and even then they kinda overlap. @1stDecadeTW's suggestion of crossing flags is a neat idea I like that too but his flags have a long pole, ideal for crossing. Whereas tw flags have qeuite a short pole.
![8fc8612aac6cc80bec3e6651c0da1b1f](https://user-images.githubusercontent.com/344608/48536832-06286980-e8b0-11e8-9ee4-07333df7ca66.png)

> If its a blue team coloured tee anyone can relate it to team gametype... its either teamcoloured or default. Its hard to misunderstand

but why a blue tee and not a red tee? u either show both teams or non everything inbetween is bias ^^

**Comment by Zatline** [comment]
@Oy colored as non colored
![gametypes](https://user-images.githubusercontent.com/344608/48537601-56a0c680-e8b2-11e8-8b1b-68b410210608.png)

**Comment by Dune-jr** [comment]
About the flags, if crossing them makes them too pixelated, you may want to overlap them?

I don't think it's too bad if one shows more than the other, no need for perfect symmetry imo.

**Comment by oy** [comment]
@Zatline not sure about the deathmatch icons. Doesn't scream deathmatch as @Landil would say :)
Maybe show a weapon (instead)?

**Comment by Dune-jr** [comment]
:+1: some games have crossed swords for that. Maybe cross two weapons, e.g. a shotgun and a grenade?

**Comment by Fisico** [comment]
Survival and ctf are good now.. DM looks kind of strage with the feet position... tdm looks very strange with the half colored tee. I like the idea from @Dune-jr

**Comment by Zatline** [comment]
@oy we could do both perhaps, having only weapons is kinda difficult to realize a team version
![gametypes](https://user-images.githubusercontent.com/344608/48656277-262c6a00-ea23-11e8-9e09-70306d9deb32.png)

**Comment by Dune-jr** [comment]
So, we tried to do the crossing weapons thing yesterday with @LordSk and @Zatline, but it seems like it is hard to add a team indicator for TDM when done so.

My suggestion for that would be to represent two tees facing each other for TDM (with weapons or not), and one tee or a bunch for DM. Even without colors, it should be easily distinguishable.

**Comment by Zatline** [comment]
I actually rly like the tdm one with that mixed pattern don't get what's so weird looking it's an icon after all and has the same style as the teamed skull what makes everything fit quite nicely

**Comment by oy** [comment]
https://static.thenounproject.com/png/14261-200.png
That's a good example for a team icon - maybe adapt that for tdm.

**Comment by Zatline** [comment]
@Oy I already tried that and that ended up not so good I completly scraped it. 
![ab89c29b1217a61a898e08b74b20eda7](https://user-images.githubusercontent.com/344608/48674389-da291480-eb4b-11e8-8193-5f19d1092abb.png)

It just doesn't fill the entiere 1:1 aspect and the face cutoff when fit to 1:1 aspect, left and right, on the tees is so segnificant it just doesn't look good so I tried it diagonaly as that would give me more room to play with and it ended up like this
![aeff4a53a9274ba3779be95bd852d841](https://user-images.githubusercontent.com/344608/48674208-dbf1d880-eb49-11e8-8dda-a32582786a3c.png)
had this one posted on Discord for quick feedback some people complained that tees were of different size and that I should perhaps add a weaopon as you also suggested. A weaopn however adds quite some additional detail to the mix so I had to sacrefice tees for the sake of keeping it simplistic.
what I ended up with was the latest one, which I personally most like.
![f0db081b7d6f5f857d60213d6fa5cbee](https://user-images.githubusercontent.com/344608/48674435-94208080-eb4c-11e8-8e96-32b378e66bfc.png)

**Comment by oy** [comment]
@Zatline you could move up the 2 tees in the background
https://pngtree.com/free-icon/team_836416

**Comment by 1stDecadeTW** [comment]
self-descriptive CTF, DM and TDM icons:

![ctf dm tdm](https://user-images.githubusercontent.com/44511917/48678381-22463800-eb48-11e8-9bd7-cea30c363dd4.png)

**Comment by Dune-jr** [comment]
The execution could be polished to look more teeish, but I like the pattern/idea :)

**Comment by Zatline** [comment]
skull was LMS and TLMS I tought?

**Comment by Dune-jr** [comment]
@Zatline yeah, it should probably be tees instead

**Comment by 1stDecadeTW** [comment]
DM and TDM are more associated with skulls, and last man standing with "alive" tees.

**Comment by Zatline** [comment]
1st, Icons should not vary a lot when made for the same overall gametype so dm showing one skull and tdm showing multiple skulls is an inconsistancy imo and detail got added bringing me to 2nd, 
Icons should be as minimalistic as possible, kiss principle, one skull alone already works 
3rd, We already had this dicussion the skull was already been proposed as icon representing death match.

**Comment by Dune-jr** [comment]
> DM and TDM are more associated with skulls, and last man standing with "alive" tees.
> 
> Edit: I need to think how LMS and TLMS gametype icons could look.

The deadtee image is *very* remindful of survival if you have played any - it is the only gamemode where it appears. See what @oy said:

> the dm/tdm icons look like survival ones, cause we have the dead tee there in the scoreboard

**Comment by 1stDecadeTW** [comment]
> > DM and TDM are more associated with skulls, and last man standing with "alive" tees.
> > Edit: I need to think how LMS and TLMS gametype icons could look.
> 
> The deadtee image is _very_ remindful of survival if you have played any - it is the only gamemode where it appears. See what @oy said:
> 
> > the dm/tdm icons look like survival ones, cause we have the dead tee there in the scoreboard

The only solution I can figure out is to propose the LMS and TLMS icons, skull fits better in DM, even though they are used in lms scoreboard... Look other games with DM gametype icons, they are similar with skulls, and LMS icons include the at least three characters with the winning one on top of the others

**Comment by oy** [comment]
@1stDecadeTW the skulls look good but like said probably sth for the survival gametypes.

**Comment by Dune-jr** [comment]
Just change the skulls to some tees and the sketch is good imo :)

**Comment by Dune-jr** [comment]
I believe the DM icon was supposed to be an alone tee, to show that you're on by your own. I think @Oy only meant the three-tees pattern for TDM :)

I personally like it (sorry!), I only find it odd that colors are alternated in all of your TDM icons (e.g. red head/blue foot, then red foot/blue head).

**Comment by Zatline** [comment]
Icons should be easy recognizable to the gametype just by their pure shape so when ever there is a single tee with a hammer u know it's deathmatch! team deathmatch is just a sub version of deathmatch and that's exactly what the mixed colored tee represents, a sub version of it's other self. 
The mixed way that the single tee was colorized is on purpose it represents the chaotic structure of tdm that there is no structure, that teams don't have a base nor a section of the map where they specifically spawn in and own, but rather move everywhere mixed all around the map all randomly.

**Comment by oy** [comment]
@Zatline looks good. 👍 
About the icons:
Some diversity besides colours looks better for me. These 2 gametypes are pretty different - in dm you play on your own and in tdm you play as a team. And it's more intuitive if the icon shows that.
And teams in tdm have their own spawn areas within the map, like ctf.

**Comment by 1stDecadeTW** [comment]
What do you think about that gametype icons mockup? I've made those icons for DM, TDM, LMS and TLMS

![imagen1](https://user-images.githubusercontent.com/44511917/48869386-9ed45300-eda2-11e8-953a-fec94e89cca8.png)
![imagen2](https://user-images.githubusercontent.com/44511917/48869387-9ed45300-eda2-11e8-909c-ef6147ec4f47.png)
![imagen3](https://user-images.githubusercontent.com/44511917/48869388-9ed45300-eda2-11e8-8baa-c98b74549a4d.png)

**Comment by Dune-jr** [comment]
> What do you think about these gametype icons mockup? I've made these icons for DM, TDM, LMS and TLMS

We don't need any more icons for DM/LMS/LTS/CTF.  I believe @Zatline's execution is pretty good already:
 
![image](https://user-images.githubusercontent.com/355114/48892716-f922f180-ee3e-11e8-9bff-1c8862eeac83.png)

Now, for TDM, I really think this is the idea that should be achieved:

![image](https://user-images.githubusercontent.com/355114/48892639-d264bb00-ee3e-11e8-99c2-efada7721f4f.png) ![image](https://user-images.githubusercontent.com/355114/48892608-bd882780-ee3e-11e8-9c0a-143336924b67.png)

- Tees look angry
- They are ordered in two teams, left and right
- No strange mixture of color. left = red, right = blue

The only problem is that icons must be square (and small), which seems to make it much harder. imo the best fix is @oy's suggestion:

> @Zatline you could move up the 2 tees in the background
> https://pngtree.com/free-icon/team_836416

**Comment by oy** [comment]
Yeah move the ones outside up and closer to each other should do it. The ones with feet look better for my taste.

**Comment by Zatline** [comment]
@oy I like feets too
![gametypes](https://user-images.githubusercontent.com/344608/48910424-394e9800-ee70-11e8-873f-26b7bd81b42b.png)

**Comment by oy** [comment]
That looks great 👍

**Comment by 1stDecadeTW** [comment]
@oy @Zatline @Dune-jr 
![gametype icons version 3 0](https://user-images.githubusercontent.com/44511917/48962122-5d2dde80-ef41-11e8-8eb8-462612bbe3bc.png)

**Comment by Landil** [comment]
![delme](https://user-images.githubusercontent.com/333183/49071611-a7a7a780-f22e-11e8-9f1d-ba4ef5bc6966.png)

So here are my two pennies. Everything is a quick sketch. The original file is a mess. Some has to remake it 😞 
- dm inspired by old splash tee 
- stick to the original body feet ratio
- tdm and survival different approach
- stick to the original flags 
- added race flag which is inspired by the original one
- settings icon slightly adjusted

TODO:
- maybe one should adjust the flag colors to the desaturated tee colors
-  dm tee has to be flatted (2D)

**Comment by Dune-jr** [comment]
@Landil we have already merged in @Zatline's work in #1726 :/
Of course we can still apply fixes.

The team colors in those icons are much less saturated than ingame too, now.

**Comment by Landil** [comment]
> 
> 
> @Landil we have already merged in @Zatline's work in #1726 :/
> Of course we can still apply fixes.
> 
> The team colors in those icons are much less saturated than ingame too, 

These are my suggestions... if they might help to improve the result I'm fine, if not I'm fine, too. If it's too late. Well, then it's too late. 🙈

**Comment by oy** [comment]
Really like the team approach @Landil.
That gun for dm might be too detailed for an icon.

**Comment by Landil** [comment]
> 
> 
> Really like the team approach @Landil.
> That gun for dm might be too detailed for an icon.

Then I would use the cammo skin instead (for dm and maybe tdm).

**Comment by oy** [comment]
@Landil yeah that might look better 👍

**Comment by oy** [comment]
Not sure if mods should use the mod gametype icons or stick to the old unpure icon. there's no other indicator anymore - the column is gone.

**Comment by Zatline** [comment]
>/!\ 

always tought that icon was related to server being of different version / incompatible or some sort ..
didn't know it was actually indicating mods ughh that's awkward
