### ISSUE TITLE
Friends tab

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1638]
What's the friends tab to look like?
Ideas:
- display name + clan?
- display map + gametype the friend is on?
- display "playing" when playing, "watching" when a spectator?
- display a friend multiple times? when it fits the friend and the clan criterium? (like it's now in the friend browser) or just display it once?

**Comment by Zatline** [comment]
- yes kinda, does it fit in the sidebar?
- but only when fullscreen, no idea how that would fit in the sidebar.
- interesting not sure would be a nice addition perhaps
- [old concept](https://gyazo.com/54549be40d70fdbcfc7f4e80bc153e4b) has it two times but not ideal I guess .. 
could make it one, if clan is is added show him there, if not then he's listed regulary.

not sure if this works already couldn't ever test but when u "follow" a clan have the clan tag added as friend, you should be able to see and join all individual members that are online from the clan even when they are not added as friend. :)

**Comment by 1stDecadeTW** [comment]
![screenshot_1](https://user-images.githubusercontent.com/44511917/48309147-5c587e00-e539-11e8-9d0a-11d9f8344a2d.jpg)
![screenshot_2](https://user-images.githubusercontent.com/44511917/48309148-5cf11480-e539-11e8-9d04-07a95e1b76db.jpg)

**Comment by oy** [comment]
> btw. not sure if this works already couldn't ever test but when u "follow" a clan have the clan tag added as friend, you should be able to see and join all individual members that are online from the clan even when they are not added as friend. :)

Yeah, that's how it works in the friend browser.
