### ISSUE TITLE
Make it so that spectators don't rejoin server as players after map change

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1639]
When server the server rotates the map (or a vote is called to change), spectators, especially those that are afk, should not rejoin as players (but instead, stay spectators).

I guess the best way to go with that would be client-side.

**Comment by themisak** [comment]
There is a server command for that

**Comment by Dune-jr** [comment]
@themisak The server command makes all the players that join default to spec, if I'm not mistaken.
What I propose is that clients that auto-reconnect after a map change go to spectators by themselves.

It might be a tad bit cleaner with a protocol change though, to enter directly as a spectator.
