### ISSUE TITLE
Flag still lags behind carrier

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1640]
It seems that on the trunk version, the flag still lags behind the tee. Wasn't this supposed to be fixed? :/

**Comment by Fisico** [comment]
it indeed was fixed... in the newest builds the bug is back as it seems.

**Comment by oy** [comment]
@Dune-jr 
Are you sure you were on a server with the actual trunk version?

**Comment by Dune-jr** [comment]
@oy yes, this happened on two servers with trunk version, one of which @LordSk compiled
