### ISSUE TITLE
Ending a round by ninja-killing a hooked tee sends the hook at (0,0) coordinates

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1642]
This odd combination of three things:

- player 2 hooks player 1
- player 2 kills player 1 with ninja
- round ends at the death of player 1 (deathmatch, survival...)

triggers a bug that sends the hook target coordinates at the top left corner of the screen.

(ninja weapon might not be necessary.)

**Comment by Stitch626** [comment]
This already exists in 0.6, but its no big deal there.

**Comment by fokkonaut** [comment]
just set hookpos to playerpos in gamecore

**Comment by TsFreddie** [comment]
is this fixed?
![image](https://user-images.githubusercontent.com/3797859/97773398-5d51a280-1b8a-11eb-9fd9-6490dc652aad.png)

**Comment by oy** [comment]
Seems to be fixed.
