### ISSUE TITLE
Ingame console doesn't block inputs in menu

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#1660]
When pressing the uparrow in ingame console to get the last command it has effect on the menu settings. The console should block this input for the menu.

![menu](https://user-images.githubusercontent.com/20344300/48319456-7fa12d00-e60e-11e8-875a-e3f6d77d97ca.gif)

**Comment by Dune-jr** [comment]
That is strange. The console returns true, and should capture the arrow keys:
https://github.com/teeworlds/teeworlds/blob/e2c6ce81eb9e084ceced500363790d3f079271fb/src/game/client/components/console.cpp#L556-L569

And the stack input is correctly ordered:
https://github.com/teeworlds/teeworlds/blob/e2c6ce81eb9e084ceced500363790d3f079271fb/src/game/client/gameclient.cpp#L216-L219

I'm not sure why this happens.
