### ISSUE TITLE
Emotes no longer trigger eye emotions

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1663]
It used to be that the Shift emotes would trigger happy eyes and what not. This behavior is no more, I guess that it is a bug.

**Comment by Dune-jr** [comment]
Oh, it was a mod thing? Sorry then, I remembered wrong.
But yeah, I guess it would be a nice little easy feature to add.

**Comment by oy** [comment]
The eyes are a gameplay feature. Dunno if a problem might arise from that. @Sonix- what do you think?

**Comment by ChillerDragon** [comment]
Some people play without sounds and then the eyes are nice indictator for specific events. Or even with sounds it is hard to tell who made the kill if it was not your own tee.

The eye on emotes is nice for mods like ddrace but not good for pvp based gametypes especially vanilla based ones.

**Comment by Dune-jr** [comment]
Probably not a good idea to add this in Teeworlds then. Server mods can still tweak this as they like, I guess.

**Comment by 1stDecadeTW** [comment]
> Probably not a good idea to add this in Teeworlds then. Server mods can still tweak this as they like, I guess.

Make it a server side setting, so you can turn it on/off in server.cfg

**Comment by oy** [comment]
Closing this.
