### ISSUE TITLE
Add menu_heaven maps (split from #1618)

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1668]
![image](https://user-images.githubusercontent.com/355114/48227794-9ee85200-e3a3-11e8-89b6-6c9d84e3ec94.png)

If I may add, I find the "heavens" background quite nice too, even though it's simple:

_Originally posted by @Dune-jr in https://github.com/teeworlds/teeworlds/issues/1618#issuecomment-437158266_

----

Yeah looks good. Maybe we should split that to a different topic? To use that map separately or different time? Do a night one?

_Originally posted by @oy in https://github.com/teeworlds/teeworlds/issues/1618#issuecomment-437450329_

----

Dunno, looks cheap to me :/

_Originally posted by @Sonix- in https://github.com/teeworlds/teeworlds/issues/1618#issuecomment-437452139_

---

clouds need to be animated if not already and there should be more passing over the screen

_Originally posted by @Zatline in https://github.com/teeworlds/teeworlds/issues/1618#issuecomment-437457261_

---

Could be pimped up a bit - more clouds, sun?, butterflies? :)
And/Or include the old 0.2 background :)
![menu_background](https://user-images.githubusercontent.com/293850/48282017-cb11da80-e458-11e8-96d2-f31a19ddf5f5.png)

_Originally posted by @oy in https://github.com/teeworlds/teeworlds/issues/1618#issuecomment-437458409_

**Comment by Dune-jr** [comment]
I believe @Sonix- is already working on day&night maps (but couldn't assign him).

**Comment by oy** [comment]
@Dune-jr should be possible now

**Comment by Dune-jr** [comment]
The background maps don't achieve unanimity because they are somewhat disruptive and mask UI details:

> menu map thing is a cool option sure but more distructiv to the user experience than perhaps intended, the day jungle map is very bright and gets anoying after some time while the night jungle map is calm but leads to UI details getting lost in the dark.

I can feel some of that too. I think that those heaven maps should be simpler, and less disruptive, as an alternative (since we can switch between the two themes).

This way, people who dislike very dynamic/disruptive/rich backgrounds can find contentment without disabling everything altogether. That's my view of it :)
