### ISSUE TITLE
Update server difficulty icons to make standard and competitive more distinguishable

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1669]
This is an issue we have talked about with @Zatline.
Maybe there could be a small, subtle change to the difficulty.png to make the difference more noticeable:
![image](https://user-images.githubusercontent.com/355114/48449324-55807400-e7a2-11e8-900e-083bb3f22724.png)

Casual looks different enough already. :)

**Comment by android272** [comment]
I think that the eyes in both of these look different enough.

**Comment by oy** [comment]
The difference to casual is bigger - but dunno if this could be done for the other 2 as well.

**Comment by Dune-jr** [comment]
> I think that the eyes in both of these look different enough.

The image is zoomed a bit. On a big list in a widescreen, I find it quite difficult.

**Comment by oy** [comment]
It's because of the wrong dimension. It' not power of 2.

**Comment by Zatline** [comment]
I think the difficulties need some improvement overall in terms of differential and they kinda look odd in the browser compared to the all other icons. I didn't expect them to be desplayed there for each server in the browser so the icon style needs to be adjusted to make em fit better to all the other icons.

**Comment by Zatline** [comment]
@oy have changed the eyes a bit choose ninja expression for competitive as it indicates danger and tension, mixed evil eyes into normal difficulty to overall differentiate in shapes.
![difficulty](https://user-images.githubusercontent.com/344608/48852118-f4156200-edac-11e8-9bb5-b2ba5a04d45c.png)

**Comment by Dune-jr** [comment]
Hmm, I think the "normal" eyes look quite odd.

**Comment by oy** [comment]
Maybe use the old double evil eyes? And make the ninja one normal and the double evil competive? The competitive players always have the ninja powerup disabled when playing.

**Comment by Sonix-** [comment]
what about having them coloured differently (like we do with ping)?
![idea2](https://user-images.githubusercontent.com/2030615/48865954-6ac45680-edd1-11e8-95f4-c7e44b4dad48.png)

**Comment by oy** [comment]
Dunno if that would be misleading? I mean people usually tie green with good and red with bad.

**Comment by Zatline** [comment]
As difficulty increases color fades, competitive is supposed to look bit scary imo 

![rect6217](https://user-images.githubusercontent.com/344608/48909206-f4753200-ee6c-11e8-97c7-29ee22212d28.png)

**Comment by oy** [comment]
Great, think they're fine now.

**Comment by Dune-jr** [comment]
@Zatline we need them in a 256x256 image now, with 64 pixels of blank space on the right and bottom. GitHub is pixelated so we're stuck without you.
