### ISSUE TITLE
Server browser: small bugs & adjustment suggestions

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1670]
Gotta say the whole thing looks pretty slick already. Thanks for the work so far :)
Here are some small bugfixes & adjustment suggestions:

- [x] make dropdown filters expandable by clicking on the line (instead of the [+]). 

- [x] align:center game types, like all other columns
![image](https://user-images.githubusercontent.com/355114/48450102-3e8f5100-e7a5-11e8-9df3-a9dff4f2d79f.png)
The non-pure warning icon might be annoying to align though :/

- [x] ~~fix gametype field alignment in server info for pure servers~~

- [x] suggestion: do not show the game types scrollbar when it's not necessary
![image](https://user-images.githubusercontent.com/355114/48449792-09ceca00-e7a4-11e8-9ad2-9e9bac422f58.png)

- [x] remove top left icons, not useful
![image](https://user-images.githubusercontent.com/355114/48449809-1c490380-e7a4-11e8-92f7-c66470173f6d.png)

- [x] add some space between the + and `Clear`:
![image](https://user-images.githubusercontent.com/355114/48449930-777af600-e7a4-11e8-9fb7-c6db47e0944e.png)

- [x] isn't the friends tab the least often accessed one? why is it the first and bigger tab?
http://puu.sh/C1mpN/ed89af007d.png
![image](https://user-images.githubusercontent.com/355114/48449955-937e9780-e7a4-11e8-83fc-72e1fd2bbaa0.png)

- [x] make those tabs toggle-able with the `Tab` key

- [ ] inline server filter editing is bugged, remove the feature altogether?
![image](https://user-images.githubusercontent.com/355114/48449993-b7da7400-e7a4-11e8-9790-645e60ddf3e0.png)

- [ ] ~~I don't think this (i) has to be yellow anymore:~~ change the placeholder (i) to something

relevant: #1605

**Comment by 1stDecadeTW** [comment]
Gametype filter improvement: clickable toggle on/off gametypes.

This will make possible to have an INCLUSIVE and EXCLUSIVE gametype filter.

So it will be a toggle include (green) / exclude (red) / desactivate (grey).

Green border = Include in search results.
Red border = Exclude from results.
Grey border/background = desactivate state, the filter is ignored (doesn't include nor exclude), it's just there if you want to activate it or desactivate later, it will save you time of adding it in a future.

![screenshot_2](https://user-images.githubusercontent.com/44511917/48502762-f18f9700-e805-11e8-8746-b13df4c93fe8.jpg)
![Uploading Screenshot_3.jpg…]()

**Comment by oy** [comment]
> fix gametype field alignment in server info for pure servers

There the icon gametype icon should be placed - already reserved the space.

> align:center game types, like all other columns

If an icon for pure gametypes will be added it might be better to align it that way. So it looks better, dunno?

> I don't think this (i) has to be yellow anymore:

Just used that icon as a place holder. "<" and ">" icons might be better?

**Comment by Dune-jr** [comment]
> > fix gametype field alignment in server info for pure servers
> 
> There the icon gametype icon should be placed - already reserved the space.

Oh, makes sense.

> 
> > align:center game types, like all other columns
> 
> If an icon for pure gametypes will be added it might be better to align it that way. So it looks better, dunno?

It looks odd with the other columns being centered. That makes sense though. Maybe someone will have a better idea.

> > I don't think this (i) has to be yellow anymore:
> 
> Just used that icon as a place holder. "<" and ">" icons might be better?

Ah, yeah, absolutely.

**Comment by oy** [comment]
> > > align:center game types, like all other columns
> > 
> > 
> > If an icon for pure gametypes will be added it might be better to align it that way. So it looks better, dunno?
> 
> It looks odd with the other columns being centered. That makes sense though. Maybe someone will have a better idea.

We could see how it looks with the icons and then decide :)

Another thing: now when you add a friend respectively its indicator makes the entry green. How about doing it like in @LordSk [mockup](https://user-images.githubusercontent.com/294603/47577257-b6a4ec80-d946-11e8-9bf8-49f062f9e355.png) with a heart?

**Comment by nheir** [comment]
>     * The non-pure warning icon might be annoying to align though :/

That's fine not to align the icon with a centered text, mainly because inconsistent alignement of image is a pain to see.
This will be more relevant with aligned pure gametype icons.

**Comment by 1stDecadeTW** [comment]
I guess that this is more related with "friends tab" issue, but here are some suggestions::

![screenshot_1](https://user-images.githubusercontent.com/44511917/48529418-a488e080-e858-11e8-8040-c62436a4e90f.jpg)
![screenshot_2](https://user-images.githubusercontent.com/44511917/48529419-a488e080-e858-11e8-8df8-28d29a4c254c.jpg)
![screenshot_3](https://user-images.githubusercontent.com/44511917/48529420-a488e080-e858-11e8-975b-c41f536b3da2.jpg)
![screenshot_4](https://user-images.githubusercontent.com/44511917/48529421-a488e080-e858-11e8-9a1d-9cd95fdbfa31.jpg)

**Comment by Dune-jr** [comment]
> Another thing: now when you add a friend respectively its indicator makes the entry green. How about doing it like in @LordSk [mockup](https://user-images.githubusercontent.com/294603/47577257-b6a4ec80-d946-11e8-9bf8-49f062f9e355.png) with a heart?

I think that's very good, but then the favorite icon should be changed to a star like in his mockup. This way we have a different icon for both, plus stars make more sense anyway

**Comment by LordSk** [comment]
Can clicking on a server switch to the **server info** tab?

**Comment by Zatline** [comment]
@Oy @Dune-jr don't like how the filter tab sudenly got scaled up for no apperent reason. 
I don't think and feel that it's more user frendly than before, not noticable but it looks noticable worst than before the + and - icons most spesifically, they are too big now they look strange, out of place! 
Don't add inconsistancy to the mix guys please, I'm really not liking this please reverse it! 
If u want the icon to be bigger we can discuss making the icon bigger graphically but don't scale by code individually just don't ..

**Comment by Dune-jr** [comment]
Issue: Alt+Tabbing in the server browser triggers the Tab hotkey and changes the filter/info/friend tab.

I haven't found a workaround :(

**Comment by oy** [comment]
Huh, could you post a picture? Don't think anything changed lately.

**Comment by Zatline** [comment]
@Oy they look noticable bigger and less sharp, left .0 right .1
![e1a451c1bb25f4074cc6d6df0802ea9b](https://user-images.githubusercontent.com/344608/48665754-933c1000-eab4-11e8-90d2-29d5ab83350d.png) ![e845d2ba41289dee0eaefacae177d523](https://user-images.githubusercontent.com/344608/48665755-933c1000-eab4-11e8-86dc-83787d3a6d34.png)
