### ISSUE TITLE
Text overlap on server  info screen

### ISSUE THREAD

**Issue by gunchleoc** [teeworlds/teeworlds#1671]
On the server info screen, I am getting a serious text overlap in the Scottish Gaelic locale. This cannot be fixed by changing the translation.

I recommend reducing the header font size and giving the headers enough vertical space for a second line.

![serverinfo](https://user-images.githubusercontent.com/4095570/48477009-64921100-e7f8-11e8-9e62-d2887458553b.png)

 The menu button also does not have enough space.

**Comment by Dune-jr** [comment]
@gunchleoc Could be changed, but maybe MOTD should not be translated then? I think that's what several other translations did. It's already not in full in English :/

**Comment by gunchleoc** [comment]
"MOTD" is fitting just fine in this screenshot. "Server Info" isn't. The proper translation for it would be "Fiosrachadh an fhrithealaiche" and I have already shortened it to "Mun fhrithealaiche". That's the best that I can do.

Note that the "Game info" header doesn't seem to have any issues.

I also just noticed that the "No" for the password is the wrong translation and can only be fixed by having individual translations for the word "No", or changing the source string to "None". Gaelic doesn't have a simple translation for "No", and we need to echo the verb in the question, which can't be done in this context.

**Comment by Dune-jr** [comment]
> I also just noticed that the "No" for the password is the wrong translation and can only be fixed by having individual translations for the word "No", or changing the source string to "None". Gaelic doesn't have a simple translation for "No", and we need to echo the verb in the question, which can't be done in this context.

Hmm, the only way would be to change this line

https://github.com/teeworlds/teeworlds/blob/d2365df9275c278c0fc8e129dbdeb8a177b81fe3/src/game/client/components/menus_ingame.cpp#L339

to ```Localize("None")```. Not sure how well that sounds in English.

> "MOTD" is fitting just fine in this screenshot. "Server Info" isn't. The proper translation for it would be "Fiosrachadh an fhrithealaiche" and I have already shortened it to "Mun fhrithealaiche". That's the best that I can do.
>
> Note that the "Game info" header doesn't seem to have any issues.

Strange, it's the same code:
https://github.com/teeworlds/teeworlds/blob/d2365df9275c278c0fc8e129dbdeb8a177b81fe3/src/game/client/components/menus_ingame.cpp#L323-L324
https://github.com/teeworlds/teeworlds/blob/d2365df9275c278c0fc8e129dbdeb8a177b81fe3/src/game/client/components/menus_ingame.cpp#L367-L368

**Comment by gunchleoc** [comment]
> 
> 
> > I also just noticed that the "No" for the password is the wrong translation and can only be fixed by having individual translations for the word "No", or changing the source string to "None". Gaelic doesn't have a simple translation for "No", and we need to echo the verb in the question, which can't be done in this context.
> 
> Hmm, the only way would be to change this line
> 
> [teeworlds/src/game/client/components/menus_ingame.cpp](https://github.com/teeworlds/teeworlds/blob/d2365df9275c278c0fc8e129dbdeb8a177b81fe3/src/game/client/components/menus_ingame.cpp#L339)
> 
> Line 339 in [d2365df](/teeworlds/teeworlds/commit/d2365df9275c278c0fc8e129dbdeb8a177b81fe3)
>  Localize("Password"), CurrentServerInfo.m_Flags&IServerBrowser::FLAG_PASSWORD ? Localize("Yes") : Localize("No") 
> 
> to `Localize("None")`. Not sure how well that sounds in English.

We'll have the same problem with "Yes" here: How about:

```
CurrentServerInfo.m_Flags&IServerBrowser::FLAG_PASSWORD ? Localize("Using passwords") : Localize("Not using password") 
```

Or use symbols:


```
Localize("Password"), CurrentServerInfo.m_Flags&IServerBrowser::FLAG_PASSWORD ? "✓" : "–" 
```

**Comment by gunchleoc** [comment]
> It could be changed to this:
> It aligns well with the "Game type". Not sure if that looks good? PR is ready in case.

I think it looks good.

> For the tab issues, that's very unfortunate, I don't see what can be done immediately. I would really like to implement smart max-width text labels that try to reduce the font size up to a certain minimum if the text is too long.

That would definitely be the best solution all around. It's probably non-trivial to do, so whenever you find the time to implement this is fine :)

**Comment by Dune-jr** [comment]
There are possible workarounds, but it's just a flaw of the translation system: if a word in English is used to mean slightly different things, it cannot be differentiated in other languages.

For the tabs on the short-term, would it be possible to grossly abbreviate it? e.g. like "srv. info" in English.

**Comment by gunchleoc** [comment]
> About passwords, there are possible workarounds, but it's just a flaw of the translation system: if a word in English is used to mean slightly different things, it cannot be differentiated in other languages.

It would ne easier if you were using gettext natively, because you'd have access to the pgettext function for these with an extra header file. It would solve the plural forms bug too, because you'd have access to ngettext.

> For the tabs on the short-term, would it be possible to grossly abbreviate it? e.g. like "srv. info" in English.

No, I can't. Nobody would understand what I'm talking about. English speakers have become used to everything being strongly abbreviated and articles being dropped etc, but that's not viable for all other languages.

**Comment by Dune-jr** [comment]
So 12a9d2a842a3f5c56f34399b53be6e619f20826a closes this.

Smart max-width text label would remain to be done in the future.

**Comment by heinrich5991** [comment]
We do have translations with context by the way, but they have to be used in the code. `Localize` supports a second parameter.

**Comment by Dune-jr** [comment]
> We do have translations with context by the way, but they have to be used in the code. `Localize` supports a second parameter.

Oh, TIL. Should probably be done for Yes/No then

**Comment by oy** [comment]
They're used somewhere, but can't rember where.

**Comment by Dune-jr** [comment]
Found it!

https://github.com/teeworlds/teeworlds/blob/92e9ee83d5738d14efd77cf580aafafa94b7c119/src/game/client/components/menus_demo.cpp#L506

Thanks grep
