### ISSUE TITLE
Improve the quit button

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1678]
![image](https://user-images.githubusercontent.com/355114/48565993-064d5700-e8fa-11e8-9ab6-d41c1b6aa51f.png)

No need for anything fancy, but there's gotta be a way to make something better than this. The default font does not really make a good cross with 'X'

**Comment by Zatline** [comment]
@Dune-jr good u bringing this up,
- align it with the tabs 
- make button 1:1 aspect 
- use the X icon instad of X from the font 
- button regulary black but 25% darker than the regular menu as it doesn't have a gradient backlayer
- use rgba: f92b2bff at 75% opacity as mouseover 


![path11953](https://user-images.githubusercontent.com/344608/48568715-47486a00-e900-11e8-94e7-784e929ef689.png)
![rect11947](https://user-images.githubusercontent.com/344608/48568732-4ca5b480-e900-11e8-836c-34dac3e8e783.png)

**Comment by Dune-jr** [comment]
This all sounds good except:

> * align it with the tabs

You should be able to click X by clicking the corner. Leaving empty space above X hinders usability.

**Comment by Fisico** [comment]
yep like the last one..

the exit button should be in the corner and not aligned with the tabs(sry @Zatline ) :D

**Comment by Zatline** [comment]
alright then align it to the edges instead but keep the botton the size of the menu tabs with the rounded edges for consistancy remove upper right edge to indicate the botton is linked to the entire screen.

![path11953](https://user-images.githubusercontent.com/344608/48573607-0acf3b00-e90d-11e8-9d62-bd3c13c62ee0.png)
![rect11947](https://user-images.githubusercontent.com/344608/48573608-0acf3b00-e90d-11e8-8d8c-1d314f0ec072.png)
