### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1681]
Resolve vulnerabilities and issues discussed here: https://www.teeworlds.com/forum/viewtopic.php?pid=121675#p121675

> So....
>
> Version server is vulnerable, to what extent is not clear right now, however this is a minor issue as it is not working anyway (version.teeworlds.com for example doesn't even resolve to an address). Hence i mostly skipped this part.
> 
> master server has a few obvious vulnerabilities that can be fairly easily resolved.
>   - `SERVERBROWSE_GETCOUNT` is vulnerable to amplification. simple fix: enlarge `SERVERBROWSE_GETCOUNT` by at least 2 bytes. (or make it a struct with two empty bytes whose existence are checked but not the values (only size is checked)
>   - Heartbeat checking is prone to amplification. i'd suggest making the try count amount of tries a constant and enforcing `SERVERBROWSE_HEARTBEAT` size of `MAX_TRIES*sizeof(SERVERBROWSE_FWCHECK`). Alternatively, enforce a size of any*`sizeof(SERVERBROWSE_FWCHECK)` and use it like "credits", if the request is `4*8` bytes large, you allow up to 4 check packets, if its `32*8` bytes large, you allow for 32 checks. (however "used" credits must not be re-used, additional heartbeat checks must only be performed if enough "traffic credits" are there. just an example. (as you see, the basic idea is never sending out more bytes than you received from a given address)
>
>UPDATE: Probably a better alternative would be a three way handshake here as connections to the master server are long-lived so once a connection is secured with a token, it can stay that way and you don't waste traffic.
>   - `SERVERBROWSE_GETLIST` is vulnerable. As the client determines the server count anyway, a simple approach would be to enlarge the `GETLIST` packet to `SERVERCOUNT*SERVERINFO` bytes (and headers are equal size, however note multiple packets would be sent in response, so `(SERVERCOUNT*sizeof(SERVERINFO))+sizeof(HEADER)*num_packets_for_SERVERCOUNT`. the master server would store this value and cut off the response if `GETLIST` was unsufficiently large.
> 
> Additionally i would like to re-think the anti spoof tokens. game traffic should ideally be authenticated and encrypted if this is possible with low ping penalties. i'd prefer using either authenticated encryption (AES-GCM) or (packet+hmac(token,packet)) instead of just (packet+token). However, this is not so much a problem for the master server.
> 
> Thats my thoughts about the master server. The reasons i picked simply enlarging packets instead of a complicated handshake is that a handshake is a bit much overhead for short lived "connections" such as fetching a serverlist once.
> UPDATE: for server registration and heartbeat i recommend an actual handshake. this connection is long-lived.

_Originally posted by **Schwertspize** in https://www.teeworlds.com/forum/viewtopic.php?pid=121676#p121676_

---

> I basically agree with most of what Schwertspize said.
> 
> My proposed solution to most of the problems:
> 
> Initial connect/get token packet must be at least 512 bytes (e.g. as implemented in the fix-0.6 branch), so as to completely make reflection worthless.
> 
> HTTPS (definitely with S) for the master server list, preferably with all the server infos already (would also make the refresh faster)
> 
> Tiny nit: I agree that there's little reason to use md5 for anything, but I don't think it's unsafe in the presence of a sufficiently random input, against preimage attacks.

_Originally posted by @heinrich5991 in https://www.teeworlds.com/forum/viewtopic.php?pid=121679#p121679_

---

> For that tiny nit. I don't regard md5 as the biggest problem. Packets are relatively small, and reserving only 20 bits for packet authentication makes it entirely possible to send all the million packets within 10 seconds until token rotation. Or, if that's just barely not possible, you retain a high percentage of win and will probably crack the next seed. As for https,as much as I despise it (it adds _a lot_ of unnecessary bloat instead of just using DTLS or TLS for example), i see that it would allow far better load balancing and reliability.
> 
> As for protocol, I would favor a simple approach. No heartbeat checking as that can be worked around quite easily. No server info as it would greatly limit teeworld's openness. Alternate serverlists? Must be supported by the individual server. Favorite list just storing ip addresse (or domains)? Nop. Custom server info for custom clients? Nop.
>
> I would suggest a protocol that consists of a simple post request to put your server in the masterlist for say 1 or 5 minutes. The master server checks if the given ip matches the source ip, or if a domain was given, that domain resolved to the server. Get provides a list of addresses.

_Originally posted by **Schwertspize** in https://www.teeworlds.com/forum/viewtopic.php?pid=121680#p121680_

**Comment by oy** [comment]
The first quoted post is out of date, there's a 3 way handshake for everything already.
The token size and the token request packet should be increased.

**Comment by heinrich5991** [comment]
I'll take a look at it tomorrow if you don't mind.

**Comment by oy** [comment]
@heinrich5991 Sure 👍

**Comment by heinrich5991** [comment]
Yea, never mind. :( Apparently I can't find the time for even simple tasks.

**Comment by oy** [comment]
The token size increased to 32bit and the packets for the initial token request (connect/get) need a minimum datasize of 512bytes now. The https master is a big thing and can be added later. There is the master serverlist cache as backup for now. 
So this should be good for now.

**Comment by oy** [comment]
Make a new issue  - if there isn't yet? - for the http master and then close this probably best.

**Comment by heinrich5991** [comment]
Awesome! Thanks for fixing that. :)

**Comment by oy** [comment]
@heinrich5991 
What do you think, increase the token size by 1 byte to be on the save side? Then brute forcing it wouldn't be feasible anymore within a reasonable time or without excessive use of bandwidth (at one point it turns into a DOS and makes the whole brute force pointless).
