### ISSUE TITLE
Server browser: Wrong behaviour with inline filters

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1682]
The line doesn't get background-highlighted when I hover with mouse, but it becomes black: 

![screenshot_2018-11-16_22-42-46](https://user-images.githubusercontent.com/355114/48648824-0bd99880-e9f1-11e8-9dd0-c881b9a0f65c.png)

Also, clicking on the "edit" button of the filter opens/closes the filter, even though I thought I had fixed that...

**Comment by oy** [comment]
That highlight thing is probably because of the dark background.
Will fix the close/open filter thing - that browser is like a minefield...

**Comment by Dune-jr** [comment]
Yeah, I walked into a few mines already.

> That highlight thing is probably because of the dark background.

When you don't expand filters, just hovering the mouse over them normally make them have 1) black text 2) a white background. The white background is gone

**Comment by oy** [comment]
![screenshot_2018-11-17_11-51-16](https://user-images.githubusercontent.com/293850/48660254-3d894880-ea5f-11e8-8867-f8f888da2528.png)
Works for me.

**Comment by Dune-jr** [comment]
Alright then :)
