### ISSUE TITLE
The quit button, again

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1683]
So after the Quit button was changed, I got a few messages asking for it to be changed.

* the corner edges. @Zatline asked for top left/bottom left/bottom right. @LordSk and I, to my knowledge, would prefer all corners. @Sonix- prefers bottom left or all corners (not sure).

* the X itself. So the current X is pixelated. @Zatline sent an enlarged `friend.png` to deal with this. It still feels a bit pixelated, maybe? I think we should not upscale `friend.png` but instead have a `quit.png`. @Sonix- would prefer to use the unicode character "\u2715". Doesn't seem to look too different for me.

* the background. It is white, I changed it to black to match other buttons, as asked by @Sonix- 

* the size. I made it the size of the other buttons (27).

I chose 0.25 alpha but we're probably going to switch to 0.5 with #1576. This is what it looks like right now:

![image](https://user-images.githubusercontent.com/355114/48659643-84be0c00-ea54-11e8-878d-aec11f64c0fc.png)

**Comment by Sonix-** [comment]
Personally I'd prefer to use an unicode character instead of an image, because it may lose quality and look different on various resolutions and keep general consistency between buttons which are mostly fonts.
This is how it looks using "\u2715" instead of "X":
![screenshot_2018-11-17_10-24-49](https://user-images.githubusercontent.com/2030615/48659847-dddb6f00-ea57-11e8-8f25-88d83f4a3c60.png)
![screenshot_2018-11-17_10-24-51](https://user-images.githubusercontent.com/2030615/48659849-e338b980-ea57-11e8-9718-2873f1c54a42.png)

Note: the example is applied before #1679

**Comment by Zatline** [comment]
@Sonix that unicode X from the font seems almost idendical from what I see quite interesting

**Comment by Dune-jr** [comment]
What about the corners?

**Comment by Zatline** [comment]
like previeuly 3 edges round, upper left edge not round (linked to window border).

**Comment by Sonix-** [comment]
> like previously 3 edges round, upper right edge not round (link to window border).

You mean 1 round corner? Before it had only 1 round corner and personally was ok.

**Comment by Zatline** [comment]
![rect11947](https://user-images.githubusercontent.com/344608/48678377-c2b94e00-eb82-11e8-84ad-64a4b62e75f2.png)

**Comment by Sonix** [comment]
Just popping in here because this is the second thread I was accidentally mentioned in. Please try to metion the correct @Sonix- so my inbox doesn't get spammed. Happy coding!

**Comment by Dune-jr** [comment]
Now that you participated here, your name automatically appears in the dropdown list @Sonix D:

**Comment by Dune-jr** [comment]
So all I need now is a directive for the edges. 

@Sonix- and @LordSk say 1

@Zatline says 3

I say 4.

**Comment by oy** [comment]
Maybe ask the [wheel](https://wheeldecide.com/) then :)

**Comment by Learath2** [comment]
I'd go for only rounding the bottom-left corner

**Comment by Fisico** [comment]
me too.

but zatlines optione with 3 rounded corners is also ok

**Comment by Dune-jr** [comment]
Current progress

1: ![image](https://user-images.githubusercontent.com/355114/48848365-063ed280-eda4-11e8-9380-c6c34a211518.png)
3: ![image](https://user-images.githubusercontent.com/355114/48848461-3d14e880-eda4-11e8-9db8-d2a11f3ca242.png)
4: ![image](https://user-images.githubusercontent.com/355114/48848393-122a9480-eda4-11e8-9991-010b0844e2c8.png)

I went with @Sonix's font.

I'll probably go with 1 then. People told me it's centered, but it still looks strange to me.
