### ISSUE TITLE
Level icons have wrong dimensions

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1684]
The [level icons](https://github.com/teeworlds/teeworlds/blob/master/datasrc/ui/icons/level.png) have wrong dimensions.

**Comment by Dune-jr** [comment]
@Zatline ^

**Comment by oy** [comment]
It should be 192x128.

**Comment by Zatline** [comment]
![skill_lvl](https://user-images.githubusercontent.com/344608/48758673-233ead00-eca1-11e8-8f7c-d704d16d753a.png)
