### ISSUE TITLE
v-sync big fps jumps over v-sync limit (SDL 2.0.9 and newer problem)

### ISSUE THREAD

**Issue by Fisico** [teeworlds/teeworlds#1693]
Something v-sync related is not working,

The game is always trying to limit the fps to 60, every x seconds it jumps to ~120fps and then tries to limit it down to 60. The game than lags a split of a second cause of the fps spike.

The video below shows the problem.

https://streamable.com/pwhhz

GPU Driver is up to date,
Specs: Intel i7 2600k
Nvidia GTX 470
24GB Memory
Windows 10 1803 x64

edit: in tw 0.6.5 and 0.7 release all is good. There the fps don't jump over the v-sync limit.

**Comment by oy** [comment]
Did you use v-sync of the fps-limiter?

**Comment by Fisico** [comment]
i have v-sync enabled.

With the fps limiter it is the same problem.

**Comment by Fisico** [comment]
@oy 
https://streamable.com/19hvs

looks interesting...

**Comment by Fisico** [comment]
the problem comes from the newest SDL versions form the SDL buildbot.
https://buildbot.libsdl.org/sdl-builds/sdl-visualstudio/

Problem is fixed with the SDL.dll(self compiled 2.0.7 version) @LordSk sent me.

**Comment by LordSk** [comment]
![image](https://user-images.githubusercontent.com/294603/48677726-6aca1980-eb79-11e8-8405-9786a249108d.png)

Could reproduce. Shipping with 2.0.7 should fix it.

**Comment by oy** [comment]
2.0.8 seems fine too - that's the one within the 0.7.0 release. We'll check back again when 2.10 is out.

**Comment by Dune-jr** [comment]
It seems like this is a Windows-only problem.

**Comment by 0xfaulty** [comment]
@oy @Fisico Somebody tried with 2.0.10? It was released on July 25

**Comment by oy** [comment]
Seems fixed now.
