### ISSUE TITLE
Chat color

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#1697]
@Dune-jr suggested
>  just have a cl_blindmode console option revert to the old red highlight for those that really need it. The rest can wait for an advanced/HUD tab, if we end up having one.

**Comment by LordSk** [comment]
So you want an option for color blind people to see highlights better, right.
Color blindness comes in several shapes and forms, what you suggest though is that we revert the change to highlights through a setting, making it **red**.

Here is a picture showing how color blindness can affect people's vision (directly taken from [this wikipedia link](https://en.wikipedia.org/wiki/Color_blindness))

![image](https://user-images.githubusercontent.com/294603/48775199-a32e3c80-eccc-11e8-8302-f1014cf0c995.png)

As you can see, a lot of color blind people can't perceive **red/green** very well, if at all. These same people have however a better sense of blue shades than most of us (source: I had a red-green color blind friend, and if you look at the color gradient, it makes sense).

The truth is, Teeworlds is currently ill-equipped to deal with this. The game is very colorful by nature and we need to think of complete solutions to accommodate their condition, not quick hacks like this which won't solve much.

**Comment by Stitch626** [comment]
But if you redesign the menus, what about the maps? The flags? I believe the problem would be a bit bigger than just chat colors and menus :/

**Comment by ChillerDragon** [comment]
After playing 0.7 for a while now I stopped looking too odd.
