### ISSUE TITLE
In game, Escape should not save the state of the menus

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1698]
Right now, in-game, the Settings menu can be accessed as a second layer of the "pause"/ingame menus:

```
Game ----<Esc>----> Ingame menus -> Settings menus
```

In 0.7, in order to go back to the game, you press `<Esc>`:

```
Settings menus ----<Esc>----> Game
```

But there is **no way** to go back to the Ingame menus. You have to click a "Back" button that is very inconveniently placed in the bottom left of the screen. Indeed, if you go back, this happens:

```
Game ----<Esc>----> Settings menus
```

I propose to simply revert to the 0.6 behavior, which is:

```
Game ----<Esc>----> Ingame menus -> Settings menus
Settings menus ----<Esc>----> Ingame menus ----<Esc>----> Game
```

All you need is to double press `<Esc>` again, and the menus become less frustrating to browse in-game. That would be an easy fix.

Related: #1611 

---
Edit: second option voiced by @Zatline:
```
Game ----<Esc>----> Ingame menus -> Settings menus
Settings menus ----<Esc>----> Game
Game ----<Esc>----> Ingame menus
```

**Comment by Fisico** [comment]
ESC should always bring you back to the game. Not a jump to another menu or tab.

**Comment by oy** [comment]
Seems obsolete now with the changed ingame menu #1611 ?

**Comment by Dune-jr** [comment]
@oy: I don't know. It's true that we no longer have to click an obscure Back button.

But It's still really a pain whenever one wants to change team/disconnect to press `Esc` then click on the top bar, then on the very bottom of the screen. That's a lot of mouse travelling. I feel like with the changes in #1611 it would make a lot more sense to have the "Spectate/Join red/Join blue/Disconnect" button as a second row again, like in 0.6 :/

**Comment by Stitch626** [comment]
I'm fine with pressing ESC several times - rather than using my mouse to click some buttons. For example: You are on a server and you are alone. You are testing some settings and you hear something in the background. You can easily press ESC several times to see quickly whats going on. Not possible with mouse buttons. It's the same behavior in other common games, to press ESC several times to exit one submenu after another to get back to your game. And my personal opinion would be like that.

**Comment by Zatline** [comment]
@Dune-jr thinking about it again I find hiting ESC twice makes the most sense as @Stitch626 says most games function exactly this way and in it's core it's basically like reset.

**Comment by quadCoreZ** [comment]
option 4 is the best imo

**Comment by Zatline** [comment]
option 4 is the best makes most sense and the most simple. 
A bottem cluster at the top like seen in 3 arg very odd no game has these kind of bottems at the top.
directly game related tabs are generally at the bottem, I'd like to suggest an alternative to 3 at least
still favoring 4 tho with 5 following, 2 is a total mess, 1 in it's core is like 4 but bad.

5. move bottems down
![game_menu](https://user-images.githubusercontent.com/344608/49239960-60730f80-f404-11e8-98be-2569119e237f.png)

**Comment by oy** [comment]
Would not move the tabs down cause they're always on top within the other menus. Doesn't feel consistent - same for moving the buttons up.
If 4 would be the option it should be apply to the other ingame tabs (players, server info, call vote) as well.

**Comment by Zatline** [comment]
yeah you're probably right, thinking about it again I think I'd be okay with option 3 I guess well as long as it keeps the 0.7 look like in the latest image if that helps.

**Comment by LordSk** [comment]
![image](https://user-images.githubusercontent.com/294603/49321695-4707bb80-f509-11e8-99f3-cd79bc972991.png)

That's not bad.

**Comment by Zatline** [comment]
@LordSk looks just like the old 0.6 cluster, bad spacing .. bad everything. 😕 
keep 0.7 look, there is no going back to ugly 0.6 .. not with me.

I'm ready to compromise but only if done right, 
otherwise go with option 4 as that seems to have majority anyway.
![game_menu](https://user-images.githubusercontent.com/344608/49322617-4c690400-f511-11e8-9dc1-9aa1f1965e01.png)

**Comment by 1stDecadeTW** [comment]
> ![image](https://user-images.githubusercontent.com/294603/49321695-4707bb80-f509-11e8-99f3-cd79bc972991.png)
> 
> That's not bad.

Lets just reorder and improve this pause menu layout, it's convenient and proper for teeworlds's mechanics. For example, Statins could be inside GAME tab, and players and friends tab could be merged.

**Comment by Dune-jr** [comment]
> @LordSk looks just like the old 0.6 cluster, bad spacing .. bad everything. 

But most important: good usability! Function first.

0.7.0 was the first time I made a bind for "disconnect" because it was so annoying to hit.

> keep 0.7 look, there is no going back to ugly 0.6 .. not with me.
> I'm ready to compromise but only if done right,

"Form follows function", we can improve the form now.

> ![game_menu](https://user-images.githubusercontent.com/344608/49322617-4c690400-f511-11e8-9dc1-9aa1f1965e01.png)

I think tabs look better than flying buttons, why did you remove the tabs? :/
