### ISSUE TITLE
Add wallhammer back agian

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#1699]
I saw this [epic moment on youtube](https://youtu.be/JHOmg9XulWY?t=82) and I love it!

It would be awesome to have this wallhammer back agian for epic ctf2 moments.

**Comment by ChillerDragon** [comment]
@oy yes that is true it is no intuitive. Nor is hookfly or some of the other crazy but nice things teeworlds allows. But since its not a core element of the gameplay it doesn't matter. Nobody needs to know it to master the game. But everyone is free to use it and have fun.

**Comment by ChillerDragon** [comment]
@Dune-jr sounds like you agree the video was nice. But why do you think it is a bad bug that has to be removed.

For me it seems like that it was not planned and then people called it a bug because nobody implemented it intentional. So everybody agrees on removing it. But what if it actually could be a feature. And the only reason to remove it is that it is a bug. And the only reason it is called a bug is because it wasn't planned.

Even tho it is an unplanned child we don't have to kill it :c

**Comment by hamedasl** [comment]
> @Dune-jr sounds like you agree the video was nice. But why do you think it is a bad bug that has to be removed.
> 
> For me it seems like that it was not planned and then people called it a bug because nobody implemented it intentional. So everybody agrees on removing it. But what if it actually could be a feature. And the only reason to remove it is that it is a bug. And the only reason it is called a bug is because it wasn't planned.
> 
> Even tho it is an unplanned child we don't have to kill it :c

you are right

**Comment by S4EED** [comment]
@ChillerDragon "I see that currently the majority seems to dislike the idea ._."

**Comment by hamedasl** [comment]
> Teeworlds allows for some strange behavior but I don't think that justifies reintroducing bugs, just because there was one cool video using that.

Thats not just because one video! after many years, now its a part of Gameplay.

**Comment by Sonix-** [comment]
It never was part of gameplay in vanilla, dont bring / confuse ddnet related features here please

**Comment by Zatline** [comment]
In PUBG the pan stoping bullets was not intentinal either even labeled as bug by the devs but it established itself as part of the gameplay and so it became a feauture. It seems we have a similar situation here.

**Comment by Dune-jr** [comment]
It not being originally intended does not mean it shouldn't be kept, yes.
It doesn't mean it should, either.

**Comment by ChillerDragon** [comment]
@Dune-jr it doesn't harm so I see no disadvantage. It could be unintuitive but I never saw anybody complaining about it in DDrace mods even tho it is not part of vanilla. I don't know how it was back then in when it was part of vanilla. But i think nobody was annoyed by it. But a few people might enjoy it.

**Comment by Sonix-** [comment]
We have been without it for 8+ years just fine without it

**Comment by ChillerDragon** [comment]
@Sonix- yea sure it is fine. And nobody actually needs it because it doesn't play a big role gameplay wise. But it is a nice add-on and if it doesn't hurt why not add it?

**Comment by Dune-jr** [comment]
Reintroducing a bug that had no gameplay effects would just be weird imo.

**Comment by oy** [comment]
Like said, that behaviour wasn't intended and so the flaw was fixed many years ago. It's not coming back. Same goes for the wall flag passing.

**Comment by ixPost** [comment]
What is a wall hammer?

**Comment by ChillerDragon** [comment]
> What is a wall hammer?

Bra I even added a youtube link showcasing a wallhammer.
