### ISSUE TITLE
Key binding to switch tabs

### ISSUE THREAD

**Issue by android272** [teeworlds/teeworlds#1706]
It would be nice if you could quickly switch between tabs like you do on a web browser. I perpose that CTRRL+TAB move you to the next tab to the right, While CTRL+SHIFT+TAB would move you to the previouse tab to the left.

Places where this would be used:
Settings:
![settings](https://user-images.githubusercontent.com/5912527/48872266-5e7ed000-edb6-11e8-9a44-16dff5470a5a.png)

Server Browser:
![serrverr](https://user-images.githubusercontent.com/5912527/48872265-5e7ed000-edb6-11e8-97e9-80bb0b004a4f.png)

In Game:
![game](https://user-images.githubusercontent.com/5912527/48872267-5e7ed000-edb6-11e8-95fb-b7bf389d8cc8.png)

Notice that in the game while on the call vote tab when you press CTRL+TAB you move back to the start instead of going to settings. This is because setttings is not a tab but a button. In the Server Browser however friends is a tab so while on Local CTRL+TAB should move you to the friends tab.

**Comment by oy** [comment]
I guess shift+tab could open the steam overview in the steam version.

**Comment by Dune-jr** [comment]
Not sure if `Ctrl+Shift+Tab` triggers the steam overview. Does it?

**Comment by oy** [comment]
@Dune-jr 
Tested, it does open it, But doesn't work to close it again...

**Comment by Dune-jr** [comment]
Fixed by https://github.com/teeworlds/teeworlds/commit/a63f9d088c0d9ca62490eb1e71183aa6d20295b2 and previous commits
