### ISSUE TITLE
Server filters aesthetics

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1708]
@Zatline complained about the lack of consistency in the size of the filters, introduced by 7b963e5

This is what it looks like, before and after the commit: 

![image](https://user-images.githubusercontent.com/355114/48893099-d2b18600-ee3f-11e8-86b5-219e13850345.png)![image](https://user-images.githubusercontent.com/355114/48893112-d9d89400-ee3f-11e8-9f1d-a25b8707619c.png)

In both cases the [+] are very pixelated.

1. should 7b963e5 be reverted?
1. @Zatline, can you upscale it - and release the sources, at least privately? (see the private forum thread)

**Comment by oy** [comment]
https://github.com/teeworlds/teeworlds/issues/1670#issuecomment-439647534 that was before the commit. Now they look again like in 0.7.0.
What resolution is this in the picture? They're totally sharp for me on 1920x1080.

**Comment by Dune-jr** [comment]
![image](https://user-images.githubusercontent.com/355114/48896215-5de24a00-ee47-11e8-93fa-ad186a281e73.png)

800x600. Not sure if that's just the resolution being small

**Comment by oy** [comment]
Yeah, has to scale down the icons, that's why it gets blurry.

**Comment by oy** [comment]
Could use a different texture mapping for the textures to make it sharper for low resolutions.
How it looks now when scaling down:
![screenshot_2018-11-22_12-27-19](https://user-images.githubusercontent.com/293850/48900276-3a70cc80-ee52-11e8-9bfe-ffe7284dead7.png)
Different mapping:
![screenshot_2018-11-22_12-25-56](https://user-images.githubusercontent.com/293850/48900236-2927c000-ee52-11e8-82e7-50a9df92f995.png)

**Comment by LordSk** [comment]
I was think of doing that as well @oy, have some image not generate mipmaps and use the LINEAR min filter. We don't want to use mipmaps for small stuff anyway.
