### ISSUE TITLE
Some country flags are missing for languages

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1721]
Breton, Catalan, Esperanto and Galician are currently missing a flag

**Comment by heinrich5991** [comment]
Three of these are regions within larger countries (Breton: France; Catalan and Galician: Spain) and Esperanto doesn't even have an associated country.

This is part of a larger problem that we associate countries with languages. In general, there's not a one-to-one mapping, e.g. German is spoken in Switzerland, Austria and Germany, but apparently Catalan, Galician and Spanish are spoken in Spain. As said, Esperanto doesn't even have an associated country, but its Wikipedia page does have a flag.

![breton](https://user-images.githubusercontent.com/366230/48981330-45d32a80-f0d4-11e8-9295-804128d0e03c.png)
![catalan](https://user-images.githubusercontent.com/366230/48981331-45d32a80-f0d4-11e8-9806-1afda6163a95.png)
![esperanto](https://user-images.githubusercontent.com/366230/48981332-466bc100-f0d4-11e8-8299-2829f68558cb.png)
![galician](https://user-images.githubusercontent.com/366230/48981333-466bc100-f0d4-11e8-8e04-172aa8a5a9f0.png)

**Comment by Dune-jr** [comment]
Do we have flags that cannot be used as country flags? It would be silly for someone to have an "esperanto" flag in game, right?

**Comment by heinrich5991** [comment]
Yes.

**Comment by Dune-jr** [comment]
Apparently there is a template shadow to put on the flag somewhere in the forums that Landil made.
