### ISSUE TITLE
Improve tile skip optimization

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1728]
For smaller maps the tile skip optimization leads to bigger maps in the end, f.e. dm3 or dm8.

**Comment by LordSk** [comment]
Is it really worth the complexity? We could save/load small maps differently but I don't think a few Kb is worth the trouble.

**Comment by oy** [comment]
Well, some maps got twice the size. Don't think it's much of a hassle to add it.

**Comment by oy** [comment]
Invalid. Bigger maps are caused by f209aea10eb9e443839247c07612c6a64d638df0
