### ISSUE TITLE
Move score at the first column of the scoreboard and keep scoreboard expanded.

### ISSUE THREAD

**Issue by 1stDecadeTW** [teeworlds/teeworlds#1734]
When you play in CTF, seeing the score of you and other players somehow motivates you to play harder, but its quiet difficult to refer to your score or others scores in the current scoreboard.

Scoreboard should be expanded all the time, its anoying to see all those texts and stats condensed in a tiny row.

![deepinscrot-1537](https://user-images.githubusercontent.com/44511917/49052310-e7c84500-f1b0-11e8-8c9a-b58212d7ba5a.png)
![deepinscrot-1731](https://user-images.githubusercontent.com/44511917/49052311-e860db80-f1b0-11e8-903b-25eddc162255.png)

Edit: country flags should be placed where the score is actually placed, and viceversa.

**Comment by Zatline** [comment]
agree 100%

- switch score with flags
- lock scorebord to a fixed and fully expanded size
- additionally get rid of k/d

**Comment by Zatline** [comment]
also why has the name been colored green??  it looks ridiculous

**Comment by 1stDecadeTW** [comment]
> also why has the name been colored green?? it looks ridiculous

I think that player coloured green is supposed to help with the visibility in server full of players. We need to try it.

**Comment by Dune-jr** [comment]
I'm not sure if I like separating the score from the K/D... doesn't feel intuitve

> Edit: country flags should be placed where the score is actually placed, and viceversa.

So you want country flags all the way to the right?

> also why has the name been colored green?? it looks ridiculous

I agree this needs to be changed to something less visible, it's a niche feature

**Comment by Zatline** [comment]
my first concept that leaded to what we currently have must have been inspired by [Battlefield 3](https://i.gyazo.com/c835505a9c4e6b60c52efda48d21bef7.jpg) & [Battlefield 4](https://i.gyazo.com/4ca5f46588ea90907e6f37a7e9bde32c.jpg) scorebord which I played a lot at that time it has the layout exactly the way it currently is in 0.7 (only placement is missing) however I personally find that the old board structure like it was in 0.6 
**-> score, tee, player, clan, flag, ping** just suits Teeworlds more dunno anymore I agree spliting k/d from score is not very intuetiv :/

could we do both and make it an option? 
0.6 -> classic, 0.7 modern only if that wouldn't be too much

>Its the ready state, that green colour

very interesting I like the idea but the execution is questionable as of rn

**Comment by Dune-jr** [comment]
> could we do both and make it an option?

IMO, no. Making an option for this kind of UI design choice is a bit absurd. If we want to add more stats than we have room for, then those additional stats belong in an additional stats scoreboard.

I personally would rather keep K/D, but I would still prefer to remove them from the main scoreboard than to make them *an option*.

**Comment by Fisico** [comment]
i agree the scorebaord should have a fixed hight, only the spectator box should expand dynamically.
I think it is possible to change score with the flag and it will be ok.

**Comment by Sonix-** [comment]
K/D doesnt reset on restart

**Comment by Fisico** [comment]
Some ideas for a dynamic fixed height scoreboard.

The scoreboard lines should correspond to the maximum player slots.
Some examples:
Server max players 16, spectatorslots 0, gametype team… = 8 lines.
Server max players 16, spectatorslots 8, gametype team.. = 4 lines.
Server max players 16, spectatorslots 6, gametype noneteam = 10 lines.

**Comment by PeterMaffay89** [comment]
Well, imo the sort criteria for the list is not clear. Usually, as a user, i expect my list to be sorted after the first or last column. 
In the 0.6 SB the score was the first column and the sort criteria (fine).
In the 0.7 SB the flag is the first column and the last the ping, but NEITHER are the sort critera. Even worse, there is no visible indication for any.

Therefore I vote for moving the score **to the last column**. Yep, that one wasn't suggested yet.

Let us take a brief look at the scoreboard of *CounterStrike GO*. The score is the last one, plus it is visually marked as sum column. Very intuitive.

![screenshot_csgo_scoreboard](https://user-images.githubusercontent.com/43857716/49469021-b5e55d00-f806-11e8-81ce-58ce2f50a267.jpg)

**Comment by Fisico** [comment]
like the idea to put K/D and score on the right side of the scoreboard.

**Comment by Zatline** [comment]
@Fisico @sepulzera yeah seems intuitive I'd be okay with that 👍

**Comment by Fisico** [comment]
maybe also highlight the score column

**Comment by Dune-jr** [comment]
Sounds like moving the score last is one thing we agree on.

@oy should that be included in 0.7.1?

**Comment by Fisico** [comment]
Ping | Flag | Tee | Name | Clan | K | D | Score
and highlight the score column in some way.

**Comment by Dune-jr** [comment]
> Flat | Name | Clan | Ping | K | D | Score

> Ping | Flag | Tee | Name | Clan | K | D | Score

Huh, you changed the ping to the first column? So I guess we don't actually agree on where to put the ping column.

**Comment by Fisico** [comment]
i talked to @Zatline yesterday and we agreed it is best to clone the cs:go scorebaord. @sepulzera also said that.

**Comment by nheir** [comment]
I disagree with the Flag preceding the Tee. Tee is to recognize the player in the game, Name and Clan to name it, Flag should come after this.

If putting the ping at first column , I'd prefer it in grey, or something that don't pick the eye.

**Comment by Dune-jr** [comment]
I think the flag in the middle of the scoreboard would be very strange

**Comment by sepulzera** [comment]
Easy one: 
The score column is a result column. Therefore it should definitely be the last column. We all agree on that.
Anything else related to the score should come before the score column.
And the order of ping, flag and playername+clan is unimportant.

But for the sake of readability, we should just stick with the cs:go layout:
Ping | Icons related to the player | Name stuff | Score stuff.
They just put the ping before the name, to make it separate from the other score relevant stuff. And grayed it out coz it is uninteresting overall.

**Comment by oy** [comment]
@Dune-jr 
Yeah, could switch it for 0.7.1.

**Comment by oy** [comment]
Further discussion here #1826
