### ISSUE TITLE
Mouse sense on Razer Blade Pro

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#1742]
I spend some money to buy a laptop that can run teeworlds at a decent framrate. But sadly it has a broken mousesense. It is THE NEW RAZER BLADE PRO - 4K (GTX 1080). The game runs smooth. But it is nearly impossible to control the mouse. I used the same os, mouse, dpi and ingame sense on multiple devices and the razer blade pro seems the only one making problems. Maybe it is the laptop or maybe it can be fixed from the teeworlds side I am not sure at all what the problem is.

Since the screen is 4K i also have the highdpi issue agian and everything is full of pixsels but i don't think that is the mousesense issue. I tried the ddnet client aswell that supports 4K screens and the mousesense is broken there aswell.

**Comment by Dune-jr** [comment]
Does the mouse work fine on the desktop?

**Comment by ChillerDragon** [comment]
@Dune-jr I think it works pretty fine on Desktop. But it is easier for me to tell the difference in games because i can actually see how i miss aim things. I tried to test it in CS:GO swell because i play that occasionally but the framerate was too bad to test the sense. But i am pretty sure that the sense on Desktop is okay.

Oh and i noticed that linux high dpi support seems to be working. I did a dual boot on my other Razer laptop and on Debian teeworlds scales up to 4k smoothly. But macOS and windows make some trouble for me.

**Comment by Dune-jr** [comment]
I can confirm 4K runs fine for me on Linux.

But isn't 4K on Mac the problem then? Have you tried lower resolutions? What is the mouse sensitivity like, too high, too low, irregular?

**Comment by ChillerDragon** [comment]
It is not only macOS it is windows as well. On mac it is locked to a specific very low resolution and on windows i didn't test enough i just tried to set it to screen resolution and it reseted to the lower one.

It is hard too explain what is going wrong with the sense. I play a very high sense i can't really see the mouse i feel it. But maybe it is even irregular because I tried to manually fix it by changing dpi and in game sense.

**Comment by oy** [comment]
Could you check again with "inp_grab 0"?

**Comment by oy** [comment]
Not reproducible.
