### ISSUE TITLE
Disconnect messages ingame and in demo

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#1744]
I had two tees on local server both using default skin:
![screenshot from 2018-11-30 10-54-33](https://user-images.githubusercontent.com/20344300/49282156-bf7d6680-f48e-11e8-8c81-81d67fd318e6.png)

Then I disconnected one tee and i realized that the skin looks weird in the top right message:
![screenshot from 2018-11-30 10-55-56](https://user-images.githubusercontent.com/20344300/49282164-c2785700-f48e-11e8-8375-9e0154283206.png)

I checked the demo file and there the name was correct and the skin aswell:

![screenshot from 2018-11-30 10-55-18](https://user-images.githubusercontent.com/20344300/49282161-c1472a00-f48e-11e8-8b51-1c4e157a76b8.png)

Sidenotes:
The screenshots are reproduced that is why the timer doesn't make sense. Also ignore the top border it was me not being able to take a proper screenshot.
Tested on debian 9.

**Comment by oy** [comment]
@ChillerDragon 
The kill msg comes after the player disconnected. So the client have the information of the player who left anymore. Should probably stop sending the kill messages when someone leaves.

@android272 
Was that on a modded server?
