### ISSUE TITLE
64 players problem

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1748]
When joining a 64 player server with a client in debug mode, some players aren't introduced.

**Comment by Dune-jr** [comment]
Also, @nheir segfaults when printing the capture message (and it shows (null) for real players for him)

**Comment by nheir** [comment]
Caused by #1751

**Comment by oy** [comment]
Should be fixed - protocol object didn't update properly when changing max_clients c0efc8b3eaae10ab8053f992742168db28510e56.
