### ISSUE TITLE
Inputs get stuck in the rc

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#1761]
I just tested the windows 64bit rc and i realized that the inputs get stuck very often. Sometimes i am not able too hook then it keeps hooking and shooting even if i press nothing.

I downloaded it from the release page and told windows that teeworlds should overwrite the scaling to have less bugs on 4k screen.

**Comment by Dune-jr** [comment]
That sounds related to the 4k/scaling stuff. Can you try on a non-4k screen?

**Comment by ChillerDragon** [comment]
I tried on a regular fullhd screen it had the same result.

**Comment by savander** [comment]
Input stuck, when you press shift (the circle with emoticons). You can't do anything then.
Also, if you press, for example move-right, and release that move while holdin the circle, the player keep moving. etc.

**Comment by ChillerDragon** [comment]
@savander you genius! Yes it is a emote bug. And i press shift all the time. It is not just the emote circle. Also `` bind lshift emote 7`` direct emotes stuck the input.

**Comment by ChillerDragon** [comment]
Oh it has actually nothing to do with emotes it is the shift key.
@Dune-jr it might be related to the compose binds https://github.com/teeworlds/teeworlds/pull/1589

**Comment by Dune-jr** [comment]
Sounds like it is related to #1589 indeed. I'll have a look.

**Comment by Dune-jr** [comment]
One issue is that pressing `Shift+D` is not meant to trigger `D` binds (and thus you will no longer move right). That is an issue if, for example, `lshift` is bound to emotes.

I'm looking for a good solution to this.

**Comment by oy** [comment]
Binds for which you keep the button pressed (starting with +) should just be allowed to be bound to single keys and should always be triggered despite any modifier.

**Comment by Dune-jr** [comment]
@oy that sounds like a brillant fix.
