### ISSUE TITLE
Fork until 0.7.1 release

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1765]
Since 0.7.1-rc has been released, the development of new features should fork away from the polishing of 0.7.1. We don't want to introduce new bugs.
I suggest to create a 0.7.1 branch and keep master for further development (or the other way around).

**Comment by ChillerDragon** [comment]
Or we simply release no new features until we have an actual release.

**Comment by oy** [comment]
Would rather wait with adding new features till 0.7.1 is released.
Shouldn't wait too long with the 0.7.1 release.

**Comment by Dune-jr** [comment]
Alright then.
