### ISSUE TITLE
Transifex can enforce character limits

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1770]
Enforcing a character limit for each string could prevent a few headaches with text overflow from translations.

However, I don't think the UI even knows how much space the label is allocated (in most cases, at least?). The size of each character is also variable. 

I think it could make sense to add this as a Localize parameter (optional, at least). Maybe it could be calculated from the width and the font size? With some optimistic margin - it's no perfect solution, but it helps a bunch.

Nothing would have to be enforced Teeworlds side, but it would help a lot with the translation process.

**Comment by oy** [comment]
Characters have different widths. So a character limit might be not the determining factor.

**Comment by Dune-jr** [comment]
Yeah, the variable character width is an issue that cannot be worked around.

Yet an optimistic character limit could act as a safeguard, couldn't it?

**Comment by oy** [comment]
Dunno if one language uses many short chars like i or l and another many wider ones like m or w. Then you have a significant difference.

**Comment by Dune-jr** [comment]
Alright, closing then.
