### ISSUE TITLE
64 players: some server has players that aren't introduced (RC)

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1775]
Appeared on the /32 ÆON server. According to Savander, the unintroduced player did not appear on the scoreboard or in the player count. Maybe he could expand on that so we can investigate.

That server has 0.7.1 as a version string so it should be RC or above.

**Comment by savander** [comment]
Without a name, you are not able to use chat at all. You can read, but not write. Maybe network-layer is using "name" somewhere, so since you can just enter nothing as a nickname, things could break.

**Comment by oy** [comment]
https://github.com/teeworlds/teeworlds/blob/master/src/game/client/components/chat.cpp#L372

**Comment by axblk** [comment]
I checked the logs of the corresponding server. This player actually had a name.

**Comment by oy** [comment]
Seems like 2 different issues?
