### ISSUE TITLE
When the IDs option is turned off, IDs should be disabled in the flag capture message

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1776]

**Comment by savander** [comment]
The same, with "join, left, spec" messages. I think, it affects every message, where ID is presented

**Comment by LordSk** [comment]
As stated here https://github.com/teeworlds/teeworlds/pull/1711

> A few hard coded text IDs still persist however, in system messages. As they are deeply connected to translations, I wasn't sure what the right approach for them would be.

**Comment by LordSk** [comment]
It seems like a good solution indeed
