### ISSUE TITLE
Enable map checker

### ISSUE THREAD

**Issue by axblk** [teeworlds/teeworlds#1781]
What about enabling the map checker again?

**Comment by Dune-jr** [comment]
Is there any development work?

I mean, is there any issue with https://github.com/teeworlds/teeworlds/blob/8e8e05c4f37670359b7b54a95a8b94285de4a7cc/src/engine/shared/mapchecker.cpp#L49-L105 or is it just about uncommenting it?

**Comment by oy** [comment]
Hm, not sure. There have been changes to the code but I guess it should work ok. Some testing would be good.
The version server has to be updated.

**Comment by oy** [comment]
Should probably fix the version server too in that regard.
