### ISSUE TITLE
Pick emoticon with mouse button press

### ISSUE THREAD

**Issue by sepulzera** [teeworlds/teeworlds#1787]
This issue may be related to #1786.

I joined a game and opened the emoticon wheel/menu. Now I can (actually have to) send an emoticon by hovering it with the mouse and then releasing the *emoticon wheel key button*.

It would be more intuitive if I could click on the emoticons. That action should close the wheel/menu and send the clicked emoticion.

**Comment by fokkonaut** [comment]
no, instead you should be able to move your mouse around how you want in the emote tab and if you place it in the middle and release shift you wont send an emoticon.

**Comment by sepulzera** [comment]
I didn't mean to choose one over the other. I should be **additionally** able to pick the emoticon with a mouse button press over an emoticon.

Why? Because this was my first attempt, after not playing this games for a long period of time.

**Comment by fokkonaut** [comment]
I wouldnt add a "click".

**Comment by Dune-jr** [comment]
I think setting `m_Active` to 0 after a click to act as a `+emote` release would be nice, and more intuitive, like @sepulzera says.

**Comment by oy** [comment]
Clicking anything makes no sense. The whole menu stays open until you release the key you bound +emote to. Closing it with a click would instantly open it up again as long as the +emote key is pressed.

**Comment by sepulzera** [comment]
That are technical interna. You could ignore the key press, as the action is done.

**Comment by oy** [comment]
Would change how the whole thing behaved like forever.

**Comment by sepulzera** [comment]
Could you please elaborate on this?

On a conceptual level, my requirement is to *close the window on a click*, furthermore to *ignore the key press* then. I do not see any break in behaviour here. Currently, you can close the window and send the emoticon via key release. Now, additionally, via mouse click. This is nothing special at all.

On a technical/implementational level you are basically answering, that this could not be done with few lines of code. But, that is coding and at least for me (still being on the conceptual level) irrelevant.

What really matters would be an estimation, **how much have to be changed** and **how much time it would take**. Then you could priorize this requirement or eventually drop it for being too complex (what I honestly could not believe).

**Comment by nheir** [comment]
Imo, first attempt is a relevant argument but I feel the way the emoticon work is intuitive at the second try anyway. Furthermore, players are likely to use their mouse without pointing anything (see #1565 ), this UI design follows the same spirit.

**Comment by sepulzera** [comment]
Ok, sorry guys.

I just compared it to how the scroll wheel of Dota2 works: The same way like our wheel now.

![screenshot_dota_messagewheel](https://user-images.githubusercontent.com/43857716/49684236-435bd200-fad1-11e8-9518-76845dacc701.jpg)

BUT there is one subtle difference: You can not point with the mouse on the messages, instead you have to select it with this *wheel pointer*. Therefore you won't actually try to click of them (as you are not pointing on them directly).

What do you think about this? I feel that reimplementing this is sort of a bigger change, making it not quite worth it.

**Comment by oy** [comment]
@sepulzera 
Like I wrote before. The current behaviour is that an action is performed as long as the bound key is pressed. Wouldn't be logical when the emote selector closes though you still hold the key that keeps it open.

**Comment by sepulzera** [comment]
@oy 
Sorry for being a nuisance here, but I still think to be right. Therefore I will try to start over this discussion to improve my point.

For buttons, the common UI pattern for mouse usage is to point on the element and click it.
Now, the *emote selector* is made up of actually x buttons. Thus if I have to point on it with my mouse cursor, I intuitively want to click it. I think we all agree on this, like @nheir also did.

Dota2 solved this issue. Their *message selector* is basically the same to the teeworlds *emote selector*. You keep pressed a button and choose the option.
But they removed the mouse cursor for the selector. I strongly assume that the reason is to remove the above explained confusion: Now you can not directly point on the option with the mouse cursor. Intuitively you won't expect to choose the option via mouse click.

**Long story short:**
Our emote selector has an usability flaw: We point with the mouse cursor on a button/option but can not use it with the mouse.

I think there are two ways to fix it: 
1. Remove the mouse cursor like Dota did. This may be a bigger change, eventually making it not quite worth it with our limited manpower.
2. Make the emotes clickable.

If we are going for option 2, you (oy) basically said:
As the *emote selector* is still being pressed, we also need to ignore that button press until it is released again. And you think that this behaviour be *logical*.

But I wouldn't agree on this. First, you will release the button afterward as your action is done. Second, you can keep other buttons pressed as well, without doing any actual action (like keeping "1" pressed, but after switching to the hammer nothing will happen anymore). 
-> I really can not see any logical flaw here.

**Comment by nheir** [comment]
@sepulzera 
You misunderstand my message. Clicking may be intuitive but that is not enough to make a flaw in the picking UI. The UI has room for improvement but picking an emote is fairly easy once you understand how it works. Figuring this is a matter of two try at most. 

About intuitive thought, the emote UI hides if I release the shift key, intuitively, it's logical that the picking is bound to the shift key, then clicking is not more intuitive that the actual behavior.

About your two points, 1. is the easiest to implement but I feel like it makes the UI less intuitive (again).

**Comment by sepulzera** [comment]
> Figuring this is a matter of two try at most.

So, basically you agree that it isn't intuitive as it is. But then you don't agree to fix it, as it is (at least in your opinion) simple enough.
This is what really confuses me. Where is the line?

At least for future reference, we should document why we chose to not fix it. "Wayne" would be ok for me, though it is fairly subjective.

**Comment by nheir** [comment]
The first try is based on experience, that why in this case, this is more intuitive **at first** to click. You don't improvise by doing something you never did at first. But this does not make the actual behavior wrong since it become obvious to that releasing the shift(or emote bind) sends the emote.

I don't suggest to quote me as reference, I'm only sharing my opinion as you do here.
