### ISSUE TITLE
Mousewheel inputs are much slower

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1792]
This follows to a report from AMN. Mousewheel inputs in the RC are quite slow, making it difficult to use that to use the pistol. While the reload speed did not change (still 125ms since 0.4.0 or so), the way the mousewheel inputs are treated did.

I think this should be changed/fixed. I have a mouse with adjustable mousewheel sensitivity and I am able to fire bullets at high speed like in 0.6 while AMN cannot (and has wrist issues forcing him to use the mousewheel).

Edit: I checked the value of `Event.wheel.y` there:
https://github.com/teeworlds/teeworlds/blob/834a433ca84e7e00ebdd9a5689d8a5631d7723c6/src/engine/client/input.cpp#L188-L191
and it's always 1/-1 for me, so I'm not sure where the issue comes from. It's definitely different in 0.6.
Besides, strangely enough, I can't make `bind mousewheelup +fire` work on my linux laptop (yet `ctrl+mousewheelup` works...).

**Comment by LordSk** [comment]
I have the same behaviour on 0.6 and 0.7 (Windows 10 x64).

**Comment by Dune-jr** [comment]
AMN reported this is fixed.

I am not sure what happened, probably some user-specific issue. I suggest we close this.
