### ISSUE TITLE
"Click on a player or flag to follow it" shouldn't be displayed when player joins an empty server

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1797]
I tried things out today, joined an empty dm1 server, got this message, it was weird.
Probably shouldn't trigger on server entry at all.

**Comment by oy** [comment]
Yeah, should be skipped for an empty server. But would keep it on join.

**Comment by sepulzera** [comment]
I join an empty server as spectator. Therefore, no message is displayed.
Now another tee joins and eventually the match gets started.

In that case, the message would never be displayed. Wouldn't it be better to display this message permanently, like the warmup message?

Furthermore, I find the feature confusing overall. I should "click" sth without a mouse cursor?
