### ISSUE TITLE
The download file appears to contain a virus

### ISSUE THREAD

**Issue by xslKnight** [teeworlds/teeworlds#1801]
Download the files to the Windows 10 system, and the software housekeeper prompts for a hacker virus。

**Comment by Dune-jr** [comment]
@xslKnight which files did you download, and where?

What software triggered an alert?

I know Avira always detects a Trojan, at least :/

**Comment by xslKnight** [comment]
I download from https://www.teeworlds.com.And the software is Tencent security manager.So don't I know why it shows that.

**Comment by oy** [comment]
There seem to be 2 false positive for the 0.6.5 download. But Tencent reports it's [clean](https://www.virustotal.com/de/file/e825aedd9c47ae9936a19bc1aa75b9cfed8b5d5474ac5aeede9fa5a3247d201e/analysis/1544128704/)

**Comment by xslKnight** [comment]
I'll check back when I have time.Thanks for your reply.

**Comment by xslKnight** [comment]
I'll check back when I have time.Thanks for your reply.

**Comment by xslKnight** [comment]
I'll check back when I have time.Thanks for your reply.

**Comment by xslKnight** [comment]
I'll check back when I have time.Thanks for your reply.

**Comment by Dune-jr** [comment]
@xslKnight Which version did you download? [0.7.1-rc seems fine too](https://www.virustotal.com/de/file/2b10da3f892ced18cb0564e638fee0dd9af0df716d741e20312b1e92fe16f4fc/analysis/)

**Comment by xslKnight** [comment]
It 's not clear to me which version it is.

**Comment by Dune-jr** [comment]
@xslKnight What does the folder/zip say?

teeworlds-0.6.5?  
teeworlds-0.7.1-rc?

**Comment by xslKnight** [comment]
Let me see....  emmmmm It shows that teeworlds-0.6.5-win32.

**Comment by Dune-jr** [comment]
@xslKnight Please try with the last version, 0.7.1-rc:

https://downloads.teeworlds.com/teeworlds-0.7.1-rc-win32.zip

**Comment by xslKnight** [comment]
Okay, I'll download it later

**Comment by xslKnight** [comment]
There is something wrong with the Chinese display of the software. After clicking, you will be completely blank after clicking, and you cannot set back English in the found language.

**Comment by Dune-jr** [comment]
@xslKnight that is strange, what font do you use? (in `data/fonts`) `DejaVuSans.ttf`?
Can you send a screenshot?

**Comment by xslKnight** [comment]
![default](https://user-images.githubusercontent.com/40093942/49732934-1f5be480-fcbb-11e8-9185-8fdd320c8249.png)     And  I found the setting of language at last.But it can't be connetcted which shows 
![default](https://user-images.githubusercontent.com/40093942/49732991-53cfa080-fcbb-11e8-8f50-36fddfcf21e4.png)

**Comment by xslKnight** [comment]
This is the font 
![default](https://user-images.githubusercontent.com/40093942/49733316-1ddeec00-fcbc-11e8-8343-af9209d5b5b9.png)

**Comment by Dune-jr** [comment]
> ![default](https://user-images.githubusercontent.com/40093942/49732934-1f5be480-fcbb-11e8-9185-8fdd320c8249.png) And I found the setting of language at last.

I don't see any problem there.

In order to use Chinese, you need a font that supports Chinese. Put it in `data/fonts/` and choose it with `cl_fontfile` in F1 console :

```
cl_fontfile DejaVuSans.ttf
```

> But it can't be connetcted which shows
> ![default](https://user-images.githubusercontent.com/40093942/49732991-53cfa080-fcbb-11e8-8f50-36fddfcf21e4.png)

This is not related to language. You chose some outdated server. Pick any other server and it should be fine.

> This is the font
> ...

What does `cl_fontfile` in F1 console say, @xslKnight ?

**Comment by Dune-jr** [comment]
> This is the font
> ![default](https://user-images.githubusercontent.com/40093942/49733316-1ddeec00-fcbc-11e8-8343-af9209d5b5b9.png)

Did you change the  `DejaVuSans.ttf` font in `teeworlds.0.7.1-rc-win32/data/fonts`?

**Comment by xslKnight** [comment]
I have installed DejaVuSans.ttf. The console shows "failed to open 'autoexec.cfg'". 

    And which server I should  pick?

**Comment by Dune-jr** [comment]
> I have installed DejaVuSans.ttf.

Even if it is installed on your computer, you **must** change it in `teeworlds.0.7.1-rc-win32/data/fonts`.

> The console shows "failed to open 'autoexec.cfg'".

This is normal, not an error.

> ```
> And which server I should  pick?
> ```

Any, for example look for `Fisico`, this one is up-to-date.

**Comment by xslKnight** [comment]
Okay,I got it.

**Comment by Dune-jr** [comment]
@xslKnight feel free to close the issue when everything works. :)

**Comment by heinrich5991** [comment]
0.6.5 has a known false-positive of Avira. It does not contain a virus to the best of my knowledge, I compiled it on my machine.

**Comment by Dune-jr** [comment]
@heinrich5991 avira also flags 0.7.1 for some it seems (not for me)
