### ISSUE TITLE
Strange behavior where not everyone is notified of a player leaving the game

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1813]
On the following screenshots, only @LordSk was informed that "4: Strayed" left the game. I didn't get any notification.

![image](https://user-images.githubusercontent.com/355114/49687725-6d2feb80-fb07-11e8-8557-7801298a82cb.png)
![image](https://user-images.githubusercontent.com/355114/49687726-6e611880-fb07-11e8-90d9-01272dde4b5d.png)

It has only happened once and I'm not sure what triggered it. Dummies were on the server.

**Comment by oy** [comment]
@Dune-jr Was the player still in the scoreboard for you?

Seems a vital packet didn't get delivered.

**Comment by oy** [comment]
@Dune-jr do you remeber if the team sizes within the scoreboard were correct? Then there's another problem. Otherwise this should be fixed now.

**Comment by Dune-jr** [comment]
I think I checked thoroughly for anything odd at that time, so I think everything was correct, but I can't say for sure, @oy

**Comment by oy** [comment]
Well, we close this for now.
