### ISSUE TITLE
copy last screen x infinity when out of map

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1814]
isnt this fixed since 0.6? how can it be a bug again
![base profile screenshot 2018 12 08 - 17 01 06 02](https://user-images.githubusercontent.com/35420825/49687946-01e81880-fb0b-11e8-8ac0-b73099c1708f.png)

**Comment by Dune-jr** [comment]
Use `gfx_clear 1` is the map has issues.

**Comment by oy** [comment]
Yeah, like @Dune-jr wrote. Use gfx_clear 1 for bad maps.
