### ISSUE TITLE
some weird bugs with team changing

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1817]
may be related to #1813 

so, i tested a bit with Avo and we have some really weird bugs. we dont know how t o reproduce it but we did it 2 times. the bug is, that i am for example in spectators and Avos scoreboard is showing i am in team blue. the other screens show that he is in team blue for me, but in team red for himself.

Avos Screenshot 1 (i am in team red for him, but for me in spectators)
https://cdn.discordapp.com/attachments/521010908198076417/521012807899021345/screenshot_2018-12-08_18-18-36.png

My screenshot 1
https://cdn.discordapp.com/attachments/521010908198076417/521012773564448778/Base_Profile_Screenshot_2018.12.08_-_18.18.36.11.png

Avos screenshot 2 (he is in team red, but for me he is in team blue)
https://cdn.discordapp.com/attachments/521010908198076417/521011313036623893/screenshot_2018-12-08_18-12-48.png

My screenshot 2
https://cdn.discordapp.com/attachments/521010908198076417/521010960585195521/Base_Profile_Screenshot_2018.12.08_-_18.10.32.92.png

**Comment by nheir** [comment]
from server log, fokkonaut screenshots are the expected result
this is on (my) modded server, I will inspect next week
