### ISSUE TITLE
settings dont recognize what background i chose after game restart

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1833]
![base profile screenshot 2018 12 10 - 14 28 05 37](https://user-images.githubusercontent.com/35420825/49735585-ddfe1180-fc87-11e8-85e5-dbffe24a3d30.png)

**Comment by fokkonaut** [comment]
ofc heavens because its selected (but the background is none as i selected it before the restart)

**Comment by Dune-jr** [comment]
Alright, I reproduced it. So apparently, if you set `cl_menu_map ""` then restart, it does not load any map - as it should - but `cl_menu_map` somehow goes back to the default `heavens`. So that's a bug.
