### ISSUE TITLE
hover over settings make hint appear

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1834]
if you hover over a setting (for example Show social) you should see a little pop up window where your mouse is that prints the text that you would see in f1 (usign the example show social, the hint text would be "show social data like names, clans, etc"

**Comment by Dune-jr** [comment]
Remark: hint texts over all settings will generate a large overload of strings to localize.

**Comment by oy** [comment]
True.
But would probably still be good to have some hints. Maybe just use them for settings that aren't that obvious?

**Comment by Robyt3** [comment]
Here is my take on tooltips:

![grafik](https://user-images.githubusercontent.com/23437060/101999148-79447a00-3cda-11eb-8b74-201bf8ca71e8.png)

![grafik](https://user-images.githubusercontent.com/23437060/101999154-82354b80-3cda-11eb-8b5e-ecfc1d84df5c.png)

![grafik](https://user-images.githubusercontent.com/23437060/101999159-8cefe080-3cda-11eb-87a4-8d94b48209b2.png)

![grafik](https://user-images.githubusercontent.com/23437060/101999171-a729be80-3cda-11eb-98c8-3434cf24b08e.png)

![grafik](https://user-images.githubusercontent.com/23437060/101999163-96794880-3cda-11eb-8f28-c163078c9283.png)

![grafik](https://user-images.githubusercontent.com/23437060/101999175-b14bbd00-3cda-11eb-872d-ba022f99324f.png)

Anythings else specifically that should have a tooltip?

**Comment by oy** [comment]
@Robyt3 looks good 👍 
The `+-` for gametypes in the server filter could need a tooltip too.
