### ISSUE TITLE
settings menu -> selected option

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1835]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35420825/49736031-4a2d4500-fc89-11e8-97c6-9fe8fe864abc.gif)

as you can see here, if my mouse is in the left menu (language) the current language is selected, when i move to the right site (theme) the current theme is selected and the language is un-selected. but when i am not in any of those two menus, the last selected setting stays selected and wont get unselected.

**Comment by sepulzera** [comment]
See also #1771 for the general discussion about UI item hovering.
