### ISSUE TITLE
Ease up compilation by providing a working respository/folder of other/sdl & other/freetype

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1842]
Right now, figuring which libraries to install, under what folder architecture, especially on Windows, is a mess. The majority of the problems I get asked support for are just that. Where to get the libs? Which version? Why doesn't it find them, what should the folder names be?

And with people trying to port things to 0.7, this will go on.

Could we improve this by providing an official zip, folder, or git repository (submodules?) of working SDL/freetype libraries? (SDL 2.0.8, is it?)

Related: #1347

**Comment by Dune-jr** [comment]
Any suggestion on the medium to use, @oy?

> provide an official zip, folder, or git repository (submodules?) of working SDL/freetype libraries (SDL 2.0.8, is it?)

**Comment by LordSk** [comment]
How about another repository "teeworlds-dependencies" with binaries for each target we support. I've seen it done before.

**Comment by oy** [comment]
Fixed.
