### ISSUE TITLE
The 0.7 server popup is too small for the text

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1843]
![image](https://user-images.githubusercontent.com/355114/49834088-d62f9180-fd9b-11e8-81b7-2747bdd292a6.png)

**Comment by sepulzera** [comment]
Imo we could remove the hash info. It is way too technical for the common user.
*Wrong version. Server is running '0.7' and client '0.7 DDNet'.*

The mods developer should be responsible to set the version string properly, if compatibility breaks.

**Comment by Dune-jr** [comment]
1. It's a problem with other messages, not just hash
2. Mods shouldn't put info in their hash, that's not what it's for. It's to check for protocol incompatibilities and prevent very strange behaviors.

**Comment by sepulzera** [comment]
1. For instance?
2. You can check for protocol compatibility without displaying "random" numbers to the end user ;-)
They are of no value except for devs.

**Comment by Dune-jr** [comment]
> 1. For instance?

I suspect if the popup window doesn't act nice with this message, it won't act nice with others. I vaguely remember this problem, but I don't have an instance to show off.

> 2. You can check for protocol compatibility without displaying "random" numbers to the end user ;-)
>    They are of no value except for devs.

Ah, so you meant changing the error message, I thought you meant scrapping the feature.

I guess it could say something like `Protocols mismatch, server version incompatible.` But having the hashes be displayed is *very* helpful to troubleshoot problems when those screenshots appear in support, so I don't think I like removing the hashes too much.

**Comment by nheir** [comment]
Let the full message in console then.

There is space in the dialog box, so for any other message that does not fit, it should break into two lines.
