### ISSUE TITLE
Linux x86 cross-compilation fails because of _mm_pause call

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1844]
*Credits to @heinrich5991 and @LordSk for quickly troubleshooting this issue.*

So compiling with `arch=x86` fails on current master:

```
[1/2] [1] c++ src/engine/client/client.cpp
In file included from /usr/lib/gcc/i586-linux-gnu/4.9/include/immintrin.h:29:0,
                 from src/engine/client/client.cpp:5:
/usr/lib/gcc/i586-linux-gnu/4.9/include/xmmintrin.h: In member function 'bool CClient::LimitFps()':
/usr/lib/gcc/i586-linux-gnu/4.9/include/xmmintrin.h:1238:1: error: inlining failed in call to always_inline 'void _mm_pause()': target specific option mismatch
 _mm_pause (void)
 ^
src/engine/client/client.cpp:1779:15: error: called from here
    _mm_pause();
               ^
```

This is what intel tells us about `_mm_pause`: https://software.intel.com/en-us/node/524249

A simple fix to this is to add the option `-msse2` in bam for x86 architectures.

**Edit:** I also had to hardcode the path to freetype for some reason

**Comment by heinrich5991** [comment]
Note that this will still fail to compile for architectures other than Intel (and AMD) ones. The code in question is quite unportable:

https://github.com/teeworlds/teeworlds/blob/dff453d377e56a1389ca4313767b4f05f61b7985/src/engine/client/client.cpp#L5

https://github.com/teeworlds/teeworlds/blob/dff453d377e56a1389ca4313767b4f05f61b7985/src/engine/client/client.cpp#L1779

I suggest to remove it until a portable solution is found. Teeworlds code (especially outside src/base/system.c) should not rely on such compiler- and architecture-specific functions without fallback.

**Comment by heinrich5991** [comment]
@LordSk ^
