### ISSUE TITLE
Commented out safeguard code in make_release.py

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1845]
https://github.com/teeworlds/teeworlds/blob/44ae120706273ccd68987a0cc1a41b8c78b6bc84/scripts/make_release.py#L35-L38

Why was this code commented out? Starting `make_release.py` with the wrong architecture (x86 instead of linux_x86, in my case) silently defaults to x64, and is dangerously error-prone

**Comment by oy** [comment]
No idea why it has been commented out. But has been done 11 years ago f7ea0b2ba8851e4c0ceaef0a8b2361adfc218443

**Comment by Dune-jr** [comment]
@heinrich5991 might know
