### ISSUE TITLE
Discussion: Add Feature to show past Chat (Scrollbar)

### ISSUE THREAD

**Issue by themisak** [teeworlds/teeworlds#1849]
Hey Guys,

I wanted to start a discussion weather it would be a good idea to add a Scrollbar in the Chat so that you can see the past chat more easily. LordSk had the Idea give all the Credits to him!

Maybe it could be also possible to scroll trough the chat when pressing u + mousewheelscroll for faster scrolling

Hope you like the Idea,
Cheers

**Comment by Dune-jr** [comment]
There is already a discussion about that in https://github.com/teeworlds/teeworlds/issues/1828

I would like to see a scrollbar or a page system too. But best to keep the discussion there. :)

**Comment by themisak** [comment]
Well but in #1828 its about a scrollbar in the scoreboard.

But I am talking about a scrollbar in the Chat so you can see what people before wrote and you dont always have to press f1 to see it

**Comment by lryjnks** [comment]
Yes that would be really a good function apart from F1

**Comment by themisak** [comment]
It would make it much easier to read the chat of the past

**Comment by Dune-jr** [comment]
Closed by https://github.com/teeworlds/teeworlds/pull/2195
