### ISSUE TITLE
Discussion: Add Feature to send copied links in Chat

### ISSUE THREAD

**Issue by lukasfaik** [teeworlds/teeworlds#1850]
Hey Guys,

Discussion to add the possibility to send links via Teeworlds.

Cheers

**Comment by Dune-jr** [comment]
So just copy/paste? Issue #12

**Comment by themisak** [comment]
and maybe that you can click it or open it that it opens in a webbrowser ?

**Comment by oy** [comment]
Don't think that tw should open any third-party tools.
