### ISSUE TITLE
Text input improvements (part 1 of 2)

### ISSUE THREAD

**Issue by 1stDecadeTW** [teeworlds/teeworlds#1851]
Part 1 of 2: selecting, copying,pasting and moving in text.

Let's improve the text input adding these chat features: 
+ Move between words: ctrl + left/right arrow.
+ Select text letter by letter, it increases the speed of selection with time: shift + left/right arrow.
+ Select text line by line (horizontally): shift + home/end.
+ Select text line by line (vertically): shift + up/down arrow.
+ Copy and paste: ctrl + c/v.

**Comment by Dune-jr** [comment]
> Move between words: ctrl + left/right arrow.

Already done: #1825

> Copy and paste: ctrl + c/v.

This is https://github.com/teeworlds/teeworlds/issues/12


> - Select text letter by letter, it increases the speed of selection with time: shift + left/right arrow.
> - Select text line by line (horizontally): shift + home/end.
> - Select text line by line (vertically): shift + up/down arrow.

Doesn't sound too intuitive to me :/

**Comment by 1stDecadeTW** [comment]
When I press ctrl + arrows in chat, it does nothing :\

**Comment by Zwelf** [comment]
I have some commits implementing clipboard functionality in my repository. I can rebase them again after finishing #1825.

Here are the commits adding the clipboard to CInput
Zwelf/teeworlds@8fbd8a9d4f651ddfd1c63afe32fd29f06b2c2026
Zwelf/teeworlds@b8a8a955cf1a58bad106ed6cb2f47d91e75d12c6
Zwelf/teeworlds@251c7039dd06a98e1fe152bc2ca0ddd710e78cc5

**Comment by Dune-jr** [comment]
Got plans to rebase those and fix #12 now that #1825 is merged, @Zwelf ?

**Comment by oy** [comment]
Maybe do one at a time ;)
