### ISSUE TITLE
Whisper target selection is not intuitive and not consistent (Ctrl-Tab does not work for highlights)

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1852]
People are struggling with the whispers, I'm not sure what could be done though.

It doesn't matter as much for highlights because you can type the beginning of the name of the player and get it on the first try or two.

Maybe there should be a way to type the beginning of a player's name, somehow.

**Comment by 1stDecadeTW** [comment]
Whipers could follow this behavior:
- "X" opens the whisper chat (already done).
- "Backspace" erases the selected name in whisper
- Then you can type the initials of the player you want to send a whisper, and press Tab to select that player name (this is the same behavior as the "All" chat).
