### ISSUE TITLE
Show Skilllevel Ingame

### ISSUE THREAD

**Issue by themisak** [teeworlds/teeworlds#1854]
With the New Skilllevel Tags for Servers in the Server List it should also get shown Ingame in the Server info Box. Please Add it There too so everything is clean.

![screenshot_2018-12-13_12-47-59](https://user-images.githubusercontent.com/44925034/49936854-5a396480-fed5-11e8-817e-138a630f73ce.png)

**Comment by Dune-jr** [comment]
Agree. We'll need to eat up a line from the MOTD, though.

**Comment by fokkonaut** [comment]
no, place it on the right side. thats even better because it fits Game Info.

**Comment by themisak** [comment]
I would also fit it on the right side, maybe under Players
