### ISSUE TITLE
Make the scroll smooth + resize the scroll bar size according to the content.

### ISSUE THREAD

**Issue by Ryozuki** [teeworlds/teeworlds#1857]
On some menus, you can shrink some submenus to the point where scrolling makes no sense, but the scroll bar is still shown small and you can scroll to move it,  but it does nothing obviusly.

I would also make the scrolling "smooth", just like you scroll in your browser.

**Comment by AssassinTee** [comment]
Can you show an example of this? The Scrolling is very smooth if you use the mouse instead of the mouse-wheel. I can't find any instance, where the scroll "is shown small". Only instances, where the content is small enough, that the scroll bar itself makes no sense

**Comment by oy** [comment]
@AssassinTee check out settings->control, it uses the new scrollbar system.

**Comment by Dune-jr** [comment]
So this is just about generalizing @LordSk's scrollback API to regions that do not use it?

**Comment by oy** [comment]
Yeah.
