### ISSUE TITLE
Ammo pickup

### ISSUE THREAD

**Issue by sepulzera** [teeworlds/teeworlds#1858]
For some more complex gameplay on maps, I would like to be able to place weapon ammo only.
This gives the ability to place fewer weapons but not reducing the usable ammo overall, creating more and stronger points of interests.

Eventually, this could be reused for #1069

**Comment by fokkonaut** [comment]
you can code it for your own. i dont think this is needed for vanilla

**Comment by themisak** [comment]
I also like it !

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
