### ISSUE TITLE
macOS shows char suggestions when pressing A longer

### ISSUE THREAD

**Issue by tyurderi** [teeworlds/teeworlds#1860]
@oy as I mentioned in the chat the suggestions shows up while playing and pressing A too long. Actually I mean this:

![bildschirmfoto 2018-12-13 um 22 51 24](https://user-images.githubusercontent.com/9164292/49969771-ae6e3400-ff29-11e8-841f-247989645add.png)

In Teeworlds it is shown in the top-left corner of the game. It is not interrupting the gameplay at all but is still a visible bug.

I've been using the latest version of Teeworlds (0.7.1) and macOS 10.13.6.

P.S.: I love to see that teeworlds continues ❤️

**Comment by ChillerDragon** [comment]
I thought I made this issue already lul. Seems like I only flamed on irc xd. I noticed this annoying bug on all newer apple computers.

P.S.: Hi @tyurderi

**Comment by oy** [comment]
Hm, tested on 10.13.6 with this version https://github.com/teeworlds/teeworlds/releases/download/0.7.1/teeworlds-0.7.1-osx.dmg and couldn't produce it. Did you use that one?

**Comment by tyurderi** [comment]
@oy Yes I can reproduce the same behavior also on my newer MacBook with macOS 10.14.1

**Comment by ChillerDragon** [comment]
Pasting this in terminal probably solves it:
```
defaults write -g ApplePressAndHoldEnabled -bool false
```

**Comment by Robyt3** [comment]
Can someone with Mac test with the changes in [pygame PR 1367](https://github.com/pygame/pygame/pull/1367/files)?

The fix seems to be to remove the delegate application:
```
sdlMain = [[SDLMain alloc] init];
[[NSApplication sharedApplication] setDelegate:sdlMain];
```

**Comment by Dune-jr** [comment]
cc @ChillerDragon @jxsl13

**Comment by ChillerDragon** [comment]
I can not reproduce the bug on my system so I do not know if it solved it.
I applied this diff (not sure if it is correct) and compiled it in case anyone else wants to test it:

```
diff --git a/src/osxlaunch/client.m b/src/osxlaunch/client.m
index 8bdfb74..9d757ec 100644
--- a/src/osxlaunch/client.m
+++ b/src/osxlaunch/client.m
@@ -190,7 +190,6 @@ static void setupWindowMenu(void)
 static void CustomApplicationMain (int argc, char **argv)
 {
        NSAutoreleasePool       *pool = [[NSAutoreleasePool alloc] init];
-       SDLMain                         *sdlMain;
 
        /* Ensure the application object is initialised */
        [SDLApplication sharedApplication];
@@ -211,14 +210,9 @@ static void CustomApplicationMain (int argc, char **argv)
        setApplicationMenu();
        setupWindowMenu();
 
-       /* Create SDLMain and make it the app delegate */
-       sdlMain = [[SDLMain alloc] init];
-       [[NSApplication sharedApplication] setDelegate:sdlMain];
-
        /* Start the main event loop */
        [NSApp run];
 
-       [sdlMain release];
        [pool release];
 }
```

[teeworlds-noSDLMAIN.zip](https://github.com/teeworlds/teeworlds/files/4078269/teeworlds-noSDLMAIN.zip)

**Comment by oy** [comment]
Will try.

**Comment by Learath2** [comment]
Actually getting the accent menu to work properly will be quite a problem. We could maybe be able to render a fake NSTextView over the text inputs, I've seen a Minecraft plugin do the same.
