### ISSUE TITLE
Option to swap chatsounds

### ISSUE THREAD

**Issue by lryjnks** [teeworlds/teeworlds#1862]
The function to change the chat sound via the settings would be cool.

Like DDNet

**Comment by fokkonaut** [comment]
ddnet doesnt have that, but you can swap the sound files in data/audio for msg-client and msg-highlight

**Comment by Dune-jr** [comment]
Specifically:
```
datasrc/audio/sfx_msg-client.wv
datasrc/audio/sfx_msg-highlight.wv
```
