### ISSUE TITLE
Compiling on mac with SDL2

### ISSUE THREAD

**Issue by tyurderi** [teeworlds/teeworlds#1863]
Yet this issue is only a suggestion to extend the actual tutorial for compiling teeworlds on macOS.

It says:
>Download libsdl from the http://libsdl.org and put SDL.framework in /Library/Frameworks

But this step is not enough. You should add that (if you are using homebrew) that you can install the other sdl requirements using `brew install sdl2` and also tell that SDL2 is required for teeworlds.

**Comment by Dune-jr** [comment]
The relevant github for this is actually https://github.com/teeworlds/documentation. The teeworlds.com documentation is generated from this git repository. (not immediately obvious, I know)

Please move your issue there, or even better, PR your suggested changes :)

**Comment by tyurderi** [comment]
Oh, didn't see. Will do :)

**Comment by tyurderi** [comment]
See https://github.com/teeworlds/documentation/issues/16.
