### ISSUE TITLE
Server becomes invalid when setting sv_player_slots lower than the number of players

### ISSUE THREAD

**Issue by nheir** [teeworlds/teeworlds#1865]
Solutions:
 - Send players to spectators
 - Don't drop these servers (when max_players < num_players)
 - Make the server send the max between sv_player_slots and num_players
 - Wait for reload/restart to update serverinfo
 - Don't drop server with more players than max_player

**Comment by LordSk** [comment]
I vote for the 3rd option, seems like the less disruptive one.

**Comment by sepulzera** [comment]
>3rd option is fake.
>>You can interpret it as only lowering the player slots once people join the spectators/leave the game. It's probably the most useful variant (and retaining current behavior) if you e.g. put this player slots stuff into the votes.

I still don't understand the use case. If I lower the ingame slots, I do so to play f. e. 2on2. Why would you keep the other 12 players then? You need to move all of them manually to spectators then.

Anyway, personally I think we shouldn't send fake data at all. And imo this would be.

**Comment by Dune-jr** [comment]
Yeah, but you want to move a select few to the spectators. Usually it goes like that:

1. Set 4 player slots
2. Ask people to move/Force move them to specs

In the interval, we get 12/4, which is an issue. You can simply consider that `sv_player_slots 4` does not allow any player to join in if there are ≥ 4 players in-game. Nothing fake there.

**Comment by nheir** [comment]
I forgot one solution : 
 - make this option to need a reload/restart

**Comment by oy** [comment]
Might be best to update with reload command - similar to gametype.

**Comment by Dune-jr** [comment]
I am not sure it is the best way, a lot of times clanwars happen with a vote to set a max of players.

A reload shuffles (afk, namely) specs and players, it is quite bad.
Sorry for reacting late

**Comment by nheir** [comment]
another solution
 - don't drop server with more players than max_player

**Comment by nheir** [comment]
ok, this is not even an issue… everything was fine from the beginning, sorry
