### ISSUE TITLE
Sorting by players always takes bots in account

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1867]
![screenshot_2018-12-15_01-28-23](https://user-images.githubusercontent.com/355114/50036361-b8b32f80-0008-11e9-9755-20caa2d76d67.png)

**Comment by nheir** [comment]
Should the game hide also bot spectators whatever the spectator filter ?

https://github.com/teeworlds/teeworlds/blob/d1bf48f42cbf512428c311bb7c06b7ed7be5b034/src/game/client/components/menus_browser.cpp#L519-L529

**Comment by Dune-jr** [comment]
That looks like a bug.

**Comment by oy** [comment]
@nheir 
That's what it does.
https://github.com/teeworlds/teeworlds/blob/d1bf48f42cbf512428c311bb7c06b7ed7be5b034/src/game/client/components/menus_browser.cpp#L511 initial value.

Fixed by #1868
