### ISSUE TITLE
Stuck on Connecting to Server

### ISSUE THREAD

**Issue by duralakun** [teeworlds/teeworlds#1869]
I downloaded and compiled version 0.6.5 on Ubuntu 16.04
Often when i try to join a server my client gets stuck on "Connecting to {server ip}"
I close it and reopen it and I still cant connect.
I tried to connect to many different servers, vanilla and none vanilla, which work and which don't seem to be random.

I then downloaded and compiled version 0.6.2
With this version the problem appears much less often.
Also when it appears it seems to cancel the connection on its own after 10 sec or so.

I would use version 0.7 but it only shows very few servers. Is it not compatible with older versions?

**Comment by oy** [comment]
Yeah, 0.7 isn't compatible with 0.6 and 0.6 will just get crucial security fixes.
