### ISSUE TITLE
Failure to open configs in absolute paths since 0.7, reportedly

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1872]
```
[5c142019][console]: failed to open '/home/teeworlds/twservermanager07/teeworlds/s1.conf'
```

Someone reported this error when upgrading from 0.6 to 0.7. I made sure with him that the file was indeed at that path. The permissions are correct too:
```
-rwxrwxrwx 1 teeworlds teeworlds 50 Dec 14 22:19 /home/teeworlds/twservermanager07/teeworlds/s1.conf
```
Local paths and autoexec.cfg still work.

**Comment by ChillerDragon** [comment]
How do you load that config? I remember that DDNet decided to only allowed relative paths from specific starting points to fix security vulnerabilitys comming with the ``exec`` command. Because ingame admins could read text files even if they are not teeworlds configs.

**Comment by Dune-jr** [comment]
With `teeworlds_srv.exe -f path/to/config`

**Comment by oy** [comment]
Yeah, you can't use absolute paths. Just relative paths starting from the ones you specify in storage.cfg. So we prevent that someone pulls some shenanigan.

**Comment by Dune-jr** [comment]
So that's a feature. Then either do nothing and close the issue, or print some sort of error message on how we don't allow absolute paths.

**Comment by Dune-jr** [comment]
Thanks!
