### ISSUE TITLE
Add ui_mousesens as an UI option

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1874]
>>would be useful the possibility to adjust mouse sensitivity also for navigation into menus
>>this is very important to improve the usability and precision of the editor
>
> There's "inp_mousesens" to adjust the ingame mouse sensitivity and there's ui_mousesens for the menus.
> Should probably add an ui-option for it to the settings.

__@oy in https://www.teeworlds.com/forum/viewtopic.php?pid=122161#p122161__

**Comment by fokkonaut** [comment]
ddnet has that one.

**Comment by savander** [comment]
UI Mousesens in General/Client ? Or different place?
![screenshot_2019-01-03_02-50-34](https://user-images.githubusercontent.com/2012010/50620845-69bf3280-0f02-11e9-87a8-ed87585ad60c.png)

**Comment by Sonix-** [comment]
Should be where the other mousesens is

**Comment by Dune-jr** [comment]
Yeah. No room in general

**Comment by savander** [comment]
Then here. 
![screenshot_2019-01-03_14-53-14](https://user-images.githubusercontent.com/2012010/50641264-acffbc80-0f67-11e9-9d37-22c453589896.png)

**Comment by 1stDecadeTW** [comment]
Why don't you name it "Ingame mouse sense" and "UI mouse sense" ?

**Comment by savander** [comment]
Mouse sens. is current naming. I didn't change anything, just added UI Mouse sens. setting

**Comment by Dune-jr** [comment]
I would like something like that, at least for the UI movement speed. Get a  `[  ] Use custom sensitivity` thing going.

![image](https://user-images.githubusercontent.com/355114/50686090-37a1f380-101c-11e9-961f-cee7886b8b38.png)![image](https://user-images.githubusercontent.com/355114/50686093-3a044d80-101c-11e9-840c-642556dbef20.png)

**Comment by savander** [comment]
I think, in that case we have to introduce new config option? For example. `ui_enable_mousesens`

**Comment by oy** [comment]
Should probably call one "Ingame mouse sens" and the other "Menu or General mouse sens".
