### ISSUE TITLE
Please update wavpack copy to something modern

### ISSUE THREAD

**Issue by ignatenkobrain** [teeworlds/teeworlds#1875]
The last release was somewhere in 2017, which is 13 years later than the bundled copy.

**Comment by heinrich5991** [comment]
Why?

Does it contain security vulnerabilities? (Note that not even that really matters, we only give it trusted input.)

We use the tiny decoder from http://wavpack.com/downloads.html, I don't think it has a newer version. The CMake pull request (#1730) will make the Linux version use wavpack from the environment if it is available.

**Comment by oy** [comment]
Seems fixed.
