### ISSUE TITLE
[cmake] [0.7.1] Can't join any servers

### ISSUE THREAD

**Issue by ignatenkobrain** [teeworlds/teeworlds#1881]
I'm teeworlds maintainer in Fedora and I'm trying to package new 0.7.1 version, however I can't join any servers..

Any help is highly appreciated!

![screenshot from 2018-12-15 18-11-53](https://user-images.githubusercontent.com/2866862/50045540-0ecdb480-0095-11e9-85a1-05b514faa02f.png)

**Comment by Dune-jr** [comment]
Thanks for the quick packaging! Much appreciated. 

I have already seen this issue. Are you attempting to build with cmake, by any chance?

What is the best way to notify Fedora devs of a new stable version, by the way? I have been trying to reach out

**Comment by ignatenkobrain** [comment]
@Dune-jr yes, I'm trying to use cmake because I got tired of trying to fix bam ;)

Either send me an email or open a bug on bugzilla.redhat.com.

**Comment by ignatenkobrain** [comment]
https://github.com/teeworlds/teeworlds/pull/1730/files#r241955701

**Comment by Dune-jr** [comment]
Ah, I was on my phone and didn't see you commented there too.
If I remember correctly (I may not), another problem is this change: https://github.com/teeworlds/teeworlds/pull/1730/files#diff-6ce9ff7f9c9df1f80523077b149b7e9aL9 that may (wrongly) affect the hash

**Comment by oy** [comment]
Should work with the merged cmake stuff.
