### ISSUE TITLE
Build fails to build on non-x86 (because of immintrin.h)

### ISSUE THREAD

**Issue by ignatenkobrain** [teeworlds/teeworlds#1882]
```cpp
../src/engine/client/client.cpp:5:10: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h> //_mm_pause
          ^~~~~~~~~~~~~
```

**Comment by Dune-jr** [comment]
The fix was not ported to CMake, I believe.
On 64bit, you can simply comment ou the #include.
If it doesn't work, can you try to add the compilation flag `-msse2`? It should fix it afaik.

#1844

**Comment by ignatenkobrain** [comment]
@Dune-jr I don't think that `-msse2` will work on ppc64le or s390x or arm, because it is x86-specific.

**Comment by Dune-jr** [comment]
Right.
Since you're on 64-bit, it should simply work without ` #include <immintrin.h>`

**Comment by ignatenkobrain** [comment]
@Dune-jr there is also 32bit arm ;)
