### ISSUE TITLE
Round Score Reset

### ISSUE THREAD

**Issue by msiglreith** [teeworlds/teeworlds#1885]
A reset issue which has been reported a few times but I couldn't find an issue so far.
I assume both played on a 0.7.1 server.

> Captain AMN: scores and kills don't match after round re-start through voting for example

> Jambi: Using restart with a timer will restart the match but doesn't reset the scores.

**Comment by sepulzera** [comment]
I can confirm this bug. Did a restart via rcon but the team scores didn't get reset. (Iirc the player scores did)
