### ISSUE TITLE
When the whisper target leaves, the message is still sent

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1889]
It shows an empty target name. Here I was PMing LordSk:

![image](https://user-images.githubusercontent.com/355114/50058817-259c0600-017e-11e9-934d-87e7581f92ae.png)

**Comment by oy** [comment]
Would probably best to close the chat dialog, when the person leaves?

**Comment by Dune-jr** [comment]
You're right, @oy
