### ISSUE TITLE
Design Diskussion: about Assists in the Scoreboard for kill supports

### ISSUE THREAD

**Issue by themisak** [teeworlds/teeworlds#1900]
Hey Guys,

In Vanilla gameplay sometimes someone does 95% of the Damage and another Person makes the kill and gets a kill score in the scoreboard but the guy who actually made most of the Damage stays unmentioned and gets nothing!

I think it would be Great to Add assists for kills in the Scoreboard. So if someone makes 95% of the damage or at least helps for a kill he should get a reward in form of an assist in the scoreboard.
(Like other games like league of legends have it too)

What do you guys think about it?

Kind regards

**Comment by Fisico** [comment]
Great idea. 
But how should assist be counted? Only stats, or + 0.5 points to score? Thinking of deadmatch to 20 for example. 
If you do more than 50% damage you should get an assist point. Also if you shoot a player of the cliff.

**Comment by sepulzera** [comment]
50 % overall? Or should it be time based? 50 % of the health he had 3 seconds before? Will the "50 % threshold" be reset when the player picks health up? Will it be reset when the player gains full health? ...

**Comment by Dune-jr** [comment]
I don't think score matters that much that an obscure assist system would be worthwhile

**Comment by fokkonaut** [comment]
Its called kill stealing.

**Comment by Zatline** [comment]
I think assists should be rewared in some way or another there are games like Battlefield that even count some assists as a kill which in my opinion is kinda fair and quite a modern thing to do.
I'm not saying tw should start counting assists as kills no no no but reward in terms of score would deffinetly help it up. The scoresystem needs some revamp anyway there where plans in 2013 have to go trough some folders find that .txt file ..

**Comment by 1stDecadeTW** [comment]
I agree with @Zatline 👍

**Comment by themisak** [comment]
I also agree with Zatline!

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
