### ISSUE TITLE
cant read first line of autoexec (probably other files too?)

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1901]
put for example sv_name "cool server" in first line and the server will be unnamed server as it cant read the first line.

**Comment by ChillerDragon** [comment]
Haha i thought it is only me (idk why xd). I always put some documentation comment in the first line to bypass the bug. But i think it is an windows only bug.

**Comment by sepulzera** [comment]
> But i think it is an windows only bug. *- ChillerDragon*

I can confirm that this is working for 0.7.1 on Linux x86_64.

**Comment by fokkonaut** [comment]
i always put a `#` in the first line

**Comment by oy** [comment]
Can't reproduce. Works on Windows with 32Bit, 64Bit, release and debug version.

**Comment by fokkonaut** [comment]
i guess that too

**Comment by sepulzera** [comment]
@fokkonaut Maybe you could provide your file, then we can investigate further?

**Comment by fokkonaut** [comment]
no, it was the line endings. i created a new file and it works

**Comment by sepulzera** [comment]
BOM or charset?

**Comment by oy** [comment]
Was probably the utf8 BOM.

**Comment by ChillerDragon** [comment]
@fokkonaut ![wisdome of the aancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png )
pls don't close the issue because YOU know the answer -.-
I think I created a regular textfile in windows and changed the .txt to .cfg by renaming it and I don't know any better way.

**Comment by fokkonaut** [comment]
file->save as->change ending to .cfg

**Comment by sepulzera** [comment]
@ChillerDragon Thanks for the nice xkcd-image. Btw you could provide a file as well.
@oy If it really is the BOM, then we actually should try to fix it. As the config params are all ascii, detecting+ignoring the BOM shouldn't be difficult.
