### ISSUE TITLE
Colored icons look really good in the server browser too

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1903]
4k screenshot:

![screenshot_2018-12-18_14-59-01](https://user-images.githubusercontent.com/355114/50158933-acafc200-02d5-11e9-9e31-8b077e5d5745.png)

**Comment by LordSk** [comment]
This looks much better than the black and white versions we have right now.

**Comment by themisak** [comment]
Yes I also think its much better !

**Comment by sepulzera** [comment]
I love colors. :heart: 
And with the colored difficulty on the left and ping on the right, it doesn't look imbalanced, too.

**Comment by Dune-jr** [comment]
Only changing the selected line to colorful would be a minor change.
I think this server browser looks much better than the white one. It's not only about the black icons looking poor, it's about the overall look, @Zatline.
The level difficulty icons were difficult to distinguish - that's gone, the slight colors change works wonderfully.

**Comment by 1stDecadeTW** [comment]
Colorful gametypes / difficulty icons look much better and they are pretty distinguishable.

**Comment by 1stDecadeTW** [comment]
I prefer the original idea, to always keep gametypes and level icons colorful... The main reason of the icons is to distinguish between gametypes, and the mouse hover effect doesn't contribute to that purpose.

**Comment by themisak** [comment]
I also think the original idea is better

**Comment by oy** [comment]
Could remove the not longer needed greyscale parts now.

**Comment by oy** [comment]
@Dune-jr no, they're just a client thing.

**Comment by Dune-jr** [comment]
> @Dune-jr no, they're just a client thing.

I mean, with whatever icons would have been made for 0.7.1. You would have to crop them again, correct?

**Comment by oy** [comment]
No, could make it support both types - old (3 parts) and new (just 1 part).
