### ISSUE TITLE
Compilation fails with irregular filenames with bam

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1905]
I'm still not sure if it's on bam's side or on the Teeworlds configuration side:
```
[1/3] [3] copy datasrc/ui/gametypes/ictf).png -> build/x86_64/debug/data/ui/gametypes/ictf).png
[2/3] [1] copy datasrc/ui/gametypes/idm).png -> build/x86_64/debug/data/ui/gametypes/idm).png
[3/3] [6] copy datasrc/ui/gametypes/itdm).png -> build/x86_64/debug/data/ui/gametypes/itdm).png
sh: 1: sh: 1: Syntax error: ")" unexpectedSyntax error: ")" unexpected

sh: 1: Syntax error: ")" unexpected
bam: 'copy datasrc/ui/gametypes/itdm).png -> build/x86_64/debug/data/ui/gametypes/itdm).png' error 512
bam: 'copy datasrc/ui/gametypes/idm).png -> build/x86_64/debug/data/ui/gametypes/idm).png' error 512
bam: 'copy datasrc/ui/gametypes/ictf).png -> build/x86_64/debug/data/ui/gametypes/ictf).png' error 512
bam: error: a build step failed
```

**Comment by nheir** [comment]
what are ictf/idm/itdm ? and why is this only trigger for these specific files ?

**Comment by Dune-jr** [comment]
Those are custom gametype icons. As far as I know, "ictf).png" is a file name valid on any OS, but the Teeworlds build system fails to copy them.

It's a bit of an edge case but it looks like there is a poorly written copy function somewhere in the build script, so I think it is relevant to this repository.

**Comment by oy** [comment]
Works on windows.

**Comment by Dune-jr** [comment]
So @Oy found the problem: https://github.com/matricks/bam/blob/master/src/tools.lua#L350


https://github.com/Dune-jr/bam/commit/4d01a7718787e44c79fe503d415e100db38331dd fixes it
