### ISSUE TITLE
Add instagib game mode

### ISSUE THREAD

**Issue by sepulzera** [teeworlds/teeworlds#1907]
I introduced Teeworlds to two friends of mine. We enjoyed playing Instagib for the beginning very much. They struggled enough with the very unique movement of Teeworlds. Just shooting the laser with insta kill gave them a fun time, while improving their movement. 

On the other hand, they didn't enjoy Vanilla at all. Learning the movement AND all the weapons was too much at once. They ended getting killed all the time, with no chance on their own.

Imo, we should consider to add Instagib as Vanilla gametype. Eventually, we should even suggest Instagib for the first games.

What do you think?

**Comment by lryjnks** [comment]
I see it the same way! 
Just like DDrace it should also become a standard gametype in my opinion.

**Comment by themisak** [comment]
We have had this discussion for years now. The Community wants the "main" Gametypes as vanilla but the devs don't want it.

I am 100% your opinion @sepulzera and @lryjnks . Instagib is very friendly to new players and was by far one of the most popular gametypes of Teeworlds.

The Gametypes wich were realy big in Teeworlds should become Vanilla (Race, DDRace and Instagib). But due to the devs it will never happen I guess. These Big Gametypes made Teeworlds Big Back in the Time and are what the community seems to want.

**Comment by Dune-jr** [comment]
Let's say it becomes part of the standard gametypes. What benefits does that bring to instagib? It's not like it needs any client side feature to work properly.

**Comment by lryjnks** [comment]
@Dune-jr  Don't get me wrong, but with many people it is the case that they simply go to a server before they play around with the "filter". I was astonished how many servers Teeworlds has after removing the check mark "Standard Gametype".

And as @sepulzera  already mentioned it is much easier for new players to play Instagib than Vanilla.

We are not looking for benefits for Instagib, but want to make it easier for new players to get started. 

Don't you find it frustrating when you play a new game and hardly try to get a kill? In my opinion an "Oneshot Kill" mod makes more sense to motivate the players.

**Comment by sepulzera** [comment]
I see more benefits than that, in addition to have a way smoother start with Teeworlds.
- Instagib will be on Teeworlds Tab together with as Standard Gametype, making it easier to find at the start
- Better integration into quickstart, #1051
- Instagib will be playable with all mods without the need to merge it (for now, you can't add 2 mods at once)
- You can alter the UI client-sided, f. e. remove the health UI (irrelevant for Instagib)
- I am sure we will come up with many more great ideas, like LordSk's shield

I wouldn't suggest to integrate every popular mod as standard gametype. But there are too many good arguments for Instagib to ignore it, imho.

**Comment by themisak** [comment]
I think I head that there are plans to make race an offical gametype too though. What was the argument to make race offical and not instagib? I would love to see both as standart gametypes.

BUT: When making instagib a vanilla mod there should be the old ctf4 map brought back as standart map too!!!

**Comment by Zatline** [comment]
I think people making a point here, like @lryjnks says ..
>We are not looking for benefits for Instagib, but want to make it easier for new players to get started.

I may support the idea but only if we end up with Lord's version.

**Comment by Zatline** [comment]
@themisak in my opinion Lord's version of Instagib already is the superior version, it has all that old insta lacked, only thing I would change is to cancel the initial wall bounces when laser explodes on ground.

**Comment by oy** [comment]
Weapon management and diversity is part of teeworlds gameplay and should be kept throughout official gametypes. Further more gameplay behaviour should be consistent:
 - laser does 5 damage and doesn't instantly kill you
 - the laser ammo doesn't auto refill

**Comment by lryjnks** [comment]
> * laser does 5 damage and doesn't instantly kill you

That's why we want to add the iCTF mod as the default gametype.

again:

Vanilla is too heavy for newbies. We should offer a simpler mod for newbies where they can get their first successes. (kills)

**Comment by sepulzera** [comment]
> Further more gameplay behaviour should be consistent:
>*  laser does 5 damage and doesn't instantly kill you
>*  the laser ammo doesn't auto refill

Just make the rifle red and call it instagib-rifle then :roll_eyes:.

**Comment by Dune-jr** [comment]
I still don't see any way in which instagib would benefit from being official, apart from getting more of the new players.

**Comment by sepulzera** [comment]
Just try it yourself. Introduce a friend to Teeworlds and see, what (s)he will more enjoy. Why shouldn't we make an enjoyable game, after all?

**Comment by Dune-jr** [comment]
Well, if my friend enjoys instagib more, he can already play instagib at its full potential in Teeworlds right now. Where is the problem?

**Comment by lryjnks** [comment]
@Dune-jr @oy 

Do you want to get new players or not?



> We are not looking for benefits for Instagib, but want to make it easier for new players to get started.

        ^---


From your point of view, can you explain why iCTF should not be an Official Mod?

**Comment by 1stDecadeTW** [comment]
I'd prefer to make instashield an official vanilla gametype.

BUT, two conditions must be achieved before releasing  this new gametype:
- Improve the gametype name, make it more descriptive just as CTF, LMS, DM.
- Make it possible to play alone or as a team.

**Comment by sepulzera** [comment]
> Well, if my friend enjoys instagib more, he can already play instagib at its full potential in Teeworlds right now. Where is the problem?

Exactly there is the problem. If you start Teeworlds, the Serverbrowser will tell you to pick a standard gametype from the Teeworlds-Tab. Thus you will pretty much go for CTF, as they are the most frequent visited vanilla servers.

How should you know that Instagib exists, and that it is more newbie friendly?

**Comment by Dune-jr** [comment]
> If you start Teeworlds, the Serverbrowser will tell you to pick a standard gametype from the Teeworlds-Tab.

No, it won't? Players can click Teeworlds or All, as they wish.
It's not some sort of hidden function.

**Comment by sepulzera** [comment]
Guess my friends are just plain stupid, then.
Seriously, who would even consider choosing as server from  the All Tab when starting teeworlds for the first time?
Sorry for sharing my ideas based on experiences. I am very irritated how you don't even try to improve your point.

**Comment by themisak** [comment]
Like I also didn't know for long time how to get started in Teeworlds and it took long till I found my way to instagib where I got happy. @sepulzera

There isn't just one Teeworlds and Vanilla mods don't realy get played a lot, look at lms... It nearly never got played. Why not take mods wich are popular and make Teeworlds a superb game!! 

And @Dune-jr  there is a client related feature wich instagib would profit from, and that is that the hearts and shields could get removed for insta in top left corner. 

It would just be a big step up for Teeworlds if Instagib and Race could be offical, there were plans for race anyways!

I am also kinda unhappy how the Teeworlds Team respect what MANY MANY People would like to see for Teeworlds. Here on Github if someone of the Teeworlds Team reports an issue it gets instantly labled, a milestone gets set and and and. When other People report something nothing happens in many issues.

**Comment by ChillerDragon** [comment]
> Players can click Teeworlds or All, as they wish.
It's not some sort of hidden function.

Thats not true. You can't click a button you don't search or know about. Many people never touch the filters before they uninstall the game. I played vanilla for one year because I didn't know there is more.

Imo instagib shouldn't be standard gametype but we should promote non standard gametypes c:

**Comment by Dune-jr** [comment]
@ChillerDragon @sepulzera This was in 0.7. This is no longer the case. Look at the screenshot below.

This is what people see on their first start. There is **no more "Standard gametype" by default**. There is an "All" filter and a "Teeworlds" filter. Is there really **anyone** who didn't figure out how to play on mods on 0.7? I don't think so.

![screenshot_2018-12-20_10-36-29](https://user-images.githubusercontent.com/355114/50276832-35983c00-0443-11e9-9608-f31985a2ac30.png)

---

> I am also kinda unhappy how the Teeworlds Team respect what MANY MANY People would like to see for Teeworlds. Here on Github if someone of the Teeworlds Team reports an issue it gets instantly labled, a milestone gets set and and and. When other People report something nothing happens in many issues.

There is no "Teeworlds Team" on Github - only Oy. Issues get labelled when Oy accepts them as valid and should get fixed/implemented.

Contentious issues on gameplay do not get accepted easily. And from the last 5 issues I opened, only 1 is tagged. People get treated fairly, please recognize that.

**Comment by nheir** [comment]
so the point is about seeing insta/race mods in serverlist when a newbie,  does enabling ALL filter by default solve this point ?

also, why insta/race and why not other mods ?
insta is still evolving, see the shield and explosion feature. The fact that it is a mod make changes fast because client does not have to change and players do not need to update their game.
Race is pretty stable though, but there are plenty of other mods. 

anyway, to discover TW, newbies would benefit from a tutorial.
I support the diversity of weapons in tw official and the base mechanism that Oy recalled.
I personally didn't like instagib at first because of instakill by players I hardly saw. Vanilla was easier and funnier to start for me.

**Comment by ChillerDragon** [comment]
@Dune-jr oh ye sorry I am not used to 0.7 at all. The server browser had such an bad impression on me and I never tried to click around and hoped someone will improve it before I switch to 0.7 hehe.

But ye then ignore my statement about promoting non standard gametypes.

**Comment by sepulzera** [comment]
@Dune-jr You are still ignoring my arguments at all. I didn't complain that it is too difficult to play non-standard gametypes. I didn't say that even for once! **I am saying that we should give beginners an easier start with the game.** And that **Instagib** would be a good way to do so, based on *- some kind of a little -* usability study.

My friend started the game. (It was actually more complicated due to the GLIBC thingy, but let us put that aside). Then, she clicked "Settings" to turn off the Background music and lowering the sound volume (personal preference). Back to the main menu, she pressed "Play". After looking around for about 2 minutes at the serverbrowser (it isn't very intuitive), **she opened the Teeworlds section and picked a random server filled with people playing**.

*Side Note: The last sentence is very important. She didn't filter the server neither by difficulty nor by the gametype. Because, how should she even know? There is no guide or tutorial.
And as she wanted to play Teeworlds and not TeamFortress2 (by wording, those servers should appear in the All Tab, too. But that is out of the scope of this issue), she clicked the Teeworlds section.*

After 30 minutes of playing, she was very frustrated and was going to close the game. She had no chance at all. The movement was very unique, she didn't really know what to with the flag and getting kills was unlikely (there are like no newbies around, I wonder why?). And no, she is not new to computer gaming.

Then, I let her connect to an Instagib server. While still struggling with the hook, she eventually could get some kills and actually enjoyed playing it. And having some **fun time** is more important than learning all aspects of Teeworlds at once, ain't it?

**Comment by themisak** [comment]
> also, why insta/race and why not other mods ?
> insta is still evolving, see the shield and explosion feature. The fact that it is a mod make changes fast because client does not have to change and players do not need to update their game.
> Race is pretty stable though, but there are plenty of other mods.

Instagib is also very stable. Shield ICTF is not instagib, it has different gameplay. Instagib has been stable for years and years

and I agree 1ßß% with @sepulzera

**Comment by Sonix-** [comment]
Explosion is nothing new btw

**Comment by Fisico** [comment]
i don't like the idea to make instagib an offical gamemode.
Some things that does not correspond to the vanilla gameplay are the very fast gameplay. Basicly you make one or 2 kills and than got killed. K/D Ratios under 1 are mostly the case for general players.
For example CS:GO there is no offical gametype that limits you to one weapon and always headshot to lern the game. As mod it is ok but i dont think it works as an official gamemode.


> > * laser does 5 damage and doesn't instantly kill you
> 
> That's why we want to add the iCTF mod as the default gametype.
> 
> again:
> 
> Vanilla is too heavy for newbies. We should offer a simpler mod for newbies where they can get their first successes. (kills)


CS:GO does not have a noob mode, it has gungame and thats it. 
A completely different gametype that does not confuse new players... if you want to be good in Teeworlds you have to invest time, that’s also the case for some other games like CS, SC2, TF2, Dota, you name it and they are all played well. I am personally against making Teeworlds vanilla more noob friendly. Teeworlds Vanilla was always a very competitive setting. Maybe more time should be invested in making it “esport” ready.

**Comment by sepulzera** [comment]
@Fisico CS:GO has casual games and matches based on level. Dota2 has a tutorial and very bad bots, that the game suggests to play you against initially. SC2 has a singleplayer campaign.... i don't know for TF2, though.

That bring said, you are pretty wrong tbh.

**Comment by Fisico** [comment]
I am for a tutorial/training map with bots. That is a great way to learn the basic gameplay. 

But i agree the "all" tab should be the default tab open in the server browser for empty config's. So newbies see that there are mods available

SC2 single player campaign is basically a different game. There is not much common with multiplayer ladder or vs ai.

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
