### ISSUE TITLE
Considering laser jump/explosion for vanilla

### ISSUE THREAD

**Issue by Zatline** [teeworlds/teeworlds#1908]
This may have potential, here my suggestion 

- like in [InstaShield (0.7 Instagib)](https://www.teeworlds.com/forum/viewtopic.php?id=12618) explosion is triggered when laser is fired very close to the ground
- laser explosion inflicts more overall damage than a usual granade explosion
- due to more damage the resulting jump should of course be a little bit stronger
- explosion cancels the bounce off the wall impotant!
so you can't  jump and wall bounce at the same time, it's a fair tradeoff which helps balancing it.
- new  [laser-dedicated particle effect](https://gyazo.com/b4d1a3417dda615a4f27b6b4ebf4713f)

If done like described above laser would even add a spin on race think about it, 
it would have a stronger jump abillity but u can't propound a shot unlike with granade lancher so it gives people a choise to wrap their head around it adds to the skill sealing and trick shot mechanics u could sync up granade explosions with a final laser explosion for that extra boost that u wouldn't have got when u had not switched the weapon.

**Comment by Dune-jr** [comment]
I think those gameplay discussions should be kept in the forum, they are getting out of control here.

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
