### ISSUE TITLE
Mouse Relative Mode

### ISSUE THREAD

**Issue by msiglreith** [teeworlds/teeworlds#1910]
0.7 uses raw input for receiving mouse delta data directly. while prior versions manually warped the mouse cursor back to the middle of screen and calculated the delta.

Raw inputs are not influenced by the mouse settings of the OS like mouse acceleration.
It would be nice to have an option to use the old relative mouse mode approach (see https://wiki.libsdl.org/SDL_HINT_MOUSE_RELATIVE_MODE_WARP).

**Comment by 1stDecadeTW** [comment]
The gameplay feels weird with raw mouse input, and this is stoping players from migrating to the new 0.7 version (including me).
