### ISSUE TITLE
On Linux, mouse1+mouse2 becomes mouse3

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1916]
This means things like shotgun+hook result in no input by default.
However, if I `bind mouse3 "+hook;+fire"` it works.

I'm not sure if it's a particular Linux configuration that causes this, I use a pretty clean Linux Mint 17. Does anyone else reproduce?

**Comment by Dune-jr** [comment]
Yeah, I thought it's standard Linux behavior (at least Ubuntu?). It results in a mouse3, and copy pastes text

**Comment by oy** [comment]
Doubt we can do sth about it. We rely on the input states that we get from SDL.
You could check how the input states that we gather [here ](https://github.com/teeworlds/teeworlds/blob/master/src/engine/client/input.cpp#L157 )are correct.

**Comment by Dune-jr** [comment]
Yeah, just checked SDL sends a mouse3. So can't fix.
