### ISSUE TITLE
Serverversion Desplay Bug

### ISSUE THREAD

**Issue by themisak** [teeworlds/teeworlds#1917]
Watch screen to see the problem guys, the text is too long

![screenshot_2018-12-23_00-40-35](https://user-images.githubusercontent.com/44925034/50379512-7fec0980-064b-11e9-94a9-b371b91d59c0.png)

**Comment by LordSk** [comment]
We could also use some of the completely empty space at each side, to give more room for longer text to be displayed. I don't know why we ended up with such a small portion of the screen being utilised but I guess that's off topic here.

**Comment by Dune-jr** [comment]
Because it has to fit the tightest aspect ratios :/

**Comment by oy** [comment]
But we still have a bit room left on 5x4 that we could/should use.
The DoLabel function has an optional 5th paramter LineWidth:
`UI()->DoLabelScaled(&Row, pInfo->m_aVersion, FontSize, CUI::ALIGN_LEFT, Row.w);`
