### ISSUE TITLE
Supporting old macOS

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#1918]
I realized that somewhen during 0.6 the support for older Mac OS X versions stopped.
I just tested some versions on a Mac OS X 10.7.5 iMac:

0.6.1 worked fine.
0.6.2 launched but i was not able to move the mouse.
all newer versions did not launch.

I am not saying some one has to fix this and it is super important but I just wanted to mention it. The hardware is from 2011 and I know a lot of apple users who keep their hardware for decades. And apple does not allow an software update. Teeworlds has some players that play the game because nothing else runs on their devices. Especially the changes in 0.6 should not be to crucial that dropping the support is the only way to go. I am not sure about 0.7 but maybe some compiler flags for old mac versions could do the thing already. These flags might loose some optimizations on newer devices but we can provide two downloads.

Some error message I got on newer versions that did not launch:
```
$ ./Teeworlds.app/Contents/MacOS/teeworlds 
dyld: Library not loaded: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
  Referenced from: /Users/chiller/Desktop/./Teeworlds.app/Contents/MacOS/../Frameworks/libSDL2-2.0.0.dylib
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by ChillerDragon** [comment]
I have no longer access to the hardware and I wasnt able to install xcode because the os is too old xd.
It is probably possible to update but I didn't find the update in the AppStore where it usually is. It seems like apple doesn't want the os to be updated. And if apple doesn't want something the average apple user is pretty stuck. But ye I can keep trying the next time i get my fingers on such an old thingy.

**Comment by oy** [comment]
You could probably bundle that missing lib but not gonna do that. That system is just too old and the possible user base almost zero. So not gonna fix this.
