### ISSUE TITLE
MOTD can no longer be skipped by pressing Tab

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1920]
Following https://github.com/teeworlds/teeworlds/commit/09dd6e930186b779d92bf272b1876bc91c7a3b5f, pressing <Tab> (`+scoreboard`) does not skip the MOTD like it used to - you simply cannot open the scoreboard.

It was frustrating to wait for the MOTD to disappear to see who is ingame. An actual workaround was to press <Esc>, but that usually opens the menus, so it is not very intuitive.

I think this should be changed back to the 0.6 behavior.

**Comment by oy** [comment]
Pressing escape closes the modt like it always had.

**Comment by Dune-jr** [comment]
I wrote `<Esc>` in the issue but github apparently removed it due to the < >

So I just tested it, in 0.6, you can close the motd with Tab/`+scoreboard`. That was my reflex and probably will be that of others.
