### ISSUE TITLE
Teeworlds 0.7.1 Crashing

### ISSUE THREAD

**Issue by themisak** [teeworlds/teeworlds#1923]
Sometimes my Client Crashes and I don't know why.

Also If I tab in and out of teeworlds it takes over 1 second wich is realy long for a 10mb game :D, it kinda is not super stable

Also when starting Teeworlds and I am listening to music on media player or youtube the music is shortly lagging while the game is starting. Its just kinda makes my pc unstable

**Comment by Dune-jr** [comment]
Can you describe what happens during crashes?

**Comment by themisak** [comment]
The Game just closes or freezes

**Comment by Dune-jr** [comment]
I meant before the crash. What were you doing? Does it happen at any particular moment? Always ingame?
It is difficult to investigate this issue without more context.

**Comment by oy** [comment]
Is it still happening?
Might be related to some older SDL version, can't reproduce it.

**Comment by oy** [comment]
Non-reproducible.
