### ISSUE TITLE
Mouse not moving in Main Menu at startup

### ISSUE THREAD

**Issue by themisak** [teeworlds/teeworlds#1924]
When starting the Game, the Mouse sometimes does not move until I left click and then it only works that I can move it to somewhere. Before left clicking its centered in the middle

**Comment by Dune-jr** [comment]
Do you play in fullscreen? What system? Please give me more details.

**Comment by themisak** [comment]
Yes I am Playing Fullscreen

the System is

Amd Ryzen 2400g (Graficcard is on the processor)
b350 Chipset motherboard
8Gb ram
Windwos 10 1809
250Gb ssd samsung 960 evo

**Comment by Fisico** [comment]
i had the same problem, recompiling with SDL 2.0.8 fixed it for me.

**Comment by themisak** [comment]
I don't know how to compile under windows. Can you Fix this in the official downloads ?

**Comment by Dune-jr** [comment]
You have one of the official Windows releases, @themisak ? Those should be SDL 2.0.8

**Comment by themisak** [comment]
Yes I use the official release from the website!

**Comment by LordSk** [comment]
Does using `inp_grab 0` help?

**Comment by oy** [comment]
Still happening?
Experienced it in the past, but never seen that happening anymore with the latest version.

**Comment by oy** [comment]
Non-reproducible.
