### ISSUE TITLE
teeworlds.exe includes trojaner

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1933]
![desktop screenshot 2018 12 27 - 16 44 09 62](https://user-images.githubusercontent.com/35420825/50485733-cbf5d000-09f6-11e9-8360-b10d13a78d9f.png)

??? just downloaded 0.7.2 and unzipped it and my defender is warning me.

**Comment by oy** [comment]
Where did you download it?
Reports from [github](https://www.virustotal.com/de/url/6dd3cf4b63543a8368e5f628db5a1aa3814654a4af6a362c45184ee6804433eb/analysis/1545927530/), [file](https://www.virustotal.com/de/file/fd70ed43e325e6218ba5ecc90b1f1a6fdb1ded893d65440528b5374bea3864e8/analysis/1545925879/)
Also scanned with ms defender (latest definitions) - everything alright.

**Comment by fokkonaut** [comment]
teeworlds.com of course

**Comment by Dune-jr** [comment]
Try the windows 64 bit

**Comment by fokkonaut** [comment]
yup, worked. thanks
