### ISSUE TITLE
deathtiles still skipable?

### ISSUE THREAD

**Issue by WaRNe0nx3** [teeworlds/teeworlds#1936]
So in 0.6 it was possible to skip 1tile wide deathtiles with enough speed caused by either ninja sword, or enough grenade spam and gravity.

This is probably only relevant in Race but still it would be nice if it is fixed.

**Comment by teoman002** [comment]
The problem is that the tile-colission with CheckPoint() is not called when the tee is too fast.
More precisely the tee skips the tile in one tick, such that no collisions can occur.
Therefore you need trajectory estimation like in Projectile.cpp to check future collisions.

**Comment by ChillerDragon** [comment]
Imo this can be seen as a feature. It is fun to cheat and mappers can care about that and make it impossible. Hope the "bug fix" doesn't eat to much performance.

**Comment by AssassinTee** [comment]
It doesn't :) It just uses what is already there
