### ISSUE TITLE
Some sounds may be poorly located

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1939]
On teeworlds master:
```
[5c2961b5][chat]: 11: Zeta-Hoernchen: Dune: something's wrong with the sound
[5c2961c0][chat]: 11: Zeta-Hoernchen: it's not a smooth transition between left
and right
[5c2963b1][chat]: 11: Zeta-Hoernchen: hmm
[5c2963b5][chat]: 11: Zeta-Hoernchen: i noticed when they were far up
[5c2963c2][chat]: 11: Zeta-Hoernchen: and i was standing right the hammer was far left
[5c2963cc][chat]: 11: Zeta-Hoernchen: and if i was standing directly under it was far right
```

Can someone confirm feeling this?

**Comment by Sonix-** [comment]
Yeah I also noticed it sometimes, a sudden sound switch from a speaker to another (left to right or viceversa).

**Comment by Speedy-Consoles** [comment]
I took a quick look into the code and found the relevant piece in src/engine/client/sound.cpp:
```
int dx = v->m_X - m_CenterX;
int dy = v->m_Y - m_CenterY;
float Dist = sqrtf((float)dx*dx+dy*dy);
if(Dist >= 0.0f && Dist < m_MaxDistance)
{
	// constant panning (-3dB center)
	float a = 0.5f;
	if(dx < 0)
		a -= (Dist/m_MaxDistance)/2.0f;
	else
		a += (Dist/m_MaxDistance)/2.0f;
	
	float Lgain = sinf((1-a)*pi/2.0f);
	float Rgain = sinf(a*pi/2.0f);

	// linear falloff
	float Falloff = 1.0f - Dist/m_MaxDistance;

	Lvol = Lvol*Lgain*Falloff;
	Rvol = Rvol*Rgain*Falloff;
}
else
{
	Lvol = 0;
	Rvol = 0;
}
```
This is strange, considering that the separate dimensions only play into `if(dx < 0)`. The actual direction of the sound is not used. The difference in the left and the right channel only depends on the distance and which channel is louder depends on if the source to the right or the left. So if the sound source is far away up and just a little bit to the right, it sounds like it's coming completely from the right. The same holds for the left side. So if you're walking past the x component of something that is far above or below you, the sound suddenly changes side.
The relevant commit is d1ee52c372. It was probably correct before, but i didn't take a very deep look into it.
