### ISSUE TITLE
Windows x64 Compiling not possible with latest version

### ISSUE THREAD

**Issue by Fisico** [teeworlds/teeworlds#1946]
Windows x64 compiling is not possible any more with the latest build.

Download.py asks for a x86_64 argument that can't be run because cross platform compiling is not supported on windows. 

Latest TW source
Latest bam build
VS 2017 Community Edition

------------Log----------
[ 11/707] [2] c++ src/engine/shared/ringbuffer.cpp
usage: download.py [-h] [--arch {x86,x86_64}] [--conf {debug,release}]
                   TARGET [TARGET ...]
download.py: error: argument --arch: invalid choice: 'unknown' (choose from 'x86', 'x86_64')
bam: 'Downloading SDL2 headers and DLL...' error 2

[ 59/707] [8] c++ src/game/client/render_map.cpp
usage: download.py [-h] [--arch {x86,x86_64}] [--conf {debug,release}]
                   TARGET [TARGET ...]
download.py: error: argument --arch: invalid choice: 'unknown' (choose from 'x86', 'x86_64')

[ 60/707] [3] c++ src/game/client/ui.cpp
[ 61/707] [6] c++ src/game/client/gameclient.cpp
bam: 'Downloading freetype headers and DLL...' error 2

[136/707] [2] c src/engine/external/wavpack/metadata.c
src/engine/external/json-parser/json.c(141): warning C4311: "Typumwandlung": Zeigerverkürzung von "json_object_entry *" zu "unsigned long"

**Comment by LordSk** [comment]
This happens because bam does not detect x64 when building with MSCV2017 64bit.
The arch is then set to 'unknown'.
If we then try to force the arch, `bam arch=x86_64` we get a `Cross compiling is unsupported on Windows.`, because we check against bam's arch in bam.lua.

```lua
function GenerateWindowsSettings(settings, conf, target_arch, compiler)
	if compiler == "cl" then
		if (target_arch == "x86" and arch ~= "ia32") or
		   (target_arch == "x86_64" and arch ~= "ia64" and arch ~= "amd64") then
			print("Cross compiling is unsupported on Windows.")
			os.exit(1)
		end
```
https://github.com/teeworlds/teeworlds/blob/master/bam.lua#L218

A simple fix would be checking the appropriate [predifined macro](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2017) (_M_IX86, _M_AMD64).
https://github.com/matricks/bam/blob/master/src/platform.h#L106

Since matricks isn't really keeping bam up to date, should we use @Dune-jr's fork for now?

**Comment by Dune-jr** [comment]
@LordSk There were plans to fork bam in https://github.com/teeworlds/bam/, I think it's time to execute that. @matricks does still maintain it, but it can take a long time, so it would make sense to do that and systematically pull upstream changes.

I think there was a third bug fix we wanted to apply, but I forgot which.

**Comment by heinrich5991** [comment]
Now that CMake is merged, you could also try compiling with CMake. It probably still needs a tutorial though.

**Comment by oy** [comment]
Hm, thought I made a pr about that fix years ago. Seems like I forgot and just fixed it locally....

**Comment by matricks** [comment]
I have no PR for it and I don't have access to any windows machines. Make a PR and I'll merge it.

**Comment by Dune-jr** [comment]
Fixed by https://github.com/matricks/bam/commit/6cbfb77603f6e5cf704b2f28ac8b0ca5cabe0ea8 and https://github.com/matricks/bam/commit/b937e38b7c7c7d559a156c43ea37ae104c1d159c upstream.

https://github.com/teeworlds/bam was also created and is up-to-date.
