### ISSUE TITLE
Tick overflow

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#1961]
If the server will run for a long time without a map change/reload the game tick will overflow eventually.

**Comment by teoman002** [comment]
If the game tick approaches some large value, the server could do a IGameController::ResetGame() to solve this problem.

**Comment by fokkonaut** [comment]
We have this already:
https://github.com/teeworlds/teeworlds/blob/0c338f0e00e21cd01c8f4eddc88fc831d855e068/src/engine/server/server.cpp#L1366

**Comment by oy** [comment]
Oh fixed that already.

**Comment by AssassinTee** [comment]
0x6FFFFFFF
Why this value? why not a config value? Can somebody translate this in seconds - 434.964859028 days on 50 tps

**Comment by oy** [comment]
A config value wouldn't make much sense here.
