### ISSUE TITLE
Make automapping a toggle

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1963]
Following a (misunderstood) suggestion by @savander, the automapper could be an ON/OFF toggle that works in real time as you are making the map. I don't see any issue this would bring up - the current automapper is quite fast.
It doesn't sound like too much code either

https://www.teeworlds.com/forum/viewtopic.php?id=11496
![advanced_mappers_2](https://user-images.githubusercontent.com/355114/50863012-96a99480-139d-11e9-934d-c111da961ed0.gif)
![advanced_mappers_2](https://user-images.githubusercontent.com/355114/50863051-b640bd00-139d-11e9-88a7-ff963db1e3ca.gif)

Thoughts?

**Comment by 1stDecadeTW** [comment]
These three missing features would make the map editor almost perfect:
1) Real time automapper toggle ON/OFF
2) Play (test) map button
3) Undo last (10 ?) action.

**Comment by Dune-jr** [comment]
This is #552

**Comment by oy** [comment]
fixed by #2090
