### ISSUE TITLE
gun sound is gone

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1964]
.

**Comment by Dune-jr** [comment]
Give more details. What version?

**Comment by fokkonaut** [comment]
idk current version
0.7.2 i think

**Comment by fokkonaut** [comment]
gun wont make sounds

**Comment by Dune-jr** [comment]
Never heard of such an issue, so you'll have to give more details.

**Comment by oy** [comment]
Maybe a modified server?

**Comment by fokkonaut** [comment]
no

**Comment by fokkonaut** [comment]
how would that even influence ir

**Comment by Dune-jr** [comment]
Sounds are controlled by the server.
Best to figure what causes it before filing a report.

**Comment by fokkonaut** [comment]
was the server lol
