### ISSUE TITLE
Unable to type umlaut and other non-ascii characters into text fields

### ISSUE THREAD

**Issue by Zwelf** [teeworlds/teeworlds#1971]
How to reproduce:
1. Use a keyboard layout with non-ascii characters (e.g. German)
2. Try to input characters like äöü (placed on ;'[) into the server search field
3. no characters or squares are shown

Expected behavior: see umlaut characters
Tested on Linux 64 bit with the versions 0.7.1, 0.7.2 (downloaded from teeworlds.com) and master (self compiled)
Works expected on 0.6.5

**Comment by Zwelf** [comment]
Additional note: pasting these characters with #1962 works fine.

**Comment by oy** [comment]
Tested with German - works for me.

**Comment by Zwelf** [comment]
Strange, I can't reproduce this on any other system.
The issue is occurring on a Manjaro System with Gnome on x11 and Teeworlds is the only application, where this happens. Tested it on a Manjaro live system with Gnome on x11 and can't reproduce it.
I think we can close the issue, because it is not reproducible and it might not be related with Teeworlds.

**Comment by oy** [comment]
https://github.com/teeworlds/teeworlds/blob/master/src/engine/client/input.cpp#L153-L155
We just use what SDL provides - nothing we can do there it seems.
