### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by loskiq** [teeworlds/teeworlds#1976]
```
$ ./teeworlds
./teeworlds: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by Mohammedaljaafari** [comment]
good evening my friend
My mobile not recovery plead my help.
Name Mobile : ROBIN My next bit
ID: 3031066657070
the number device : 3551510702
83405

في الأربعاء، ١٦ يناير، ٢٠١٩ ٩:٣٠ ص، كتب Amir <notifications@github.com>:

**Comment by oy** [comment]
Inactive.
