### ISSUE TITLE
RgbToHsv is probably misnamed

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1981]
This should probably be `RgbToHsl`, right?
It's used throughout the codebase

https://github.com/teeworlds/teeworlds/blob/b45545e6d382cdf953a3c313ba960b64b598c6db/src/base/color.h#L115-L119

Edit: also, `HsvToRgb` has the same issues

**Comment by Dune-jr** [comment]
Let's see:

https://github.com/teeworlds/teeworlds/blob/b45545e6d382cdf953a3c313ba960b64b598c6db/src/base/color.h#L146-L147

`l` is just the max of RGB.

> 2
> Find the minimum and maximum values of R, G and B.
> 
> min = 0.09 (the R value)
> max = 0.46 (the B value)
> 
> 3
> Now calculate the Luminace value by adding the max and min values and
> divide by 2.
> 
> L = (0.09 + 0.46)/2 = 0.275 which rounded up is equal to 28%
http://www.niwa.nu/2013/05/math-behind-colorspace-conversions-rgb-hsl/

RGB to HSL: L is `min+max/2`

> Cmax = max(R', G', B')
> Cmin = min(R', G', B')
> Δ = Cmax - Cmin
> 
> Value calculation: V = Cmax
https://math.stackexchange.com/questions/556341/rgb-to-hsv-color-conversion-algorithm

RGB to HSV: V is `max`

So the comment is wrong, and this is truly a RgbToHsv function... and it seems to be correctly used (also at src/game/editor/editor.cpp:2452):

https://github.com/teeworlds/teeworlds/blob/8a5e6ebe87090fe5e2beab605c6255f88c8c61cf/src/game/editor/popups.cpp#L1139-L1143

So just change the comment and close the issue?

**Comment by oy** [comment]
Yeah, that should be good.
