### ISSUE TITLE
Make the visualiziation of labels consistent

### ISSUE THREAD

**Issue by sepulzera** [teeworlds/teeworlds#1986]
This issue is related to #1985.

Currently, labels are inconsistent visualized:
- Many are left aligned
- Others are centered
- Most have a colon
- Some have no colon (Server browser > Server details)

I suggest to make all labels left aligned, to make scanning the rows easier. 
And to add all missing colons to [clearly separate labels from text](https://ux.stackexchange.com/questions/3611/should-label-and-field-be-separated-with-colon).

**Comment by Dune-jr** [comment]
What areas are you talking about? Can you give screenshots?

**Comment by sepulzera** [comment]
Server Browser > Address:
![screenshot_server-browser_address](https://user-images.githubusercontent.com/43857716/51383049-ad2bba80-1b18-11e9-98c9-78ffe3457bb2.jpg)

Server Browser > Server Filter:
![screenshot_server-browser_server-filter](https://user-images.githubusercontent.com/43857716/51383052-aef57e00-1b18-11e9-844e-f5c616afcc7c.jpg)

Server Browser > Server Details:
![screenshot_server-browser_server-details](https://user-images.githubusercontent.com/43857716/51383055-b026ab00-1b18-11e9-963a-729414f3e8b5.jpg)

Settings > Controls:
![screenshot_settings-controls](https://user-images.githubusercontent.com/43857716/51383060-b157d800-1b18-11e9-8add-6baffda2f8a4.jpg)
