### ISSUE TITLE
Grenades continue moving (even through walls) when game ends

### ISSUE THREAD

**Issue by Fudgyking** [teeworlds/teeworlds#1991]
It happened twice to me today. I was playing DM and I shot a grenade just before the game ends. Instead of freezing in the air, it went through all the walls without exploding. I guess this is a problem with all projectiles but its hard to test.

**Comment by teoman002** [comment]
Put this into tick of the weapon type that shouldn't move after the game has ended:
`if( IsMarkedForDestroy() ) return;`
