### ISSUE TITLE
Sanitize clipboard strings: pasting text with \n in text fields doesn't work well

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1992]
Pasting text with \n in text fields (e.g. host address) doesn't work well.

The textfield enter a strange state, where it apparently takes in account the newline, displays it as a [] box character, and the caret does not match its actual position (only the X position is displayed).

Pasted strings must be sanitized

**Comment by Dune-jr** [comment]
Thanks!
I am thinking we might want to differentiate between single and multiple line inputs for that (not sure if it's already done somewhere?).

**Comment by oy** [comment]
Not sure if the console could handle it. Besides that there's no current use case.

**Comment by Dune-jr** [comment]
Doesn't chat allow multiple line inputs?
