### ISSUE TITLE
bam.lua: Windows sometimes needs explicit python call

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1993]
https://github.com/teeworlds/teeworlds/blob/6ec984bbd5f0be0968a8202dc4fcf0ee96bb5f8b/bam.lua#L23-L29

*FudgyToday at 5:29 PM*
> \> I mean, I changed that line : dl = Python("python scripts/download.py")
> \> if I dont write python inside, it doesnt work
> \> in the function Python()
> \> it adds "python" in front only if its not windows
> \> I like the comment there
> \> "-- Python is usually registered for .py files in Windows"
> \> not for me somehow

**Comment by oy** [comment]
Should be fixed by #2369
