### ISSUE TITLE
Back, packet bad

### ISSUE THREAD

**Issue by kurosio** [teeworlds/teeworlds#1994]
this really bad, send extra << bufers, or it is possible to bypass?
many limits for modder

// send clear client information
	CNetMsg_Sv_ClientDrop cclient;
	cclient.m_ClientID = ClientID;
	cclient.m_pReason = "";
	cclient.m_Silent = 1;
	Server()->SendPackMsg(&cclient, MSGFLAG_VITAL|MSGFLAG_NORECORD, -1);

	// got in cleared information client information
	CNetMsg_Sv_ClientInfo rest;
	rest.m_ClientID = ClientID;
	rest.m_Local = 0;
	rest.m_Team = m_apPlayers[ClientID]->GetTeam();

	rest.m_pName = "Hello";
	rest.m_pClan = Server()->ClientClan(ClientID);
	rest.m_Country = Server()->ClientCountry(ClientID);
	rest.m_Silent = 1;

	for(int p = 0; p < 6; p++)
	{
		rest.m_apSkinPartNames[p] = m_apPlayers[ClientID]->m_TeeInfos.m_aaSkinPartNames[p];
		rest.m_aUseCustomColors[p] = m_apPlayers[ClientID]->m_TeeInfos.m_aUseCustomColors[p];
		rest.m_aSkinPartColors[p] = m_apPlayers[ClientID]->m_TeeInfos.m_aSkinPartColors[p];
	}
	Server()->SendPackMsg(&rest, MSGFLAG_VITAL|MSGFLAG_NORECORD, -1);`

**Comment by Dune-jr** [comment]
I don't understand. Where exactly is the problem?

**Comment by kurosio** [comment]
I'am for self mode used CNetObj_De_ClientInfo how Object
