### ISSUE TITLE
First click on a server after leaving one acts like a double click

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1998]
I was reported this bug by someone ingame (@fudgyking maybe?), tested and confirmed it

**Comment by Fudgyking** [comment]
This also happens to me on menu items in the editor. My first click on a map name counts as a double click.  I cant pinpoint the exact steps to reproduce that though. It happens less often.

**Comment by oy** [comment]
Can't reproduce. How do you leave the server? Clicking the disconnect button?
