### ISSUE TITLE
logging leads to lag

### ISSUE THREAD

**Issue by Shereef** [teeworlds/teeworlds#200]
Mo(2) Said:
Currently I have a reasonable suspicion that Teeworld-Servers may lag if harddrive is busy and someone join or leave if you have logging enabled even if there is more then enough CPU and Network-bandwidth available. Boths events creates log-entries. If even others noticed the same I would suggest some delayed or independent logging because today it's easy possible that CPU and Network would not be the bottleneck.

Greetings,
Mo(2) 

http://ddrace.info/forum/showthread.php?115-Lags-when-logging-is-on&p=612&viewfull=1#post612

i have also experienced this my self on player leave (windows 7 x64)
i know for a fact that Mo(2) uses Linux, i think amd64 but not sure

**Comment by MegaManSec** [comment]
I'll just c'np my comment on that pull request to here.
It perhaps should have its own issue, but it is also some-what relevant.

"Can we have an option for minimalistic logging? I.e don't log weapon pickups. This wouldn't completely fix the problem but it would be good for very active servers that are never switched off.."
