### ISSUE TITLE
Server address should always match the highlighted server

### ISSUE THREAD

**Issue by sepulzera** [teeworlds/teeworlds#2003]
In some cases the (displayed) server address will not match the highlighted server. Thinking that the correct server is already chosen, I press [Connect] to join. But in the end I will hop on a very different server.

The server address should always match the highlighted server.

**Edit:** Ways to reproduce:
* Select a server from _Global_. Switch to _Local_. Select a local server. Switch back to _Global_. The prior selected server from _Global_ is still selected, but the server address points to the local one.
* Select a server. Change the server address. The prior selected server is still selected.

------

Teeworlds: 0.7.1
OS: Linux Mint 19.1, Cinnamon Edition

**Comment by Dune-jr** [comment]
I don't know, sometimes you want to type in the address bar. Should it really instantly deselect anything in the browser?

I can see the issue, but I don't see an elegant answer

**Comment by sepulzera** [comment]
> Should it really instantly deselect anything in the browser? *- Dune-jr*

Yes it should. Otherwise the highlight is wrong and misleading. Eventually, you could highlight the related server, if any. But that would be another feature, I guess.

**Comment by sepulzera** [comment]
Amended ways to reproduce, see edit.

**Comment by fokkonaut** [comment]
Very nice! This is annoying me for a bunch of weeks now, since I hop between my local server for testing and my online server for playing a bit a lot
