### ISSUE TITLE
swap teams does not swap teamscore

### ISSUE THREAD

**Issue by sepulzera** [teeworlds/teeworlds#2004]
See https://github.com/teeworlds/teeworlds/blob/4ae94d4745a3d8b6a45c5d129382ef3604c29722/src/game/server/gamecontext.cpp#L437-L449

The method CGameContext::SwapTeams() will swap the teams, but not the teamscore.

Swapping the teams can be triggered by:
* command _swap_teams_
* end of match with _sv_match_swap_
* some mod (my very own case)

Swapping the teams should swap the teamscore, too.

**Comment by Dune-jr** [comment]
I agree, I think the teamscore should be swapped
