### ISSUE TITLE
LTS and LMS handle UpdateDeadSpecMode differently

### ISSUE THREAD

**Issue by sepulzera** [teeworlds/teeworlds#2005]
LTS and LMS are both survival gametypes.

OnCharacterDeath, LMS calls UpdateDeadSpecMode:
https://github.com/teeworlds/teeworlds/blob/4ae94d4745a3d8b6a45c5d129382ef3604c29722/src/game/server/gamemodes/lms.cpp#L17-L25

However, LTS does not.

I think that the code of LMS is redundant, as it is done in their parents IGameController::OnCharacterDeath:
https://github.com/teeworlds/teeworlds/blob/4ae94d4745a3d8b6a45c5d129382ef3604c29722/src/game/server/gamecontroller.cpp#L236-L241

**Comment by LordSk** [comment]
Don't hesitate to make a pull request @sepulzera (especially for such an easy and straight forward change).
It is much easier for the maintainer to pull a change than to take the time and do it himself. That's a good find anyway, thanks for reporting.
