### ISSUE TITLE
Use some code metrics and/or statistics tool

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2009]
Hi,
I tested my own teeworld source with [codacy](https://www.codacy.com/) and found a hell of a lot of issues with the quality of the teeworlds sourcecode.

[Codacy link of my project](https://app.codacy.com/project/AssassinTee/Teeworlds-Zod2/dashboard)

Most of the issues are found in the scripts folder with the python scripts. Some issues come from a lot of C-Style casting. The tool has found some Security vulnerabilities, too.

My issue is that the source code got an **E** (scale is A to F), so a bad grade.
I think it would be nice to use such a tool for quality control.

**Comment by Dune-jr** [comment]
Note: all the (alleged) security vulnerabilities are relative to development scripts (make_release...), not to Teeworlds itself. That should be fine.

More of an opinion now: I don't think imposing constraining strict rules like "no C-style pointer casting" fits Teeworlds well.

Some issues, however, are interesting. I saw that some strings are being passed without const reference, but that seems to be specific to your mod. Do you have any way to run it on teeworlds instead?

**Comment by AssassinTee** [comment]
The json errors are due to a comma to much. After lists and arrays the last element doesn't get a comma. They are easy fixable.

**Side Note**: 
Json can manage booleans:
data/skins/bluekitty.json
"custom_colors":"true" -> "custom_colors":true

I removed the python reader and the C-style pointer casting pattern

I will run it on direct teeworlds (at least on my clean fork)

Thank you for your feedback :)

**Comment by AssassinTee** [comment]
So I did the same with a clean teeworlds source and came to the same results as you
[Result](https://app.codacy.com/project/AssassinTee/teeworlds/dashboard)

* CPP results
    * "Error Prone" warnings:
        - Member variable 'classname::varname' is not initialized in the constructor. 32
        - Either the condition is redundant or there is possible null pointer dereference: pointer. 3
* C results
    * "Error Prone" warnings:
        - Either the condition is redundant or there is possible null pointer dereference: pointer. 3
    * "Security":
        - Problems with strlen, strncpy and usleep

**Comment by oy** [comment]
Yeah, seems the relevant issues are covered.
