### ISSUE TITLE
cmake not working with clean source

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2018]
Hi, its me again!

I can't compile with cmake. It looks like there are files missing

[cmakeerror.txt](https://github.com/teeworlds/teeworlds/files/2828309/cmakeerror.txt)
Here is a stacktrace. I am using a clean teeworlds and pulled the last master.

thank you in advance,
Assa

Edit 1.: Sorry, got the wrong file first

**Comment by Dune-jr** [comment]
This should be fixed by

```
git submodule init
git submodule update
```

However, requiring those submodules to compile with cmake is probably not a desirable state... thanks for reporting.

**Comment by heinrich5991** [comment]
Or in one step:

    git submodule update --init

**Comment by dwatteau** [comment]
> This should be fixed by
> 
> ```
> git submodule init
> git submodule update
> ```
> However, requiring those submodules to compile with cmake is probably not a desirable state... thanks for reporting.

Yes, this is blocking the update on OpenBSD, because the 0.7.2 tarball is missing the maps and translations. Relying on `git submodule update` during the build is not going to be accepted in the ports tree.

Could the next 0.7.3 release include them by default in the generated tarball? Thanks.

**Comment by oy** [comment]
@dwatteau you can still build it using bam, like in the past.

**Comment by dwatteau** [comment]
@oy Building it yes, but having `maps/` and `translations/` in the resulting package no. Because https://github.com/teeworlds/teeworlds/archive/0.7.2.tar.gz doesn't have them.

That's why Debian is repackaging their own tarballs as well:
https://metadata.ftp-master.debian.org/changelogs/main/t/teeworlds/teeworlds_0.7.2-2_changelog

> "However see README.source. We have to add maps and translations manually because network connections at build time are not allowed."

**Comment by heinrich5991** [comment]
We should create a source release tarball for the next version again (like we did in 0.6.5 and before) which includes the maps and the localisation.

**Comment by heinrich5991** [comment]
@dwatteau I added complete source tarballs to the release, e.g. check out https://github.com/teeworlds/teeworlds/releases/download/0.7.2/teeworlds-0.7.2-src.tar.xz.

**Comment by dwatteau** [comment]
Thank you very much @heinrich5991, I confirm that this will let me upgrade the teeworlds port on OpenBSD -current. Thanks again!

**Comment by oy** [comment]
Fixed by 4d45e21e6d29cc6b8c65ede74e12a9a4313a9faa
