### ISSUE TITLE
Readme appveyor badge link missguiding

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2020]
Hi, its me again!
Clicking on the appveyor-badge just reconnects to the image to camo.githubusers.com.
Example how it should look like:

```
[![Build status](https://ci.appveyor.com/api/projects/status/rfhb7d6755ce28xi/branch/master?svg=true)](https://ci.appveyor.com/project/AssassinTee/teeworlds-zod2/branch/master)
```

By just using the link to a picture you could easily fake the "build passing" badge

[![fake](https://img.shields.io/badge/build-passing-brightgreen.svg?logo=appveyor)](www.teeworlds.com)

Going through your history:

First going to "heinrich5991":

[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/foeer8wbynqaqqho?svg=true)](https://ci.appveyor.com/project/heinrich5991/teeworlds)

Now only showing the badge (missing link):

![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/teeworlds/teeworlds?branch=master&svg=true)

trying this link [https://ci.appveyor.com/project/teeworlds/teeworlds?branch=master](https://ci.appveyor.com/project/teeworlds/teeworlds?branch=master) brought me to the conlcusion, that you don't want that anyways

This issue is so minor, that this ticket is an overkill

**Comment by oy** [comment]
The badge was faulty before. Added the link f0ebc6272bd64dc0dced77c7e2ad78553f106d20.
