### ISSUE TITLE
Add search bars in Editor and Vote Menu

### ISSUE THREAD

**Issue by TeeSlayer** [teeworlds/teeworlds#2024]
That would make things so much easier. You can have a look at the DDNet client, they've had that for quite some time already. A recursive search for file selection in both "Load Map" and "Add Image" would be even better. :)

**Comment by LordSk** [comment]
Can you post screenshots related to the feature? That'd be really helpful.

**Comment by TeeSlayer** [comment]
See:

![alt searchbar_1](https://lolinet.info/download/screenshots/searchbar1.png)
![alt searchbar_2](https://lolinet.info/download/screenshots/searchbar2.png)

**Comment by 0xFaulty** [comment]
@TeeSlayer "Error Fetching Resource" for me, can you reupload screenshots?

**Comment by Dune-jr** [comment]
@0xFaulty They are github-hosted screenshots (https://camo.githubusercontent.com), I think the issue is on your end

**Comment by ChillerDragon** [comment]
Oh if you are on it already please make it better than ddnet :)
It is very annoying that you have to use the mouse and click into the search bar.

Please directly set the cursor into the search bar so you can start typing without mouse delay.
And or add a search hotkey to get the cursor back in. I suggest using '/' as used by unix tools, trello, github etc...

**Comment by TeeSlayer** [comment]
@0xFaulty Nginx crashed on my server for some reason. It's up again.
