### ISSUE TITLE
64x64 game type icons not working correctly.

### ISSUE THREAD

**Issue by android272** [teeworlds/teeworlds#2025]
I thought that TW was going to go with 64x64 pixel game type icons in 0.7.2 but when I use icons with these dimensions I get the result seen below where the icons get stretched vertically and are cut off. When I use 64x192 icons however they look normal. Did this not get changed in the final release of 0.7.2 or was it planned for the next release?

![bitmap](https://user-images.githubusercontent.com/5912527/52386832-a9bf8b00-2a55-11e9-8bd3-41c8df561e03.png)

**Comment by Dune-jr** [comment]
This was changed after 0.7.2. This is the commit:https://github.com/teeworlds/teeworlds/commit/d1657320a9b24d50b3e62fb0b5597c50f1c06ccc

**Comment by oy** [comment]
Yeah, that has been done after the 0.7.2 release and will be included in the next release.
