### ISSUE TITLE
Missing explicit localization calls

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2027]
https://github.com/teeworlds/teeworlds-translation/issues/71
It seems that there are some missing `Localization(...)`.

The browser header seem to be missing, see patch https://github.com/Dune-jr/teeworlds/commit/6cfda9401e2485a435e70affc2e07b019f6ae950

The skin parts locales are more tricky:
```const char * const CSkins::ms_apSkinPartNames[NUM_SKINPARTS] = {"body", "marking", "decoration", "hands", "feet", "eyes"}; /* Localize("body","skins");Localize("marking","skins");Localize("decoration","skins");Localize("hands","skins");Localize("feet","skins");Localize("eyes","skins"); */```

That could be an issue with the convert algorithm 

Thanks [ArionWT](/ArionWT) for the report

**Comment by ArionWT** [comment]
Same issue with 'K' and 'D' in a scoreboard headerbar.
![_2019-02-09_17-42-34](https://user-images.githubusercontent.com/8038546/52522146-5a19d300-2c92-11e9-94fc-81d23d519ffd.png)

**Comment by Dune-jr** [comment]
@ArionWT I don't think K/D should be translated.

**Comment by ArionWT** [comment]
@Dune-jr, It makes sense 🤔
