### ISSUE TITLE
No padding in some dialogs

### ISSUE THREAD

**Issue by ArionWT** [teeworlds/teeworlds#2028]
There is no left padding in remove skin/demo and rename demo dialogs in the menu:

![_2019-02-09_17-09-47](https://user-images.githubusercontent.com/8038546/52522018-05298d00-2c91-11e9-8511-b21373406882.png)

**Comment by masahiroCAN** [comment]
Hi I'm Masa. I would like to work on this bug as my first contribution to this project. I should be able to make a PR soon. I'm very excited to work with you guys:)

**Comment by masahiroCAN** [comment]
do you mind if I ask anyone how to reproduce this bug? i am new to this project and having hard time reproducing this bug.

**Comment by Dune-jr** [comment]
Game start menus -> Demos -> Delete one

If you don't have a demo, join a server -> Esc -> Record

For the skin, you have to make a custom skin in Settings -> Tee to delete one

**Comment by masahiroCAN** [comment]
Thank you!

**Comment by masahiroCAN** [comment]
Does it make more sense display these messages with center aligned? just suggestion.

**Comment by oy** [comment]
Fixed by b6c0abe9930bf3ef7f009465db856885910d3de9
