### ISSUE TITLE
Scroll the show_chat area with Pageup/Pagedown 

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2035]
Similarly to the console, this could let players see more chat history without having to use a nerdy console. 

I assume it should only work when `+show_chat` is active, and not save state.

**Comment by AssassinTee** [comment]
Do you want to use the mousewheel for this? I may see a problem with weapon switching

**Comment by sepulzera** [comment]
Possible duplicate of #1849.

**Comment by Dune-jr** [comment]
Ah, indeed. I suspected this was already mentioned somewhere but didn't find it. Thanks @sepulzera.
