### ISSUE TITLE
Standard map/gametype filters behavior is confusing

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2057]
> huh, i can't uncheck 'standard gametype' in the filter
> oh, that was terribly confusing
> under 'All' that filter works just fine, but if you tick it you get exactly the same result as the 'Teeworlds' filter
> you can't even move down 'Teeworlds'?

There should at least be some more consistency / less confusing UI design.

- if you can't untick Standard [gametype/map] in Teeworlds, you shouldn't be able to tick it in All
- if you can't use it, it should be grayed out (or not displayed)

**Comment by oy** [comment]
Think it should be possible to disable standard map/gametype. So you can easily work around with the filter.
Agree that settings which you can't use should be grayed out.

**Comment by Dune-jr** [comment]
Something like that then:

![image](https://user-images.githubusercontent.com/355114/54498048-4f420600-4902-11e9-8834-0e9b84afe84c.png)

> Think it should be possible to disable standard map/gametype. 

You mean enable? Because if you can disable the standard gametype filter in the Teeworlds filter, then it's no longer any special, right?

**Comment by oy** [comment]
Yeah, enable/disable - use that setting in all but the Teeworlds filter.

Yeah, that looks fine. 👍

**Comment by Dune-jr** [comment]
I haven't found a better way than this: https://github.com/teeworlds/teeworlds/commit/59c56d72b907112fc6709a688e82f5fa9b778054

This resets the color to `Graphics()->SetColor(1.0f, 1.0f, 1.0f, 1.0f);` after setting it to gray.
Also, should the ordering, or the behavior of the filters "Standard gametype" and "Standard map" change?

**Comment by oy** [comment]
fixed by 59c56d72b907112fc6709a688e82f5fa9b778054
