### ISSUE TITLE
for some reason bam refuses to compile

### ISSUE THREAD

**Issue by Koleotank** [teeworlds/teeworlds#2058]
for some unknown reason, i keep getting an error every time i'm compiling bam, even if i downloaded it from the teeworlds github account.
here's what the error is:
![image](https://user-images.githubusercontent.com/38538179/54084114-ed473680-432c-11e9-817e-8aa80644b036.png)

(i did include bam in the teeworlds opensource folder.)

**Comment by Dune-jr** [comment]
What Microsoft Visual Studio version are you using? Try running the `x64 Native Tools Command Prompt` first

**Comment by oy** [comment]
Seems it doesn't work using an absolute path. Try a relative path or change into the bam dir and run the script.

**Comment by oy** [comment]
Invalid. Created an issue on [bam](https://github.com/matricks/bam/issues/130).

**Comment by oy** [comment]
Fix upstream https://github.com/matricks/bam/pull/135
