### ISSUE TITLE
Empty nicknames

### ISSUE THREAD

**Issue by TerminalMan** [teeworlds/teeworlds#2062]
In v 0.7.2 it is possible to play with an empty nickname. An issue that existed before and was fixed before.

https://github.com/teeworlds/teeworlds/issues/616

Speculation:

The client appears to still have a nick validity check, but it doesn't appear to run after a nick change. After a client restart however it does, because the nick is then set to 'unnamed tee'

**Comment by TerminalMan** [comment]
The problem is that the UI flag indicator on the right side of the screen tells you 'the flag is in base' while actually someone without a nick is carrying it. Thus even though it may be fine on the technical side, using no name gives an unfair advantage.

**Comment by oy** [comment]
When the flag is taken it renders the tee of the carrier next to the flag. So you see right away if the flag is taken or in base despite the nick name.

**Comment by Dune-jr** [comment]
You also can't ping people with empty nicknames.

**Comment by TerminalMan** [comment]
> When the flag is taken it renders the tee of the carrier next to the flag. So you see right away if the flag is taken or in base despite the nick name.

After testing it, I see what you mean. But it's rather subtle, I didn't even notice it on my own and even when you know it you have to look twice.

> You also can't ping people with empty nicknames.

tbf. i doubt these people want to be pinged

**Comment by oy** [comment]
![screenshot_2019-03-17_18-00-48](https://user-images.githubusercontent.com/293850/54494834-c796d000-48de-11e9-8279-e493ef7946f3.png)
Think you notice the difference pretty well.
There're also small names like .'´° which would be hard to catch like empty ones.

**Comment by fokkonaut** [comment]
tees without a name can hide behind doodads, if placed over game

**Comment by oy** [comment]
Ok, then we'll remove the empty nicknames with the next version.

**Comment by jxsl13** [comment]
You also cannot distinguish with a whisper command between two players having the same nick.

**Comment by Dune-jr** [comment]
What way should we go about this? Old clients can still send empty nicknames. Should they be replaced server-side by the good old `(1)`?

**Comment by ChillerDragon** [comment]
@Dune-jr as already mentioned on discord. It would be very nice to go to the old system also for duplicated names. As @jxsl13 said also with whisper it becomes a bigger problem. But also good ol' regular chat is more confusing when two players can have the same name.

**Comment by oy** [comment]
@Dune-jr doing it server sided is probably best.
