### ISSUE TITLE
Client refuses to take server updates

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2063]
Hi, it's me again!
I am currently trying to port some Mods from Teeworlds 0.6 to 0.7 and it seems impossible for a client to change its skincolor/skin. Currently only other players see the server sided changes.

I already made a (german) [post](https://teeworlds-friends.de/thread/9084-umfrage-modideen/) about this.

I wrote a function to change the TeeInfos, which is performing a silent reconnect. But even when the `local` flag is set, it doesn't update on the client side.

Is this a bug or a feature?
```
void CGameContext::ChangeClientInfos(int ClientID)
{
    //Change Player Infos
    GenSkin(ClientID);
    int color = GenColor();
    for(int p = 0; p < 1; p++)//1: only change body
    {
        m_apPlayers[ClientID]->m_TeeInfos.m_aUseCustomColors[p] = true;
        m_apPlayers[ClientID]->m_TeeInfos.m_aSkinPartColors[p] = color;
    }

    //Info Message
    CNetMsg_Sv_ClientInfo ClientInfoMsg;
    ClientInfoMsg.m_ClientID = ClientID;
    ClientInfoMsg.m_Local = 0;
    ClientInfoMsg.m_Team = m_apPlayers[ClientID]->GetTeam();
    ClientInfoMsg.m_pName = Server()->ClientName(ClientID);
    ClientInfoMsg.m_pClan = Server()->ClientClan(ClientID);
    ClientInfoMsg.m_Country = Server()->ClientCountry(ClientID);
    ClientInfoMsg.m_Silent = true;

    //Connection Message
    CNetMsg_Sv_ClientInfo NewClientInfoMsg;
    NewClientInfoMsg.m_ClientID = ClientID;
    NewClientInfoMsg.m_Local = 0;
    NewClientInfoMsg.m_Team = m_apPlayers[ClientID]->GetTeam();
    NewClientInfoMsg.m_pName = Server()->ClientName(ClientID);
    NewClientInfoMsg.m_pClan = Server()->ClientClan(ClientID);
    NewClientInfoMsg.m_Country = Server()->ClientCountry(ClientID);
    NewClientInfoMsg.m_Silent = true;
    for(int p = 0; p < 6; p++)
    {
        ClientInfoMsg.m_apSkinPartNames[p] = m_apPlayers[ClientID]->m_TeeInfos.m_aaSkinPartNames[p];
        ClientInfoMsg.m_aUseCustomColors[p] = m_apPlayers[ClientID]->m_TeeInfos.m_aUseCustomColors[p];
        ClientInfoMsg.m_aSkinPartColors[p] = m_apPlayers[ClientID]->m_TeeInfos.m_aSkinPartColors[p];

        NewClientInfoMsg.m_apSkinPartNames[p] = m_apPlayers[ClientID]->m_TeeInfos.m_aaSkinPartNames[p];
		NewClientInfoMsg.m_aUseCustomColors[p] = m_apPlayers[ClientID]->m_TeeInfos.m_aUseCustomColors[p];
		NewClientInfoMsg.m_aSkinPartColors[p] = m_apPlayers[ClientID]->m_TeeInfos.m_aSkinPartColors[p];
    }

    //Disconnect Message
    CNetMsg_Sv_ClientDrop Msg;
    Msg.m_ClientID = ClientID;
    Msg.m_pReason = "colorchange";
    Msg.m_Silent = true;

    //Send to Other players
    for(int i = 0; i < MAX_CLIENTS; ++i)
    {
        if(!m_apPlayers[i] || i == ClientID)
            continue;
        ClientInfoMsg.m_Local = 0;
        NewClientInfoMsg.m_Local = 0;
        Server()->SendPackMsg(&Msg, MSGFLAG_VITAL|MSGFLAG_NORECORD, i);
        Server()->SendPackMsg(&NewClientInfoMsg, MSGFLAG_VITAL|MSGFLAG_NORECORD, i);
        Server()->SendPackMsg(&ClientInfoMsg, MSGFLAG_VITAL|MSGFLAG_NORECORD, i);
    }

    //Send to ClientID
    Server()->SendPackMsg(&Msg, MSGFLAG_VITAL|MSGFLAG_NORECORD, ClientID);
    ClientInfoMsg.m_Local = 1;
    NewClientInfoMsg.m_Local = 1;
    Server()->SendPackMsg(&NewClientInfoMsg, MSGFLAG_VITAL|MSGFLAG_NORECORD, ClientID);
    Server()->SendPackMsg(&ClientInfoMsg, MSGFLAG_VITAL|MSGFLAG_NORECORD, ClientID);
}
```

**Comment by nheir** [comment]
Feature, atm, the client renders your tee according to the client preference, the team (and ninja), it does not expect the server to set its own skin/color/whatever

**Comment by AssassinTee** [comment]
That can't be entirely true, because you can change the client color and skin from serverside once, the moment the client is joining.

**Comment by nheir** [comment]
right, the server sanitizes client info before entering, i was wrong

**Comment by oy** [comment]
There currently is no feature to update the tee render info. Could do sth for the next version.

**Comment by teoman002** [comment]
That would make some of us very happy!

**Comment by AssassinTee** [comment]
Would support zCatch, Infection, catch16 (colorcatch) and a lot of other community mods 👍

**Comment by AssassinTee** [comment]
i read the client code:
(src/game/client/gameclient.cpp line 632)
```
if(pMsg->m_Local)
{
	if(m_LocalClientID != -1)
	{
		if(g_Config.m_Debug)
			Console()->Print(IConsole::OUTPUT_LEVEL_ADDINFO, "client", "invalid local clientinfo");
		return;
	}
	m_LocalClientID = pMsg->m_ClientID;
	m_TeamChangeTime = Client()->LocalTime();
}
```

the `m_LocalClientID != -1` statement prevents updates from happening.
I guess you did so to prevent Servers from changing the ClientID and allowing more then 16/64 players.
you could change the statement to `if(m_LocalClientID != -1 && m_LocalClientID != pMsg->m_ClientID)`. This way you allow changes in the client info but prevent changes in the ClientID.

**Comment by teoman002** [comment]
Can you create a pull request for them to review?

**Comment by AssassinTee** [comment]
@oy 's update is why I didn't do a pull request, we got an own message for updating client infos now! Good work <3

**Comment by teoman002** [comment]
@AssasssinTee @oy

I want to port infclass.
Could you guys provide an example on how to use this new skin changing feature?

Let's say, I have a CPlayer object and I want to change its skin black or to a skinname.

I appreciate your help!

**Comment by Dune-jr** [comment]
@teoman002 This is offtopic.

The server-side function to change the skin of a player is added in the closing commit 975baec: https://github.com/teeworlds/teeworlds/blob/975baecb3d83d6f4b81c7009330c832fae8cb191/src/game/server/gamecontext.cpp#L282-L293

**Comment by teoman002** [comment]
That was not helpful, because you did not answer my question. I already know that the server is able to send skin updates to the player. (with this commit)
My question was, how the server can force change a skin. After that obviously SendSkinChange() must be called.

**Comment by Dune-jr** [comment]
I did not answer in detail because this is not the place for it.
In order to change a player's skin, update `m_apPlayers[ClientID]->m_TeeInfos` and call `SendSkinChange(ClientID)`. That is enough afaik.

**Comment by AssassinTee** [comment]
you may have trouble changing the skininfo to valid Information. The skins are defined in json files (where you can find the names) and TeeInfo 1-6 are `body`, `marking`, `decoration`, `hands`, `feet`, `eyes`. 
The colors are **NOT** RGB, but HSL.

So if you want to change the body color to black, you have to change `m_aSkinPartColor[0]` to the black HSL value and you have to set `m_aUseCustomColors[0] = 1`, so you activate custom colors

GL Assa
