### ISSUE TITLE
Make --console a console option

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2078]
I was wrong about https://github.com/teeworlds/teeworlds/pull/1593. It seems like the Windows console still blinks on release builds, so there is no benefit in not having a --console option (@nheir ).

It would be nice to have this an option that can be put in settings.cfg, because we have a lot of Windows users that ask for help, and it is difficult to instruct them to start within the console.

I am not sure if that really helps because the console will still shutdown quickly... So we would need an additional option to dump the console logs to a .log file (if it doesn't already exist)

**Comment by ChillerDragon** [comment]
So far I never had problems telling a windows user to start teeworlds from commandline to keep the console log even if it crashed.

But yes please bring the console option back :) I am sick of using my weird alias linky thing to start tw 0.7
