### ISSUE TITLE
Index 22 rule of automap for grass main is not correct

### ISSUE THREAD

**Issue by Fudgyking** [teeworlds/teeworlds#2089]
Here's some example of what automapper does. You can see that some tiles of ID 20 should be of ID 22.

![screenshot_2019-04-11_20-41-30](https://user-images.githubusercontent.com/5041807/56004625-573f5c80-5c9a-11e9-892b-d09a9dc24f9b.png)

I saw a weird looking comma in the rule for index 20, as if the condition was a WIP, maybe it has to do with that?

**Comment by Dune-jr** [comment]
The automapper rules could largely be improved, yes. Winter dark is not good either iirc.

If you find the time for it, please submit any improvements :)
