### ISSUE TITLE
Creating a server with a lot of dummies crashes it

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2098]
`./teeworlds_srv dbg_dummies 30` crashes.
Will have a look later and fill in details

**Comment by Dune-jr** [comment]
> [quakenet] \<Oy\> or clamp number of dummies to max clients
> [quakenet] \<Dune\> - online clients
> [quakenet] \<Oy\> Savander: https://github.com/teeworlds/teeworlds/blob/master/src/game/server/gamecontext.cpp#L1520 -\> for(int i = 0; i \< g_Config.m_DbgDummies && i \< Server()-\>MaxClients(); i++)
> [teeworlds] \<Savander\> That doesn't fixed the crash problem :PP [...] server says: `game\server\player.cpp(11): already used`
> [quakenet] \<Oy\> hm, you shouldn't be able to connect when the server is full with dummies
> [quakenet] \<Oy\> engine doesn't know about the dummies
> [...]
> [quakenet] \<Oy\> other issue then

**Comment by oy** [comment]
Fixed by 27cb488f927ebb68d73e5462b68806b16a3d0cf9
