### ISSUE TITLE
Can't compile with latest bam build

### ISSUE THREAD

**Issue by Fisico** [teeworlds/teeworlds#2101]
I am not able to compile the latest version with the latest bam build.

https://pastebin.com/M6Dt96YW

There is a mess in the download script.

The process cannot access the file because it is being used by another process: 'teeworlds-libs-4bf6dbc8c9f9b2fa89b2b5be1928f5e85bca01e6/sdl\\include\\SDL_opengles2_gl2ext.h'

Windows 10
Visual Studio 2017 Com
Bam from teeworlds/bam

**Comment by Fudgyking** [comment]
Ye it does that for me too, but after compiling in 2-3 passes those errors go away lol
Definitely annoying though.

Windows 7

**Comment by Fisico** [comment]
@Fudgyking you are right... if i run my compile script 3 times it works... very strange
