### ISSUE TITLE
Settings icon is not centered

### ISSUE THREAD

**Issue by Sonix-** [teeworlds/teeworlds#2103]
![screenshot_2019-04-21_08-16-15](https://user-images.githubusercontent.com/2030615/56466222-b9246280-640e-11e9-9c18-263d48c851d2.png)

**Comment by Dune-jr** [comment]
![image](https://user-images.githubusercontent.com/355114/56665585-9ca45680-66aa-11e9-8fd0-377ce877adb3.png)

This is what I get when replacing the UTF-8 character with a `X` (just an example). It's a bit better, but not completely centered, right? So I guess it could be an issue with the way the centered DoLabel is done?

menus.cpp
```cpp
UI()->DoLabel(&Temp, pText, Temp.h*ms_FontmodHeight, CUI::ALIGN_CENTER);
```
ui.cpp
```cpp
void CUI::DoLabel(const CUIRect *r, const char *pText, float Size, EAlignment Align, int MaxWidth, bool MultiLine)
{
	switch(Align)
	{
	case ALIGN_CENTER:
	{
		float tw = TextRender()->TextWidth(0, Size, pText, MaxWidth);
		TextRender()->Text(0, r->x + r->w/2-tw/2, r->y - Size/10, Size, pText, MaxWidth, MultiLine);
		break;
	}
```

Everything looks fine to me. Maybe the UTF-8 character has a poorly recordedsize?

**Comment by AssassinTee** [comment]
str_length("\xE2\x9A\x99") == 3
https://stackoverflow.com/questions/11034058/strlen-and-utf-8-encoding
But i can't confirm, that thats the problem. I changed the str_length function in system.c and it didn't help

**Comment by oy** [comment]
Good catch 👍 
Probably related somehow.

**Comment by AssassinTee** [comment]
After Debugging a really long time, i found out, that it's not (as far as I can tell) related to str_length.
In TextEx the cursor counts the Characters and Glyphs and (if you don't render) you will get 3 characters and 1 glyph.

I predict the TextWidth is not correct for the settings icon and thus not rendering it perfectly central.
But it does that with other unicode characters, too.

I tested https://www.fileformat.info/info/unicode/char/26ab/index.htm and https://www.fileformat.info/info/unicode/char/2638/index.htm

![](https://www.fileformat.info/info/unicode/char/26ab/medium_black_circle.png)
![](https://www.fileformat.info/info/unicode/char/2638/wheel_of_dharma.png)
