### ISSUE TITLE
0.7.3 source tarball is not compressed

### ISSUE THREAD

**Issue by akien-mga** [teeworlds/teeworlds#2104]
Up until 0.7.1 source archives were provided as both .zip and .tar.gz.
With 0.7.2, the .tar.xz compression was added, which is nice as it's more efficient than gzip.

For 0.7.3 however, the source tarball is only an uncompressed `.tar`, not using either gzip or XZ.

**Comment by Dune-jr** [comment]
Yeah, I agree, it would probably be nice to replace the tar archive with something compressed.

So apparently, since 0.7.2 we no longer link the github automated archive. iirc this because we need to have an official zip that contains submodules (languages and maps).

**Comment by oy** [comment]
Fixed for 0.7.3.1
