### ISSUE TITLE
Crash not finding easter.png

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2105]
> [5cbcb899][game/png]: failed to open file. filename='mapres/easter.png'
> 
> [2]+  Speicherzugriffsfehler  (Speicherabzug geschrieben) ./build/x86_64/debug/teeworlds
> user@user

Hi its me again,
I already know how to fix it (by updating the submodules), but the client shouldn't crash.
Happy easter,
Assa

**Comment by Dune-jr** [comment]
Hi,

`easter.png` is not part of the submodules. How is that related to the crash?

**Comment by AssassinTee** [comment]
hmm, can't reproduce, I have no idea what happens, it just happens sometimes when I enter a server with a clean custom build client

**Comment by AssassinTee** [comment]
Something is broken <.<
[image of broken teeworlds](https://i.imgur.com/s3FEsOq.png)

**Comment by Dune-jr** [comment]
That is strange. I am aware there is a double free crash in maplayers.cpp that randomly happens after loading a lot of maps with easter eggs; but not finding `easter.png` is new to me.

**Comment by oy** [comment]
Should be fixed too
