### ISSUE TITLE
Out of tree build broken by version parsing

### ISSUE THREAD

**Issue by AMDmi3** [teeworlds/teeworlds#2108]
You use relative path in version extraction command:

```cmake
file(STRINGS src/game/version.h VERSION_LINE
  LIMIT_COUNT 1
  REGEX GAME_RELEASE_VERSION
)
```

this breaks out of tree builds (which are the default for most packaging systems, I believe), because there's no `src/game/version.h` in the build directory. You cannot use `PROJECT_SOURCE_DIR` either because project is defined latter and it needs version defined. I've hacked it temporary by using `CMAKE_CURRENT_SOURCE_DIR`, however the right solution would be to define version in CMake only, and generate the _header_ out of it, not the other way around.

**Comment by heinrich5991** [comment]
I'm only using out-of-tree builds since the inception of CMake, are you sure that this is the problem? It sounds more like a problem fixed by the commit you recently commented on.

**Comment by heinrich5991** [comment]
Indeed, using the version I've currently checked out (not the current one), I can do an out-of-source build just fine, and this command also exists in that version.

I think your problem lies elsewhere.

**Comment by AMDmi3** [comment]
You are right, must be insufficient cleanup of build directory on my side. Sorry for the noise. I'd still recommend to set the version in CMake though.
