### ISSUE TITLE
Build fails on s390x

### ISSUE THREAD

**Issue by limburgher** [teeworlds/teeworlds#2111]
See log.
[build.log](https://github.com/teeworlds/teeworlds/files/3121886/build.log)

**Comment by Dune-jr** [comment]
Looks like the issue is here:

https://github.com/teeworlds/teeworlds/blob/f4a18aa6aeb29634b60565c4ebf0b99777551636/src/engine/shared/datafile.cpp#L174-L176

```
../src/engine/shared/datafile.cpp: In member function 'bool CDataFileReader::Open(IStorage*, const char*, int)':
../src/engine/shared/datafile.cpp:175:98: error: no matching function for call to 'min(unsigned int, int64&)'
  175 |  swap_endian(m_pDataFile->m_pData, sizeof(int), min(static_cast<unsigned>(Header.m_Swaplen), Size) / sizeof(int));
      |                                                                                                  ^
In file included from ../src/engine/shared/datafile.cpp:4:
../src/base/math.h:85:32: note: candidate: 'template<class T> T min(T, T)'
   85 | template <typename T> inline T min(T a, T b) { return a<b?a:b; }
      |                                ^~~
../src/base/math.h:85:32: note:   template argument deduction/substitution failed:
../src/engine/shared/datafile.cpp:175:98: note:   deduced conflicting types for parameter 'T' ('unsigned int' and 'long long int')
  175 |  swap_endian(m_pDataFile->m_pData, sizeof(int), min(static_cast<unsigned>(Header.m_Swaplen), Size) / sizeof(int));
      |          
```

**Comment by Dune-jr** [comment]
@limburgher can you try with this patch? https://github.com/teeworlds/teeworlds/commit/3079436c35623833bbca1480daca8b9b0b3485f3

**Comment by limburgher** [comment]
Fails:
[build.log](https://github.com/teeworlds/teeworlds/files/3122101/build.log)

**Comment by Dune-jr** [comment]
Looks like I didn't edit on time, sorry ^^"

**Comment by limburgher** [comment]
Also failed: 
[build.log](https://github.com/teeworlds/teeworlds/files/3122134/build.log)

**Comment by Dune-jr** [comment]
So basically we have 
```cpp
in function `int CServerBan::BanExt<XXXXXX >(XXXXXX*, XXXXXX::CDataType const*, int, char const*):`
server.cpp:197: undefined reference to `int CNetBan::Ban<XXXXXX >(XXXXXX*, XXXXXX::CDataType const*, int, char const*)'
```

because this function:
https://github.com/teeworlds/teeworlds/blob/07fa835e0f9435de1b9b67510d6bae3aa1bd2645/src/engine/server/server.cpp#L157-L160

calls this function:
https://github.com/teeworlds/teeworlds/blob/07fa835e0f9435de1b9b67510d6bae3aa1bd2645/src/engine/shared/netban.cpp#L293-L295

The templates seem to strictly match but somehow the compiler doesn't match?
Got any clue, @oy?

**Comment by oy** [comment]
@Dune-jr  Could try to explicitly instantiate that function like done with MakeBanInfo https://github.com/teeworlds/teeworlds/blob/07fa835e0f9435de1b9b67510d6bae3aa1bd2645/src/engine/shared/netban.cpp#L621

**Comment by oy** [comment]
Adding
`template int CNetBan::Ban<CNetBan::CBanPool<NETADDR, 1> >(CNetBan::CBanPool<NETADDR, 1> *pBanPool, const NETADDR *pData, int Seconds, const char *pReason);
template int CNetBan::Ban<CNetBan::CBanPool<CNetRange, 16> >(CNetBan::CBanPool<CNetRange, 16> *pBanPool, const CNetRange *pData, int Seconds, const char *pReason);`
at the end helps?

**Comment by Dune-jr** [comment]
It builds for me.
Maybe @limburgher could try to apply (again) https://github.com/Dune-jr/teeworlds/commit/d0bfb6e9c651a8484d6f3bc2967495edb7a5307d ?

**Comment by limburgher** [comment]
Failed.
[build.log](https://github.com/teeworlds/teeworlds/files/3127440/build.log)

**Comment by Dune-jr** [comment]
Both https://github.com/teeworlds/teeworlds/commit/3ae7e85 and https://github.com/Dune-jr/teeworlds/commit/d0bfb6e9c651a8484d6f3bc2967495edb7a5307d must be applied. Sorry if that was not clear.

It is equivalent to PR https://github.com/teeworlds/teeworlds/pull/2114

**Comment by limburgher** [comment]
Ah, that worked. Thank you!
