### ISSUE TITLE
TeeComp board problems

### ISSUE THREAD

**Issue by Fudgyking** [teeworlds/teeworlds#2112]
Right now the newly added TeeComp stats highlight your tee instead of the tee you're spectating.
Is it supposed to show spectators in the stats in the first place?

Also for some reason, when I close the map editor, the stats board appears for a short time. If I'm testing a map on a LAN server, when I save the map and exit the editor before the server reloads the map, the stats board appears and stays visible until I press the associated key.

**Comment by Sonix-** [comment]
As spec statsboard should be still available and highlight only the player you are following and ofc no highlight if im free view

**Comment by Dune-jr** [comment]
> As spec statsboard should be still available and highlight only the player you are following and of course no highlight if in free view

Yeah, that's because the statboard was not updated with some scoreboard changes, I'm taking care of that.

> Is it supposed to show spectators in the stats in the first place?

You mean purple tees I assume? I don't know. Probably should hide them?

**Comment by Fudgyking** [comment]
Well imo none of the possible stats are relevant for spectators so there's no reason to put them in the board.

**Comment by Dune-jr** [comment]
> Well imo none of the possible stats are relevant for spectators so there's no reason to put them in the board.

Alright, no specs then

> Also for some reason, when I close the map editor, the stats board appears for a short time. If I'm testing a map on a LAN server, when I save the map and exit the editor before the server reloads the map, the stats board appears and stays visible until I press the associated key.

This is probably because the default bind for the statboard is "e".
