### ISSUE TITLE
Disable nethash checks?

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2121]
#2118 broke the nethash again

**Comment by AssassinTee** [comment]
A lot of servers simply overwrite it so player can join.
See for Example:
https://github.com/AssassinTee/catch64/blob/master/src/game/version.h

**Comment by oy** [comment]
That would be really bad, cause they're there for a reason. You can easily break prediction and/or the whole game by doing the wrong stuff. You have to know what you're doing and be careful when messing around with these things.

**Comment by AssassinTee** [comment]
This argument is weak, since you can mess with a lot of stuff in teeworlds. And I think anybody who wants to mess around with the protected code, will do it.

**Comment by heinrich5991** [comment]
> That would be really bad, cause they're there for a reason.

That's not the thing that prevents you from doing it though. As said in the pull request, it's one of the things often hardcoded in mods.

This breaks Teeworlds development from time to time, pull requests are inspected for backward-compatibility anyway (← one could make the argument here that a changing nethash alerts the reviewer to check more carefully).

Is there an upside besides "it's there for a reason"? Has it helped in the past?

**Comment by oy** [comment]
Of course you can mess around without the nethash, that doesn't prevent you from doing it, but it's a good indicator if sth is wrong.
Like the network message have to keep the same order and variables. If you change sth there it might look good when trying it but sometime you'll end up with a problem.
