### ISSUE TITLE
Feature for buffered Chat

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2127]
Some visual updates for buffered chat:
Chat:
![](https://i.imgur.com/z7GFmaW.png)
Teamchat:
![](https://i.imgur.com/V01QEq0.png)
Whisper:
![](https://i.imgur.com/33v6stq.png)

Should I change anything?

**Comment by Dune-jr** [comment]
It's going good but I think there is room for visual improvements.


### Helper text
- The callvote bubble does not use ' ' around the key name and the chat commands also do not use ' ', so I would advise not to:
![image](https://user-images.githubusercontent.com/355114/57046162-e6270f80-6c6f-11e9-9a14-823c53a8c176.png)
- The chat is carefully color coded and I would advise not to add more colors if unnecessary. In my opinion the helper text should be white or gray (like the already existing helper text for chat commands). I understand that the blue comes from this inspiration image that I sent:
![image](https://user-images.githubusercontent.com/355114/57046240-1e2e5280-6c70-11e9-983e-dea50c58fdf2.png)
but this blue is in the color code for that game, not for Teeworlds
- I would also keep the same text, "resume chatting" sounds better to me
- At the contrary, the All/Team/Whisper are all white now? It's confusing, I was wondering why the chat mode was "nameles". One should play on the alpha, but not on the color.
- The helper text should have some margin, it feels like 0px on the edge right now

### Misc
- The chat bubble does not seem to have alpha (or at least not nearly as much as the rest) so it doesn't blend in well.

**Comment by AssassinTee** [comment]
You have seen everything, how i actually programmed it

- The helper text was really 0px on the edge
- Chat bubble had full alpha
- Made a gray box for buffered text

I fixed all of it
Chat All:
![](https://i.imgur.com/CRoG5c4.png)
Teamchat:
![](https://i.imgur.com/rd9juSP.png)
Whisper:
![](https://i.imgur.com/nYte5He.png)

**Comment by Dune-jr** [comment]
- The text alpha looks good to me.
- I think the alpha wasn't completely applied on the chat symbol though. It is difficult to see without looking at the code but I think the logo at least is 100% alpha.
- The helper text is quite hard to read. I don't think using grey is best. What does white give? Or some in-between gray?
- The 0px margin is not great but putting it too far right is not good either. Please try with a long broadcast "WWWWWWW..." to see how much space we have.
- Cropping spectators to "spectat" looks very odd (at least to me)

**Comment by AssassinTee** [comment]
- I was wondering about that chat symbold, too
- I will try a lighter gray :)
- The cropping of spectators is not done by me? I don't know why it is, looks like I have no tranlations installed
