### ISSUE TITLE
[bam] X does not exist and no way to generate it

### ISSUE THREAD

**Issue by LordSk** [teeworlds/teeworlds#2136]
I'm on a brand new PC/installation, cloned teeworlds, built teeworlds/bam, and ran bam inside visual studio command prompt. I get this error message.

```
bam: error: 'other/freetype/windows/lib64/freetype.dll' does not exist and no way to generate it
bam: error: a build step failed
```

Some dependency issue perhaps?

**Comment by Dune-jr** [comment]
That's a common issue I get when switching branches :/

**Comment by LordSk** [comment]
Workaround; comment these lines

https://github.com/teeworlds/teeworlds/blob/master/bam.lua#L396-L399

Build, uncomment them and rebuild.
