### ISSUE TITLE
where to change render distance

### ISSUE THREAD

**Issue by teoman002** [teeworlds/teeworlds#2137]
Hello, we are working on a project that requires a big circle of `CNetObj_Projectile`
But when the circle is too big, it is chopped into 4 parts, due to limited render distance.

I already searched in the client for source code that is responsible for that, but I ended my search with the `OnRender() `method in `game/client/components/items.cpp` which did not include any variable about render distance.

There is also the file `render.h / .cpp` in `game/client/`
and `graphics.h` in `engine/` folder

Do you guys know where the render distance is located or how it works?

**Comment by fokkonaut** [comment]
seems more like the amount of projectiles is too large rather than the render distance, since shot projectiles also dont disappear on that "line"

**Comment by nheir** [comment]
Data sent by the server are clipped so that the client receives only a window of data centered on its view point

**Comment by Dune-jr** [comment]
Questions about the code are best fit in the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2) or directly asked in [our official IRC](https://www.teeworlds.com/?page=docs&wiki=rules/irc_rules). The issue system is not well equipped to provide help with programming around the game.

**Comment by teoman002** [comment]
Alright, feel free to close this issue!
