### ISSUE TITLE
Add a Console command to echo a client-side chat message

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2142]
Since https://github.com/teeworlds/teeworlds/pull/2042 implemented client-side chat messages:

![image](https://user-images.githubusercontent.com/355114/58248199-d45ef680-7d5b-11e9-8661-6a8e092c67ad.png)

It could be useful to have an f1 command similar to `echo` that prints those messages. Here is a use case:

> n000b Today at 9:55 AM
i whisper to myself if i activate some binds so i know if it activated or deactivated:grimacing:

**Comment by Robyt3** [comment]
Any suggestions for a name? `echo_chat`?

**Comment by Dune-jr** [comment]
`print`, `info`, `alert`?

**Comment by Robyt3** [comment]
Since we already have `say` and `say_team`, maybe just `say_self`?

**Comment by Dune-jr** [comment]
Makes sense to me
