### ISSUE TITLE
Scoreboard spectator bug

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2143]
See image
![img](https://i.imgur.com/KwN66eY.jpg)

**Comment by Dune-jr** [comment]
This is a bug with IDs in general and not with the scoreboard UI in particular, I believe

**Comment by AssassinTee** [comment]
what wonders me about this is that the ID-UI-Rekt and the ID-Text (Number e.g. 8) are disconnected

**Comment by Dune-jr** [comment]
Yes, that is the bug with IDs, wrong width calculation

**Comment by Dune-jr** [comment]
@ChillerDragon @oy do you remember if there was a LineWidth fix since 0.7.3?

**Comment by oy** [comment]
@Dune-jr yeah, there was a mixup fixed 1ca020ea195b079bcc26aee28774eb79bada9e87 Sometimes width was handled as Line width and sometimes as string length. Dunno if that effcts this.
