### ISSUE TITLE
Trim trailing whitespaces of (Remote)console commands

### ISSUE THREAD

**Issue by sepulzera** [teeworlds/teeworlds#2147]
Executing the rcon command "sv_gametype ctf " should set the gametype to CTF (after a reload). Instead, the default gametype DM gets activated, due to the trailing whitespace.
Leading whitespaces already get trimmed.

-> Trim trailing whitespaces of console command's input data.

**Comment by oy** [comment]
There's a difference: There're no commands starting with a whitespace, so they can be removed automatically. But whitespaces can be part of string parameters and might be essential so removing them automatically could raise problems.

**Comment by sepulzera** [comment]
I was talking about leading whitespaces before the command arguments. Sorry if I wasn't clear enough.

Like "sv_gametype &nbsp;&nbsp;ctf " (3 whitespaces before and 1 after ctf) gets extracted to  "sv_gametype" and " &nbsp;ctf " (2 whitespaces before and 1 after ctf) AND finally trimmed to "ctf".

At least I believe that this is what is happening. After all, the leading whitespaces of "ctf" are gone and the gametype correctly set. But "sv_gametype ctf " will fail and set DM.

**Comment by sepulzera** [comment]
As the fix was reverted, this issue should be reopened. Shouldn't it?
