### ISSUE TITLE
Its not possible to abort the restart timer

### ISSUE THREAD

**Issue by Sonix-** [teeworlds/teeworlds#2153]
Join a server, open up F2 and type in restart 20 to restart the game in 20 seconds.. the countdown starts --> Open up F2 again to abort the timer "restart 0" and it cancels the timer but inits the "Game starts in" timer which restarts the game resetting scores and all practically acting like an immediate restart.

Solution would be to remove the game timer after aborting restart, just clear the warmup countdown like its always been.

**Comment by sepulzera** [comment]
```restart -a``` to abort the timer 😺 

But ```restart 0``` should be fine, too. Though as a user I would expect it to restart immediately.

Regardless of the implementation, it should always be possible to revert user actions, like starting a restart timer. (+1)
