### ISSUE TITLE
Closing scorboard

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#2158]
Sometimes the scoreboard doesn't close when releasing the associated bind.

**Comment by Dune-jr** [comment]
Never experienced that, not sure what would cause it

**Comment by oy** [comment]
Just happens with vsync enabled I think. Maybe the input gets lost somehow. Though that shouldn't happen...

**Comment by Dune-jr** [comment]
Got a laggy, very underclocked computer, and it happens all the time now

**Comment by Dune-jr** [comment]
I will update and report if the bug ever occurs again
