### ISSUE TITLE
Please revert chat hide in menu

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2161]
Could we please get the chat back? Also in menu and in demo editor and everywhere else where it was and where it was usefull. Everytime I write bye in chat and go to menu to disconnect i hear the chat ping but I don't know if the message is "ok bye" or "please wait". Also there is plenty of space so why hide it? It was also annoying when someone explained the vote menu to me in chat and I had to tab back in all the time. Also scanning demos for chat messages became really annoying.

It simply is a downgrade.

Here is the change by @SushiTee from 2012 that removed chat in menu:
https://github.com/teeworlds/teeworlds/commit/c74637ae6ded59a2eb31518f9cc7739d4e3b8afd#diff-da8e51385055fcc863833513a3930b15R392

**Comment by sepulzera** [comment]
Imho those are several complaints mixed:
1. Make a bind to write 'bye' and quit the game. As you will leave instantly, you can not receive any reply. Joke aside: I do not see how not hiding the chat would fix your real problem here. What if the other player was just about to send the message, but you left 1 ms earlier? What you want is a server-independent chat, like Steam Friends communication, that would even send you the message after you logged out (next time when you come online).
2. You needed someone to explain the vote menu. Could you please elaborate on what exactly was not intuitive? That should probably get improved.
3. Scanning demos for chat messages doesn't sound like a real use case to me. Btw. I didn't know that Teeworlds has a demo EDITOR, but only a demo viewer? Could you please provide a screenshot?

I do agree that it feels strange to hide the chat when pressing ESC, as the opened top menu doesn't interfer with the chat at all. But it does make sense to hide complexity to the user, e. g. different UI parts that shouldn't be needed for the current task.

**Comment by ChillerDragon** [comment]
@sepulzera 

1. I usually wait in menu until the message arrives. Trust me it worked fine the last 6 years.

2. A custom mod had a lot of options and features in the vote menu.

3. It is a real use case. I can only repeat that I am doing this since years. And yes it is a demo viewer sorry. For example if you search a specific moment that was epic. You can play with the speed while scanning the chat reacting to it. Or as a moderator/admin you quickly scan chat messages also while switching between replay speeds in the menu. So you can see who complained about what while looking at what actually happened.

Imo chat in the background is not adding complexity to the ui. And it mostly makes sense to be able to read it. Especially if you also hear the sound it makes the ux worse and confusing. Trust me I am a big fan of simple ui. But rather remove everything else than the chat please, because it is very important.

**Comment by sepulzera** [comment]
1. I assume you refer to the chat bubble that appears while typing. That would basically only work if your ViewPort is at the other tees position. Not very reliable, don't you think?
2. Ok, at least it is no specific vanilla UX issue. But opening a menu tab would probably overlap the chat on lower resolutions. At this point the chat should be hidden, even if the chat would stay when only opening the menu via ESC.
3. I would need at least a screenshot for a proper response. At this point I would agree that the chat should stay while using demo viewer functionality, as it is part of the demo.

**Comment by ChillerDragon** [comment]
@sepulzera

1. If you really are curious if the person is chatting sure you can spec that tee before leaving and opening the window. Sometimes that is the case because you chill next to each other already (yes stuff like lol-town and people just hanging out to chat is a thing). Or you spectate the player you are interested in anyways. But usually what I do and I assume many others do is: write something like bye in chat open menu and wait 3 seconds before clicking disconnect to see the bye from 1 or 2 others. No chat bubble needed.

2. Even overlap is no problem because you can read the chat just fine. Even if it is on the border and on shitty background.

3. Sushi probably thought of cleaning the ui in menu. Which is a good idea. But I guess he didn't really think about the importance of chat. And I assume he forgot, that demo player is seen as menu. Because why would you hide the HUD in the demo. Especially if you look at pro plays you want to stay in the demo menu and still see the health for example. But the HUD in demo player should be another issue. Less important than the chat imo.

Here some screenshots how it would look like with the fix:

![screenshot_2019-06-24_19-06-18](https://user-images.githubusercontent.com/20344300/60038098-a1d64f80-96b3-11e9-8464-b87c4ee136a0.png)
![screenshot_2019-06-24_19-08-32](https://user-images.githubusercontent.com/20344300/60038099-a1d64f80-96b3-11e9-9b63-7047efc4acf2.png)
![screenshot_2019-06-24_19-05-35](https://user-images.githubusercontent.com/20344300/60038100-a1d64f80-96b3-11e9-91fb-226c30cdbe19.png)
![screenshot_2019-06-24_19-05-55](https://user-images.githubusercontent.com/20344300/60038101-a26ee600-96b3-11e9-83c0-97cd6552ce87.png)

**Comment by oy** [comment]
The chat was disabled when showing the menu cause there were problems reading the menu otherwise.

There shouldn't be a chat sound when chat is not shown..

**Comment by sepulzera** [comment]
Imo the demo player should display the chat properly, even while using demo functionality. Eventually move this to a second issue?

Regarding the ingame chat:
As soon as a menu tab gets opened the chat shouldn't be visible anymore. Maybe we could keep the chat visible for the simple menu (ESC only)? Hiding the chat there doesn't make much sense.

**Comment by sepulzera** [comment]
> There shouldn't be a chat sound when chat is not shown.. - oy

That would be very confusing! The sound is there for a purpose. It is like removing bullet sounds when you don't actually see it. Huh.

But that should definitely be a separate issue. (Spoiler: I would vote to remove the normal chat message sounds and only keep the PM sounds).
