### ISSUE TITLE
Binds blocked by shortcuts

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2165]
https://github.com/teeworlds/teeworlds/commit/9183584dab2e746162ef2883c2427901fc70d5b4

The new menu shortcuts overwrite settings binds. Try for example to settings -> controls and bind something on the key 'v'.

**Comment by Dune-jr** [comment]
I don't think ingame menus should have shortcuts

**Comment by oy** [comment]
How do they block the binds? Binds shouldn't work when the menus are active.

**Comment by ChillerDragon** [comment]
@oy this: https://github.com/teeworlds/teeworlds/commit/9183584dab2e746162ef2883c2427901fc70d5b4

added shortcuts for the menu. So if you press 'v' for example you go to votes. But under settings -> controls you might wanna press v to "bind" the key.

**Comment by oy** [comment]
Ah, so you can't bind sth in the settings menu when ingame.
