### ISSUE TITLE
dm8 snow animation not smooth after 10000 minutes

### ISSUE THREAD

**Issue by sepulzera** [teeworlds/teeworlds#2170]
I joined a server with dm8 running. The match was ongoing for about 10373 minutes. Everything was fine, except the snow animation. It felt like lower fps.

**Comment by Sonix-** [comment]
just end the round?

**Comment by sepulzera** [comment]
Good idea. My first guess was to reboot the whole server. [/sarcasm] Not really constructive, imho.

If a round can get longer than 10000 minutes, then it should work without any bugs. Maybe the bug is minor important for being a really rare case, but it is anyway a bug.

**Comment by ChillerDragon** [comment]
@Sonix- might be a rare case but still some public servers have such long rounds if the scorelimit is high and players rage quit before they finish a round.

Or some modifications like city usually never end rounds. It would be nice if the animations stay clean :)

**Comment by oy** [comment]
Looks like this one #63

**Comment by sepulzera** [comment]
Just this time it is server sided.

**Comment by Dune-jr** [comment]
Is it?

**Comment by sepulzera** [comment]
Well, maybe not. You made me thinking. Just ignore that comment, I have no clue how the animations are being calculated.

**Comment by oy** [comment]
It's done client-sided.

**Comment by TsFreddie** [comment]
Is this fixed?

**Comment by Robyt3** [comment]
I don't think it is. I found a server with > 7400 minutes on dm3 and the snow animation was already somewhat unsmooth: [issue2170_dm3.zip](https://github.com/teeworlds/teeworlds/files/5467170/issue2170_dm3.zip)
