### ISSUE TITLE
m_pController->OnPlayerInfoChange(); not called, when player changes skin

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2179]
When someone changes his/her skin ingame, there is no easy way for the mod to know that the player changed his/her skin, thus I propose this small change.

I think this could be helpful for everyone modding the game using virtual functions that do not interfere much with vanilla logic.

gamecontext.cpp:1046

maybe something like this(would need OnPlayerInfoChange() to return a bool):
```
// update all clients
if (m_pController->OnPlayerInfoChange(pPlayer);)
{
    for (int i = 0; i < MAX_CLIENTS; ++i)
        {
            if (!m_apPlayers[i] || (!Server()->ClientIngame(i) && !m_apPlayers[i]->IsDummy()) || Server()->GetClientVersion(i) < MIN_SKINCHANGE_CLIENTVERSION)
                continue;
                SendSkinChange(pPlayer->GetCID(), i);
        }
}
```

or simply at the end of the case:

```
for(int i = 0; i < MAX_CLIENTS; ++i)
{
    if(!m_apPlayers[i] || (!Server()->ClientIngame(i) && !m_apPlayers[i]->IsDummy()) || Server()->GetClientVersion(i) < MIN_SKINCHANGE_CLIENTVERSION)
        continue;
        SendSkinChange(pPlayer->GetCID(), i);
}
m_pController->OnPlayerInfoChange(pPlayer);
```

**Comment by AssassinTee** [comment]
> When someone changes his/her skin ingame, there is no easy way for the mod to know that the player changed his/her skin, thus I propose this small change.

https://github.com/AssassinTee/catch64/blob/master/src/game/server/gamecontext.cpp#L1308

There is, just catch the message?
