### ISSUE TITLE
Disable teamchat in non-team games

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2184]
Maybe it would be less confusing if teamchat was disabled client-side in non-team games. Thoughts?

**Comment by oy** [comment]
You still have different teams (ingame, spectators) in non-team games that you want to address specifically. Sometimes you join spectators to discuss something in teamchat so you don't disturb the other players.

**Comment by Dune-jr** [comment]
Good point, I forgot about that.
