### ISSUE TITLE
teeworlds.exe is not a valid Win32 application

### ISSUE THREAD

**Issue by pmaprog** [teeworlds/teeworlds#2186]
I get the error when I run teeworlds 0.7.3 win32 version on my WinXp x86

**Comment by Rei-Tw** [comment]
Upgrade to windows 10.

**Comment by Dune-jr** [comment]
Hey. I think the latest version is unfortunately not compatible with XP, forgot why. Maybe building it yourself would remedy to this?

We should add this to the FAQ.

**Comment by pmaprog** [comment]
Yes, I compiled with MinGW and it started. Thanks!
