### ISSUE TITLE
Survival spawn in relevant gamemode

### ISSUE THREAD

**Issue by nheir** [teeworlds/teeworlds#2187]
Should this part (or a subpart) be moved to lts/lms.cpp ?

https://github.com/teeworlds/teeworlds/blob/960b01667d72b29a3b0ea152267ffe31faac050a/src/game/server/gamecontroller.cpp#L248-L262

**Comment by Dune-jr** [comment]
Yeah, surely another survival mode wouldn't necessarily have the same parameters. I think the function should just be

https://github.com/teeworlds/teeworlds/blob/960b01667d72b29a3b0ea152267ffe31faac050a/src/game/server/gamecontroller.cpp#L265-L270

**Comment by AssassinTee** [comment]
Shouldn't the ammount of ammo for each weapon be a gamemode variable?
This makes me think of the question if we should add gamemode specific variables (which I think we should)
