### ISSUE TITLE
'Controller support' is missing from Steam page

### ISSUE THREAD

**Issue by tedstoychev** [teeworlds/teeworlds#2189]
In v0.7.3 controller (joystick) support was added to the game [1] but this information ('Full controller support') is missing in the game's Steam page [2].

[1] https://steamcommunity.com/games/380840/announcements/detail/1642034851150697506  
[2] https://store.steampowered.com/app/380840/Teeworlds/

**Comment by Dune-jr** [comment]
That is right, but controller support is experimental:

- There is no UI for it, so you can't expect someone to figure out the commands by themselves
- There are some issues remaining (https://github.com/teeworlds/teeworlds/issues/2056)
- With some joysticks, there simply aren't enough buttons to play Teeworlds

So I think it is not a good idea (yet) to add this to the Steam page

**Comment by tedstoychev** [comment]
Thanks for the clarification. I'm closing the issue.
