### ISSUE TITLE
Buggy double emoticons

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2190]
when entering `emote 16` in f1, you will have 2 emoticons above your head

**Comment by Dune-jr** [comment]
Yup

![image](https://user-images.githubusercontent.com/355114/63060807-95bc8080-bef3-11e9-99ac-c6c7182ec503.png)

**Comment by oy** [comment]
Good catch 👍

**Comment by GutZuFusss** [comment]
Yeah, very good catch! I wonder how you found out about it... 🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔
