### ISSUE TITLE
Do not register defaults in settings.cfg

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2201]
This lets us change the defaults on future new releases.

**Comment by heinrich5991** [comment]
Note that we should record settings explicitly set to the default values.

I.e. have a flag that tells us whether the user set the value or if they haven't.

**Comment by Dune-jr** [comment]
That sounds like a large code overhead. Is it really that important to remember that a user manually tried a setting back and forth?

**Comment by oy** [comment]
How do you want to determine that a user set the default value manually?

**Comment by heinrich5991** [comment]
You can't for the past, but you can for the future. If it's been changed at all, it's been user-set.

Mh. *shrug*

In the future, if we apply a "new default" for a boolean config variable without keeping track of whether the user set it explicitly, it simply becomes the value for all users (which they can change later).

**Comment by Dune-jr** [comment]
> In the future, if we apply a "new default" for a boolean config variable without keeping track of whether the user set it explicitly, it simply becomes the value for all users (which they can change later).

My personal take on that is that it is fine

**Comment by oy** [comment]
How about using the reset feature? Then it's like it never has been changed right?

The tricky thing about manually setting the default value is that you don't know:
- if the user wants to use the value which is also the default value (always keep that value)
- or wants to use the default value in general (update to a possible new default value)

**Comment by oy** [comment]
Fixed by 06d445a3d66606b1c4cebe278a627436c15736e5
