### ISSUE TITLE
make str_utf8_skip_whitespaces return const char* as well as the passed a const char*

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2203]
Instead of casting to const char, make the function return const char* as well as the passed argument.
That casting looks super unclean imo.
#### Before:
```c++
char *str_utf8_skip_whitespaces(char *str)
{
	char *str_old;
	int code;

	while(*str)
	{
		str_old = str;
		code = str_utf8_decode((const char **)&str); // <----- This here

		if(!str_utf8_is_whitespace(code))
		{
			return str_old;
		}
	}

	return str;
}
```
#### After:
```c++
const char *str_utf8_skip_whitespaces(const char *str)
{
	const char *str_old;
	int code;

	while(*str)
	{
		str_old = str;
		code = str_utf8_decode(&str);

		if(! str_utf8_is_whitespace(code))
		{
			return str_old;
		}
	}

	return str;
}
```

**Comment by Dune-jr** [comment]
> #### Before:
> ```c++
> char *str_utf8_skip_whitespaces(char *str)
> ```

Where did you find this code? Please check the master branch, `str_utf8_skip_whitespaces` doesn't have this signature

**Comment by jxsl13** [comment]
lol.
Is has the const char signature, but also the ugly const char cast there

**Comment by Dune-jr** [comment]
So the "before" code does not match the current code?

https://github.com/teeworlds/teeworlds/blob/ec1097f93f0fd2945d3aa57d66bc9e86910f49d4/src/base/system.h#L1406

So if I understand it right all you want to do is to remove the cast? Just that one bit?

**Comment by jxsl13** [comment]
yeah, basically that. I literally don't know where I got the non cast version from, might be either DDNet or zCatch, while I was adding DDNet's utf8 confusable characters stuff to zCatch.
