### ISSUE TITLE
Velocity server debugs are way too spammy, and enabled by default in the system console

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2214]
PRs https://github.com/teeworlds/teeworlds/pull/2206/ and https://github.com/teeworlds/teeworlds/pull/2207/

cause this:
![image](https://user-images.githubusercontent.com/355114/64267863-69ff4a00-cf37-11e9-84eb-c58ffc6f309e.png)

This is extremely spammy, even for a debug mode, and buries all other information.

This debug line is also poorly formatted: https://github.com/allan-simon/teeworlds/blob/a11fcb1c5e8d8c0e29189b210bde35ea08c4609a/src/game/server/entities/character.cpp#L684
It is too long, causes line breaks (see screenshot) and there are unnecessary whitespaces at the end.

I suggest that we:
- remove the velocity debug outputs
- make the "shot" debug outputs only displayed when `debug 1` is set
- reformat kill lines to either an `id:name:team` sort of format, or not display teams if not in debug (and, not least, this would restore compatibility with existing tools!)

**Comment by ChillerDragon** [comment]
Oh I like reducing the length by using ``id:name:team`` but I would prefer to have the numbers together and not surrounding the name so more like ``id:team:name`` or ``team:id:name``.

**Comment by oy** [comment]
@Dune-jr 
Sounds good.
`id:name:team` should shorten that line enough. `id:team:name` like @ChillerDragon suggested might be easier to parse.
