### ISSUE TITLE
Spectator mode HUD, flag resizing is buggy

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2221]
If you hold rshift while in spectatormode, the menu to select a player pops up. If too many players are online the names will get smaller and also the flags resize. But there are 2 issues.
1. The flags are not on the tee, they are offset
2. the flags next to Free-View (the one you can select, to spectate) are also getting resized.

**Comment by fokkonaut** [comment]
Reopen? 2. is not fixed

**Comment by Dune-jr** [comment]
2b02abd ?

**Comment by fokkonaut** [comment]
I havent tested this, but the description looks not like what was needed; If there are so many players, that the spectator menu entries get smaller, also the selectable flags get resized, which should happen. Is that fixed now?

**Comment by oy** [comment]
Yeah, in the commit @Dune-jr mentioned.
