### ISSUE TITLE
editor - add downscaled image preview when selecting images

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2224]
editor - add downscaled image preview when selecting images

**Comment by Learath2** [comment]
Where? We already have them when selecting the image for tile layers.

**Comment by jxsl13** [comment]
This issue has been opened half a year ago. Someone might have added that on the mean time without referring or closing this issue.

**Comment by Learath2** [comment]
Well, feel free to close it if that was the place you were referring to

**Comment by jxsl13** [comment]
It's seemingly not yet added:
![Bildschirmfoto 2020-03-07 um 20 43 10](https://user-images.githubusercontent.com/371944/76151522-276d2480-60b6-11ea-867d-83fe8fe713b8.png)

**Comment by Learath2** [comment]
Ah I see, when adding images

**Comment by Robyt3** [comment]
Fixed by https://github.com/teeworlds/teeworlds/commit/73fd801e81e0a1f3d7af73307b689b166541e790.

![screenshot_2022-03-10_20-13-20](https://user-images.githubusercontent.com/23437060/157737646-af641d05-81e4-4577-b738-acf5c835eccd.png)
