### ISSUE TITLE
Logarithmic scale scrollbars

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2226]
With joystick sensitivity being incredibly variable depending on the controller, we are going to need non-linear scrollbars.
It would probably make sense to also use that for the sound volume.

**Comment by Robyt3** [comment]
The max. ping filter could probably also use this after #2267.

Where should we put the interpolation function interface and implementations? menus.h?

**Comment by Dune-jr** [comment]
> The max. ping filter could probably also use this after #2267/#2365.

Yes, that would be wise

> Where should we put the interpolation function interface and implementations? menus.h? New file?

Just leave it in the menus component where the rest of the scrollbar code is, imo.

I made an attempt to implement this issue a while ago but ended up with a *lot* of bugs so I paused it.
