### ISSUE TITLE
Incompatible demos

### ISSUE THREAD

**Issue by axblk** [teeworlds/teeworlds#2230]
The PR #2129 changed the format of the snapshots. For the client-server communication this does not matter, since the protocol only uses snapshot deltas.
The demos however, use complete snapshots for the keyframes, so the current master cannot play demos from 0.7.3, same for the other way round.

Solutions that come to my mind:
1) Revert the PR
2) Convert the snap format when loading and saving demos
3) New demo format version

**Comment by Dune-jr** [comment]
Right, that should be addressed before 0.7.4.

**Comment by LordSk** [comment]
We could revert it for the time being. I'm not sure how to keep the changes with git though (and I don't have the original branch anymore).

Ideally we should have a demo format that does not depend heavily on a center piece structure of the game. So 2. and 3. at the same time.

**Comment by Dune-jr** [comment]
From my point of view, the priority is to preserve the compatibility of demos between every 0.7.x version. It would be very confusing to explain to users which versions their demos are compatible with, especially when they're all mixed up in a folder :/
