### ISSUE TITLE
Use heart emote to show friendship in scoreboard

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2236]
A suggestion

**Comment by ChillerDragon** [comment]
Where exactly? Like a normal emote above the tee? Is there even space? And isn't the scoreboard bloated enough?

**Comment by Dune-jr** [comment]
A normal emote, just like ingame. The point of using that, instead of — for example — the serverbrowser heart icon, is to add a discrete symbol and not bloat it any further.

**Comment by oy** [comment]
Dunno about that one. Shouldn't the scoreboard focus on gameplay related stuff?
There's the player info page to see who's your friend.

**Comment by Dune-jr** [comment]
That makes sense.
