### ISSUE TITLE
Snap invalidation broken for `CSnapshot::GetItem`

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#2237]
<s>Broken by #2216, see https://github.com/teeworlds/teeworlds/pull/2216#issuecomment-531835438.</s> False, see below.

**Comment by axblk** [comment]
I am pretty sure that #2216 has not changed anything in this regard. The variable `m_TypeAndID`, inside each snap-item is still set to -1. However, it is true that this is never actively checked, but it has always been like that.
Instead, the client usually uses the ID to identify the item. After setting `m_TypeAndID` to -1, the ID no longer has a meaningful value.

**Comment by heinrich5991** [comment]
Hmmm. I guess you're right. The first thing the client does after getting the invalidated item via `IClient::SnapGetItem` is to match its type, so this is harmless.

A little weird that the items do make it into the game though.

**Comment by heinrich5991** [comment]
I guess it's not too bad for them to leak into the game with type ID -1.
