### ISSUE TITLE
Steam listing does not include the new assets

### ISSUE THREAD

**Issue by ghost** [teeworlds/teeworlds#2238]
![image](https://user-images.githubusercontent.com/7173984/65079262-bcdff500-d96c-11e9-957a-085c520f4a55.png)

I assume the new one would be based on this: 
![image](https://user-images.githubusercontent.com/7173984/65079300-d1bc8880-d96c-11e9-87b8-36a8ad742fd0.png)

**Comment by Sonix-** [comment]
I did send heinrich the updated cover, should be good now:

![Screenshot (97)](https://user-images.githubusercontent.com/2030615/71778132-0f8bfe00-2faa-11ea-919e-d6a423acee03.png)
@heinrich5991 do we need some other assets or can this be closed?

**Comment by heinrich5991** [comment]
Theoretically, we could also use the following ones:

**Comment by heinrich5991** [comment]
Thanks to the awesome @Sonix-, we now have all the Steam library assets!
