### ISSUE TITLE
Improve team change log message

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2239]
currently a join message looks like:
```
[game]: team_join player='0:nameless tee' team=0
```

But a team change message looks like
```
[game]: team_join player='0:nameless tee' m_Team=0
```

So if you want to parse/look at the logs you have to know that ``team`` means join and ``m_Team`` means change. So I suggest changing it to ``[game]: team_change player='0:nameless tee' team=0``

Maybe change can even show old and new team? But not too sure about that.

**Comment by Dune-jr** [comment]
I think it's a bug and they are supposed to be the same. There is a 
```
[2019-09-19 14:58:10][server]: player is ready. ClientID=0 addr=[0:0:0:0:0:0:0:1]:57268
[2019-09-19 14:58:10][server]: player has entered the game. ClientID=0 addr=[0:0:0:0:0:0:0:1]:57268
```
message before.

**Comment by fokkonaut** [comment]
player ready and player join is something different
