### ISSUE TITLE
Callvote options that cannot be called

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2242]
Suggestion: a lot of servers use callvote options as section labels, for example:

![screenshot_2019-09-21_13-23-34](https://user-images.githubusercontent.com/355114/65372644-0a14dd00-dc73-11e9-84fb-8590fbf01ac7.png)

Those could be flagged by the server and rendered differently client-side, as well as not be callable. It should be doable in a backwards compatible way.

I'm not quite sure how it should be rendered in the UI though.

**Comment by jxsl13** [comment]
I think votes in general should rely on some kind of id for identification instead of using their descriptions, as that way duplicate vote options seem kind of not possible, especially those that are used as section deviders. adding a flag for not votable ootions makes also a lot of sense.

**Comment by oy** [comment]
Maybe redesign the whole thing? So that you can create votes with sub menues? and specific options a user can choose from. Then the whole thing would be more clear and structured.
Maybe even add a ingame UI you can use - similar to spec/emote menu.
Would be useful for mods as well - remember the old nodes mod?

**Comment by jxsl13** [comment]
I'd highly love for this voteoptionserver to be encapsulated in a class.

**Comment by LordSk** [comment]
I like @Dune-jr 's idea. It seems simple enough to implement and easy to use. Sub-menus might a bit overkill though? Except if the whole idea is to show/hide sections when clicking on a header.
