### ISSUE TITLE
Selecting demos with arrow keys is broken

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2253]
Spotted by rqza.
When selecting a demo in menus_demo it was possible until 0.7.3.1 to switch demos with arrow keys. This is no longer working in current master.

**Comment by Dune-jr** [comment]
This is a bug introduced after 0.7.3.1, so it should be fixed before 0.7.4, preferably,

**Comment by oy** [comment]
[This](https://github.com/teeworlds/teeworlds/pull/2197/files#diff-cad6690c312d4ab80e91a046cdbb5becL1076) broke the navigation in listboxes with arrow keys. The new scrollbars don't provide that feature yet.

**Comment by ChillerDragon** [comment]
Works fine thanks :)
