### ISSUE TITLE
make kills and deaths server side with client side fallback

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2255]
I think the Kills and Deaths feature makes at the current point in time not much sense, as one, in my opinion(other opinions allowed :D) would want to see a player's Kills/Deaths during the whole match and not the kills/deaths that person earned since I joined the server. 
This leads to, I guess, some confusion when people might talk about K/D.
If there are 16 players on a server, it's most likely that everyone sees a different K/D for most of the other players, especially  the K/D of some dominating player(e.g. LMS or so).
The current Kills and Deaths are inconsistent and arbitrary and thus an obsolete information.

A solution might be some special server message that sends all of the player's current K/D information when the player enters the game. After the initial synchronization, I think the old counting system can be used. If the initial sync message fails, the old fallback counting is used.

If I'm completely wrong as about how the system works please correct me, thx.

**Comment by axblk** [comment]
I agree with you but I'd go even further. The whole stats should be handled serverside and spread to the clients via snap objects.
The current counting system contains some hacky solutions (for example detecting game restart) that I would not rely on. This would also enable mods to handle stats on their own.

**Comment by jxsl13** [comment]
I wonder if that overhead is wanted that might come with the extra data that is sent for the player stats synchronization, thus I proposed that hybrid solution.

**Comment by axblk** [comment]
Well, the snaps are only sent if they change, and since the data does not fluctuate very much, there is probably little left after all the compression levels.

**Comment by oy** [comment]
That's planned see #158

**Comment by AssassinTee** [comment]
Maybe a more custumizable scoreboard would be an option, where the server sends the Headers and informations and the client just has a "scoreboard framework"

Just an idea

**Comment by oy** [comment]
@AssassinTee 
The statboard already provides that feature.

**Comment by oy** [comment]
Continues in #158
