### ISSUE TITLE
Allow moderators to use the "logout" command by default.

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2256]
Allow moderators to use the "logout" command by default.
Well, otherwise mods are forced to rejoin the server.
Also a documentation would be helpful on the teeworlds in regard to how to use the moderator configuration stuff in the server setup. website or in this repo's wiki.

Here is a reference to my zCatch example config.(contains moderator stuff)
https://github.com/jxsl13/zcatch/wiki/Server-configuration-example

A command not mentioned is also `mod_status` which prints the accessible commands that moderators can use.
This command could be also a command that is by default accessible to moderators, as it does not give them any more information that the rcon auto completion doesn't.

**Comment by Dune-jr** [comment]
Yeah makes sense. Documentation issues lie at https://github.com/teeworlds/documentation btw

**Comment by jxsl13** [comment]
It seems you already opened an issue containing exactly these missing parts long ago.

**Comment by Dune-jr** [comment]
`mod_status` should get the same treatment

**Comment by oy** [comment]
@Dune-jr 
Dunno if that's needed, mods have all available commands in their tab completion already.

**Comment by Dune-jr** [comment]
@oy that's a good point yeah
