### ISSUE TITLE
Use a separate settings.cfg file to help users straddling between the two versions

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2257]
```
if not settings7.cfg:
  cp settings.cfg settings7.cfg
open settings7.cfg
```

Might want to find a better naming scheme.

Also add a comment in the settings file indicating the version of the client (if anything, just for readability).

**Comment by Dune-jr** [comment]
I think https://github.com/dune-jr/teeworlds/commit/d85f516bf119e1d47b5215b26dffd9dcf9a13721 would work just fine. What name should we go with? `settings07.cfg`?

**Comment by oy** [comment]
@Dune-jr yeah, that would be fine. Just use a constant for the names and add the comment about the version. That naming sheme would be good.
Maybe add a new entry [here](https://github.com/teeworlds/teeworlds/blob/master/src/game/version.h) like major version and use that? So we don't forget it when doing a new release.

**Comment by Dune-jr** [comment]
Right

> Maybe add a new entry here like major version and use that? So we don't forget it when doing a new release.

Good point
