### ISSUE TITLE
MOTD shows less information since 0.7.3.1 release

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2258]
On @fokkonaut's server there is a footer in the last lines of the motd which gets displayed in 0.7.3.1 but not in current master.
![motd_0 7 3 1](https://user-images.githubusercontent.com/20344300/66125454-40dde200-e5e7-11e9-9467-f5bffe449398.png)
(screenshot 0.7.3.1)

After https://github.com/teeworlds/teeworlds/commit/d2545c213245fce42438c171283a05c5f661524f the footer is not visible anymore:

![motd_current_master](https://user-images.githubusercontent.com/20344300/66125441-3885a700-e5e7-11e9-8a14-95c8089588f8.png)
(screen shot at master after https://github.com/teeworlds/teeworlds/commit/d2545c213245fce42438c171283a05c5f661524f)

**Comment by fokkonaut** [comment]
I made a function that always displays this footer at the bottom of the mod, no matter the lines above. And I dont see why this shouldnt work anymore, this is definitely a bug.

**Comment by jxsl13** [comment]
*cough port tw to c++17 and use the STL cough end*
