### ISSUE TITLE
Flag carrier doesnt update in spectator

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2260]
If you watch a flag using rshift, the carrier is in parantheses behind red/blue flag at the bottom right. If the owner changes, the name in the parantheses doesnt update

**Comment by SijmenSchoon** [comment]
I can't reproduce this in 0.7.3.1

**Comment by Dune-jr** [comment]
@SijmenSchoon I cannot reproduce this either on trunk.
@fokkonaut Maybe this only happens when a server modification makes a flag change directly from an owner to another, without ever being dropped? That's not supposed to happen

**Comment by fokkonaut** [comment]
Ah wait, its handled with the SendGameMsg, right?
