### ISSUE TITLE
[Meta-Tracker] GNU/Linux Mobile

### ISSUE THREAD

**Issue by WorryTheBirds12** [teeworlds/teeworlds#2265]
## Basic Information

**Description**: TeeWorlds on GNU/Linux Mobile.
**Platforms**: TuxPhones has a list of them [here](https://tuxphones.com/all-linux-distributions-for-smartphones/)

## Solutions

Many others have been talking about adaptive layouts.
_TL_;_DR_ Basically, adapt the current Linux UI for smaller screens. :)

![adaptive-layout](https://coinsh.red/u/adaptive.jpeg)

### Alternative designs

Developing a separate applications or porting the Android application.

## Additional context

Preferably, the applications would be using a tarball to start.
Therefore, it is easier to port to a variety of mobile OSes.

______________________________

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=81860592)](https://www.bountysource.com/issues/81860592-meta-tracker-gnu-linux-mobile)

**Comment by oy** [comment]
We don't plan a mobile version for Teeworlds.

**Comment by WorryTheBirds12** [comment]
https://play.google.com/store/apps/details?id=com.teeworlds

**Comment by oy** [comment]
That's not an official version.
