### ISSUE TITLE
Add console warning when trying to change the value of sv_max_clients

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2268]
I believe `sv_max_clients` cannot be changed via rcon, only by the initial config. This should be made clear with a warning

**Comment by fokkonaut** [comment]
Well, if you type it without a parameter you see the value didnt change

**Comment by ChillerDragon** [comment]
@fokkonaut I don't know if I understand you correctly but for me the value updates:
```
sv_max_clients
Value: 8
sv_max_clients 16
sv_max_clients
Value: 16
```

**Comment by Dune-jr** [comment]
Good point, @ChillerDragon, we might even want to refuse to update the value?

**Comment by sepulzera** [comment]
IIRC it takes effect after a reload, doesn't it?

**Comment by Dune-jr** [comment]
I don't think so, cbw

**Comment by fokkonaut** [comment]
@ChillerDragon ah forgot, I made that happen in my mod

**Comment by oy** [comment]
Changing that value currently has no effect. Could change that so you can change the max clients without a restart.
