### ISSUE TITLE
Make it so that you can't filter out all three server levels

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2274]
No one wants an empty filter and it's a significant factor of "I can't find any server" issues. Similar to https://github.com/teeworlds/teeworlds/issues/2267

**Comment by AssassinTee** [comment]
Can you clarify what you mean by server levels? Easy/Medium/Hard ?
Standard/Non-Stanard ?
Low/Medium/High ping?

**Comment by Dune-jr** [comment]
![image](https://user-images.githubusercontent.com/355114/67626139-30fc9b00-f83f-11e9-9a78-37addca45799.png)
