### ISSUE TITLE
Server browser should also match searches against gametypes

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2275]
This would make quickly searching for a gametype more convenient. Surely when one searches for `CTF`, it is reasonable to display all servers with a CTF gametype. The gametype string should be highlighted in blue.
It already works for maps.

Based on a suggestion from @fokkonaut

**Comment by oy** [comment]
The gametypes had their own search bar in the filter, so it they were skipped for the quick search.
