### ISSUE TITLE
RFC: extend server browser view

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2276]
I did some UI margin tweaks in the server browser (and the rest of the offline UI).
They were well received and I was asked to open discussion for a possible push to the vanilla client.
Ignore the favorites tab.

![screenshot_2019-10-27_12-05-11](https://user-images.githubusercontent.com/355114/67634366-cb49f680-f8b2-11e9-86c3-9de31726c8d2.png)
![screenshot_2019-10-27_12-05-07](https://user-images.githubusercontent.com/355114/67634367-cb49f680-f8b2-11e9-9b15-14c6f7d19edd.png)

This is https://github.com/Dune-jr/teeworlds/commit/f5bf0bcb6d5ddde46e7169bc1585b7b06f6ab5af

**Comment by oy** [comment]
The current design is probably resolution independent, so there's empty space on the sides for widescreen resolutuions.

**Comment by Dune-jr** [comment]
I remember there was some fuss about widescreen resolutions indeed.
Right now, we use

```cpp
float VMargin = Screen.w/2-365.0f;
```  
Instead, we could use  
```cpp
float VMargin = fmin(Screen.w/2-365.0f, 40.0f);
```  
This would ensure the margin is no bigger than 40.

The width of each column is constant, except for that of the server name. On wider ratios, the server name column is reduced in space, like in 0.6.   
In this commit, I also applied a +17% increase in font and static column widths.

**Comment by Dune-jr** [comment]
This is what it looks like on 4:3:

![screenshot_2019-10-27_13-23-51](https://user-images.githubusercontent.com/355114/67635295-18cb6100-f8bd-11e9-8173-940aeb6cf13a.png)

Admittedly, this might eat a bit too much on the server name column.

**Comment by oy** [comment]
Yeah, that server name is kinda short.

Another thing I noticed on the pictures. The icon of the settings button is not vertically aligned. Does that happen on the official client too?

**Comment by Dune-jr** [comment]
@oy huh, the official client is fine. Not sure how I broke that one :)

**Comment by sepulzera** [comment]
Both feel a bit bloated, due to the narrow space between the columns Type and Map.
Plus I would add some space on the left side of "Search:" and "Host adress:".

Generally, I prefer @Dune-jr 's variant. Good job!
