### ISSUE TITLE
Server throws `invalid id` when spectating the same flag again

### ISSUE THREAD

**Issue by nheir** [teeworlds/teeworlds#2284]
Step to reproduce:
 - Spectate the red flag with spectator menu
 - Spectate again the red flag

Result:
 - Server send invalid id error

Solutions:
 - Client side: don't ask again to spectate the same flag
 - Server-side: don't throw an error

**Comment by fokkonaut** [comment]
serverside fix of course

**Comment by Dune-jr** [comment]
You want client-side too because of older server versions

**Comment by fokkonaut** [comment]
They can fix it theirselves, we dont have to clean there stuff up with a new client.

**Comment by nheir** [comment]
In fact, this can be triggered if the user asks the same spec_mode (other than player) with console

Usually, the client does not ask the same player twice (because of code).

One can argue that asking the same specmode is wrong and that the server can complain instead of dropping the message.
