### ISSUE TITLE
No password attempt limit on local server

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2286]
I guess one cannot get banned on own local server so this results in unlimited rcon attempts. The message looks odd tho:
![teeworlds_max_rcon](https://user-images.githubusercontent.com/20344300/68878164-85d95600-0707-11ea-9ae3-62604302d442.png)

**Comment by oy** [comment]
Yeah, it prevents the ban. Though when set to just kick it would work. 
Could drop that "x/n" when a user can't be banned.

**Comment by Vy0x2** [comment]
&m_LocalhostIPV4 is in my case 127.0.0.1:0 and I get banned with 192.168.1.4, so not working for me.

**Comment by heinrich5991** [comment]
Connect via 127.0.0.1 and you'll be fine.

**Comment by Vy0x2** [comment]
okay but thats like a halfhearted fix that doesnt fix the problem in like 90% cuz who connects with locahost

**Comment by oy** [comment]
That's not what the issue was about. Nothing changed in regard of who can be banned or not. This just changed the notice for clients who already couldn't be banned before.
Yours is a possible different issue.

**Comment by Vy0x2** [comment]
got it
