### ISSUE TITLE
Survival HUD should show count of remaining players

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2298]
It would be useful for survival gametypes to see a count of remaining alive players at a quick glance. I think this is common in battle royale type of games. This would be relevant to survival-type modifications as well.

Edit: some gametypes already implement this through broadcasts:
![image](https://user-images.githubusercontent.com/355114/69903156-02b63200-138e-11ea-83c2-86ac20ecc9fb.png)

**Comment by oy** [comment]
In team-based survival gametypes it shows the remaining players in the score hud.
For non-team based ones that feature is still [missing](https://github.com/teeworlds/teeworlds/blob/master/src/game/client/components/hud.cpp#L277). Should come up with a good idea.
