### ISSUE TITLE
Port -DPREFER_BUNDLED_LIBS to bam

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2300]
Reportedly, this `-DPREFER_BUNDLED_LIBS` feature was implemented in the CMake files only, and is somewhat required for Mac releases. 
It should be written for bam as well to enable Mac releases from bam builds.

**Comment by oy** [comment]
Invalid, use [the release script](https://github.com/teeworlds/teeworlds/blob/master/scripts/make_release.py) for bam.
