### ISSUE TITLE
Race icon's

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#2316]
Race needs a better icon for the finish messages and a gametype icon for the server browser.

**Comment by Sonix-** [comment]
I made two versions based on @Zatline's svg sources:
![CTF](https://user-images.githubusercontent.com/2030615/70846883-5f215300-1e5e-11ea-90f6-6c311b394c2a.png)
![MOD](https://user-images.githubusercontent.com/2030615/70846887-67798e00-1e5e-11ea-8f84-811025061dc6.png)

Ingame messy screenshot:
![screenshot_2019-12-14_10-39-42](https://user-images.githubusercontent.com/2030615/70846900-7fe9a880-1e5e-11ea-93bf-9c54220cd153.png)

CTF is the first option while MOD's are the other flag beneath

**Comment by Sonix-** [comment]
Third option:
![MOD](https://user-images.githubusercontent.com/2030615/70847076-60ec1600-1e60-11ea-898b-4a3cb65d5a1f.png)
![screenshot_2019-12-14_10-55-59](https://user-images.githubusercontent.com/2030615/70847082-65183380-1e60-11ea-86c8-2aa41c1ee42d.png)

**Comment by oy** [comment]
Third option looks best.

**Comment by Zatline** [comment]
I think 2 looks the best as none of the squares look squeezed (like option 1) or cut off (like option 3)


> ![MOD](https://user-images.githubusercontent.com/2030615/70846887-67798e00-1e5e-11ea-8f84-811025061dc6.png)

**Comment by Sonix-** [comment]
4th option:
less cut off
![CTF](https://user-images.githubusercontent.com/2030615/71115165-a185bf80-21d1-11ea-851c-cc260866b346.png)

**Comment by oy** [comment]
Looks good 👍
