### ISSUE TITLE
Icon for ingame browser

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2318]
We could use a globe-like icon for the ingame browser menu button:

![image](https://user-images.githubusercontent.com/355114/70848214-f938c980-1e65-11ea-8b93-a28ca63be13c.png)

**Comment by Dune-jr** [comment]
![image](https://user-images.githubusercontent.com/355114/70849758-d4028600-1e7a-11ea-86c3-dc38c952fafe.png)
![image](https://user-images.githubusercontent.com/355114/70849761-d5cc4980-1e7a-11ea-8a52-b66cbd6589b1.png)

Two guys on discord said they preferred 2
I like them both

Not sure what the shading thing on the top is supposed to look like btw. Probably black everywhere

**Comment by Zatline** [comment]
I'd prefer 2nd as well

**Comment by 1stDecadeTW** [comment]
Settings should be shown as icon on the right top, next to the quit button, just like it's shown in the main config menu. To get consistency?

**Comment by Dune-jr** [comment]
The issue with that is that it's quite an important button and it makes it harder to find

**Comment by Dune-jr** [comment]
Closed by https://github.com/teeworlds/teeworlds/pull/2331
