### ISSUE TITLE
Santa Hat on Teeworlds and pushing of religion is very offensive to me

### ISSUE THREAD

**Issue by Christian606** [teeworlds/teeworlds#2345]
The Santa Hat on Teeworlds and pushing of religion is very offensive to me, additionally xmas has cost millions of Jews their lives over the centuries, yet even if that was not the case, pushing religious symbols as part of a product update is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

Version: 0.7.4
Commit: 28f9da3
Date: 2019-12-25
OS: FreeBSD

Steps to Reproduce:

    Install latest build of Teeworlds.

Does this issue occur when all themes are disabled?: Yes

Additional reading on the issue that most certainly needs to be considered. https://www.sefaria.org/sheets/51928?lang=bi

**Comment by Sonix-** [comment]
Open up F1--> type "cl_show_xmas_hats 0" et voila no more xmas

**Comment by heinrich5991** [comment]
You can permanently turn it off by putting `cl_show_xmas_hats 0` in the local console.

Press f1 while you're in the client, type `cl_show_xmas_hats 0`, press enter t confirm, press f1 to close the console again.

**Comment by heinrich5991** [comment]
I'm locking this because I don't want to discuss the merits of including Santa hats in Teeworlds or not.
