### ISSUE TITLE
Selection of chat commands works poorly after a client command was removed

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2349]
Reported by @fokkonaut, I have not investigated this. Should fill in with some more details on what happens; if I recall right, moving up and down with arrow bugs, thinking that the removed client command was still there

**Comment by oy** [comment]
Fixed by e8b9ff3e19fa87d8a48097e90f9a3b416b12e53c

**Comment by Dune-jr** [comment]
Ah, didn't see. Thanks :)
