### ISSUE TITLE
Chat does not get closed after executing chat command

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2350]
When executing a chat command sent by the server, the chat does not close after executing

**Comment by Fudgyking** [comment]
Was about to open the same issue

**Comment by Ryozuki** [comment]
It closes for me, i can't reproduce this.

https://github.com/teeworlds/teeworlds/blob/031177b2a05a0c89136d7dddb3d0bf1ae743a7b7/src/game/client/components/chat.cpp#L1387

**Comment by Vy0x2** [comment]
you still need to set m_show to false so the black window disappears, maybe just call OnRelease

**Comment by oy** [comment]
Thx :)
