### ISSUE TITLE
Sort statboard players by team

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2355]
It's a bit messy right now (and sorted in no particular order).
Might want to sort by score as well, like the scoreboard

**Comment by Sonix-** [comment]
Quick mockup of possible options:
1
 ![team_statboard1](https://user-images.githubusercontent.com/2030615/71642699-a8bbcb80-2caf-11ea-824d-7c592061c49b.png)
2
![team_statboard2](https://user-images.githubusercontent.com/2030615/71642700-aa858f00-2caf-11ea-830f-f4c889c07603.png)

**Comment by jxsl13** [comment]
blue > red :D

**Comment by Zatline** [comment]
It would be nice if we show the team that is winning first, a nice little detail that ensures that both teams are equally valued by design and can both have either position in the statboard.

**Comment by Sonix-** [comment]
It would get way too confusive, the team leading may change every minute

**Comment by Zatline** [comment]
@Sonix- good point perhaps better solution show the team that the player is part of on the top. :)
