### ISSUE TITLE
Pickup types

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2358]
Since this commit (https://github.com/teeworlds/teeworlds/commit/23df3c609eebda63bbf219ddcf989e9a63a2a49d) it is not possible to create hammer and gun pickups anymore, I know they are not used in vanilla, but mods like HMH-Monster, my mod or other level mods also use hammer and gun pickups. Would be cool to get them back.

**Comment by Dune-jr** [comment]
Even if you add them again, it will not be visible to previous 0.7 clients

**Comment by fokkonaut** [comment]
I know, but for the future it will work. Most people update. Even those who dont really wanna update do it at some point.

**Comment by ChillerDragon** [comment]
> Even those who dont really wanna update do it at some point.

(insert 0.6 meme here) xd

**Comment by AssassinTee** [comment]
why is this patched out in the first place? Shouldn't this be coded in a general matter ...

**Comment by Dune-jr** [comment]
> why is this patched out in the first place? Shouldn't this be coded in a general matter ...

Because you cannot pick up hammers, that makes no sense except as a mod hack.

**Comment by fokkonaut** [comment]
Its not only used as a pickup, in HMH Monster and other battle mods the different pickup types are bots, the type showing the strength of them. And there, also gun and hammer is used. But for example my mod has droppable weapons.
