### ISSUE TITLE
Dyncam

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2371]
> I find it very weird that you cant toggle dynamic camera just using f1 cl_dynamic_camera. You have to use the button in the settings or set the rest manually.
Vanilla code:
`https://github.com/teeworlds/teeworlds/blob/e036ee22b5021c738b766ed1c63e227e05678be4/src/game/client/components/menus_settings.cpp#L968`

> ddnet has changed that:
`https://github.com/ddnet/ddnet/blob/77957c00b94611c6cec697f228b98d981830ee6c/src/game/client/components/menus_settings.cpp#L93`

> we can just remove them, they are all different variables

**Comment by Dune-jr** [comment]
I don't see the difference, except that using the GUI in Teeworlds vanilla makes you reset a bunch of camera parameters. Did I miss something?

**Comment by fokkonaut** [comment]
dont know, but doesnt work just using f1 for me

**Comment by oy** [comment]
Tested it and works for my by toggling `cl_dynamic_camera` in the console.
