### ISSUE TITLE
Double binds are not recognized

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2372]
When having a double bind, the setting is not recognized in the controls menu. Or for example I have an emote chat bind, and thats also not recognized for the message when you leave the chat. (Press x to resume chatting, it says key not found for me

**Comment by AssassinTee** [comment]
technically you didn't bind the chat to any key. Lookup Settings->Controls->Chat and you won't see any letter there

**Comment by oy** [comment]
@AssassinTee is right. It's a combination of commands and not a real assignment to one command which wouldn't allow multiple binds. Dunno if that should be fixed?

**Comment by AssassinTee** [comment]
@oy the fix iam working on just hides the message if the key is not found, so it doesn't say `Press key not found to resume chatting`. I can't compile the client currently so I didn't do a PR. But wtf github referencing the issue in my fork here oO

**Comment by fokkonaut** [comment]
Should definitely be fixed I think. Dont just hide the message please. I would also show it in the settings, if unbound there then just unbind the whole key I think.

**Comment by Dune-jr** [comment]
It sounds reasonable to me to look for such custom binds as a fallback.
