### ISSUE TITLE
Display favorites on top of the server list

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2376]
Since two filter sets cannot be open at once, I believe this would make the favorites feature a lot more useful. I propose to pin them above others, and the chosen sort would be applied to them separately.

Thoughts?

**Comment by jxsl13** [comment]
makes sense if you have few favorites.
what about people with like 50 favorites?

**Comment by oy** [comment]
Would rather keep them in their own set, especially when you have lots of them.
