### ISSUE TITLE
Server browser entries added to wrong list if LAN is refreshed while Internet refresh is running

### ISSUE THREAD

**Issue by Robyt3** [teeworlds/teeworlds#2379]
1. Start refreshing on internet tab
2. Switch to LAN tab
3. Start refreshing while it's still refreshing
4. Internet entries are being added to the LAN server list if their server info is received after the second refresh

------

1. Launch client to server browser with last selected tab being LAN
2. Refresh while the automatic internet refresh is still running
3. Internet entries are being added to the LAN server list, the internet server list stays empty

------

Also occurs in 0.7.1

**Comment by Dune-jr** [comment]
I can reproduce

**Comment by Robyt3** [comment]
Only a single refresh should be run concurrently for each tab -> disable the button during refresh? And fix mixing of lists.

**Comment by Dune-jr** [comment]
Ideally a second refresh should cancel the first. I'm not familiar with that part of the code, one dirty fallback would be to check whether the address are localhost or not. But it might be possible to do better.

It seems like
```diff
--- a/src/engine/client/serverbrowser.cpp
+++ b/src/engine/client/serverbrowser.cpp
@@ -268,6 +268,10 @@ void CServerBrowser::SetType(int Type)
 void CServerBrowser::Refresh(int RefreshFlags)
 {
        m_RefreshFlags = RefreshFlags;
+       m_NumRequests = 0;
+       m_pNetClient->Flush();
```

helps partially

**Comment by Dune-jr** [comment]
Hmm, looks like it was a coincidence and doesn't help much

**Comment by Dune-jr** [comment]
This was caused by https://github.com/teeworlds/teeworlds/commit/eead3c

https://github.com/teeworlds/teeworlds/blob/f7b66851fe94ff06e90238d03cdc9f90a0cc7c44/src/engine/client/serverbrowser.cpp#L506-L509

`m_CurrentLanToken` is never picked because `pEntry` is never `null`
