### ISSUE TITLE
"Low fps" on new chat-command feature

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2381]
See images: I think half fps is pretty significant
I tested it on gCTF, since it uses all server-command slots
![default](https://i.imgur.com/G4CA7u7.png)
![lowfps](https://i.imgur.com/0xPRLri.png)

**Comment by fokkonaut** [comment]
Can you test it on my server?

**Comment by AssassinTee** [comment]
There was a lot of traffic on your server, so i tested it on Race. The server has less chat-commands, but you can still see the difference:
![default](https://i.imgur.com/kltTFp1.png)
![lowfps](https://i.imgur.com/xvaGoQB.png)

**Comment by jxsl13** [comment]
is there a difference if you just open the chat without the chat commands?
F1 console?
F2 console?

**Comment by AssassinTee** [comment]
yes, only opening the chat results (only) in **sligtly** slower fps (which is natural):
![chat_open_no_command](https://i.imgur.com/TmFA5wK.png)

To crunch the numbers:

| image  | fps  |
| ------- | ---- |
| default | 2910 |
| chat | 2721 |
| chat-commands | 1400 |

**Comment by oy** [comment]
You have to compare it to open chat with lots of text as lots of text will decrease the fps significantly.

**Comment by AssassinTee** [comment]
![lol](https://i.imgur.com/ACZFovI.png)
lol
