### ISSUE TITLE
Race – Differentiate personal best from server best/record.

### ISSUE THREAD

**Issue by Fisico** [teeworlds/teeworlds#2389]
Right now it is very confusing a personal best record is displayed in the chat as a potential server record because “Fisico has set a new record: 00:10.481 (1.547 seconds faster)” This should be changed to “Fisico has set a new personal record: 00:10.481 (1.547 seconds faster)”.

If it is a server record it should be: “Fisico has set a new server record: 00:10.481 (1.547 seconds faster)”
This needs to be checked in the translations as well then.

**Comment by oy** [comment]
Fixed by #2430
