### ISSUE TITLE
Customizing HUD for demo viewer

### ISSUE THREAD

**Issue by zooom7z** [teeworlds/teeworlds#2390]
I'm recording demos and making movies, but in 0.7 it's became harder, on 0.6 I got TDTW modification of TW with full HUD customization, but now, on 0.7 I can't find good client for it.

I see two ways to handle it:
1. Automatically hiding all (turning off) HUD's in demo viewer (ALSO time bar in the bottom, when u pressing Esc he's going minimal and still showing 5 seconds and THEN hiding, i must record highlights on 6-7 seconds before, it's annoying).
2. Making more options in settings to manage every HUD (ammo, hd, broadcast, kill log, chat). And don't forget about time bar in the bottom of demo viewer.
![](https://cdn.discordapp.com/attachments/529689846642507778/665288178772475955/Image1.jpg)

This time bar that showing 5 seconds after pressing Esc:
![](https://cdn.discordapp.com/attachments/529689846642507778/665290917976080384/unknown.png)

**Comment by Dune-jr** [comment]
What do you want precisely?
You can use `cl_showhud 0` to disable HUD.

**Comment by zooom7z** [comment]
> What do you want precisely?
> You can use `cl_showhud 0` to disable HUD.

It's not working :D still showing chat and kill log in demo viewer.
cl_showhud 0 hiding only ammo, hp and top score in the right bottom.

**Comment by zooom7z** [comment]
> What do you want precisely?
> You can use `cl_showhud 0` to disable HUD.

![image](https://user-images.githubusercontent.com/35894722/72187151-93f1dd00-33ff-11ea-93d2-4cacd542d6d0.png)
look how it works in TDTW 0.6, it have switchers on every HUD.

**Comment by Dune-jr** [comment]
> > What do you want precisely?
> > You can use `cl_showhud 0` to disable HUD.
> 
> It's not working :D still showing chat

`cl_filter_chat 2` then

>  and kill log in demo viewer.

I guess we should add that to the no-hud option. Would be nice not to make another option just for that.

**Comment by zooom7z** [comment]
> I guess we should add that to the no-hud option. Would be nice not to make another option just for that.

good idea :)
