### ISSUE TITLE
Raise a warning when trying to compile with MinGW and 64 bit

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2395]

**Comment by heinrich5991** [comment]
Is the build broken?

"Fix the MinGW 64 bit build."

**Comment by Dune-jr** [comment]
This was a suggestion from @oy I put here to not forget. I think it was about people compiling on 64 bit with mingw32, which happens often. Just happened to me that bam autoselected 32-bit gcc on Windows even though I was building for 64-bit, so this might just be a bam issue, kind of forgot what it was exactly about

**Comment by oy** [comment]
@Dune-jr it doesn't autoselect gcc anymore when you can't build the 64bit version. Still want some error message?

**Comment by Dune-jr** [comment]
Ah, so it was patched already. Will test

**Comment by Dune-jr** [comment]
Works! Missed the commit :)
