### ISSUE TITLE
sv_max_clients can be changed in rcon, to no effect

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2401]
After the start of the server, `sv_max_clients` can no longer be changed.
However, it is possible to set it to a different value in the rcon. It does not take effect, though.

Solutions:
- Tweak the code so that you can change `sv_max_clients` ingame (possibly a lot of code changes and dynamic allocations?)
- Add a warning in rcon or make it impossible to change `sv_max_clients`

This issue was raised by Rilla

**Comment by oy** [comment]
Duplicate #2268.
