### ISSUE TITLE
Improve loading and the loading screen

### ISSUE THREAD

**Issue by Robyt3** [teeworlds/teeworlds#2403]
1. Loading is already pretty fast on my machine, but most time is spent before the loading screen is shown. To give some rough numbers of how it feels, maybe 0.3 seconds are only the console window, then about 1 seconds of just a white screen, then 0.5 seconds of the loading screen progress bar. The white screen should be as short as possible, which means the loading screen should be loaded as soon as the graphics are.

2. There is a 0.5 second freeze when activating the server filter for the first time. Seems to be static initialization because of a lot of buttons and other UI elements.

3. Gametype images are loaded when the browser is activated. I think this should be part of the loading screen, because you are almost guaranteed to need them anyway.

4. The loading scrollbar shows only about 2-3 different states before being finished at a random point (on my rather fast machine). After everything is integrated into the progress bar, we should try to have it move uniformly (somewhat at least).

5. Improve UI:
    - Show a percentage or make it more clear where the progress bar ends.
    - Show what is being loaded currently. Doesn't need to be down to the file for everything in my opinion.
    - Make it more visually appealing. Show the teeworlds banner, maybe something animated even.

**Comment by Dune-jr** [comment]
:+1: Sound is a big part of the loading, and that was nicely improved in 0.7.3 (?). Looking at the loading code, there is probably room to load more things during the loading bar indeed

**Comment by oy** [comment]
Not sure if there can be done much more. There's lots of initialisation that needs to be done before something can actually happen. And we might end up with a longer loading time.
For me f.e. the loading takes about 1 second in release mode.

**Comment by Robyt3** [comment]
Closed by #2459. Fancier UI changes are probably not worth it, considering the loading screen is only shown for 1 second.
