### ISSUE TITLE
Make Localize variadic and support reordering substition variables

### ISSUE THREAD

**Issue by Robyt3** [teeworlds/teeworlds#2404]
Whenever `Localize` is used with a placeholder, you'll see this pattern in the code:
```
char aBuf[256];
if(m_pClient->m_Snap.m_NotReadyCount == 1)
    str_format(aBuf, sizeof(aBuf), Localize("%d player not ready"), m_pClient->m_Snap.m_NotReadyCount);
else if(m_pClient->m_Snap.m_NotReadyCount > 1)
    str_format(aBuf, sizeof(aBuf), Localize("%d players not ready"), m_pClient->m_Snap.m_NotReadyCount);
// use aBuf
```
By making Localize variadic, this would reduce a lot of duplicated str_format code.
This would also allow for implementing #2030 more easily, so if Localize is also plural aware, the above code would now look like this:
```
Localize("%d player(s) not ready", m_pClient->m_Snap.m_NotReadyCount);
```
With a RFC on how the original string should look like. Singular? Plural? Both, like I did?

-----

EDIT: Disregard this, see #2032.

The second part to support better localization would be to allow reordering the placeholders.

A translation string "Localize("'%s' called for vote to kick '%s' (%s)" expects that translations use the same order for the arguments. To change the order, e.g. on Android the Formatter can use "%3$d" instead of "%d" to reference the third variadic argument and format it as a number. Normal format strings would still be supported.

As I see it however, this would basically mean getting rid of `vsnprintf`, at least for Localization. So we would probably need an external dependency, like https://github.com/fmtlib/fmt.

**Comment by Dune-jr** [comment]
Localize already supports reordering variable names: #2032

Keep in mind:
- the context of the string is the second parameter of Localize (example Play a video vs Play a game, will be translated differently)
- we use a script to collect all calls to Localize

This seems like it would break a lot of code, but I am a bit skeptical as to what it would achieve?

The biggest issue we have with translations right now is a way to check for overflow. A lot of translations (check Gaelic for an extreme example) are longer than their English counterpart, and look very ugly.

**Comment by Robyt3** [comment]
I see, I didn't know that function was already position aware.

I think the context should still be possible as second argument with the varargs to follow, so it shouldn't break all existing code right there, although the refactoring would make most code more readable in my opinion.

My main idea was easier support for translation of plural forms, but maybe this is to complicated to do with variadic methods.
The problem is also be that Localize doesn't allocate the memory for the translated string, so the buffer may not actually be large enough, apart from what you already mentioned about the UI. I'm not that familiar with C++, but in my opinion a lot would be easier if we used a managed string implementation for something like this.

**Comment by Robyt3** [comment]
> The biggest issue we have with translations right now is a way to check for overflow. A lot of translations (check Gaelic for an extreme example) are longer than their English counterpart, and look very ugly.

We need #109 and also for labels.

I'd like to refactor the UI components anyway, so dynamic size should be somewhat included.

I'll close this for now and try to come up with something for #2030 that doesn't require too much copy&paste to use.
