### ISSUE TITLE
"Click on a player or a flag to fllow"

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2409]
This message is annoying for me, especially on DDrace, where it occurs every few seconds when you join /pause. Can we do something about it?

**Comment by Sonix-** [comment]
On vanilla you're not supposed to switch between playing and spectating often

**Comment by fokkonaut** [comment]
Yea, in vanilla.

**Comment by Dune-jr** [comment]
I mean, if you write a hack, there are good chances it will look hacky
