### ISSUE TITLE
Add F5 for refreshing the (in game)server list 

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2421]
it's a widely used key in modified clients and browsers.

**Comment by Dune-jr** [comment]
Ctrl+R works to that effect

**Comment by jxsl13** [comment]
I only know about modified clients that use that. I'm not playing that many online games other than TW, tho.

**Comment by Robyt3** [comment]
Some of the "magic" key combinations could be turned into commands with bindings, e.g. `bind f5 "serverbrowser_refresh"`.

**Comment by Dune-jr** [comment]
> Some of the "magic" key combinations could be turned into commands with bindings, e.g. `bind f5 "serverbrowser_refresh"`.

iirc it's not such a good idea to enable key binds in the menus. The SpecialBinds class does this and is restricted to fn keys, for the consoles.

**Comment by oy** [comment]
Yeah, the fn-keys are the only binds working in the menus.
Could maybe provide commands for useful/often used ui/menu operations so people can bind them to the special keys?

**Comment by Dune-jr** [comment]
Just my two cents but I think it's fine to hardcode such things. Not many places (games or software) let you customize which button you use for refresh.

**Comment by Robyt3** [comment]
For refresh I might agree with you, but then again I'd like to have F5 as well.

I think the UI input handling could be made more flexible to allow better controller support, by allowing you to bind "menu_back", "menu_confirm" etc. to the controller buttons.
Many games also allow you to navigate the menus with the controller by other means than mapping it to a mouse, i.e. going from item to item like pressing tab in a webbrowser. But that would be part of a larger refactoring.

**Comment by jxsl13** [comment]
I think this one was added in one of the latest pr merges.
