### ISSUE TITLE
Trouble clicking on server browser filters

### ISSUE THREAD

**Issue by Fudgyking** [teeworlds/teeworlds#2422]
When I'm trying on a column name in the server browser, it selects the server under it instead. The area where I can actually click the name varies and can be nonexistent.

Example :

![screenshot_2020-01-23_16-30-16](https://user-images.githubusercontent.com/5041807/73025562-ccc98300-3dfd-11ea-84d5-5f1864eedb50.png)

Here you can see my cursor is in the middle of "Players" and its highlighting the server under it. If I click it would select the server.

**Comment by Robyt3** [comment]
I also noticed this problem. It occurs because the server list items are drawn after the header, and so they take on the "hot" state with higher priority even thou the header is on top. I'll look into it as it fits together with #2396.
