### ISSUE TITLE
Scrollbar of inline scoreboard is broken

### ISSUE THREAD

**Issue by axblk** [teeworlds/teeworlds#2429]
Clicking on the scrollbar of the inline scoreboard in the serverbrowser does not work anymore. In 0.7.4 it is fine.

**Comment by axblk** [comment]
The scrollbar of the nested scroll-region still doesn't work for me. It's rendered correctly, but hovering it, clicking it or moving the slider doesn't work.

**Comment by Robyt3** [comment]
I see. Now I get what you mean with "inline".

**Comment by oy** [comment]
Still not working
![screenshot_2020-01-27_22-31-38](https://user-images.githubusercontent.com/293850/73215842-21019980-4155-11ea-88e3-aa0e72571fbe.png)

**Comment by Robyt3** [comment]
Did you not apply the change somehow? The size in [menus_browser.cpp#L2103](https://github.com/teeworlds/teeworlds/blob/d5857a793b875351778e6833959c785e60154628/src/game/client/components/menus_browser.cpp#L2103) should be `14.0f`

**Comment by oy** [comment]
My commit changed it back somehow... works now.
