### ISSUE TITLE
Increase editor ui layer button size

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2435]
![teeworlds_editor_small_tile_button](https://user-images.githubusercontent.com/20344300/73143308-e5a19500-4098-11ea-9a19-f75da78b308b.png)
![teeworlds_editor_big_tile_button](https://user-images.githubusercontent.com/20344300/73143310-e76b5880-4098-11ea-97c1-dffc27623fe2.png)

When there are only a few tile layers and groups there is plenty of unused space. It would be nice to use it to increase the group members. This allows for faster mapping since less precise aiming is needed to switch layers. But when the whole space is eaten up and the scrollbar appears the smaller size should be used agian.

**Comment by oy** [comment]
Hm, would be kinda odd, when these buttons change sizes.

**Comment by ChillerDragon** [comment]
@oy isn't it common that ui squeezes when it reaches limits?

**Comment by oy** [comment]
Really? No example comes to my mind right now. That's an odd behavior when sizes change suddenly, there are scrollbars, so there's no need to squeeze something.

**Comment by Dune-jr** [comment]
Yeah, I don't think Teeworlds uses that anywhere

**Comment by ChillerDragon** [comment]
So you think it is better to keep the big size even if the scrolling starts? This causes more scrolling then. I thought with the changing size this could improve mapping speed with small amount of tiles but does not slow down mapping speed with a big amount of tiles. So it would only be a upgrade to the previous version.

**Comment by Dune-jr** [comment]
I think keeping the uniformity of button shapes and sizes is better.

**Comment by Dune-jr** [comment]
I'm all for a modern redesign, larger buttons, etc. but it should be a whole

**Comment by ChillerDragon** [comment]
I mean most other buttons are big already or do not have any space. But yes I understand that this would break the teeworlds button convention.
