### ISSUE TITLE
Timestamp in server log

### ISSUE THREAD

**Issue by Sworddragon** [teeworlds/teeworlds#245]
Every entry at the beginning has a value like [4ccc0913]. Is this a timestamp? If not what is it for? In my opinion there should be a formatted timestamp in the server log (or let it control with a server parameter, maybe with an own selected formatting in the parameter).

**Comment by richrd** [comment]
I have two TW servers and I'm looking at the server logs via `stdout` in the terminal as well as via `econ`. Both servers are running `version 0.7 802f1be60a05665f` and both servers have `ec_output_level 999`.


My problem is that I'm getting different output on the two servers.

On server 1 the messages look like this:
stdout `[5e85c70f][econ]: cid=0 authed`
econ: `[econ]: cid=0 authed`

On server 2 they look like this:
stdout: `[2020-04-02 11:09:21][econ]: cid=0 authed`
econ: `[11:09:21][econ]: cid=0 authed`

I'm trying to parse the logs and this is confusing me. Why does the output sometimes have the timestamp, and why is it sometimes in hex and sometimes in human readable format?
