### ISSUE TITLE
Inconsistent naming of commands that list/'dump' things

### ISSUE THREAD

**Issue by Robyt3** [teeworlds/teeworlds#2458]
The naming of commands that list/'dump' things is inconsistent and confusing.

The `bans` command lists all bans and is already short and concise. I think using the plural for all commands similar to this should be the default. Dump should only refer to writing something to the disk in that case.

The other commands use "dump" in different ways and as prefix and suffix. I propose
- `dump_binds` should be renamed to `binds`
- `tune_dump` should be renamed to `tunes`
- dump_local_console/dump_remote_console
   - should print a message in the console to indicate that a file was written (otherwise it's not clear that it does anything, especially considering the following as well)
   - should have a description that doesn't use the word "dump" again

**Comment by Dune-jr** [comment]
That's right. Only one should be careful renaming commands that are used in config files, because it is not worth breaking compatibility. I don't think any of these are, though

**Comment by Robyt3** [comment]
There is also the inconsistency of "unbindall" vs "unban_all" and "set_team_all".
"unbindall" used to appear in every version 0.5 config before all other binds, but that doesn't seem to be the case in the setting07 anymore. Is that command even necessary anymore? Seems like a dangerous command if you accidentally delete all your binds in the console.
