### ISSUE TITLE
Add option to download mapres embedded in maps

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2462]
You are already able to use a map you like and "remap" it. There are outside (maybe malicious) tools to extract images from teeworlds map, so why not add an ingame button for it?

**Comment by oy** [comment]
Out of decency there're won't be such a feature.
The better aproach would be to contact the original author and ask for the image and of course give credits.

**Comment by AssassinTee** [comment]
guess i will use the append feature instead
