### ISSUE TITLE
Autocompletion changes console text alpha

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2466]
![screenshot_2020-02-09_21-52-31](https://user-images.githubusercontent.com/20344300/74109773-95d9c800-4b86-11ea-9b90-9ff574af380a.png)

**Comment by ChillerDragon** [comment]
![screenshot_2020-02-12_00-44-43](https://user-images.githubusercontent.com/20344300/74290037-f0af2300-4d30-11ea-9dda-92cbc063d317.png)

Also affects game timer

**Comment by oy** [comment]
fixed by dc9a7174073e32330e3c114717b09f60f855bb7c
