### ISSUE TITLE
Assert stops server when max rcon tries are over

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2476]
happens since @oy did the network code refactor, i guess

**Comment by Dune-jr** [comment]
I advised @fokkonaut to open an issue anyway since this only affects recent trunk code. 0.7.4 is fine, thankfully

**Comment by Learath2** [comment]
The commit that breaks this is e0d4dc81de6f71922326a4d03ae30268dc2b682a

**Comment by fokkonaut** [comment]
This is kinda funny. Just placing this assert line https://github.com/teeworlds/teeworlds/commit/e0d4dc81de6f71922326a4d03ae30268dc2b682a#diff-a60948952f625787eb8b3cf54f82d047R297 in the code of 0.7.4 also causes this. It's just the newly added assert, maybe we should replace it by a return?

**Comment by Learath2** [comment]
I think it should be a `return` it's just leftover packets, we should just not send them. Crashing the server seems a little extra :)

**Comment by oy** [comment]
Any reports if  0.7.4 and older servers crashed that way?

**Comment by Dune-jr** [comment]
Not afaik

**Comment by oy** [comment]
@Dune-jr ok. When there're we should do a release with this commit 2272325e7325cc398d5a2a2a85d7acf0ed40db8e.
