### ISSUE TITLE
Incorrect key showing

### ISSUE THREAD

**Issue by zooom7z** [teeworlds/teeworlds#2480]
If we create combined command/bind like this:

> bind f4 "vote no; rcon vote no"

Settings can't identify it properly and in-game shows like that:
![image](https://user-images.githubusercontent.com/35894722/75338509-7c7b9000-5897-11ea-9cd1-f3b2978f6a89.png)
Any posibility to fix it?

**Comment by fokkonaut** [comment]
#2372
