### ISSUE TITLE
whisper messages are not logged properly

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2482]
https://github.com/teeworlds/teeworlds/blob/84bff2fb1786267962b24a239f88e5f012628861/src/game/server/gamecontext.cpp#L192

https://github.com/teeworlds/teeworlds/blob/84bff2fb1786267962b24a239f88e5f012628861/src/game/server/gamecontext.cpp#L196

the logging is kind of missing the recipient of a whisper message.

**Comment by Learath2** [comment]
Should you be logging whispers at all? I think there is an ethics concern there

**Comment by Dune-jr** [comment]
Definitely not.

That motivates end-to-end encryption for whisper messages.

**Comment by jxsl13** [comment]
Whisper messages are logged, but only looked at, if there is a complaint.
Especially if people are getting insulted via pms, getting spammed via pms and other offense.

**Comment by Learath2** [comment]
We just suggest people ignore others on ddnet, especially if it's through whispers. I don't like the idea of potentially private conversations getting logged at all.

**Comment by jxsl13** [comment]
Another of my concerns is to gather all possible information on people who are cheating or seem to be cheating, especially with lovely and nearly not detectable(by design) zoom modifications. Problems that other game types don't seem to have to a great extent. Thus automatically filtering through whisper for certain words might make sense, removing the need to manually look at possible whisper messages, that do actually contain private information. 
Yes, false positives are a possibility in such ambitions.

**Comment by Learath2** [comment]
It is useful sure, that doesn't mean it's not a breach of privacy.
Cameras on every corner of a country would reduce crime, it still creates a
surveillance state and is frowned upon.

**Comment by heinrich5991** [comment]
> Whisper messages are logged, but only looked at, if there is a complaint.

This is not a valid stance in the EU. The EU does not distinguish between looking or not looking at the data. Data collected is presumed to be looked at.

I strongly agree that we should not be logging whispers by default, they have a certain sense of privateness to them.

**Comment by Dune-jr** [comment]
And, regardless of the law, don't be evil.

I'm afraid end-to-end encryption is only viable with a form of accounts though. The server could intercept the public key and replace it with theirs, right?

**Comment by Learath2** [comment]
A Diffie Hellman key exchange is safe to do in public, you could use that
fact, but you'd only need to do a key exchange at the beginning of a
whisper session as it'd be a lot of traffic to establish keys between every
party on the server

**Comment by sepulzera** [comment]
Personally, I wouldn't expect a "whisper" communication via a computer game to be end-to-end-encrypted and to be really private. Though I wouldn't mind if it would. At least its tranport should be encrypted via TLS, that is usually required by the GPDR and makes sense.

But imho it shouldn't be logged, either.

Btw., detecting cheaters by scanning their whispers doesn't sound very promising to me.

> I'm afraid end-to-end encryption is only viable with a form of accounts though. The server could intercept the public key and replace it with theirs, right? - Dune-jr

Probably correct. You should compare the key hashes to validate them. But I doubt that many people do that, as it is too technical and annoying, if you have to revalidate them on every reconnection.

**Comment by Dune-jr** [comment]
For public note, we talked about this and concluded it is not safe either.

**Comment by oy** [comment]
You can read whispers when logging the network too.

Every communication on a teeworlds server should be considered non-private as you can't be sure what kinda source-code is running there.

**Comment by Dune-jr** [comment]
While I agree those communications should be considered non-private, inadvertently seeing those whenever checking the logs sounds terrible to me.

**Comment by oy** [comment]
But hiding that log meesage doesn't change anything - just gives you false-privacy. When you use the teeworlds log network command you can grab them or server hosters could simply modify their source. and add the log message back.

**Comment by sepulzera** [comment]
Reading throughput at real time and logging are two very different things, though.

> server hosters could simply modify their source. and add the log message back.

True. But that is no reason to do things in vanilla. Joining modificated servers is always some risk.

**Comment by oy** [comment]
That's an incorrect assumption. A user can't verify if a server is not modified and whisper messages are logged in the end. You always have to assume that they are.

**Comment by jxsl13** [comment]
teamchat is still not logged properly, recipient team is not visible

I think a compromise in the way that the issue is properly fixed and disabled by default with a server config variable would imo make more sense, as whoever would really want it, it would truely not matter if it's a mod or actually a vanilla server, they would add it anyway.

but yeah, not my decision.
