### ISSUE TITLE
Stats don't reset after voted for 'restart'.

### ISSUE THREAD

**Issue by IgnaceGeys** [teeworlds/teeworlds#2483]
After a game of gCTF, the score resets. To restart a game, we always vote for 'restart'. However, if we kill other players before we vote (in the time between the two games), those kills and deaths will update in the scoreboard and statboard. Then, when you vote for restart, the time and the score in the scoreboard resets, but the kills and deaths not. None of the stats in the statboard reset too. As a result you can get weird stats like captured 12 flags as you can see in the screenshot below. This was possible because I captured 2 flags before we voted restart and I captured 10 flags after we restarted. -darkstar

![screenshot_2020-03-06_21-04-31](https://user-images.githubusercontent.com/55281405/76118960-ab5bd980-5fee-11ea-964c-72bddd7b877d.png)

**Comment by Dune-jr** [comment]
Was this a 0.7.4 server? This should have been fixed by https://github.com/teeworlds/teeworlds/pull/2163

**Comment by IgnaceGeys** [comment]
Oh alright, it was a 0.7.3 server, I guess the problem is solved now if we change the version to 0.7.4. Thanks!

**Comment by AssassinTee** [comment]
I already merged 0.7.4 months ago in gctf, but server owners still use 0.7.3 so this issue is technically fixed while not in production 😒

**Comment by sepulzera** [comment]
In other games, mods would print an info into the admin console, when updates are available. Though I didn't see that in any Teeworlds mod, yet.

**Comment by AssassinTee** [comment]
@sepulzera this would be possible, if teeworlds had a http(s) client, but it's currently too much overhead for too little gain
