### ISSUE TITLE
jungle_midground.png buggy

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2485]
Assa found a bug in that mapres.
there is some transparency where it does not belong:

![bug](https://user-images.githubusercontent.com/371944/76360311-05c1a680-631d-11ea-9f3b-7c94edf1e0fe.png)
![Bildschirmfoto_2020-03-10_um_21 46 36](https://user-images.githubusercontent.com/371944/76360329-0eb27800-631d-11ea-8156-9b4e58fb1a30.png)

![Bildschirmfoto_2020-03-10_um_22 08 55](https://user-images.githubusercontent.com/371944/76360333-12de9580-631d-11ea-9862-0419df6b97f2.png)

here is a fixed version:

![jungle_midground](https://user-images.githubusercontent.com/371944/76360344-196d0d00-631d-11ea-9f0a-0bbf7b36d11e.png)

**Comment by AssassinTee** [comment]
related: https://github.com/teeworlds/teeworlds/issues/1911
