### ISSUE TITLE
GIF animations in maps

### ISSUE THREAD

**Issue by 3da** [teeworlds/teeworlds#2488]
It would open wide opportunities for map makers. Maps would be more funny and would involve more people.

**Comment by ChillerDragon** [comment]
It is already possible to do it manually by changing alpha of multiple images.

**Comment by Robyt3** [comment]
Animated water and lava tiles maybe, but using quads would probably look better anyway, if done properly. Maybe the map editor should also come with some default quad layer templates for sky, water, sun, moon etc. animations.
The GIF format itself would probably be inefficient and bloat the size of maps unnecessarily.

**Comment by 3da** [comment]
How about APNG as format for input? Internal format can be any.

**Comment by AssassinTee** [comment]
This will be an additional attack vector. An SVG support would be more usefull.

**Comment by oy** [comment]
It's already planned to support animations (#1592).
Closing this.
