### ISSUE TITLE
dbg_dummies is broken

### ISSUE THREAD

**Issue by Learath2** [teeworlds/teeworlds#2491]
`dbg_dummies` triggers one of the new "errorous client id" asserts (which is a typo btw it should be "erroneous").

We should either/both find a nice way to set those occupied client ids ONLINE from gamecontext (or add a new state for dummies) or/and move the dummy handling to the engine.

**Comment by fokkonaut** [comment]
I have dummies in F-DDrace, handled by the engine. They have their own state.

**Comment by Learath2** [comment]
You could pull request this into vanilla assuming you figured out all the kinks. I would do it but I'm not sure what the consequences of dummies moving into the engine are.

**Comment by nheir** [comment]
introduced with e0d4dc81de6f71922326a4d03ae30268dc2b682a

**Comment by AssassinTee** [comment]
In 0.8 there want to be a true dummy-bot support, too. So this is the first building block

**Comment by Robyt3** [comment]
IMO #1966 should include different AI behaviours which can be toggled, to achieve different dummies and tutorial bots (#38). Example behaviours:
- attacking
- movement (moving, jumping, hooking)
- playing objectives (capturing flags etc.)
- searching for hearts, armor and weapons

A dummy would just a bot with non of these enabled.
