### ISSUE TITLE
[Editor2] Fix group/layer list being clipped incorrectly

### ISSUE THREAD

**Issue by LordSk** [teeworlds/teeworlds#2499]
History and layer list is being clipped incorrectly on the right side.

![image](https://user-images.githubusercontent.com/294603/76709107-3bd79f80-66fc-11ea-9c15-633282e108ec.png)

![image](https://user-images.githubusercontent.com/294603/76709140-89eca300-66fc-11ea-9eef-7a02515116ca.png)

**Comment by Ryozuki** [comment]
Looks like its already fixed to me:
![image](https://user-images.githubusercontent.com/15859336/77154745-8f4f4200-6a9c-11ea-8dd7-98dc4b851074.png)

**Comment by LordSk** [comment]
(from @Ryozuki on discord)
![img](https://cdn.discordapp.com/attachments/490150878934990850/690506093788397608/unknown.png)

> i am compiling with cmake and ninja btw g++ is 
g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-pkgversion='Arch Linux 9.3.0-1' --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
gcc version 9.3.0 (Arch Linux 9.3.0-1) 
sdl 2.0.12

It is still broken on my end, as well as @Dune-jr 's.
![image](https://user-images.githubusercontent.com/294603/77156326-77c58880-6a9f-11ea-81f1-fba6da0a5c8e.png)
(from Dune)
