### ISSUE TITLE
[Editor2] Allow arbitrary reordering of groups/layers

### ISSUE THREAD

**Issue by LordSk** [teeworlds/teeworlds#2502]
Right now, dragging and dropping only allows to move one up or down. Make it so we can move the dragged item anywhere.

![image](https://user-images.githubusercontent.com/294603/76710200-c53f9f80-6705-11ea-8e67-5e9431c61f5a.png)

**Comment by Fisico** [comment]
Maybe even allow multiple layers to be dragged at the same time.

**Comment by LordSk** [comment]
Fixed by https://github.com/teeworlds/teeworlds/pull/2505
