### ISSUE TITLE
functionally overloaded chat commands don't work

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2507]
There is currently a problem with chat commands that have two functions, one being without having to pass a parameter, the second being having the same command, but having to pass a parameter, currently visible on ddrace with the /spec command.
Would be nice to tell the client that a parameter is optional.

**Comment by fokkonaut** [comment]
This is the case, [] means optional, <> means needed (or inverted, not sure rn)

**Comment by jxsl13** [comment]
the /spec is seemingly broken, as when you join spectators with /spec and try to join the game again with /spec, you can't because the auto completion fucks up.
You have to manually write /spec <press esc> <press enter>

**Comment by fokkonaut** [comment]
What do you mean? Cant reproduce.

**Comment by trafilaw** [comment]
https://www.youtube.com/watch?v=-mCvEpW5FKk

That is was @jxsl13 means
The last /spec was with pressing escape first, before you can't leave spec
