### ISSUE TITLE
Quote player names with spaces in commands

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2525]
When using player name auto completion it should quote names that have spaces.
That is useful for custom commands using names not as the last argument. Also it would improve the vanilla whisper UX because currently it can get tricky to whisper to players including spaces.

so when typing ``/whisper nam`` on tab it should autocomplete to ``/whisper "nameless tee"``

but simple names like ``/whisper foo`` should stay unquoted.

**Comment by Dune-jr** [comment]
That's why you can't have custom commands with a name and other arguments, at least last time I checked.

**Comment by Dune-jr** [comment]
> That's why you can't have custom commands with a name and other arguments, at least last time I checked.

Names can be duplicated and such a system will never cover all the corner cases.

**Comment by ChillerDragon** [comment]
@Dune-jr which corner cases are not covered and how am I supposed to whisper to players including spaces?

**Comment by Dune-jr** [comment]
> @Dune-jr which corner cases are not covered

Duplicates, if you have two ChillerDragon in the game, the whisper will not go through

**Comment by ChillerDragon** [comment]
> Duplicates, if you have two ChillerDragon in the game, the whisper will not go through

Well yes thats why we should bring back the old name system. But I do not see how this is related. Or why do you think it is a bad idea to fix the spaces issue just because names can be the same?

**Comment by Dune-jr** [comment]
> Well yes thats why we should bring back the old name system.

Old clients and servers will always accept those.

> But I do not see how this is related. 

The idea is that you can't design a proper system based on names, so trying to make a full blown shell-like command system out of it is not going to work anyway, because Teeworlds is not designed for that.

**Comment by ChillerDragon** [comment]
I think giving up bug fixes because there might be other issues is kinda meh. And how am I supposed to whisper to players including spaces other than pressing the tab key a zillion times or manually quoting it?

**Comment by Dune-jr** [comment]
Is the current system really bugged?

**Comment by ChillerDragon** [comment]
> Is the current system really bugged? As far as I know, whisper works with player names that include spaces.
> 
> If it is bugged, it should be fixed.

I could not get it working. Does not mean its very bugged but its at least not designed well for stoopid users.

**Comment by fokkonaut** [comment]
@Dune-jr it is bugged in master, as seen in my client. Since Learath2 made the update that supports `/w <playername> <message>` (for people who are used to that format from 0.6). It was generally a very good idea, but there are two things: First, the issue right here, and second you have to press Enter twice, first to get into whisper mode, second to send the message.

**Comment by Learath2** [comment]
Oh, so that's why you didn't support instant whispers, this is one thing we never solved either, I guess we can revert to `/w <playername>`

**Comment by Dune-jr** [comment]
Yes, that's why. I agree we should revert to `/w <playername>`. 
https://github.com/teeworlds/teeworlds/commit/2fc4a0dab2dceb9e4cfe5618e473e21e81f4246f#diff-da8e51385055fcc863833513a3930b15.
