### ISSUE TITLE
Extend demo browser UI (sort and filters)

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2527]
It would be nice to be able to sort demos by name and date. By default demos are kinda sorted by date due to the timestamp in name. But renamed demos loose this feature.

This was done in ddnet already:

https://github.com/ddnet/ddnet/commit/da17b795c5b7460be130084e88cb28eefe051cbe
https://github.com/ddnet/ddnet/commit/675c6eb1e099b75fb32006aaab907743ce06152a#diff-4d014b7597f3da3a22e874656229fd11

It also would be nice to have a option which loads all demos and then filter for things like:
- map
- length
- timestamps

**Comment by Dune-jr** [comment]
How does this not lag when loading a large amount of demos?

**Comment by ChillerDragon** [comment]
> How does this not lag when loading a large amount of demos?

Demo sorting by date should work fine without lag. And loading actual demo data will lag for sure and should not happen automatically if its on the main thread. So I thought maybe some load data button that shows a loading bar which can also be aborted. Not too sure about that feature. Date filter has priority.

**Comment by Dune-jr** [comment]
In order to have filter by things like map, length etc. you need to load all the demos.
So without revamping the way the demos menus work, all you can do is sort by date created, relying on OS-dependent information.

**Comment by ChillerDragon** [comment]
Yea as I said it would be nice if one is motivated. But sorting by date is a feature I really depend on in my daily tw usage.

**Comment by Learath2** [comment]
The demo headers can be extracted asynchronously in a worker thread so populating the list doesn't lag. I might do this if I feel particularly bored tonight.

**Comment by Learath2** [comment]
Also this is a duplicate of #1739

**Comment by ChillerDragon** [comment]
@Learath2  good catch!
