### ISSUE TITLE
Editor2: UiIntegerInput underflows when typing large numbers

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2535]
And in general, this looks bad when there are too many digits.
Should `UiIntegerInput` have mandatory min/max parameters?

![Screenshot from 2020-04-03 15-25-28](https://user-images.githubusercontent.com/355114/78365456-690ec380-75bf-11ea-9648-cd0d21c7714f.png)
![Screenshot from 2020-04-03 15-25-32](https://user-images.githubusercontent.com/355114/78365462-6ad88700-75bf-11ea-9815-919d2f6c5495.png)

**Comment by Learath2** [comment]
Or at the very least the number should be truncated by ... if it doesn't fit and look like this only while editing.
