### ISSUE TITLE
Warumup Time and Motd conflict

### ISSUE THREAD

**Issue by themisak** [teeworlds/teeworlds#2541]
Hey Guys,

first of all, thanks for all the good work you do on Teeworlds!

I have found a bug wich needs treatment. When you set a motd it gets outputted over the warumup. See the picture!

I also tried so switch the big warumup writing off but it doesent work. I tried sv_countdown -1 and sv_warumup -1 both dont work.

Many thanks!

![screenshot_2020-04-07_13-58-59](https://user-images.githubusercontent.com/44925034/78667498-56ef9680-78d9-11ea-9c8f-b45ca66760c0.png)

**Comment by oy** [comment]
Should probably show the smaller warmup note, like it's done after some time, while the motd is shown.

**Comment by Dune-jr** [comment]
> I also tried so switch the big warumup writing off but it doesent work. I tried sv_countdown -1 and sv_warumup -1 both dont work.

Note this part of the issue was unanswered
