### ISSUE TITLE
Wrong ip shown in connection state

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2543]
While connecting the ip shown is only set in the browser ui. So connecting via ``connect <addr>`` in console it does not show the correct ip.

![image](https://user-images.githubusercontent.com/20344300/78974648-c0a6b500-7b12-11ea-8c65-9276524362c4.png)

![image](https://user-images.githubusercontent.com/20344300/78974722-e16f0a80-7b12-11ea-8660-048dfd5b058c.png)

![image](https://user-images.githubusercontent.com/20344300/78974662-c69c9600-7b12-11ea-8298-1306a6c056ea.png)

**Comment by Dune-jr** [comment]
0.7.4 is fine, so this bug was introduced after 0.7.4.

**Comment by Robyt3** [comment]
Yeah, it has to do with the favorites password storage I introduced. I'm working on a fix.

**Comment by Dune-jr** [comment]
Oh, thanks @Robyt3
