### ISSUE TITLE
The (none) theme is broken

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2552]
If you select the `(none)` theme, the grid background no longer loads. 0.7.4 was fine

![](https://cdn.discordapp.com/attachments/510879693982007316/698576213270331502/unknown.png)

This is probably related to https://github.com/teeworlds/teeworlds/pull/2459, so cc @Robyt3

**Comment by Robyt3** [comment]
Works for me:

![screenshot_2020-04-11_22-28-03](https://user-images.githubusercontent.com/23437060/79054417-e8963580-7c44-11ea-9f1d-d197ec39c051.png)

Does the grid work correctly on the loading screen for you?

Can you check whether CMenus::RenderBackground get called at all?

The logic didn't change:

```
// render background only if needed
if(Client()->State() != IClient::STATE_ONLINE && !m_pClient->m_pMapLayersBackGround->MenuMapLoaded())
	RenderBackground(Client()->LocalTime());
```

Maybe the background map isn't unloaded properly for you?

**Comment by Learath2** [comment]
FWIW this is broken for me too

**Comment by Robyt3** [comment]
Thanks for the fix. It seems I had `gfx_clear 1` in my config, which made that clear unnecessary for me ;)

**Comment by Dune-jr** [comment]
> Thanks for the fix. It seems I had `gfx_clear 1` in my config, which made that clear unnecessary for me ;)

It's still kinda necessary, your menus turned to yellow because of that bug :D

**Comment by Learath2** [comment]
Without a Clear or gfx_clear the previous frame isnt cleared so the ui
appears in slow motion and moving things leave a trail :P
