### ISSUE TITLE
Game seems to start when warmup is at 3

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2559]
Using `sv_warmup 5` with no countdown (default) and `reload`, the game reset at 3:

https://streamable.com/vdde50

This is a bug.

**Comment by Robyt3** [comment]
See #1690 and #2383.

**Comment by Dune-jr** [comment]
Ah. This issue is not mentioned in https://github.com/teeworlds/teeworlds/issues/1690, but it looks like it is patched by https://github.com/teeworlds/teeworlds/pull/2383. I guess I will leave this open until #2383 is merged then :)

**Comment by oy** [comment]
Fixed by #2383
