### ISSUE TITLE
Scrollbars for values that exceed the the UI-defined maximum

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2563]
Settings Max fps higher than the UI limit looks odd. Should we do anything about that?

![screenshot_2020-04-15_12-42-11](https://user-images.githubusercontent.com/355114/79328812-ee2a9e80-7f16-11ea-92d9-e121d072e600.png)

**Comment by Robyt3** [comment]
I guess clamping the scrollbar handle to the minimum and maximum in UI would look better and at least allow changing the value back to a normal range via the UI.

**Comment by Dune-jr** [comment]
> I guess clamping the scrollbar handle to the minimum and maximum in UI would look better and at least allow changing the value back to a normal range via the UI.

That's probably the best way to go about it, yeah
