### ISSUE TITLE
allow to add a prefix/suffix for server side demos

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2581]
Like with the logs, that kind of get that prefix and are dumped into the same folder, 
I'd love to have this server differentiation for demos as well, as they have the same purpose of logging.

**Comment by Dune-jr** [comment]
I don't know any game that does this? They all use a predefined name format.

**Comment by jxsl13** [comment]
I cannot differentiate where the demos are from, to have a look at them depending on the server they came from.
if one hosts tons of servers the work to find the right demo would be enormous.

logfiles also use a predefined format, but still allow for prefixing them like in this case:

<img width="381" alt="Bildschirmfoto 2020-04-19 um 13 50 11" src="https://user-images.githubusercontent.com/371944/79687081-00714900-8245-11ea-920d-ce16271c8b0d.png">

**Comment by ChillerDragon** [comment]
Putting map name in the demo file could also help when each server runs a different map pool
https://github.com/ZillyWoods/ZillyWoods/commit/70b5457991c5325b2b1920ca4ea1a88e7f8b773c

**Comment by Dune-jr** [comment]
You can use a different config directory per server.

**Comment by jxsl13** [comment]
I do not see how that's doable, please elaborate in that case.
current setup:
one executable
one storage.cfg pointing to the ~/server_logs (content visible above)
each server is started with `zcatch_srv configs/autoexec_XXX.cfg`
each autoexec_XXX.cfg executes the shard file that contains rcon, econ, db etc configs.
log files are dumped into dumps/logs
