### ISSUE TITLE
Merge Player and Tee settings tab

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2583]
Make room for a tab for UI options. Use this to fix https://github.com/teeworlds/teeworlds/issues/2293

**Comment by Sonix-** [comment]
![teeplayermergetest](https://user-images.githubusercontent.com/2030615/79784812-1a915100-8343-11ea-9bf6-ae68f1a94055.png)
Quick sketch
Any thoughts?

the Custom and Delete (skin) buttons at the bottom right may look confusing

**Comment by oy** [comment]
The buttons should then probably be attached to the skin selector.
For the country selection there opens a pop-up?

**Comment by Dune-jr** [comment]
We already have a popup thing for countries in the browser

**Comment by Sonix-** [comment]
> The difficulty is the skin customization UI, that can hardly be squashed down there

Worth a try, at least imo.

**Comment by Dune-jr** [comment]
There is no free space, it's not so easy 

![screenshot_2020-04-20_21-55-01](https://user-images.githubusercontent.com/355114/79793928-add18300-8351-11ea-8747-0ec6ae935f98.png)

**Comment by jxsl13** [comment]
country flag side scroller might be cool, but dunno how hard to implement.
I kind of cannot imagine how that drop down menu would look like when it's open.
kinda scrollable?

[<][RU][>]

**Comment by Dune-jr** [comment]
Make it simple and use the existing code we have to pick a country flag imo.

**Comment by Learath2** [comment]
> There is no free space, it's not so easy.
> Iirc this "free space" was introduced (and the HSL picker scaled down) because it is required on some ratios.

@Dune-jr How about we move the pallette into the HSL picker? It'd make that space actually free

**Comment by Dune-jr** [comment]
@Learath2 sounds like a good idea to me

**Comment by TsFreddie** [comment]
![image](https://user-images.githubusercontent.com/3797859/93723823-e217cc80-fb99-11ea-8fc0-17890c63ae06.png)

thoughts?

**Comment by Dune-jr** [comment]
Excellent work!

**Comment by Zatline** [comment]
@TsFreddie very clean, great merge!
