### ISSUE TITLE
Suggestion to remove hud delay

### ISSUE THREAD

**Issue by zooom7z** [teeworlds/teeworlds#2603]
I suggest removing this 5 seconds delay of disappearing mini-hud of demo time AFTER Esc pressing.
Remove this mini-hud with time **or** at least make it for 1 second.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35894722/80720275-5e374800-8b05-11ea-9e4b-6e3261232e40.gif)

**Comment by oy** [comment]
You can press `CTRL` to make the hud disappear.

**Comment by zooom7z** [comment]
> You can press `CTRL` to make the hud disappear.

WOAH, i didn't even know, thanks🤣
