### ISSUE TITLE
Menu "shadow" corners do not match the buttons

### ISSUE THREAD

**Issue by Sonix-** [teeworlds/teeworlds#2609]
Probably happened after this commit: https://github.com/teeworlds/teeworlds/commit/5f9dfaadd31e854d947541acc2ee6542a5f7cbc4

0.7.4:
![before_corners](https://user-images.githubusercontent.com/2030615/80864443-f3138000-8c82-11ea-9ced-f929816904b7.png)

0.7.5:
![075corners](https://user-images.githubusercontent.com/2030615/80864444-f73f9d80-8c82-11ea-9e20-6bc4f259773a.png)

**Comment by Dune-jr** [comment]
Yes, this is because of the variable corner size. In `menus_start.cpp`, it should be 10, but it is forced at 5 there:

https://github.com/teeworlds/teeworlds/blob/5f9dfaadd31e854d947541acc2ee6542a5f7cbc4/src/game/client/components/menus.cpp#L2616-L2623
