### ISSUE TITLE
Negative gametype filter

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#2621]
From Discord, 2020-05-07:
>[1:43 AM] ShootXen: is there anyway to exclude some gametypes in the serverbrowser?
>[1:43 AM] ShootXen: I'm annoyed already of DDRace
>[1:44 AM] ShootXen: DDRaceNetwork should have stayed on 0.6
>[1:48 AM] heinrich5991: good question, I don't htink so
>[1:48 AM] heinrich5991: you could try to add a filter that has all known game types
>[2:04 AM] ShootXen: isn't half of the work already done? just add to the current filter system the exclude option
>[2:04 AM] ShootXen: instead of filtering for one specific just exclude that one
>[2:08 AM] heinrich5991: yes, that'd work
>[2:09 AM] heinrich5991: it also sounds good. do you have a github account? perhaps you could create an issue
>[...]
>[2:16 AM] ShootXen: Could someone create a "issue" on Github for me? I wanted to mention that the filter system is able to filter for one specific mod but not to exclude one.

**Comment by Dune-jr** [comment]
Note there is already an exclude filter that works on gametype.
