### ISSUE TITLE
Server-side K/D counting

### ISSUE THREAD

**Issue by gerdoe-jr** [teeworlds/teeworlds#2623]
When you enter the server, all K/D are zero. But score - not and it looks weird.

So, I think it must be counted as score, server-side.

**Comment by fokkonaut** [comment]
Yes, please, could be a simple new entry in the snaps

**Comment by Dune-jr** [comment]
This is already https://github.com/teeworlds/teeworlds/issues/158

**Comment by oy** [comment]
Continues in #158
