### ISSUE TITLE
"map differs from the server. [id of the map] != [id of the map]"

### ISSUE THREAD

**Issue by C3r1se** [teeworlds/teeworlds#2628]
When I tried to join a server (---=[TeeRace]=--- ; map : Light_Grey), I had the following error : 
![image](https://user-images.githubusercontent.com/34578540/82490850-227c1680-9ae4-11ea-843c-a4aab78b5e28.png)

The map would seem to download, and at the end of the download, the error message would appear.
The bug was solved by going to "AppData\Roaming\Teeworlds\downloadedmaps" and deleting all files related to the Light_Grey map.

I was able to reproduce the bug by putting back the previous Light_Grey map files in the folder.
Here are the files attached to reproduce the bug :
[downloadedmaps.zip](https://github.com/teeworlds/teeworlds/files/4658983/downloadedmaps.zip)

**Comment by heinrich5991** [comment]
The trouble seems to be that the renaming does not work on Windows when there's already a file there.
