### ISSUE TITLE
In survival, players may all spawn in one spot because of randomization

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2634]
Related to issue https://github.com/teeworlds/teeworlds/issues/2138 and PR https://github.com/teeworlds/teeworlds/pull/2182

Discord user Stiopa#2095 reported 

> Issue: Teeworlds respawning all tees in one spot ocassionaly.
> 
> Gamemode: LTS
> 
> Map: lts1
> 
> Description: The respawns in the gamemode is seemingly random, which sometime put all 3 tees in one spot, while there are other spawn points free. 
> 
> Server: SteamLUG [EU]
> IP Address: 5.189.189.42:8303
> Version: 0.7.4

Though randomizing spawns in survival makes sense, I think we should randomize the order in which they are chosen to respawn, instead of the position.

**Edit**: apparently it happens in LMS, which is even worse

**Comment by oy** [comment]
It should probably pick empty/lower player number spawns first randomly.

**Comment by Dune-jr** [comment]
Then the spawn locations will always be the same, I believe.

**Comment by oy** [comment]
Shouldn't be.
It should collect all empty spawn points first and pick one randomly. When no spawn is available collect all spawn points with 1 player around and pick one randomly from these.

**Comment by Dune-jr** [comment]
Ah, right, that works.
I believe randomizing the order of spawn also works, and it's a solution that we could apply independently of the gametype, so I think it would be prettier (it's particularly a problem in LMS because everyone spawns at once).

**Comment by oy** [comment]
Then you would have to randomize the tick handling of players, dunno if that's a good idea.
Yeah, in the other gametypes you'd only notice it at game start.
