### ISSUE TITLE
skinparts shown twice

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2640]
if you have bodyA.png in your data folder and also in your config directory skins folder it will be shown twice ingame, should be avoided

**Comment by oy** [comment]
Yeah, the 2 skin parts could be different. Don't think tw should check if skin parts are equal.

**Comment by fokkonaut** [comment]
The point about this is also, that its not just shown twice, but also double selected, which is weird and makes no sense then.

**Comment by Robyt3** [comment]
https://github.com/teeworlds/teeworlds/blob/9ad1642f7e781df5784321a499d7f43520b2a827/src/game/client/components/menus_settings.cpp#L442-L443

Skins and parts currently do not have any property that identifies from which file they were loaded. Ignoring the skins and parts with duplicate names from data folders with less priority would probably be the easiest solution.
