### ISSUE TITLE
Automatic CPU throttling

### ISSUE THREAD

**Issue by Sworddragon** [teeworlds/teeworlds#265]
The discussion from IRC:

> <matricks> could have an autosense for that one<br>
> <Sworddragon> You mean automatic activation?<br>
> <matricks> yeah<br>
> <Sworddragon> I wanted to suggest this before you wrote :O<br>
> <matricks> detect if you have over, well, a lot of fps and then throttle<br>
> <Sworddragon> Even with throttle the fps are +300. Think it should throttle more on much power
> 
> <Sworddragon> matricks: What shoudl be the limit? 30 FPS? 60 FPS? User defined value?<br>
> <Dunedune> certainly not 1400<br>
> <matricks> Sworddragon: same has the screen hz :)<br>
> <teetow> to make matters worse, distinguishing frame rates is also something you can train yourself to do<br>
> <matricks> Sworddragon: kinda sad that vsync behaves soo bad :/<br>
> <Sworddragon> matricks: But throttle can go even lower if the FPS does because of vsync

The current cpu_throttle 1 halves only the performance. This are on my pc from 600 FPS to 300 FPS. It should throttle until the refresh rate of the monitor is reached. If VSync goes below this I think it should throttle then to the VSync value. Maybe it is even a good idea to activate this reworked function then by default.

**Comment by marcoms** [comment]
@oy should vsync be limiting the frame rate to 60? On my machine cl_showfps reports values around 400...

**Comment by marcoms** [comment]
Sorry, I realised AMD Control Centre was set to never wait for vertical refresh! Changing it to allow the application decide fixes it.
