### ISSUE TITLE
Joystick too fast in menus because UI sens is dependent on mouse sens.

### ISSUE THREAD

**Issue by Robyt3** [teeworlds/teeworlds#2653]
The UI translates the mouse movement by a ratio of `m_pConfig->m_UiMousesens/float(m_pConfig->m_InpMousesens)`. This makes the menus completely unuseable with a joystick. Nudging the joystick to any direction beyond the dead-zone moves the mouse to the edge of the screen almost immediately.

I have mouse, UI, joystick sens on 100, 100, 20 respectively. This makes the menus useable when using the original patch in #2632, but that makes menu sens depend on mouse sens.

This will probably require some rewrites of the engine/gameclient to differenciate between joystick movement and mouse movement in the UI. Maybe add a different UI joystick sensibility. Either way, `ConvertMouseMove` must use the correct sensibilities.

**Comment by oy** [comment]
The UIMousesens is supposed to be used by the mouse only. The behaviour wasn't adjusted when joiystick support was added. So a UIJoysticksens settings should be added and joystick and mouse input have to be seperated.
