### ISSUE TITLE
[Old Editor] Crash on viewing envelope (ctf8)

### ISSUE THREAD

**Issue by Patiga** [teeworlds/teeworlds#2659]
This is an out of bounds access caused by a broken curve type value in a map. In this case on ctf8, the 6th and 7th envelope have such a broken value (2752512 and 527 respectively), valid values are 1-5.

I've heard that the old editor shouldn't get much attention anymore, but i think ctf8, being an official map, should be fixed.
```
Thread 1 "teeworlds" received signal SIGBUS, Bus error.
0x0000555555671a0c in CEditor::RenderEnvelopeEditor (this=0x555555935dd0, View=...) at src/game/editor/editor.cpp:3759
3759					if(DoButton_Editor(pID, paTypeName[pEnvelope->m_lPoints[i].m_Curvetype], 0, &v, 0, "Switch curve type"))
(gdb) bt
#0  0x0000555555671a0c in CEditor::RenderEnvelopeEditor (this=0x555555935dd0, View=...) at src/game/editor/editor.cpp:3759
#1  0x0000555555674ffb in CEditor::Render (this=0x555555935dd0) at src/game/editor/editor.cpp:4250
#2  0x0000555555677016 in CEditor::UpdateAndRender (this=0x555555935dd0) at src/game/editor/editor.cpp:4701
#3  0x0000555555590edc in CClient::Render (this=0x7ffff6f11010) at src/engine/client/client.cpp:794
#4  0x0000555555596a38 in CClient::Run (this=0x7ffff6f11010) at src/engine/client/client.cpp:2130
#5  0x0000555555598c8a in main (argc=1, argv=0x7fffffffe368) at src/engine/client/client.cpp:2723
```
Note: the crash was fixed with a simple bounds check in the ddnet client: https://github.com/ddnet/ddnet/pull/2193

 Also i would really like to know which editor was used for the map!

**Comment by Sonix-** [comment]
Funny thing is that I've never used envelopes on that map, must be the early .map file I started working on that had previous envelopes. 
I've been using the teeworlds editor, no custom clients I believe, or at least not ddnet. IIRC

**Comment by Patiga** [comment]
Also noteworthy: in the 7th envelope on ctf8 the 2 points are actually not in chronological order (the second point has a lower timestamp then the first one).
The standard maps seem to have quite a lot of unused envelopes in them.
