### ISSUE TITLE
Github Actions now failing for MacOS

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2664]
Looks like a freetype thing, independent of bam/cmake

```
Error: freetype 2.10.1 is already installed
To upgrade to 2.10.2, run `brew upgrade freetype`.
```

**Comment by ChillerDragon** [comment]
I have the feeling this can be fixed by waiting or rerunning the pipe. Doubt we need to put a ``brew upgrade freetype`` in there. Maybe if we are desperate we can add a ``brew update && brew upgrade``
