### ISSUE TITLE
When clicking on a friend's name (friends list) automatically select server he's playing in

### ISSUE THREAD

**Issue by Sonix-** [teeworlds/teeworlds#2666]

**Comment by Dune-jr** [comment]
Ideally it should center the server list view on it (which is not trivial because spaghetti code)

**Comment by Rei-Tw** [comment]
Or just spawn a small popup next to the friend's name with the server basic Informations and a join button

**Comment by Dune-jr** [comment]
> Or just spawn a small popup next to the friend's name with the server basic Informations and a join button

That's pretty much already what is displayed
