### ISSUE TITLE
Server loses connection to master

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2669]
When logging into rcon, the server sends lots of commands to the client. Especially in mods, like ddnet7 or my F-DDrace mod the amount of commands that the server sends is higher than in vanilla. While the commands are sent, the server loses connection to the master server and even after all commands are sent it cant find the connection back to it. Same can happen on ddnet7 servers with many votes on a mapchange/ difficulty change (e.g. from novice to brutal).

The server responds these messages:
First, when you login you have to wait around 1 minute, then the server notices it lost the connection. It will say "WARNING: Master server is not responding, switching master" once, after that it will only say "WARNING: No master servers. Retrying in 60 seconds".
(of course it also says "refreshing ip adresses" and "fetching server counts" inbetween)

@Learath2 had an idea:
> It might be that during the flood a token message goes missing and the server keeps dropping the new messages because wrong token

This could actually be true, since this error doesnt happen on 0.6, even on my bridge server it only affects the 0.7 master and not the 0.6 master, that one still works fine.
I lowered `MAX_RCONCMD_SEND` from 16 to 4, that worked as a workaround until this got actually fixed.

**Comment by oy** [comment]
The communication bewteen server and master uses connless messages which request a new valid token for each message.

**Comment by fokkonaut** [comment]
I just called the "status" command in f2 with > 80 players online, that also caused this bug, it seems like its really just the amount of traffic, since status command sends many rcon lines to the client
