### ISSUE TITLE
advanced config syntax

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2670]
I know its crazy but sometimes I feel an urge for basic if statements and variables in my config.
Things like this would be nice:

auth.cfg
```
if ui_server_address == "localhost"
  rcon_auth rcon
else
  rcon_auth crazy_secure_password
endif
```

config.cfg
```
bind x "exec auth.cfg"
```

So there is no need to add a new variable system. Just supporting comparison for the existing variables would be very useful already.

**Comment by Learath2** [comment]
This would require major rework no matter which way you intend it. If you want the conditions evaluated while the config file is being read, that would mean the order things appear in the config now matters. If you want the conditions evaluated at runtime, that'll mean we'll need to turn the conditions into objects.

**Comment by ChillerDragon** [comment]
> If you want the conditions evaluated while the config file is being read, that would mean the order things appear in the config now matters. If you want the conditions evaluated at runtime, that'll mean we'll need to turn the conditions into objects.

Yea I think that during file read is fine enough since this can be triggered during runtime using ``exec`` like shown in my example.

**Comment by Learath2** [comment]
This still requires a rather large restructuring of the way we parse config files. Currently it's just line or semicolon separated commands, for this we'll need to introduce some sort of meta commands, kinda like how it's done in shell scripting.

**Comment by Robyt3** [comment]
Yeah, if-else would require a major rework. Something that works on a single line could be easier:
`if "ui_server_address == localhost" "rcon_auth rcon"`
`if "ui_server_address != localhost" "rcon_auth crazy_secure_password"`

**Comment by axblk** [comment]
Syntax like this would only add unnecessary complexity. The console should just stay as simple as it is.

For this use-case one could just add commands like:
`exec_eq var_name value command`
`exec_neq var_name value command`
which execute the command if the value of the variable is (not) equal to the given value.

**Comment by oy** [comment]
Agree with @axblk 👍 
That would be a more simple approach.

**Comment by Learath2** [comment]
Either what @Robyt3 proposed or what @axblk proposed would work fine. One would require an expression parser though, which might be something we might not want to bother implementing.

**Comment by Robyt3** [comment]
Should be possible to implement different operators with a single command, if you interpret the arguments separately:
`if ui_server_address == "localhost" "rcon_auth rcon"`
First argument is always a config variable (either integer or string). Third argument is a constant value.
Second argument is `==`, `!=`, `<`, `>`, `<=`, `>=`. All of which can be implemented using `str_comp(a,b)` for strings and `b-a` for integers, and then comparing the difference to the expected difference defined by the operator.

**Comment by ChillerDragon** [comment]
@Robyt3

I really like the idea of the operator but also the ``exec`` keyword. What about ``exec_if`` ?
 
> Third argument is a constant value.

It makes sense and keeps it simple and all but would also be cool to interpret it as constant if it starts with a digit or quotes and otherwise interpret it as variable

**Comment by Robyt3** [comment]
> What about `exec_if` ?

`exec` is already the command to run a different config file. Would be weird for `exec_if` to be different and execute a single command if you ask me.

> It makes sense and keeps it simple and all but would also be cool to interpret it as constant if it starts with a digit or quotes and otherwise interpret it as variable

I don't think the console commands can detect whether the quotes are there, thou, so it would need a different meta character. Comparing with a constant seems enough and avoids any complicated parsing.

**Comment by ChillerDragon** [comment]
> `exec` is already the command to run a different config file. Would be weird for `exec_if` to be different and execute a single command if you ask me.

Ah okay fair. But when I read ``if`` I expect multi line support and a closing end or a then or similar. What about ``eval_if`` ?
