### ISSUE TITLE
Always allow clientside rendering of ready tick symbol

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2676]
not only in specific gamestates, this allows mods to use the tick as other indicators, for example for some kind of votes, ranks or accounts.

**Comment by ChillerDragon** [comment]
Yea in gamemodes that do not use pause this can be a sexy verified checkmark :)

**Comment by oy** [comment]
Hm, don't think the ready symbol should be misused for that.
But had a similar thing in mind, that could probably come in handy here as well:
- The server could provide an identifier (some letters or an image) for each player which would be rendered behind the player name

**Comment by fokkonaut** [comment]
I dont think a misuse is bad here. Lets be honest, where in Teeworlds dont we abuse the vanilla client's opportunities for our mods? e.g. freeze with ninja

**Comment by oy** [comment]
Yeah, that's pretty bad as well.

**Comment by TsFreddie** [comment]
> The server could provide an identifier (some letters or an image) for each player which would be rendered behind the player name

Maybe allow the new textrender to render text rotated as well so we may have identifiers that's a bit tilted to distinguish them from the name. Or, if we only need a single letter/icon (which is easier and stupider to rotate), we just need to expose a single quad.

Plus, if we can make a pipeline to build fonts from svg files. We can add icons for mods (i know), and for menus without changing much.
