### ISSUE TITLE
Extending CLineInput to be more flexible.

### ISSUE THREAD

**Issue by TsFreddie** [teeworlds/teeworlds#2706]
Currently `DoEditBox` pulls events from Input and calls `CLineInput::Manipulate` manually.
We should use an `CLineInput` instance alongwith `DoEditBox` and extend CLineInput to be allow it to be activated or deactivated.

Reason being:

- easier to tell when to call `SDL_StartTextInput()` and `SDL_StopTextInput()`
- manage a global caret position like most UI kit do, and signal unicode input method editor where to put the composition window.
- keep clipboard handling in one place and add ability to copy / paste to `DoEditBox`.
- possibly add support for text selection globally.

*These are the things that I've noticed when I'm trying to implement a proper IME support.*

**Comment by TsFreddie** [comment]
Did some experiments. For text selection and caret position, the text rendering needs to be handled by CLineInput as well.

Since moving text rendering to `CLineInput` can free some clutters in `chat.cpp` and `console.cpp`, so it should be worth doing.

**Comment by Learath2** [comment]
I worked around moving the rendering in #2521. But moving it would indeed make this easier
