### ISSUE TITLE
Server browser scrollbar too sensitive

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#2707]
When you use the mousewheel to scroll in the server browser it scrolls much more than a third, like in other scroll bar areas.

**Comment by Dune-jr** [comment]
@Robyt3 @oy I believe https://github.com/teeworlds/teeworlds/pull/2708 does not fix the underlying issue (if it is a fix at all). When the server list has only a few servers, the scroll speed is reasonable. When it is so full with servers that the scrollbar becomes a circle, it acts like a pagedown

**Comment by Robyt3** [comment]
I see what you mean. The `m_ScrollSpeed` value is mostly arbitrary and dependent on the size of the scrollregion. I'll open a new issue.
