### ISSUE TITLE
Various Out of Bounds GUI issues

### ISSUE THREAD

**Issue by Stiopa866** [teeworlds/teeworlds#2716]
In the Server Browser menu, one may click outside the server list and still hit the "remove filter" button outside the range.

The filter that is off bounds:
![20200906122335_1](https://user-images.githubusercontent.com/39134953/92323938-fbb70100-f03c-11ea-8136-4f0f5d1607b7.jpg)
Before Click:
![20200906122353_1](https://user-images.githubusercontent.com/39134953/92323940-01144b80-f03d-11ea-833d-9a5c0274ab4d.jpg)
After Click:
![20200906122355_1](https://user-images.githubusercontent.com/39134953/92323943-06719600-f03d-11ea-8ecb-6e257b1eda35.jpg)

In the Server Browser menu, one may click outside the friend list and still hit the remove friend button.

Before Click:
![20200906130151_1](https://user-images.githubusercontent.com/39134953/92324559-2f952500-f043-11ea-9295-6d6ab0075323.jpg)
After Click:
![20200906130153_1](https://user-images.githubusercontent.com/39134953/92324562-32901580-f043-11ea-99a2-c8f381933e3e.jpg)

In the Server Browser menu, one may click outside the gametype filter list and still remove the gametype:

Before clicking out of bounds:
![20200906131116_1](https://user-images.githubusercontent.com/39134953/92324612-a7fbe600-f043-11ea-8c80-7a9a2788b3b5.jpg)
After clicking:
![20200906131128_1](https://user-images.githubusercontent.com/39134953/92324613-a92d1300-f043-11ea-9dcf-e2389c0f2847.jpg)

Furthermore, some GUI elements are highlighted even when hovered over out of bounds, while others do not:

Example of an element that does not highlight:
![20200906131213_1](https://user-images.githubusercontent.com/39134953/92324640-f4dfbc80-f043-11ea-94c4-d2fc729ea7ad.jpg)
Elements that do highlight (controls tabs, friend tabs, server filter tabs respectively):
![20200906124800_1](https://user-images.githubusercontent.com/39134953/92324681-5f90f800-f044-11ea-9308-1dfe5c43c6b8.jpg)
![20200906130320_1](https://user-images.githubusercontent.com/39134953/92324684-63247f00-f044-11ea-8db2-284fddf582d7.jpg)
![20200906130802_1](https://user-images.githubusercontent.com/39134953/92324685-6455ac00-f044-11ea-898c-09e6c8e40cf8.jpg)

Version: Steam Teeworlds 0.7.5

**Comment by Stiopa866** [comment]
I've found another issue, I might rename the issue and add them onto here when I am done documenting it (or them, if I find more)

**Comment by Robyt3** [comment]
I'm working on this and other button related issues and cleanup.

**Comment by Stiopa866** [comment]
Brilliant. I'll update this issue nonetheless (want to make sure nothing is missed)
