### ISSUE TITLE
Econ `shutdown` keeps port in use (?)

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2722]
Using `shutdown` in econ blocks the port, after server restart you can't connect to econ anymore

**Comment by ChillerDragon** [comment]
```
$ netstat -tupna | grep 1303
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:1303          127.0.0.1:38348         TIME_WAIT   - 
```

**Comment by heinrich5991** [comment]
[Transmission Control Protocol#Protocol Operation](https://en.wikipedia.org/w/index.php?title=Transmission_Control_Protocol&oldid=977068225#Protocol_operation), see TIME-WAIT state.

I think it can be disabled on the OS level, but also on the socket level: [How do SO_REUSEADDR and SO_REUSEPORT differ?](https://stackoverflow.com/a/14388707).

**Comment by ChillerDragon** [comment]
@heinrich5991 I hoped for a fix that does not require tinkering with the OS and just close it properly like when using ``shutdown`` from the ingame console

**Comment by heinrich5991** [comment]
@ChillerDragon Are you sure there's a difference between using `shutdown` from the ingame console and `shutdown` via econ (both when econ is enabled)?

**Comment by heinrich5991** [comment]
See the second link on how to change the behavior via the source.

**Comment by ChillerDragon** [comment]
https://github.com/teeworlds/teeworlds/pull/2034

**Comment by ChillerDragon** [comment]
> @ChillerDragon Are you sure there's a difference between using `shutdown` from the ingame console and `shutdown` via econ (both when econ is enabled)?

Yes via ingame console it works without issue and via econ it blocks the econ port for some time at least on debian and arch

**Comment by heinrich5991** [comment]
Some testing shows that it's not relevant whether the server was shut down by econ or rcon, but rather whether someone ever connected to econ. Shutting down via rcon while someone is connected to econ also triggers the TIME-WAIT state.

**Comment by ChillerDragon** [comment]
> Some testing shows that it's not relevant whether the server was shut down by econ or rcon, but rather whether someone ever connected to econ. Shutting down via rcon while someone is connected to econ also triggers the TIME-WAIT state.

good finding so maybe on shutdown we have to close all econ connections and not only kick all tees

**Comment by heinrich5991** [comment]
Interesting, seems like I had the wrong idea about what causes this. If I connect to econ and disconnect again before the server shutdown, the socket isn't in the TIME-WAIT state.

**Comment by pure-luck-999** [comment]
Thanks for opening an issue. I have tried to mitigate it with adding a `ExecStartPre=/bin/sleep 5` to a `[Service]` section of a systemd unit file, but still it fails to close it in time on crashes. If you someone is going to fix it, please check that it will close econ on a crash too. This issue impacts econ-consuming services like stats bots and discord bridges.

**Comment by fokkonaut** [comment]
@oy how is that a feature, clearly a bug

**Comment by oy** [comment]
It's correct behaviour, that it changes to time-wait state and that the port cannot be reused again.
We could bypass it by waiting till the port is available again and then reuse it again.

**Comment by fokkonaut** [comment]
It doesnt sound like its wanted. Let me describe the problem again.
When you use shutdown via ingame console (F2) and simply restart the server after that, everything will be okay and econ will be available just after the server has started.
But if anyone (from econ or ingame) uses the shutdown command while at least one person is logged in via econ, then econ is not available after restart until the server gets restarted again. That means I cant restart my server from my mobile via shutdown, because even tho the automatic-restart after shutdown script restarts the server, the econ doesnt work afterwards.

**Comment by oy** [comment]
Yeah, that's how tcp works. The end that closes the connection ends up in TIME-WAIT state (`a connection can stay in TIME-WAIT for a maximum of four minutes known as two maximum segment lifetime`) which is the server in this case.
There're ways to work around that which are not perfect but worth a try though.

**Comment by Learath2** [comment]
(The key takeaway here is that econ is over TCP, which has a lengthy wait when closing the socket to gracefully close the connection and handle any delayed packets)

If you want to be very safe the correct thing to do would be to wait until the econ socket is gone before restarting. An acceptable workaround is `SO_REUSEADDR` which is surprisingly relatively portable.
