### ISSUE TITLE
Demo browser layout

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#2738]
@Dune-jr wrote:
> This could be a separate issue, but it feels to me like the columns Name, Length, Date should be below the `Recorded` title of the window and using `CORNER_T`. What do you think?

**Comment by Sonix-** [comment]
Agree

**Comment by Robyt3** [comment]
The Length column should be right align IMO.

Also the Length should be hidden for demos with invalid info. Right now it just shows a random, potentially negative length.
