### ISSUE TITLE
Limit name / clan length by glyphs / width instead of chars.

### ISSUE THREAD

**Issue by TsFreddie** [teeworlds/teeworlds#2741]
CJK glyphs usually takes up 3-4 chars of space. This limits the name to 4 to 5 glyphs which are way too less to express enough personality info.

Meanwhile you can have Latin names that are obnoxiously long like 16 `W`s.

Relax and limit each case would be nice.

**Comment by Dune-jr** [comment]
Isn't this a protocol limitation? If so, this would show broken names to older clients

**Comment by TsFreddie** [comment]
> Isn't this a protocol limitation? If so, this would show broken names to older clients

We can do it in 0.8.

**Comment by oy** [comment]
0.7 protocol doesn't have limitations for the name/clan length, as there not part of the snapshot anymore. We just have to increase the arrays that store the info in the server and client.
