### ISSUE TITLE
Animation Smoothness Issues on ctf2

### ISSUE THREAD

**Issue by Stiopa866** [teeworlds/teeworlds#2743]
While scouring through the teeworlds issues I stumbled upon #2170 and decided to test it ingame, on ctf2 instead. The results were interesting, to say the least.

(demos attached in a zip at the end)
Server 1 Info:
![screenshot1](https://user-images.githubusercontent.com/39134953/93633782-cc66a380-f9ef-11ea-83ca-524065c1b567.png)
Snow animation seems pretty smooth ingame.
The animation in the demo however, is very laggy.

Server 2 Info:
![screenshot2](https://user-images.githubusercontent.com/39134953/93634045-35e6b200-f9f0-11ea-99d2-124b05673b77.png)
Animation in the game seems smooth too.
The animation in the demo is better than the one on server 1, however the lags are still explicit and visible within it.

Server 3 Info:
![screenshot3](https://user-images.githubusercontent.com/39134953/93634128-5f074280-f9f0-11ea-8d91-9ae1ef0d2133.png)
The animation in the demo is pretty smooth compared to the other two, despite the round being at 4414:30 instead of 926:00 in demo 2.
The animation ingame is worse than in server 1 and two, but still not as strikingly laggy as in the demos of 1 and 2.

Ping, Versions for the servers are respectively:
38, 0.7.4
125, 0.7.5
43, 0.7.5
Running Teeworlds on Windows 10, Teeworlds from Steam.

Demos:
[demos.zip](https://github.com/teeworlds/teeworlds/files/5247647/demos.zip)

**Comment by Robyt3** [comment]
The file appears to be a renamed rar file. Can you update the link to an actual zip file?

**Comment by TsFreddie** [comment]
Re-archived zip file
[demos.zip](https://github.com/teeworlds/teeworlds/files/5251882/demos.zip)
