### ISSUE TITLE
Improve Visibility of Server Broadcast

### ISSUE THREAD

**Issue by TsFreddie** [teeworlds/teeworlds#2753]
![image](https://user-images.githubusercontent.com/3797859/93720750-f13f5000-fb82-11ea-849d-fe9d7424685d.png)

There is a backdrop for the broadcast but is it too light and usually can't cover all the text. This makes the text hard to read on some brighter maps.

We should increase the intensity and the size of the backdrop or replace it with standard CORNER_T rect.

**Comment by Dune-jr** [comment]
The text size gets smaller with larger broadcasts.
We should probably set colored broadcasts on by default, by the way. Lots of players don't know about this.
