### ISSUE TITLE
grass_main: texture bug (cutted shadow)

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2770]
![image](https://user-images.githubusercontent.com/20344300/95469615-223fc300-0980-11eb-8cb3-1ae9621bfdd0.png)

The grass tile has a slight cut in the shadow and the rotated version is even worse.

**Comment by Sonix-** [comment]
duplicate #1911

**Comment by ChillerDragon** [comment]
oopsie. Thanks @Sonix-
