### ISSUE TITLE
RFC: New tileset (egyptian?)

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#2778]
I just played a round of DDNet and found a real nice tileset that would also fit very well for Vanilla:

![screenshot_2020-10-13_21-44-09](https://user-images.githubusercontent.com/366230/95908836-e0f34d00-0d9d-11eb-9d1a-8259c187f585.png)
![screenshot_2020-10-13_21-48-06](https://user-images.githubusercontent.com/366230/95908837-e2247a00-0d9d-11eb-8c21-c56a1df60a22.png)

What do you think about this tileset? The author Pipou seemed willing to release it under a free license and work with us to polish it for release.

**Comment by heinrich5991** [comment]
The torch is animated btw. :)

**Comment by Zatline** [comment]
We already have an Egypt theme in work for 0.8, Ravie and I are taking care of that.  :)

**Comment by heinrich5991** [comment]
Anything else you have in the queue?

**Comment by heinrich5991** [comment]
Nice. :)

Sounds like I don't need to report good tilesets though, if you have so much coming up.
