### ISSUE TITLE
Pipeline for MacOS is broken

### ISSUE THREAD

**Issue by AssassinTee** [teeworlds/teeworlds#2786]
See #2784

**Comment by Learath2** [comment]
I see why it's broken. I don't get the obsolete

**Comment by ChillerDragon** [comment]
It is ``brew update`` failing there probably is no need to change and only a temporary issue but yes its not too nice. Maybe we should hack something like ``brew update || true``. I wonder how other projects handle this,

**Comment by AssassinTee** [comment]
closes by #2796
