### ISSUE TITLE
damage indicator angle value not used

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2787]
would be cool to allow server to send an angle again without the client just ignoring it

**Comment by Dune-jr** [comment]
Duplicate of https://github.com/teeworlds/teeworlds/issues/2141?

**Comment by fokkonaut** [comment]
yea true, but something has to happen I think. its so bad right now :D

**Comment by Learath2** [comment]
Well they work perfectly as damage indicators. We were kinda abusing them and they don't support that anymore. It's not really "bad". It's just disappointing :P

**Comment by oy** [comment]
Duplicate #2141
