### ISSUE TITLE
New tile system

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2788]
The current tile system and collision.cpp code is not easy to expand without re-writing the whole collision code. Can we maybe have an easy to extend tile system like DDNet has for example? Would also be nice before the water update, because that would bring alot of new functions to collision.cpp that could be avoided with a good and extensible system.

(See colflags, we really should avoid them!)

**Comment by Sonix-** [comment]
> Would also be nice before the water update
> 

What water update? 🤔

**Comment by Learath2** [comment]
The hack we have in other mods is hardly better btw. It's heavily bolted on. You'd want to use something similar to it but integrated into the collision code
