### ISSUE TITLE
RFC: Remove embedded RGB image format from maps

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#2812]
Around 15 maps from the map archive use the embedded RGB images. Basically no tileset included in Teeworlds maps will ever have no transparent pixels (top left tile is empty).

I don't think this feature is pulling its weight (the extra complexity when parsing maps) and should be removed.

It's currently not really a useful feature either because it depends on the source PNG format. If we were to embed grayscale images, we shouldn't extend the map format either, but rather convert these grayscale images to RGBA. This comes from the commit https://github.com/teeworlds/teeworlds/commit/f8e114ff5af2001e05bd17bbaa3f07eaf8497cae, used instead of the (IMO less complex) code from https://github.com/teeworlds/teeworlds/pull/973.

I'm willing to implement this if desired.

**Comment by Dune-jr** [comment]
This sounds good to me!

**Comment by oy** [comment]
> 
> 
> Basically no tileset included in Teeworlds maps will ever have no transparent pixels (top left tile is empty).
> 
Of course you can use RGB images as tilesets. The top left tile is empty by design, no matter the pixels within the tileset.

>
>
>It's currently not really a useful feature either because it depends on the source PNG format.
>
There should probably be a step within the save process that checks if the alpha channel can be removed and then do so.

Already thought about expanding that feature and add palettes and real greyscale image support to make it possible to provide smaller maps. And supporting smaller than 16x16 tile based tilesets would be useful too.

**Comment by heinrich5991** [comment]
> Of course you can use RGB images as tilesets. The top left tile is empty by design, no matter the pixels within the tileset.

I didn't say that you can't. I said that in practice you likely won't, giving a plausible explanation and statistics from the corpus of all archive Teeworlds maps.



> There should probably be a step within the save process that checks if the alpha channel can be removed and then do so.
> 
> Already thought about expanding that feature and add palettes and real greyscale image support to make it possible to provide smaller maps. And supporting smaller than 16x16 tile based tilesets would be useful too.

I think this is adding complexity at the wrong place. Supporting grayscale images too wouldn't really give benefits. More useful would be stuff like integrating the PNG directly (that has image-specific compression and supports all RGB/RGBA/grayscale), or adding a resource loader that keeps images separate from the map files. I think it is harmful for Teeworlds to re-invent image encoding, and that the RGB feature (which is barely used) should be removed.
