### ISSUE TITLE
Mangohud doesn't work

### ISSUE THREAD

**Issue by Toadfield** [teeworlds/teeworlds#2817]
I tried to use Mangohud with `MANGOHUD=1 MANGOHUD_DLSYM=1 mangophud %command%` in the launch options and it doesn't work.
I use the steam version of Teeworlds with Manjaro Kde.

**Comment by jxsl13** [comment]
the heck is mango hud

**Comment by Toadfield** [comment]
It shows cpu,gpu,ram stats and fps.
[here the github page](https://github.com/flightlessmango/MangoHud).

**Comment by Toadfield** [comment]
I forgot to mention that I already asked the mangohud creator and he said that it works for him.

**Comment by ChillerDragon** [comment]
I just tested and mangohud runs fine everywhere out of the repos from source and in steam.
I assume you have a typo because the command you provided fails:

```
MANGOHUD=1 MANGOHUD_DLSYM=1 mangophud %command%
bash: mangophud: command not found
```

Make sure it is mangohud not mango**p**hud

**Comment by Toadfield** [comment]
It still doesn't work.
Know I spelled it correct:`MANGOHUD=1 MANGOHUD_DLSYM=1 mangohud %command%`

> BTW if you are a stats guy you might be interested in ctrl+shift+d and ctrl+shift+g teeworlds debug shortcuts.

The problem with that is that it doesn't show my gpu,cpu and ram consumption of the game (or my eyes are to bad to see it in that tiny text).

**Comment by ChillerDragon** [comment]
I do not know if steam provides logs but can you try to get some logs or error messages. Maybe try running the steam version from a shell directly and check the output. Or try community/teeworlds from the repos and see if that works. It works so well on arch + gnome so I assume it should run fine on Manjaro + KDE.

**Comment by AssassinTee** [comment]
I am not sure this is a Teeworlds issue, since a third party project doesn't run on the game in this case. It's not the game that should need "a fix" for your tool to run, it's the other way round.

**Comment by oy** [comment]
This isn't a teeworlds issue you should take it up with the third party tool.

**Comment by Toadfield** [comment]
Sorry for answering late,but I tried it in the normal version that I can install from a package manager,there it works,it only doesn't work on the steam version.
