### ISSUE TITLE
Port to libretro? :D

### ISSUE THREAD

**Issue by DartPower** [teeworlds/teeworlds#2819]
Hi there, i have a idea, you want to port to libretro?
This is will be cool, really :)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by heinrich5991** [comment]
What is the motivation to port this to libretro? :)

**Comment by oy** [comment]
Would be lots of work, don't think it would be worth it nor is there the manpower.
