### ISSUE TITLE
Where can I report in-game problems?

### ISSUE THREAD

**Issue by xBeefyOreo** [teeworlds/teeworlds#2830]
![Screenshot from multeasymap](https://user-images.githubusercontent.com/64839797/102485762-56aeba00-4068-11eb-9a05-4e4f96ad2cab.png)

**Comment by TsFreddie** [comment]
http://ddnet.tw/discord

**Comment by heinrich5991** [comment]
The bugtracker is not the right place to report ingame problems. Check https://discord.gg/teeworlds for the Teeworlds Discord.
