### ISSUE TITLE
Improve descriptions in the Configure statboard

### ISSUE THREAD

**Issue by scootergrisen** [teeworlds/teeworlds#2850]
I think all the strings below Configure statboard in settings bindings should be descriptions explaning the different things.

Like instead of just "Ratio" it could be "Ratio between ... and ...".
And instead of "Net score" ir could be "Difference between frags and deaths".

"Flag grabs" and "Flag captures" kind of sound like the same thing but one is a number and the other is an icon.
So maybe "Number of times a flag was grabbed" and "Flag is captured".

"Flag captures" is wrong anyway is it not? "captures" sounds like it would be a number.

Also both the short string and the long string could appear in the configuration so you can both see what it looks like while playing the game and the description to explain what it means.

Short strings used during game:

    K
    D
    Suicides
    Ratio
    Net
    FPM
    Spree
    Grabs
    Flag grabs

https://github.com/teeworlds/teeworlds/blob/dc1802c20270679f112fef86e37e0831c8fe2104/src/game/client/components/stats.cpp#L228

Long strings that i would like to be descriptions/explanations:

    Frags
    Deaths
    Suicides
    Ratio
    Net score
    Frags per minute
    Current spree
    Best spree
    Weapons stats
    Flag grabs
    Flag captures

https://github.com/teeworlds/teeworlds/blob/42b2bbde63f1aab9235d473d894f656c4eb8027d/src/game/client/components/menus_settings.cpp#L1579-L1621

**Comment by Dune-jr** [comment]
> "Flag grabs" and "Flag captures" kind of sound like the same thing but one is a number and the other is an icon.
> "Flag captures" is wrong anyway is it not? "captures" sounds like it would be a number.

Flag grabs describe flag touches (1pt), flag captures describe a full CTF capture (100pts).
Both are numbers, the latter is visualized with a number of icons so it stands out better in the statboard.

What you have requested would fit best a tooltip system that is not (yet) implemented.

**Comment by Robyt3** [comment]
We can do this with tooltips based on #2825 but I don't want to add more things to that pull request.

**Comment by Dune-jr** [comment]
Yeah I think it's best to keep independent patches in distinct PRs, it helps get them reviewed and merged faster

**Comment by Robyt3** [comment]
The name of the Kills/Frags column in the statboard is not consistent with the settings. In the statboard it's _K_, whereas in the settings it's called _Frags_. Should the K be changed to F or should Frags be changed to Kills (and likewise FPM to KPM or K/min). I think K:D is well known as an abbreviation whereas F:D wouldn't be. Using the term Kills instead of Frags everywhere would probably be easier to understand for more players.
