### ISSUE TITLE
Use blank image instead of default flag

### ISSUE THREAD

**Issue by scootergrisen** [teeworlds/teeworlds#2851]
Instead of the default icon when no flag is selected would it perhaps be bettet with a blank image so there is not just a lot of the same default images in when viewing the stats for tee thats have not selected a flag.

Just show nothing and call it blank in the tee settings.

**Comment by Dune-jr** [comment]
Sorry, I'm not sure what you mean. How do you select a flag?

**Comment by scootergrisen** [comment]
If you press Tab during a game you might see several default flags.
They might as well not be there.

I can select flag in settings player

**Comment by TsFreddie** [comment]
Probably a personal preference thing. I like how it is consistent for each line so everyone gets a rectangle besides them in scoreboard.

You can always replace the default flag PNG with a empty transparent one.

**Comment by SoulyVEVO** [comment]
I really like the default flag and i dont think it should be replaced

**Comment by oy** [comment]
Agree, the default flag was added on purpose to keep it consitent.  You could follow @TsFreddie suggestion if you don't want them to be shown.
