### ISSUE TITLE
Let the server catch SIGINT and close gracefully

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2856]
When running the client in a terminal emulator and pressing CTRL+C it does a clean disconnect and is shutting down all components. The server on the other hand just straight up dies. Would be nice to call this code here:

https://github.com/teeworlds/teeworlds/blob/740555190a7f98ba94862e8cd01bde1a19ee6d31/src/engine/server/server.cpp#L1478

to close econ connections and all the other things. Maybe even add some hook where custom mods can add their cleanup code.

**Comment by AssassinTee** [comment]
`Maybe even add some hook where custom mods can add their cleanup code.`

I call that a "Destructor", since most mods are just programmed into the teeworlds sourcecode itself
