### ISSUE TITLE
Linux - Asian fonts aren't displaying

### ISSUE THREAD

**Issue by dginovker** [teeworlds/teeworlds#2857]
I actually posted this to the [Gaming stackexchange](https://gaming.stackexchange.com/questions/384554/teeworlds-asian-fonts-arent-displaying), but it might be a bug or have better luck here 

*****

In Teeworlds on Linux, Korean/Chinese/Japanese fonts just display as a bunch of []s. This is true both in-game and in the settings:

![](https://i.stack.imgur.com/NEN3J.png)

This is true whether I install from my package repository, the Teeworlds [Downloads](https://teeworlds.com/?page=downloads) page, or from [Flathub](https://flathub.org/apps/details/com.teeworlds.Teeworlds).

Note: It was NOT the case when I downloaded the modded DDNET client. Korean worked fine there.

This happened both on Arch Linux KDE, as well as KUbuntu 20.04

Anyone have suggestions?

**Comment by Dune-jr** [comment]
Hey @dginovker 

This is definitely the right place for this. I can reproduce this, and I believe it is expected, as the font we use - DejaVuSans - does not support CJK afaik.
You can replace that font with a font of your choice by moving the `.ttf` at the root of the Teeworlds folder, then adding it either to the `settings.cfg` (in your systems config folders) or ingame by entering the console (f1) and entering `cl_font <name of the font>`

It seems DDNet has good defaults that support CJK, unlike us

**Comment by TsFreddie** [comment]
master branch should be able to display CJK characters after https://github.com/teeworlds/teeworlds/pull/2704

If you don't want to use in-develop/unstable version of the game. Download a source han sans font and replace the `DejaVuSans.ttf` in `data/fonts`. Although without that PR, it would lag every time a new character is shown.

**Comment by dginovker** [comment]
Can confirm it works with master branch

**Comment by Freed-Wu** [comment]
Can we release a new version to fix it?

**Comment by Bamcane** [comment]
> Can we release a new version to fix it?

It has been fixed, but not released. Teeworlds won't release a new version currently. You can use DDNet client or the fork TeeworldsArchive instead. Both of them are released on the Steam
