### ISSUE TITLE
Send chat commands via client console, thereby enabling binds

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2858]
Right now it is not possible to send chat commands via `f1` console, so you cannot write binds. I ran into someone who complained about that.

@Learath2 suggested it should be doable to handle this with something like `chat_command s[command] ?r[parameters] `

**Comment by heinrich5991** [comment]
The idea sounds good, chat commands should be bindable.

The proposed solution seems like it will run into quoting issues:
To bind `/rank "Hello World"`, what would I have to enter? `chat_command rank "\"Hello World\""`?

**Comment by Learath2** [comment]
I think the `r` takes care of it, no? If it doesn't IMO that's a bug in `CConsole`
