### ISSUE TITLE
General structure of the code?

### ISSUE THREAD

**Issue by unexploredtest** [teeworlds/teeworlds#2872]
Hi, sorry if it's not the appropriate place, but when I tried asking my question in forums, I keep getting errors, and IRC chatroom is empty.
The game got my interest and I decided to study its code. Now, I get what individual line is doing but I can't put the whole thing together. Could anyone provide me a general explanation on how the code works, or something like a diagram of the code structure?

**Comment by Dune-jr** [comment]
The IRC channel is far from empty, and it is linked to bigger Discord channels as well. Access IRC with https://webchat.quakenet.org/?channels=teeworlds
The codebase is large and such a general "explain me how it works" question can't be answered, though we would be happy to help you with specific questions on IRC etc.

**Comment by unexploredtest** [comment]
> The IRC channel is far from empty, and it is linked to bigger Discord channels as well. Access IRC with 

Aha, I think I was in the wrong one. There is a Discord server for Teeworld as well?

> The codebase is large and such a general "explain me how it works" question can't be answered, though we would be happy to help you with specific questions on IRC etc.

Oh I see, thanks.

**Comment by Dune-jr** [comment]
https://discord.gg/teeworlds
IRC Channels #teeworlds on both Quakenet and FreeNode are bridged

**Comment by unexploredtest** [comment]
Many thanks
