### ISSUE TITLE
Add back mem_alloc assertions or update documentation

### ISSUE THREAD

**Issue by Robyt3** [teeworlds/teeworlds#2894]
https://github.com/teeworlds/teeworlds/commit/a5a5fe1cc886718775c863979ed873e608fae2bd removed the assertions which cover the case when `malloc` returns 0, but the documentation says otherwise.

Was this necessary for thread safety @heinrich5991 ? So should we add back the assertion, or update the documentation and remove the unnecessary macro that inserts the filename and line number?

**Comment by heinrich5991** [comment]
You can re-add the `dbg_assert` if you want, it didn't have any relation to thread safety.

I don't see that the `dbg_assert` is implied by the documentation:
>Returns: Returns a pointer to the newly allocated block. Returns a null pointer if the memory couldn't be allocated.

This means that it will return a null pointer if malloc returns one – which is exactly what it does right now. What am I missing?

**Comment by Robyt3** [comment]
True, what I read was documentation for the `mem_free` method:

>In the debug version of the library the function will assert if a non-valid block is passed, like a null pointer or a block that isn't allocated.
