### ISSUE TITLE
The "Add" button disappears from the Map Editor if you load a map with too many images

### ISSUE THREAD

**Issue by karl-police** [teeworlds/teeworlds#2895]
In the map editor if you click on "Layers" which switches you to the "Images" tab, you will notice a button called "Add". This is used to add images to the map.

Now, if you load a map that causes the list to be full with entries of images. If you scroll down the "Add" button is gone.

Now, if you remain scrolled down at the bottom and then create a new blank map. The "Add" button is still gone and will not appear back.

However, if you load a map with just a few things in the list of the "Images" tab, and then create a new map. The "Add" button will be there again.

Same if you scroll up of a map with a lot of stuff in the list and then create a new map.

&nbsp;
**Versions:** 0.6.5 and 0.7.5

**Comment by karl-police** [comment]
Alright, I was suggested a fix for this, lemme add a pull request.

**Comment by karl-police** [comment]
This is a very small change that is made.

**Comment by karl-police** [comment]
I need to make a small adjustment from the fix suggestion that was told to me.

Because when you move the scroll thing, slightly up, the button disappears which is really weird for it to do.

**Comment by Robyt3** [comment]
> Because when you move the scroll thing, slightly up, the button disappears which is really weird for it to do.

Yeah, that's what I meant with

> The scrolling should eventually be done more cleanly with a CListBox anyway.

Scrolling in some editor menus is weird. The editor can't be refactored until the client UI is refactored. And there is little incentive to invest too much in the current editor, because of the editor2 project.

**Comment by karl-police** [comment]
Does editor2 allow entities positioning of non-grid fixed values as well? I saw a gamemode using the quads to position entities, which was very smart. They even positioned spawn points with it.

**Comment by Robyt3** [comment]
The editor2 project (see #2486) is an overhaul of the editor itself and does not introduce any new map features itself.

**Comment by karl-police** [comment]
But did you not copy things from DDNet?

**Comment by Robyt3** [comment]
Some things might get ported from DDNet, but most things don't because the vanilla gameplay is basically complete as it is.

**Comment by karl-police** [comment]
> I need to make a small adjustment from the fix suggestion that was told to me.
> 
> Because when you move the scroll thing, slightly up, the button disappears which is really weird for it to do.

Alright, I updated that now.

**Comment by karl-police** [comment]
Updated https://github.com/teeworlds/teeworlds/pull/2900 of the suggested fix

now it's even better, regarding the scrolling
