### ISSUE TITLE
Package for chocolatey

### ISSUE THREAD

**Issue by xeruf** [teeworlds/teeworlds#2983]
https://community.chocolatey.org makes installing software on Windows a lot less painful :)

**Comment by jxsl13** [comment]
anyone who knows what Chocolatey is, is most likely capable of downloading a zip archive, unpack it and start the executable.

**Comment by ChillerDragon** [comment]
> anyone who knows what Chocolatey is, is most likely capable of downloading a zip archive, unpack it and start the executable.

But thats annoying.

**Comment by xeruf** [comment]
> anyone who knows what Chocolatey is, is most likely capable of downloading a zip archive, unpack it and start the executable.

The nice thing about chocolatey is that you can batch install packages from the commandline, highly time-saving when setting up a new machine

**Comment by jxsl13** [comment]
anyone knowing the command line should be capable of using curl/wget to fetch the archive and unpack it :D

I literally do not care, it'd be a quality of life improvement that has got a rather low priority and will most likely not be implemented.

Nonetheless, here is a reference for anyone willing to start this: https://docs.chocolatey.org/en-us/create/create-packages

**Comment by Robyt3** [comment]
There already exists a teeworlds package for chocolatey ;)

https://community.chocolatey.org/packages/teeworlds

**Comment by oy** [comment]
Seems fixed then ;)
