### ISSUE TITLE
Race Time Scoreboard stopped showing

### ISSUE THREAD

**Issue by Stiopa866** [teeworlds/teeworlds#3169]
At some point in 0.7.6's development it would seem that the scoreboard for the Race gamemodes has been broken.

0.7.5:
![screenshot_2022-07-24_00-16-45](https://user-images.githubusercontent.com/39134953/180625428-0803d787-7c91-4ac6-b646-5bd9fdb47542.png)

Current development version:
![screenshot_2022-07-24_00-16-33](https://user-images.githubusercontent.com/39134953/180625431-6bd54fe0-4e49-47bd-855e-d83617a23bf7.png)

**Comment by fokkonaut** [comment]
Can you try if it works in general? My server offers a way to enable it, using `/score time`.
