### ISSUE TITLE
Add levels

### ISSUE THREAD

**Issue by ixPost** [teeworlds/teeworlds#3183]
So a tutorial i think should be basic and in each few levels you learn something as well as improving your skills we could also add a story(Not just why you are fighting but also what happens to the player, also to make a change with him or the landscape) to make the game more interesting.

**Comment by visitOP** [comment]
well there is an actual tutorial map ingame, wich is fine but it teaches only the basics of novice, but I think it is enough, people are learning by themselves, that is why we have a such amount of choices of maps from novice to brutal.

**Comment by ixPost** [comment]
You know what, I realize that the Teeworlds "theme" doesn't allow levels.
