### ISSUE TITLE
Add race game mode.

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#33]
YES! We will have it.
- No player collision or weapons.
- Must be time limited. ~10 minutes should be good.
- During the time, players race to get the fastest time.
- Players can reset at anytime using a button, taking them back to the start with a count down to start race.
- The player with the fastest lap wins.

**Comment by Dune-jr** [comment]
@themisak It's not so easy. It has to be properly included client-side, too. I doubt some features like SQL integration would make it also, it doesn't fit Teeworlds.

**Comment by Fudgyking** [comment]
A simple race mod that saves records locally would not be enough?

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
