### ISSUE TITLE
Medals/awards

### ISSUE THREAD

**Issue by Ubu-** [teeworlds/teeworlds#357]
Some actions could be rewarded, like in Quake. Possible situations:
- defense: when you kill the opponent flag carrier or an enemy near you flag
- assist: you kill an enemy near your flag carrier, you return the flag when your team has the enemy flag

etc.

These rewards would fit into the statistics.

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
