### ISSUE TITLE
invisible hook

### ISSUE THREAD

**Issue by JulianAssange** [teeworlds/teeworlds#499]
if hook duration is bigger than normal, if ur the one hooking, u dont see the hook after the normal ammount of seconds, the person who isnt hooking can see it forever, but not the person who is hooking.

Hook duration isn't a tuning variable but this bug happens easily on vanilla teeworlds. Just drag another hooked tee far away and his hook gets invisible.

But I think this is wanted because of security reasons. If the hook position is at any range known it's easy to make a modified client that shows a minimap with all tee positions. But theoretically there is a solution for that. We must only show the position of every chain part to nearby players. This will give them a hint there the tee is but this makes it impossible to sense him closer as every chain part as the tee (~ tee_radius + current_hook_length). You should reopen this issue.

**Comment by ixPost** [comment]
Yeah, I got the same issue of the long invisible chain.
