### ISSUE TITLE
Text corruption in the internet/server-list on amigaos (ppc, big endian)

### ISSUE THREAD

**Issue by kas1e** [teeworlds/teeworlds#515]
Tryed to build latest source (downloaded 11 mart 2011), and have some bug, which i not have with previous port (0.5.2 version). Looks like it introduces lately, and very possible that endianes related (but i can't be sure). My os are AmigaOS4 and cpu are PPC (big endian). There is 0.5.2 port:  http://os4depot.net/index.php?function=showfile&file=game/action/teeworlds.lha.

Corruption looks like this: http://kas1e.narod.ru/tee_cor.jpg

Visually it looks like this: you run a game, all is fine, but when you press Internet, and server list start to be shown, at some point some text are corrupted (some phrases in options, server-list  and so on). 

I do some testings, and found, that when you run game and press on any otpions (but not in Internet for server-list) all works fine. Then, when you press on Internet, its start to render list , and after it  render about 20 items, then i have in the console new "pFont address", and after that , corruptions is starts.

For me it looks like something wrong with memory/array/align/allocation in terms of big-endianes (that can explain imho such corruption).

To make everything clear, i also made a little youtube video: http://www.youtube.com/watch?v=1a7PkqxV2Zo

If any more info is need i will provide it.

Thanks for help.

**Comment by oy** [comment]
Seems outdated and nobody there to test it.
