### ISSUE TITLE
New HUD elements

### ISSUE THREAD

**Issue by Ubu-** [teeworlds/teeworlds#520]
We can already display the fps, why not also displaying:
- speed
- latency/ping

**Comment by Dune-jr** [comment]
Should that be displayed? Not sure about speed, but ping is relevant.

**Comment by oy** [comment]
Yeah, ping you see in the scoreboard. Speed could be done (debug hud should already have it).

**Comment by Dune-jr** [comment]
I meant, should there be a way to permanently display ping or speed, like what there is already for FPS, on the top right corner?

Something like:
![image](https://user-images.githubusercontent.com/355114/53031642-880ace80-346d-11e9-9a68-b5ab3b3c003f.png)

**Comment by oy** [comment]
The server sends ping updates to the client only when the scoreboard is shown to save some bandwidth.
Dunno if there's a need for these values.

**Comment by Dune-jr** [comment]
Sounds like permanently displaying ping would be a bad idea, then.

Speed doesn't sound useful to me. Is there anything that should be done in this issue?

**Comment by Robyt3** [comment]
Bump. I think we can close? Ping is included in the scoreboard. Speed is more easily perceived by looking at the game, I don't think a "speed" number in some unit like pixel/tile/tee per second would help me play this game. I don't really see the use case for that.

**Comment by Dune-jr** [comment]
- Speed: I tried to implement speed/accel meters in the game. Even when it worked, it didn't feel useful at all, as you say

- Ping/latency: there are several values for ping/latency. If you type `ping` in the console you get a different result from the scoreboard value. Then there are prediction delays from ctrl+shift+d+g which are kinda useful. In a client modification, I put that prediction graph next to the ping, it's quite useful to spot lag/freezes:

![screenshot_2020-01-16_18-05-42](https://user-images.githubusercontent.com/355114/72550553-e2cdc580-388a-11ea-9086-fac5d96fd970.png)

A small freeze:
![image](https://user-images.githubusercontent.com/355114/72550810-71dadd80-388b-11ea-8ae4-7c0fca5de90f.png)

That's just an idea on topic. I'm fine with a close too. @oy?

**Comment by oy** [comment]
Yeah, closing it then.
