### ISSUE TITLE
Minimize doesn't work on mac

### ISSUE THREAD

**Issue by Ubu-** [teeworlds/teeworlds#526]
bnn: bug in SDL

**Comment by oy** [comment]
Fixed.

**Comment by oy** [comment]
With SDL_WINDOW_FULLSCREEN_DESKTOP tabbing and minimize work but the screen is messed up if it differs from the desktop resolution.
With SDL_WINDOW_FULLSCREEN the screen is fine but tabbing and minimize don't work.

**Comment by oy** [comment]
Fixed.
