### ISSUE TITLE
Different hook strength 

### ISSUE THREAD

**Issue by Ubu-** [teeworlds/teeworlds#541]
From drUncreative:

Tees have different strength of hook.
Here is a demo:
http://teedb.info/index.php?section=demos&id=21

https://github.com/oy/teeworlds/issues/closed#issue/530

**Comment by Dune-jr** [comment]
@oy should this still be fixed? I heard it was changed then reverted or something.

**Comment by oy** [comment]
Someday it should be fixed yeah :)
