### ISSUE TITLE
moving up/down in the friend list with keys also moves the serverlist

### ISSUE THREAD

**Issue by ghost91-** [teeworlds/teeworlds#688]
When you have clicked on a friend in the friend list and you move up/down with the keys, you move both in the friendlist and in the server browser. also there is no way to deselect the friend, maybe this should be done.

**Comment by oy** [comment]
Invalid due to new menu layout.

**Comment by heinrich5991** [comment]
Might still be a 0.6 bug though, can't chack right now. :/

**Comment by oy** [comment]
It is, but not gonna fix it for 0.6.
