### ISSUE TITLE
Create comprehensible code docs

### ISSUE THREAD

**Issue by wilk-polarny** [teeworlds/teeworlds#711]
Hello,

I downloaded the new and refactored sources of teeworlds 0.6.0 and had realized that there is really no documentation on the code.

All classes, constants, methods, - everything is without comments describing what they do, what to do with parameters, etc.
It seems that the code is easier to read since the refactoring happened, but it is really hard to understand how everything works.

There is no document describing where to start.

For example: How does the server work?
A few pages of documentation would be nice, or even a flow diagram.

And even if some developer finds out where to start, there is no way to find out what each classes and methods are for, what they do, what they return, what parameters/arguments to pass, etc. except by studying/debugging the whole project for weeks.

It is nice, that the code complies to some naming conventions (some variables are starting with ugly captial letters, but meh) since 0.6.0 but in my opinion, it's not enough.

Such a big project needs a good code documentation, else no one (except of some of the early day hardcore modders) will be able to contribute to this project.

An example for a good documentation using the state of the art HTML Doc Tool "Doxygen":

http://www.icu-project.org/apiref/icu4c/classStringSearch.html

--> See the difference?
You can see everything. Parent classes, method descriptors, a description of the class itself, a classoverview of all available classes, etc.

So, are there any plans to add code documentation?

Regards,
Schokomuesli

**Comment by Panquesito7** [comment]
@oy this is a very old post, but...
I think it would be a good idea to document the code.

If you need help with this, I can help as well.
We can start by documenting small files/folders. 🙂

See this project, it has very nice documentation: https://github.com/TheAlgorithms/C-Plus-Plus

**Comment by Dune-jr** [comment]
@Panquesito7 probably best to open a new issue.
Though I've used doxygen for serious projects and feel like it is debatable whether the benefit/energy-put-into ratio of such automated documentation tools is favorable over simple comments in the code.
