### ISSUE TITLE
New SDL.dll Requires MSVCR100.dll

### ISSUE THREAD

**Issue by GreYFoX** [teeworlds/teeworlds#797]
i'm unable to use teeworlds on windows after this 4869d0ed3586d55efc50 commit

**Comment by a-raccoon** [comment]
This is happening again, 5.5 years later.  Unzipped teeworlds-0.6.4-win32 and ran teeworlds.exe
Out of the box:
```
teeworlds.exe - System Error
The program can't start because MSVCR100.dll is missing from your computer. Try reinstalling the program to fix this problem. 
```
Copying MSVCR100.dll from C:\Windows\System32\ and placing it in the game directory, yields:
```
teeworlds.exe - Application Error
The application was unable to start correctly (0xc000007b). Click OK to close the application. 
```

I run Windows 7 64bit.   And the front page of teeworlds.com only offers a 32 bit download.  Checking deeper on the Downloads page, I notice the current and most previous versions are only available for Windows 32 bit.  I just grabbed 0.6.2 for Windows 64, and that plays for me.

Two questions:  1) Why doesn't the 32bit version play in Windows 7 64bit?  2) Why weren't 0.6.3 and 0.6.4 compiled for 64bit Windows?

**Comment by heinrich5991** [comment]
Hm. I compiled this on a Windows 10 64bit, with a 32bit target so it'll run on both 32bit and 64bit. I don't know why it doesn't run on your machine. Maybe I need to compile it on Windows 7...

**Comment by heinrich5991** [comment]
Can you try this one, and report if it works? https://heinrich5991.de/teeworlds/temp/teeworlds-0.6.4-win32.zip

If so, we'll replace the current binaries with this zip.

**Comment by a-raccoon** [comment]
That binary does not work either.  Same errors as above.

**Comment by Sonix-** [comment]
Is msvcr100.dll present in both C:\Windows\System32 and C:\Windows\SysWOW64 ?
I had the same issue some time ago and resolved it by downloading the missing .dlls for both 32 and 64bit versions.

**Comment by a-raccoon** [comment]
This is a fairly new Windows 7 Pro install; fall 2016.  Religiously updated (all the rollups).  I have:

C:\Windows\System32\msvcr100.dll
C:\Windows\System32\msvcr100_clr0400.dll
C:\Windows\SysWOW64\msvcr100_clr0400.dll
C:\Windows\Installer\$PatchCache$\Managed\1735F6DB1CAD0F03D9EDAC6C97E1823C\4.6.1055\msvcr100_clr0400_dll_x86
C:\Windows\Installer\$PatchCache$\Managed\1735F6DB1CAD0F03D9EDAC6C97E1823C\4.6.1055\msvcr100_clr0400_dll_amd64

The 64bit compiled version of 0.6.2 plays fine.

**Comment by Sonix-** [comment]
I guess you're missing the 32bit dll
Download from https://www.dll-files.com/msvcr100.dll.html the 32bit version of msvcr100.dll and put it in C:\Windows\SysWOW64\ and then try to run the game.

This happens with other games too, especially on fresh Windows installs, mostly because they're missing the vc redistributable packages.

**Comment by a-raccoon** [comment]
I think you missed my reply.  "C:\Windows\System32\msvcr100.dll"

The point here is, I *can't* be missing it. Because my system is a baseline "normal."  The problems are inherent with how the game is compiled.  My system is John Q Public's system.

**Comment by Sonix-** [comment]
"C:\Windows\System32\msvcr100.dll" is 64bit
while you're trying to run teeworlds-0.6.4-win32, you'll need "C:\Windows\SysWOW64\msvcr100.dll" (which is the folder for 32bit files).

**Comment by a-raccoon** [comment]
The Internet suggests that Teeworlds should "Statically link to the dll files so they are compiled into the executable instead of referenced as separate dll files."

https://www.rhyous.com/2010/09/16/avoiding-the-msvcr100-dll-or-msvcr100d-dll/
```
You can solve this any of the following ways:

1) Statically link to the dll files so they are compiled into the executable instead of referenced as separate dll files.
2) Include the dll in the same directory as the exe.
3) Force everyone to install the VC++ Runtime Redistributable before running the app.
```

**Comment by oy** [comment]
Here is a 64bit version https://www.solidfiles.com/v/p3B6XZeLevmGg.

**Comment by heinrich5991** [comment]
Does that version work?

**Comment by a-raccoon** [comment]
Yes, that version does work for me.  Note: Google Chrome wanted to delete the download when it completed, stating that it was dangerous.  It tested clean at virustotal.com.  I'm guessing Google doesn't trust files downloaded from solidfiles.com; just FYI.

**Comment by heinrich5991** [comment]
@oy How did you compile that?

**Comment by oy** [comment]
@heinrich5991 
On Windows 10 64bit with Visual Studio 2015.

**Comment by maaz23** [comment]
You can download the [misssing msvcr100.dll](https://pcpatchedup.com/msvcr100-dll) file from here
