### ISSUE TITLE
Improve automapper

### ISSUE THREAD

**Issue by AwayD** [teeworlds/teeworlds#814]
- add flipping tiles twice: "Index 10 XFLIP YFLIP"
- add rotating tiles
- fix existing rules
- make rules format/creation more simple
- make it use a parser
- add gui to create rules
- make it possible to use different configurations in one layer
- add a free hand mode
- make it possible to use the auto mapper for a specified area or brush

**Comment by Dune-jr** [comment]
Remaining issues look obsolete/redundant with https://github.com/teeworlds/teeworlds/issues/1066 and https://github.com/teeworlds/teeworlds/issues/1963
