### ISSUE TITLE
TDTW: Colors in the servers list

### ISSUE THREAD

**Issue by Ubu-** [teeworlds/teeworlds#866]
Where: server browser
What: different colors for different ping ranges (green= low ping, red=high ping...)
different colors for the number of players in a server (green = lot of slots, red=no avaliable slots...)

Why: I was really skeptic about that because of the colors in the gamer client, but if you pick the good colors it is quite nice. Faster to read, more userfriendly

(http://www.teeworlds.com/forum/viewtopic.php?id=7647)

**Comment by minus7** [comment]
Already implemented for ping, but not for player count. Is that enough? I wouldn't go with green on the player count, I'd just make it red in case it's full

**Comment by heinrich5991** [comment]
@minus7 Maybe grey out the server if it's full? A full server doesn't need something eye-catchy.

**Comment by KingteEGER** [comment]
@heinrich5991  @minus7 

The issue from @Ubu- is alleready done (**see:** minus7 commented on 5 Jan 2015)

**heinrich wrote:**
> _[...] Maybe grey out the server if it's full? A full server doesn't need something eye-catchy._

This is done to. **See:** [https://github.com/teeworlds/teeworlds/blob/master/src/game/client/components/menus_browser.cpp#L220](https://github.com/teeworlds/teeworlds/blob/master/src/game/client/components/menus_browser.cpp#L220)

In my opinion this issue should be closed.

**Comment by minus7** [comment]
Seems like it was implemented in the same commit as colorized ping already: https://github.com/teeworlds/teeworlds/commit/8e09a80e22524871ceda04f0255aa1e59147c379#diff-3287b2addb72598cfece115cfba5ded8R194
