### ISSUE TITLE
Overtime system

### ISSUE THREAD

**Issue by Choupom** [teeworlds/teeworlds#928]
Sudden death sucks as players/teams don't want to fight anymore because dieing once = lose the game.
With an overtime system you can still get back in the game if you are low hp at the end of the timelimit by temporizing a few seconds.

Once the timelimit is over and both players/teams have the same number of points, start an overtime of x minutes. The overtime starts again if there is a draw at the end of the overtime.
If sv_overtime is set to 0 use the sudden death system, else use the overtime system with the given time.

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
